//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidabright
//     Size: 7x14
//     Bold: no
//     Italic: no
//     Memory usage: 1680 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidabright7x14Data[1480] =
{
      5,  10,   0,  13,  96,  13,  10,   1, 145, 145, 145, 145,
    145, 145, 240,  65, 240, 224,   7,  10,   2, 130, 130,   0,
     11,  20,  10,  49,  17,  97,  33,  86,  81,  17, 113,  17,
     86,  81,  33,  97,  17, 113,  17, 240, 176,  21,  10,  35,
     83,  17,  81,  17, 115, 131, 129,  17,  81,  17,  17,  81,
     17,  17,  84, 129, 240,  32,  25,  10,  17,  49,  65,  17,
     17,  81,  17,  17,  97,  17, 131, 114,  17,  81,  17,  17,
     81,  17,  17,  65,  49, 240, 160,  23,  10,  34, 113,  33,
     97,  33,  99,  97,  33,  19,  33,  33,  33,  49,  49,  17,
     50,  34,  84,  18, 240, 112,   7,  10,   3, 115, 129,   0,
     11,  14,  10,  33, 129, 129, 145, 145, 145, 145, 145, 145,
    161, 161, 112,  14,  10,   1, 161, 161, 145, 145, 145, 145,
    145, 145, 129, 129, 144,  11,  10,  33, 117,  97,  17, 113,
     17,   0,   9,  64,  12,  10, 209, 145, 145, 145, 103,  97,
    145, 145, 240, 176,   8,  10,   0,  10,   1, 145, 145, 144,
      8,  10,   0,   6,  35,   0,   7,  16,   7,  10,   0,  10,
      1, 240, 224,  14,  10,  81, 129, 145, 130, 129, 130, 129,
    130, 129, 145, 129, 144,  20,  10,  34, 113,  33,  81,  65,
     65,  65,  65,  65,  65,  65,  65,  65,  81,  33, 114, 240,
    176,  13,  10,   3, 145, 145, 145, 145, 145, 145, 145, 117,
    240, 160,  15,  10,  19,  97,  49,  81,  49, 145, 129, 129,
    129, 129, 149, 240, 160,  15,  10,   4,  97,  49, 145, 145,
     99, 161, 145,  81,  49,  84, 240, 176,  16,  10,  50, 130,
    113,  17,  97,  33,  82,  33,  86, 129, 145, 131, 240, 144,
     14,  10,   5,  81, 145, 148, 146, 145, 145,  81,  34,  84,
    240, 176,  19,  10,  36,  81,  49,  65, 145,  19,  82,  49,
     65,  65,  65,  65,  81,  34,  99, 240, 160,  13,  10,   6,
    145, 129, 129, 130, 114, 129, 130, 129, 240, 224,  19,  10,
     20,  81,  65,  65,  65,  81,  33, 100,  81,  50,  65,  65,
     66,  34,  84, 240, 160,  19,  10,  19,  98,  33,  81,  65,
     65,  65,  65,  50,  83,  17, 145,  65,  49,  84, 240, 176,
      9,  10, 240, 241,   0,   6,  17, 240, 224,  11,  10, 240,
    241, 240, 240, 145, 145, 145, 145, 144,  13,  10, 240,  17,
    114,  98,  99, 130, 146, 162, 161, 240, 128,   9,  10, 240,
    240, 167, 215, 240, 240, 208,  12,  10, 161, 162, 162, 146,
    131,  98,  98, 113, 240, 224,  15,  10,   4,  97,  49,  81,
     49, 129, 130, 129, 145, 240,  65, 240, 192,  21,  10,  68,
     66,  65,  33,  35,  34,  52,  18,  33,  18,  34,  33,  18,
     19,  38,  34, 149, 240, 128,  18,  10,  65, 130, 131,  98,
     17,  97,  34,  85,  65,  65,  65,  81,  34,  67, 240,  96,
     19,  10,   5,  97,  49,  81,  49,  81,  33, 100,  97,  34,
     81,  49,  81,  49,  69, 240, 160,  16,  10,  37,  65,  65,
     49,  81,  49, 145, 145, 146, 146,  49,  84, 240, 144,  20,
     10,   6,  81,  65,  65,  81,  49,  81,  49,  81,  49,  81,
     49,  81,  49,  65,  54, 240, 144,  17,  10,   6,  81,  49,
     81, 145,  33, 100,  97,  33,  97, 145,  49,  70, 240, 144,
     16,  10,   6,  81,  49,  81, 145,  33, 100,  97,  33,  97,
    145, 131, 240, 192,  18,  10,  37,  65,  65,  49,  81,  49,
    145, 145,  67,  34,  65,  66,  49,  85, 240, 128,  21,  10,
      3,  51,  33,  81,  49,  81,  49,  81,  55,  49,  81,  49,
     81,  49,  81,  35,  51, 240,  96,  13,  10,   3, 129, 145,
    145, 145, 145, 145, 145, 131, 240, 192,  15,  10,  35, 129,
    145, 145, 145, 145, 145, 145, 145,  97,  33,  99, 112,  21,
     10,   3,  19,  65,  49,  81,  33,  97,  17, 114, 129,  17,
    113,  34,  81,  50,  51,  20, 240, 112,  14,  10,   3, 129,
    145, 145, 145, 145, 145, 145,  49,  70, 240, 144,  29,  10,
      3,  67,  18,  66,  35,  50,  33,  17,  33,  17,  33,  17,
     33,  17,  33,  34,  33,  33,  34,  33,  33,  33,  49,  19,
     67, 240,  80,  25,  10,   2,  51,  50,  49,  66,  49,  65,
     17,  33,  65,  33,  17,  65,  33,  17,  65,  50,  65,  65,
     51,  49, 240, 128,  20,  10,  36,  81,  65,  49,  97,  33,
     97,  33,  97,  33,  97,  33,  97,  49,  65,  84, 240, 144,
     16,  10,   5,  97,  49,  81,  49,  81,  34,  84,  97, 145,
    145, 131, 240, 192,  20,  10,  36,  81,  65,  49,  97,  33,
     97,  33,  97,  33,  97,  33,  97,  49,  65,  85, 130, 163,
     20,  10,   5,  97,  49,  81,  49,  81,  49,  84,  97,  33,
     97,  34,  81,  49,  67,  50, 240, 112,  17,  10,  20,  81,
     49,  81,  49,  82, 162, 146,  81,  49,  81,  49,  84, 240,
    176,  13,  10,   7,  97, 145, 145, 145, 145, 145, 145, 131,
    240, 160,  21,  10,   3,  35,  49,  65,  65,  65,  65,  65,
     65,  65,  65,  65,  65,  65,  66,  34,  84, 240, 144,  20,
     10,   3,  50,  49,  66,  49,  65,  81,  49,  81,  33, 113,
     17, 113,  17, 114, 145, 240, 160,  31,  10,   3,  33,  49,
     17,  49,  49,  17,  35,  33,  33,  17,  17,  33,  33,  17,
     17,  17,  49,  17,  17,  17,  50,  50,  65,  49,  81,  49,
    240, 112,  19,  10,   4,  34,  50,  49,  81,  33, 115, 114,
    115,  98,  33,  81,  65,  50,  51, 240, 112,  16,  10,   3,
     35,  49,  65,  81,  34,  84, 114, 129, 145, 145, 131, 240,
    160,  15,  10,   6,  65,  49, 130, 129, 129, 145, 129, 145,
     49,  70, 240, 144,  14,  10,   2, 129, 145, 145, 145, 145,
    145, 145, 145, 145, 146, 128,  14,  10,   1, 161, 145, 146,
    145, 146, 145, 146, 145, 145, 161,  64,  14,  10,   2, 145,
    145, 145, 145, 145, 145, 145, 145, 145, 130, 128,  19,  10,
     49, 145, 129,  17, 113,  17,  97,  49,  81,  49,  66,  50,
     49,  81, 240, 240,  48,   6,  10,   0,  11,  37, 240,   6,
     10,   3,   0,  13,  48,  13,  10, 240, 244, 161, 100,  81,
     49,  81,  49, 101, 240, 144,  17,  10,   2, 145, 145, 149,
     81,  50,  65,  65,  65,  65,  65,  65,  69, 240, 144,  13,
     10, 240, 240,  20,  82,  33,  81, 145, 146, 148, 240, 160,
     17,  10,  66, 145, 145,  85,  65,  65,  65,  65,  65,  65,
     66,  49,  86, 240, 128,  13,  10, 240, 240,  19,  97,  49,
     85,  81, 146, 148, 240, 160,  14,  10,  20,  97,  33,  97,
    132, 113, 145, 145, 145, 132, 240, 176,  16,  10, 240, 240,
     21,  65,  49,  81,  49,  99,  97, 150,  65,  65,  84,  80,
     18,  10,   2, 145, 145, 149,  81,  49,  81,  49,  81,  49,
     81,  49,  67,  19, 240, 128,  12,  10,  17, 240, 210, 145,
    145, 145, 145, 131, 240, 192,  14,  10,  33, 240, 210, 145,
    145, 145, 145, 145, 113,  17, 115, 112,  18,  10,   2, 145,
    145, 145,  35,  65,  18,  99, 113,  17, 113,  33,  83,  34,
    240, 128,  13,  10,   2, 145, 145, 145, 145, 145, 145, 145,
    131, 240, 192,  20,  10, 240, 250,  17,  49,  49,  17,  49,
     49,  17,  49,  49,  17,  49,  52,  19,  18, 240,  80,  16,
     10, 240, 246,  81,  49,  81,  49,  81,  49,  81,  49,  67,
     19, 240, 128,  16,  10, 240, 240,  20,  82,  34,  65,  65,
     65,  65,  66,  34,  84, 240, 160,  16,  10, 240, 246,  81,
     50,  65,  65,  65,  65,  65,  65,  69,  81, 131, 112,  17,
     10, 240, 240,  21,  65,  65,  65,  65,  65,  65,  66,  49,
     85, 145, 131,  48,  12,  10, 240, 244, 113,  17, 113, 145,
    145, 131, 240, 192,  16,  10, 240, 240,  20,  81,  49,  83,
     17,  81,  19,  81,  49,  84, 240, 176,  12,  10, 177, 145,
    132, 113, 145, 145, 145, 147, 240, 176,  16,  10, 240, 242,
     34,  81,  49,  81,  49,  81,  49,  81,  49,  86, 240, 128,
     15,  10, 240, 243,  34,  65,  50,  66,  33,  97,  17, 130,
    129, 240, 176,  21,  10, 240, 243,  33,  34,  17,  34,  34,
     17,  34,  33,  50,  33,  17,  50,  34,  65,  65, 240, 112,
     15,  10, 240, 243,  34,  66,  33,  99, 115,  97,  34,  66,
     35, 240, 128,  16,  10, 240, 243,  34,  65,  50,  66,  33,
     97,  18, 114, 129, 145, 114, 112,  13,  10, 240, 245,  81,
     33, 129, 130, 129,  33,  85, 240, 160,  14,  10,  33, 129,
    145, 145, 145, 129, 161, 145, 145, 145, 161, 112,  14,  10,
      1, 145, 145, 145, 145, 145, 145, 145, 145, 145, 145, 144,
     14,  10,   1, 161, 145, 145, 145, 161, 129, 145, 145, 145,
    129, 144,  14,  10, 240, 240, 178,  49,  49,  33,  33,  49,
     50, 240, 240, 224,
};

const tFont g_sFontlucidabright7x14 =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    10,

    //
    // The height of the font.
    //
    11,

    //
    // The baseline of the font.
    //
    9,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   18,   25,   45,   66,   91,  114,
         121,  135,  149,  160,  172,  180,  188,  195,
         209,  229,  242,  257,  272,  288,  302,  321,
         334,  353,  372,  381,  392,  405,  414,  426,
         441,  462,  480,  499,  515,  535,  552,  568,
         586,  607,  620,  635,  656,  670,  699,  724,
         744,  760,  780,  800,  817,  830,  851,  871,
         902,  921,  937,  952,  966,  980,  994, 1013,
        1019, 1025, 1038, 1055, 1068, 1085, 1098, 1112,
        1128, 1146, 1158, 1172, 1190, 1203, 1223, 1239,
        1255, 1271, 1288, 1300, 1316, 1328, 1344, 1359,
        1380, 1395, 1411, 1424, 1438, 1452, 1466,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidabright7x14Data
};
