//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidasans
//     Size: 7x11
//     Bold: yes
//     Italic: yes
//     Memory usage: 1504 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidasans7x11biData[1301] =
{
      5,   9,   0,  12,  48,  11,   9, 240,  82, 114,  98, 114,
    242, 114, 240, 160,  11,   9, 145,  17,  97,  17,  97,  17,
      0,   8,  80,  19,   9, 240,  98,  17,  82,  17,  52,  18,
     50,  17,  52,  18,  50,  17,  82,  17, 240, 112,  14,   9,
    209, 101,  50,  17,  84,  99, 100,  81,  18,  53,  97, 240,
     20,   9, 240,  66,  49,  33,  18,  18,  50,  18,  98,  98,
     18,  50,  17,  18,  33,  50, 240,  80,  18,   9, 240,  83,
     82,  18,  83,  83,  34,  18,  18,  17,  34,  34,  67,  18,
    240,  80,   8,   9, 145, 129, 129,   0,   8, 112,  12,   9,
    194,  98,  98, 114,  98, 114, 114, 114, 130, 240,  13,   9,
    178, 130, 114, 114, 114,  98, 114,  98,  98, 240,  16,  11,
      9, 240,  66,  18,  82,  82,  18,   0,   7,  32,  11,   9,
    240, 241, 129,  86,  81, 129, 240, 240,  48,   9,   9,   0,
      8,   2, 114,  98, 240,  16,   8,   9, 240, 240, 242,   0,
      6,  64,   8,   9,   0,   7, 114, 114, 240, 160,  13,   9,
    210, 114,  98, 114,  98,  98, 114,  98, 114, 240,  16,  17,
      9, 240,  83,  82,  18,  65,  34,  50,  34,  50,  33,  66,
     18,  83, 240, 128,  12,   9, 240,  82,  84, 114,  99,  98,
    114, 114, 240, 144,  13,   9, 240,  83,  81,  34, 114,  98,
     82, 101,  69, 240, 112,  14,   9, 240,  83,  81,  34, 114,
     83, 114,  65,  34,  83, 240, 128,  14,   9, 240,  98,  99,
     81,  18,  65,  34,  70,  82, 114, 240, 128,  13,   9, 240,
     84,  69,  65, 131, 130,  65,  34,  83, 240, 128,  15,   9,
    240,  99,  82,  33,  50, 116,  66,  34,  50,  34,  68, 240,
    112,  12,   9, 240,  69,  69, 113,  98,  98,  98, 114, 240,
    160,  16,   9, 240,  84,  66,  34,  50,  34,  53,  50,  34,
     50,  34,  68, 240, 112,  15,   9, 240,  84,  66,  34,  50,
     34,  68, 114,  49,  34,  83, 240, 128,  10,   9, 240, 210,
    114, 240, 146, 114, 240, 160,  11,   9, 240, 226, 114, 240,
    146, 114,  98, 240,  16,  11,   9, 240, 243,  67,  82, 130,
    130, 240, 240,  32,   9,   9, 240, 240, 117, 197, 240, 240,
    160,  11,   9, 240, 226, 130, 130,  83,  67, 240, 240,  48,
     12,   9, 240,  67,  81,  34, 114,  83, 226, 114, 240, 160,
     18,   9, 240, 100,  50,  50,  33,  36,  17,  33,  18,  33,
     34,  18,  17, 149, 240,  96,  16,   9, 240, 114,  99,  81,
     18,  66,  18,  69,  50,  34,  50,  34, 240,  96,  16,   9,
    240,  68,  82,  18,  66,  18,  53,  66,  34,  50,  34,  53,
    240, 112,  12,   9, 240,  99,  67,  98,  98, 114, 115, 116,
    240, 112,  17,   9, 240,  69,  66,  34,  50,  34,  35,  34,
     34,  34,  50,  34,  52, 240, 128,  12,   9, 240,  69,  66,
    114, 101,  66, 114, 117, 240, 112,  12,   9, 240,  69,  66,
    114, 101,  66, 114, 114, 240, 160,  15,   9, 240, 100,  51,
     98,  98,  34,  50,  34,  51,  18,  68, 240, 112,  18,   9,
    240,  66,  34,  50,  34,  50,  34,  39,  34,  34,  50,  34,
     50,  34, 240,  96,  12,   9, 240,  66, 114, 114,  99,  98,
    114, 114, 240, 160,  12,   9, 240,  98, 114, 114,  99,  98,
    114,  99,  83, 240,  17,   9, 240,  66,  34,  50,  18,  68,
     68,  82,  18,  66,  34,  50,  50, 240,  80,  12,   9, 240,
     66, 114, 114,  99,  98, 114, 117, 240, 112,  20,   9, 240,
     66,  66,  19,  35,  21,  20,  18,  35,  34,  18,  17,  33,
     34,  17,  82, 240,  64,  19,   9, 240,  66,  49,  51,  33,
     51,  33,  49,  19,  50,  19,  49,  50,  49,  50, 240,  96,
     17,   9, 240, 100,  51,  34,  34,  50,  18,  66,  18,  50,
     34,  35,  52, 240, 112,  14,   9, 240,  69,  66,  34,  50,
     34,  37,  66, 114, 114, 240, 160,  17,   9, 240, 100,  51,
     34,  34,  50,  18,  66,  18,  50,  34,  35,  52, 131, 130,
     17,   9, 240,  69,  66,  34,  50,  34,  38,  50,  18,  66,
     34,  50,  34, 240,  96,  12,   9, 240,  84,  66, 114, 130,
    130, 114,  68, 240, 128,  12,   9, 240,  54,  82, 114,  99,
     98, 114, 114, 240, 144,  18,   9, 240,  66,  34,  50,  34,
     50,  34,  34,  34,  50,  34,  50,  33,  83, 240, 128,  17,
      9, 240,  50,  34,  50,  34,  50,  33,  66,  18,  66,  17,
     83,  98, 240, 160,  19,   9, 240,  50,  99,  34,  35,  34,
     35,  19,  20,  19,  17,  19,  19,  34,  34, 240,  96,  16,
      9, 240,  82,  34,  50,  18,  68,  98, 100,  66,  18,  50,
     34, 240,  96,  15,   9, 240,  50,  34,  50,  34,  50,  18,
     83,  98, 114, 114, 240, 144,  12,   9, 240,  69,  99,  98,
     98,  98,  99, 101, 240, 112,  12,   9, 179,  98, 114,  98,
    114, 114,  98, 114, 115, 240,  12,   9, 146, 114, 114, 130,
    114, 114, 130, 114, 114, 224,  12,   9, 179, 114, 114,  98,
    114, 114,  98, 114,  99, 240,  14,   9, 240, 240,  18,  99,
     81,  18,  65,  34,  49,  50, 240, 240,   6,   9,   0,  10,
     22, 192,   7,   9,   2, 130,   0,  10, 112,  15,   9, 240,
    228,  66,  18,  50,  34,  50,  18,  69,  66,  18, 240, 112,
     16,   9, 178, 114, 113,  18,  69,  66,  18,  50,  34,  50,
     18,  68, 240, 128,  11,   9, 240, 227,  82,  98, 114, 114,
    131, 240, 128,  16,   9, 226, 114,  68,  66,  18,  50,  34,
     50,  18,  69,  66,  18, 240, 112,  13,   9, 240, 227,  81,
     18,  66,  18,  68,  82, 131, 240, 128,  13,   9, 195,  82,
    101,  82,  98, 114, 114,  98, 114, 114, 112,  16,   9, 240,
    228,  66,  18,  50,  34,  50,  18,  69,  66,  18, 114,  68,
     80,  17,   9, 178, 114,  98,  18,  69,  66,  18,  50,  33,
     66,  18,  66,  18, 240, 112,  11,   9, 178, 242, 114, 114,
     98, 114, 114, 240, 160,  12,   9, 210, 242, 114, 114,  98,
    114, 114,  98,  99,  96,  16,   9, 178, 114,  98,  34,  50,
     18,  68,  68,  82,  18,  66,  34, 240,  96,  12,   9, 178,
    114,  98, 114, 114,  98, 114, 114, 240, 160,  20,   9, 240,
    210,  18,  18,  24,  18,  18,  20,  33,  33,  18,  18,  18,
     18,  18,  18, 240,  64,  16,   9, 240, 210,  18,  69,  66,
     18,  50,  33,  66,  18,  66,  18, 240, 112,  15,   9, 240,
    227,  82,  18,  50,  34,  50,  34,  50,  18,  83, 240, 128,
     16,   9, 240, 226,  18,  69,  66,  18,  50,  34,  50,  18,
     68,  66, 114, 112,  16,   9, 240, 228,  66,  18,  50,  34,
     50,  18,  69,  66,  18,  98, 114,  80,  12,   9, 240, 210,
     17,  84,  82,  98, 114, 114, 240, 160,  11,   9, 240, 228,
     66, 115, 115, 114,  68, 240, 128,  12,   9, 240,  82,  85,
     82, 114,  98, 114, 115, 240, 144,  16,   9, 240, 210,  18,
     66,  18,  65,  34,  50,  18,  69,  66,  18, 240, 112,  15,
      9, 240, 194,  34,  50,  34,  50,  18,  66,  17,  83,  98,
    240, 160,  19,   9, 240, 194,  66,  18,  18,  18,  18,  18,
     18,  18,  18,  17,  38,  50,  18, 240, 112,  15,   9, 240,
    210,  18,  66,  18,  83,  83,  82,  18,  66,  18, 240, 112,
     17,   9, 240, 210,  34,  50,  34,  50,  34,  50,  18,  66,
     17,  83,  98,  98, 112,  11,   9, 240, 213, 114,  83,  83,
     82, 117, 240, 112,  12,   9, 210,  98,  98, 114,  82, 145,
    114, 114, 130, 224,  13,   9, 178, 114, 113, 114, 114, 114,
    113, 114, 114, 240,  16,  13,   9, 178, 130, 114, 113, 146,
     82, 114,  98,  98, 240,  16,  11,   9, 240, 240, 115,  17,
     49,  19,   0,   6,  16,
};

const tFont g_sFontlucidasans7x11bi =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    9,

    //
    // The height of the font.
    //
    11,

    //
    // The baseline of the font.
    //
    9,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   16,   27,   46,   60,   80,   98,
         106,  118,  131,  142,  153,  162,  170,  178,
         191,  208,  220,  233,  247,  261,  274,  289,
         301,  317,  332,  342,  353,  364,  373,  384,
         396,  414,  430,  446,  458,  475,  487,  499,
         514,  532,  544,  556,  573,  585,  605,  624,
         641,  655,  672,  689,  701,  713,  731,  748,
         767,  783,  798,  810,  822,  834,  846,  860,
         866,  873,  888,  904,  915,  931,  944,  957,
         973,  990, 1001, 1013, 1029, 1041, 1061, 1077,
        1092, 1108, 1124, 1136, 1147, 1159, 1175, 1190,
        1209, 1224, 1241, 1252, 1264, 1277, 1290,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidasans7x11biData
};
