//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidabright
//     Size: 6x12
//     Bold: yes
//     Italic: yes
//     Memory usage: 1532 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidabright6x12biData[1331] =
{
      5,   9,   0,  11,  32,  12,   9,  18, 114, 113, 129, 129,
    129, 240,  18, 240, 160,  13,   9,   1,  17,  97,  17,  97,
     17,  97,  17,   0,   7,  64,  18,   9,  49,  17,  97,  17,
     54,  65,  33,  81,  33,  70,  49,  17,  97,  17, 240, 144,
     15,   9,  35,  82,  17,  82, 129, 130, 114,  81,  18,  83,
    113, 240,  16,  17,   9,  17,  17,  82,  17,  82, 115, 113,
     17,  99,  81,  18,  81,  33, 240, 128,  20,   9,  50,  97,
     17,  97,  17,  83,  18,  33,  33,  17,  49,  33,  17,  49,
     49,  85, 240,  96,   9,   9,   1, 129, 129, 129,   0,   7,
     96,  13,   9,  33, 113, 129, 113, 129, 129, 129, 129, 129,
    129, 128,  13,   9,  33, 129, 129, 129, 129, 129, 129, 113,
    129, 113, 128,   9,   9,  33, 100,  81,  17,   0,   8,  80,
     11,   9, 193, 129, 129,  86,  81, 129, 129, 240, 144,   9,
      9,   0,   6,  98, 114, 129, 113, 128,   8,   9, 240, 240,
     98,   0,   6,  64,   7,   9,   0,   7, 114, 240, 160,  13,
      9,  97, 113, 114, 113, 113, 129, 113, 114, 113, 113, 128,
     18,   9,  34,  97,  33,  81,  33,  65,  49,  65,  49,  65,
     33,  81,  33,  98, 240, 144,  12,   9,  19, 114, 114, 113,
    129, 129, 114, 100, 240, 128,  13,   9,  35,  81,  49, 129,
    114,  97,  98, 113, 118, 240,  96,  14,   9,  35,  81,  33,
    129,  83, 129, 145,  65,  33,  84, 240, 128,  14,   9,  66,
     99,  81,  17,  81,  33,  70,  98, 114,  99, 240, 112,  13,
      9,  20,  81, 129, 130, 145, 130,  65,  33,  83, 240, 144,
     16,   9,  35,  81,  33,  81, 116,  81,  33,  81,  33,  81,
     33,  98, 240, 144,  12,   9,   6, 129,  98,  97, 129, 113,
    129, 113, 240, 176,  17,   9,  34,  97,  33,  81,  33,  83,
     97,  17,  81,  49,  65,  33,  98, 240, 144,  16,   9,  34,
     97,  33,  81,  33,  81,  33,  84, 113,  81,  33,  83, 240,
    144,   9,   9, 240, 210, 240, 240,  50, 240, 160,  10,   9,
    240, 210, 240, 161, 114, 129, 113, 128,  11,   9, 225,  98,
     67,  97, 130, 131, 145, 240, 112,   8,   9, 240, 240, 102,
    198, 240, 240,  11,   9, 177, 131, 145, 145,  83,  67,  81,
    240, 176,  14,   9,   3,  97,  33,  81,  33, 129,  98,  98,
    240,  18, 240, 160,  16,   9,  35,  81,  49,  67,  17,  50,
     19,  49,  20,  54,  49, 147, 240, 128,  16,   9,  81, 114,
     99,  81,  33,  85,  65,  49,  49,  65,  34,  51, 240,  64,
     17,   9,  22,  66,  33,  66,  33,  68,  67,  17,  66,  49,
     50,  33,  54, 240,  96,  13,   9,  52,  50,  49,  49, 113,
    129, 129, 130, 133, 240,  96,  18,   9,  22,  66,  34,  50,
     49,  49,  65,  34,  65,  34,  49,  50,  34,  38, 240,  96,
     16,   9,  22,  66,  33,  65,  33,  84,  66,  17,  82, 114,
     33,  54, 240,  96,  15,   9,  22,  66,  33,  65,  33,  84,
     66,  17,  82, 114,  99, 240, 144,  16,   9,  37,  50,  49,
     49, 113, 129,  36,  33,  65,  50,  34,  69, 240,  96,  19,
      9,  20,  19,  33,  50,  49,  50,  54,  34,  49,  50,  49,
     50,  49,  35,  20, 240,  64,  12,   9,  20, 113, 129, 113,
    129, 114, 114, 100, 240, 128,  14,   9,  51, 113, 114, 114,
    114, 113, 129, 114,  81,  18,  83,  96,  19,   9,  20,  18,
     50,  33,  65,  33,  81,  17,  84,  82,  17,  82,  33,  51,
     19, 240,  80,  14,   9,  20,  97, 129, 129, 114, 114,  33,
     66,  33,  54, 240,  96,  23,   9,  18,  81,  34,  35,  34,
     33,  17,  34,  19,  33,  21,  33,  34,  17,  33,  33,  33,
     18,  67, 240,  48,  22,   9,  18,  66,  34,  49,  50,  49,
     49,  17,  33,  33,  33,  17,  49,  50,  49,  50,  34,  65,
    240,  80,  18,   9,  36,  66,  33,  65,  50,  33,  66,  33,
     65,  49,  65,  49,  49,  83, 240, 128,  15,   9,  21,  82,
     33,  66,  33,  66,  18,  53,  66, 114, 100, 240, 128,  19,
      9,  36,  66,  33,  65,  50,  33,  66,  33,  65,  49,  65,
     49,  50,  68, 114, 146,  32,  18,   9,  22,  66,  33,  66,
     33,  68,  66,  17,  82,  33,  66,  33,  52,  18, 240,  80,
     14,   9,  36,  65,  49,  65, 145, 146, 129,  65,  49,  68,
    240, 128,  12,   9,   7,  81, 114, 114, 113, 129, 129, 115,
    240, 128,  19,   9,   3,  33,  65,  49,  65,  49,  49,  49,
     65,  49,  65,  49,  65,  49,  83, 240, 128,  18,   9,   3,
     50,  33,  65,  49,  65,  49,  49,  81,  17,  97,  17,  98,
    114, 240, 128,  23,   9,   3,  17,  34,  17,  33,  33,  33,
     18,  33,  33,  18,  18,  36,  18,  38,  50,  18,  65,  33,
    240, 112,  18,   9,  34,  34,  65,  33,  81,  33,  83,  83,
     82,  17,  81,  49,  50,  35, 240,  80,  16,   9,   3,  34,
     49,  49,  65,  49,  81,  17,  98, 113, 129, 100, 240, 128,
     15,   9,  37,  65,  33,  65,  33, 113, 129, 113, 113,  49,
     54, 240,  96,  13,   9,  34, 113, 114, 113, 129, 129, 129,
    114, 113, 130, 112,  13,   9,   1, 129, 129, 145, 129, 129,
    129, 145, 129, 129,  96,  13,   9,  34, 129, 114, 113, 129,
    129, 129, 114, 113, 114, 112,  15,   9, 194,  97,  17,  97,
     17,  82,  17,  65,  49,  65,  65, 240, 240,   6,   9,   0,
      9,   4, 224,   5,   9,   2,   0,  11,  13,   9, 240, 228,
     65,  34,  49,  49,  65,  19,  70, 240,  96,  16,   9,  18,
    114, 114, 113,  19,  67,  17,  65,  49,  50,  33,  68, 240,
    128,  11,   9, 240, 227,  81,  17,  81, 129, 132, 240, 128,
     15,   9,  66, 114, 114,  83,  81,  33,  65,  34,  65,  19,
     69, 240, 112,  12,   9, 240, 226,  97,  17,  83,  97,  33,
     84, 240, 128,  14,   9,  50,  97,  17,  97, 115,  97, 129,
    129, 129, 114, 113, 128,  16,   9, 240, 228,  65,  33,  81,
     33,  65,  34,  82,  17,  65,  34,  68,  80,  17,   9,  18,
    114, 114, 113,  19,  67,  17,  65,  49,  50,  33,  66,  34,
    240,  96,  11,   9,  18, 240, 146, 129, 129, 129, 114, 240,
    160,  13,   9,  50, 240, 147, 113, 129, 114, 114,  81,  17,
     98, 112,  16,   9,  18, 114, 114, 114,  18,  65,  18,  83,
     82,  17,  82,  34, 240,  96,  12,   9,  18, 113, 129, 129,
    129, 129, 129, 114, 240, 160,  17,   9, 240, 195,  21,  22,
     17,  18,  18,  35,  33,  33,  18,  33,  34, 240,  48,  16,
      9, 240, 195,  18,  65,  17,  17,  66,  33,  65,  33,  66,
     34, 240,  96,  13,   9, 240, 226,  97,  33,  65,  49,  65,
     33,  83, 240, 144,  14,   9, 240, 213,  67,  17,  66,  33,
     65,  33,  83,  81, 129, 128,  15,   9, 240, 228,  65,  34,
     49,  49,  65,  19,  67,  17, 114, 114,  64,  11,   9, 240,
    194,  18,  82, 114, 113, 113, 240, 176,  12,   9, 240, 196,
     97,  17,  98,  97,  33,  83, 240, 144,  12,   9,  33, 114,
    114, 100,  97, 129, 113, 131, 240, 144,  15,   9, 240, 194,
     34,  65,  34,  49,  34,  65,  17,  17,  70, 240,  96,  12,
      9, 240, 194,  34,  65,  34,  68,  97, 129, 240, 144,  18,
      9, 240, 194,  33,  18,  33,  18,  18,  33,  18,  17,  50,
     18,  66,  17, 240, 112,  14,   9, 240, 209,  33,  97,  17,
     83,  81,  33,  81,  34, 240, 112,  14,   9, 240, 210,  34,
     66,  33,  66,  18,  68,  97, 113,  98, 112,  12,   9, 240,
    213,  65,  33,  98,  97,  33,  69, 240, 112,  13,   9,  34,
    113, 129, 129, 129,  98, 129, 113, 129, 130, 112,  13,   9,
     33, 129, 113, 129, 129, 113, 129, 129, 129, 129, 128,  13,
      9,  34, 114, 113, 129, 130,  97, 129, 129, 129, 114, 112,
     11,   9, 240, 240, 113,  49,  49,  19, 240, 240, 160,
};

const tFont g_sFontlucidabright6x12bi =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    9,

    //
    // The height of the font.
    //
    10,

    //
    // The baseline of the font.
    //
    8,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   17,   30,   48,   63,   80,  100,
         109,  122,  135,  144,  155,  164,  172,  179,
         192,  210,  222,  235,  249,  263,  276,  292,
         304,  321,  337,  346,  356,  367,  375,  386,
         400,  416,  432,  449,  462,  480,  496,  511,
         527,  546,  558,  572,  591,  605,  628,  650,
         668,  683,  702,  720,  734,  746,  765,  783,
         806,  824,  840,  855,  868,  881,  894,  909,
         915,  920,  933,  949,  960,  975,  987, 1001,
        1017, 1034, 1045, 1058, 1074, 1086, 1103, 1119,
        1132, 1146, 1161, 1172, 1184, 1196, 1211, 1223,
        1241, 1255, 1269, 1281, 1294, 1307, 1320,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidabright6x12biData
};
