//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidasans
//     Size: 6x11
//     Bold: no
//     Italic: yes
//     Memory usage: 1464 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidasans6x11iData[1264] =
{
      5,   7,   0,   9,  80,  11,   7, 240,  17,  97,  81,  97,
    193,  97, 240,  80,  11,   7, 113,  17,  65,  17,  65,  17,
      0,   6,  80,  19,   7, 240,  33,  17,  65,  17,  35,  18,
     33,  17,  35,  18,  33,  17,  65,  17, 240,  32,  16,   7,
    161,  84,  33,  17,  65,  17,  82,  81,  17,  65,  17,  36,
     81, 176,  16,   7, 241,  81,  17,  33,  33,  33,  81,  81,
     33,  33,  33,  17,  81, 240,  17,   7, 240,  19,  49,  33,
     66,  66,  33,  17,  33,  17,  17,  34,  35,  33, 240,   8,
      7, 113,  97,  97,   0,   6, 112,  12,   7, 161,  81,  81,
     97,  81,  97,  97,  97, 113, 192,  12,   7, 145, 113,  97,
     97,  97,  81,  97,  81,  81, 208,  10,   7, 241,  18,  65,
     66,  17, 240, 240, 240,  10,   7, 240, 145,  97,  54,  49,
     97, 240, 160,   8,   7,   0,   6,  33,  97,  81, 208,   8,
      7, 240, 240,  82, 240, 240, 160,   8,   7,   0,   6,  17,
     97, 240,  80,  12,   7, 193,  97,  81,  81,  97,  81,  81,
     81,  97, 208,  17,   7, 240,  18,  65,  33,  49,  33,  33,
     49,  33,  33,  49,  33,  66, 240,  48,  12,   7, 240,  17,
     67,  97,  82,  81,  97,  97, 240,  64,  11,   7, 243, 113,
     97,  66,  65,  81, 100, 240,  32,  11,   7, 243, 113,  97,
     66,  97,  97,  51, 240,  48,  15,   7, 240,  34,  65,  17,
     49,  33,  33,  33,  53,  81,  97, 240,  32,  12,   7, 240,
     20,  33,  99, 113,  97,  81,  51, 240,  48,  14,   7, 240,
     35,  49,  81,  99,  49,  49,  33,  49,  51, 240,  32,  11,
      7, 245,  97,  81,  81,  81,  81,  81, 240,  80,  16,   7,
    240,  18,  65,  33,  49,  33,  51,  49,  49,  33,  49,  51,
    240,  32,  14,   7, 240,  19,  49,  49,  33,  49,  51,  97,
     81,  51, 240,  48,  10,   7, 240, 113,  97, 240,  65,  97,
    240,  80,  10,   7, 240, 129,  97, 240,  65,  97,  81, 208,
     10,   7, 240, 162,  50,  50, 113, 113, 240, 144,   7,   7,
    240, 229, 133, 240, 240,  10,   7, 240, 129, 113, 114,  50,
     50, 240, 176,  11,   7, 242,  65,  33,  97,  66, 177,  97,
    240,  80,  15,   7, 240,  35,  49,  49,  17,  36,  33,  17,
     17,  37, 116, 240,  16,  16,   7, 240,  49,  82,  65,  17,
     49,  33,  52,  33,  49,  33,  49, 240,  16,  15,   7, 242,
     81,  17,  65,  17,  51,  65,  33,  49,  33,  51, 240,  48,
     12,   7, 240,  20,  33,  81,  97,  97,  97, 116, 240,  16,
     16,   7, 244,  49,  49,  33,  49,  18,  49,  17,  65,  17,
     49,  36, 240,  32,  11,   7, 244,  49,  97,  84,  49,  97,
    100, 240,  32,  11,   7, 244,  49,  97,  84,  49,  97,  97,
    240,  80,  15,   7, 240,  20,  33,  81,  97,  49,  33,  49,
     33,  49,  51, 240,  32,  17,   7, 241,  33,  49,  33,  49,
     33,  37,  33,  33,  49,  33,  49,  33, 240,  32,  11,   7,
    241,  97,  97,  82,  81,  97,  97, 240,  80,  12,   7, 240,
     33,  97,  97,  82,  81,  97,  97,  66, 192,  17,   7, 241,
     49,  33,  33,  49,  17,  51,  65,  17,  65,  33,  49,  49,
    240,  16,  11,   7, 241,  97,  97,  82,  81,  97, 100, 240,
     32,  18,   7, 241,  65,  18,  34,  17,  18,  19,  17,  34,
     33,  17,  17,  65,  17,  65, 240,  20,   7, 242,  33,  34,
     33,  33,  17,  17,  33,  17,  17,  17,  34,  33,  49,  33,
     49, 240,  16,  17,   7, 240,  19,  49,  49,  17,  65,  17,
     65,  17,  65,  17,  49,  51, 240,  32,  13,   7, 243,  65,
     33,  49,  33,  36,  49,  97,  97, 240,  80,  17,   7, 240,
     19,  49,  49,  17,  65,  17,  65,  17,  65,  17,  49,  51,
    113, 113,  16,   7, 243,  65,  33,  49,  33,  36,  49,  17,
     65,  33,  49,  49, 240,  16,  12,   7, 240,  19,  49,  97,
    113, 113,  97,  51, 240,  48,  11,   7, 229,  65,  97,  82,
     81,  97,  97, 240,  64,  17,   7, 241,  49,  33,  49,  33,
     49,  17,  49,  33,  49,  33,  33,  66, 240,  48,  16,   7,
    225,  49,  33,  49,  33,  33,  49,  33,  49,  17,  66,  81,
    240,  80,  19,   7, 225,  82,  33,  34,  33,  34,  18,  17,
     17,  18,  17,  18,  18,  33,  33, 240,  32,  15,   7, 241,
     33,  49,  33,  51,  81,  83,  49,  33,  49,  33, 240,  32,
     14,   7, 225,  49,  33,  49,  33,  33,  66,  81,  97,  97,
    240,  64,  11,   7, 245,  81,  81,  81,  81,  81, 101, 240,
     16,  12,   7, 146,  81,  97,  81,  97,  97,  81,  97,  98,
    192,  12,   7, 113,  97, 113,  97, 113, 113,  97, 113,  97,
    144,  12,   7, 146,  97,  97,  81,  97,  97,  81,  97,  82,
    192,  15,   7, 240,  49,  82,  65,  17,  49,  33,  33,  49,
     33,  49, 240, 128,   6,   7,   0,   7, 117, 144,   7,   7,
      1, 113,   0,   8,  64,  16,   7, 240, 131,  49,  33,  33,
     49,  33,  33,  49,  18,  50,  17, 240,  32,  17,   7, 145,
     97,  81,  18,  50,  17,  49,  33,  33,  49,  33,  33,  51,
    240,  48,  11,   7, 240, 130,  65,  81,  97,  97, 114, 240,
     48,  17,   7, 193,  97,  51,  49,  33,  33,  49,  33,  33,
     49,  18,  50,  17, 240,  32,  13,   7, 240, 131,  49,  33,
     33,  33,  51,  65, 115, 240,  32,  13,   7, 162,  65,  84,
     65,  81,  97,  97,  81,  97,  97,  96,  17,   7, 240, 131,
     49,  33,  33,  49,  33,  33,  49,  18,  50,  17,  97,  51,
     64,  18,   7, 145,  97,  81,  18,  50,  17,  49,  33,  33,
     33,  49,  33,  49,  33, 240,  32,  11,   7, 145, 193,  97,
     97,  81,  97,  97, 240,  80,  12,   7, 177, 193,  97,  97,
     81,  97,  97,  81,  82,  80,  17,   7, 145,  97,  81,  33,
     49,  17,  66,  65,  17,  65,  33,  49,  49, 240,  16,  12,
      7, 145,  97,  81,  97,  97,  81,  97,  97, 240,  80,  18,
      7, 240, 113,  18,  17,  18,  18,  33,  33,  33,  33,  34,
     33,  34,  33,  33, 224,  17,   7, 240, 113,  18,  50,  17,
     49,  33,  33,  33,  49,  33,  49,  33, 240,  32,  15,   7,
    240, 130,  65,  33,  33,  49,  33,  49,  33,  33,  66, 240,
     48,  17,   7, 240, 129,  18,  50,  17,  49,  33,  33,  49,
     33,  33,  51,  49,  97,  96,  17,   7, 240, 131,  49,  33,
     33,  49,  33,  33,  49,  18,  50,  17,  81,  97,  64,  12,
      7, 240, 113,  17,  67,  65,  81,  97,  97, 240,  80,  11,
      7, 240, 131,  49,  98,  98,  97,  51, 240,  48,  12,   7,
    240,  17,  68,  65,  97,  81,  97,  98, 240,  64,  17,   7,
    240, 113,  33,  49,  33,  49,  33,  33,  33,  49,  18,  50,
     17, 240,  32,  15,   7, 240,  97,  33,  49,  33,  49,  33,
     49,  17,  66,  81, 240,  80,  17,   7, 240,  97,  82,  33,
     34,  33,  34,  18,  17,  18,  18,  33,  33, 240,  32,  15,
      7, 240, 129,  33,  49,  17,  66,  82,  65,  17,  49,  33,
    240,  32,  17,   7, 240, 129,  33,  49,  33,  49,  33,  49,
     17,  65,  17,  66,  81,  66,  80,  11,   7, 240, 116,  81,
     81,  81,  81, 100, 240,  32,  12,   7, 177,  81,  81,  97,
     66, 113,  81,  97, 113, 176,  12,   7, 145,  97,  97,  81,
     97,  97,  81,  97,  97, 208,  12,   7, 145, 113,  97,  81,
    114,  65,  97,  81,  81, 208,  10,   7, 240, 226,  33,  17,
     34, 240, 240, 112,
};

const tFont g_sFontlucidasans6x11i =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    7,

    //
    // The height of the font.
    //
    11,

    //
    // The baseline of the font.
    //
    9,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   16,   27,   46,   62,   78,   95,
         103,  115,  127,  137,  147,  155,  163,  171,
         183,  200,  212,  223,  234,  249,  261,  275,
         286,  302,  316,  326,  336,  346,  353,  363,
         374,  389,  405,  420,  432,  448,  459,  470,
         485,  502,  513,  525,  542,  553,  571,  591,
         608,  621,  638,  654,  666,  677,  694,  710,
         729,  744,  758,  769,  781,  793,  805,  820,
         826,  833,  849,  866,  877,  894,  907,  920,
         937,  955,  966,  978,  995, 1007, 1025, 1042,
        1057, 1074, 1091, 1103, 1114, 1126, 1143, 1158,
        1175, 1190, 1207, 1218, 1230, 1242, 1254,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidasans6x11iData
};
