//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidasans
//     Size: 5x9
//     Bold: no
//     Italic: no
//     Memory usage: 1168 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidasans5x9Data[968] =
{
      4,   6,   0,   6,   9,   6,   1,  81,  81,  81, 177, 240,
     32,   7,   6,   2,  66, 240, 240, 160,  10,   6,  35,  21,
     33,  17,  37,  34,  51, 240,  10,   6,   3,  50,  66,  82,
     66,  51,  65, 160,  11,   6,   2,  17,  35,  51,  67,  51,
     33,  18, 224,  11,   6,  18,  66,  65,  68,  33,  18,  50,
     97, 128,   7,   6,   1,  81, 240, 240, 176,  11,   6,  17,
     65,  81,  81,  81,  81,  81,  97,  64,  11,   6,   1,  97,
     81,  81,  81,  81,  81,  65,  80,   9,   6,  17,  67,  49,
     17, 240, 240,  48,   8,   6, 129,  81,  53,  49,  81, 240,
      7,   6, 240, 241,  81,  81,  80,   6,   6, 240,  50, 240,
    208,   6,   6, 240, 241, 240,  32,  11,   6,  49,  66,  65,
     81,  65,  81,  66,  65,  80,  13,   6,  18,  49,  33,  33,
     33,  33,  33,  33,  33,  50, 240,  10,   6,   2,  81,  81,
     81,  81,  81, 240,  16,   9,   6,   3,  97,  81,  50,  50,
     68, 224,   9,   6,   3,  97,  50,  82,  81,  35, 240,  10,
      6,  34,  51,  34,  17,  37,  65,  81, 224,  10,   6,   3,
     49,  83,  81,  81,  50, 240,  16,  11,   6,  19,  33,  83,
     49,  33,  33,  33,  50, 240,  10,   6,   4,  81,  65,  65,
     66,  65, 240,  32,  12,   6,  19,  33,  33,  50,  49,  18,
     33,  33,  50, 240,  11,   6,  18,  49,  33,  33,  33,  51,
     81,  35, 240,   7,   6, 193, 240,  33, 240,  32,   8,   6,
    193, 240,  33,  81,  81,  80,   8,   6, 161,  50,  34,  98,
     97, 208,   7,   6, 240,  53,  21, 240,  64,   9,   6,  97,
     98,  98,  34,  49, 240,  32,  10,   6,   3,  81,  81,  65,
     81,  81, 240,  16,  12,   6,  36,  17,  20,  17,  17,  17,
     18,  38,  20, 208,  12,   6,  33,  67,  49,  17,  51,  33,
     49,  17,  49, 208,  12,   6,   4,  33,  33,  35,  49,  18,
     33,  33,  35, 240,  10,   6,  20,  18,  65,  81,  82,  33,
     36, 208,  13,   6,   4,  33,  34,  17,  49,  17,  49,  17,
     49,  20, 224,   9,   6,   4,  33,  83,  49,  81,  84, 224,
     10,   6,   3,  49,  81,  83,  49,  81, 240,  32,  11,   6,
     20,  18,  65,  81,  49,  18,  33,  36, 208,  14,   6,   1,
     33,  33,  33,  36,  33,  33,  33,  33,  33,  33, 224,  10,
      6,   1,  81,  81,  81,  81,  81, 240,  32,  11,   6,  33,
     81,  81,  81,  81,  81,  81,  50,  64,  13,   6,   1,  18,
     33,  17,  50,  66,  65,  17,  49,  33, 224,   9,   6,   1,
     81,  81,  81,  81,  84, 224,  17,   6,   1,  49,  18,  18,
     18,  18,  18,  18,  17,  17,  17,  17,  17,  17, 208,  15,
      6,   1,  33,  34,  17,  34,  17,  33,  18,  33,  18,  33,
     33, 224,  13,   6,  19,  34,  18,  17,  49,  17,  49,  18,
     18,  35, 224,  12,   6,   4,  33,  33,  33,  33,  35,  49,
     81, 240,  32,  14,   6,  19,  34,  18,  17,  49,  17,  49,
     18,  18,  35,  97,  97,  13,   6,   3,  49,  17,  49,  17,
     50,  65,  17,  49,  33, 224,   9,   6,   3,  49,  82,  82,
     81,  51, 240,   9,   6,   5,  49,  81,  81,  81,  81, 240,
     14,   6,   1,  33,  33,  33,  33,  33,  33,  33,  33,  33,
     36, 224,  13,   6,   1,  49,  17,  49,  33,  17,  49,  17,
     51,  65, 240,  15,   6,   1,  33,  33,  33,  50,  18,  18,
     18,  18,  18,  18,  18, 192,  13,   6,   2,  33,  33,  17,
     65,  66,  65,  17,  33,  49, 208,  12,   6,   1,  49,  33,
     17,  49,  17,  65,  81,  81, 240,   9,   6,   4,  66,  65,
     65,  66,  68, 224,  11,   6,   2,  65,  81,  81,  81,  81,
     81,  82,  64,  11,   6,   1,  82,  81,  81,  97,  81,  82,
     81,  32,  11,   6,   2,  81,  81,  81,  81,  81,  81,  66,
     64,  12,   6,  33,  81,  65,  17,  49,  17,  33,  49, 240,
     64,   6,   6, 240, 240,  99, 144,   6,   6,   2,   0,   5,
     96,   9,   6, 195,  66,  49,  17,  50,  17, 224,  11,   6,
      1,  81,  83,  49,  33,  33,  33,  35, 240,   7,   6, 210,
     49,  81,  98, 240,  11,   6,  49,  81,  51,  33,  33,  33,
     33,  51, 224,   7,   6, 210,  52,  33,  99, 224,  10,   6,
     18,  65,  67,  65,  81,  81, 240,  16,  11,   6, 211,  33,
     33,  33,  33,  51,  81,  35,  48,  12,   6,   1,  81,  83,
     49,  17,  49,  17,  49,  17, 240,   9,   6,   1, 177,  81,
     81,  81, 240,  32,  10,   6,  17, 177,  81,  81,  81,  81,
     66,  64,  11,   6,   1,  81,  81,  18,  35,  51,  49,  18,
    224,  10,   6,   1,  81,  81,  81,  81,  81, 240,  32,  13,
      6, 197,  17,  17,  17,  17,  17,  17,  17,  17,  17, 208,
     10,   6, 195,  49,  17,  49,  17,  49,  17, 240,   9,   6,
    210,  49,  33,  33,  33,  50, 240,  11,   6, 195,  49,  33,
     33,  33,  35,  49,  81,  80,  11,   6, 211,  33,  33,  33,
     33,  51,  81,  81,  32,   8,   6, 195,  49,  81,  81, 240,
     32,   7,   6, 195,  50,  97,  51, 240,   9,   6,  17,  81,
     67,  65,  81,  82, 240,  10,   6, 193,  17,  49,  17,  49,
     17,  51, 240,   9,   6, 193,  33,  33,  18,  50,  66, 240,
     11,   6, 193,  18,  18,  18,  17,  20,  33,  33, 208,   9,
      6, 193,  33,  50,  66,  49,  33, 224,  11,   6, 193,  33,
     34,  17,  50,  66,  66,  65,  64,   7,   6, 196,  65,  65,
     68, 224,  11,   6,  18,  65,  81,  81,  66,  81,  81,  82,
     48,  11,   6,   1,  81,  81,  81,  81,  81,  81,  81,  80,
     11,   6,   2,  81,  81,  82,  65,  81,  81,  66,  64,   9,
      6, 240,  51,  17,  17,  19, 240,  64,
};

const tFont g_sFontlucidasans5x9 =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    6,

    //
    // The height of the font.
    //
    8,

    //
    // The baseline of the font.
    //
    6,

    //
    // The offset to each character in the font.
    //
    {
           0,    4,   13,   20,   30,   40,   51,   62,
          69,   80,   91,  100,  108,  115,  121,  127,
         138,  151,  161,  170,  179,  189,  199,  210,
         220,  232,  243,  250,  258,  266,  273,  282,
         292,  304,  316,  328,  338,  351,  360,  370,
         381,  395,  405,  416,  429,  438,  455,  470,
         483,  495,  509,  522,  531,  540,  554,  567,
         582,  595,  607,  616,  627,  638,  649,  661,
         667,  673,  682,  693,  700,  711,  718,  728,
         739,  751,  760,  770,  781,  791,  804,  814,
         823,  834,  845,  853,  860,  869,  879,  888,
         899,  908,  919,  926,  937,  948,  959,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidasans5x9Data
};
