//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidabright
//     Size: 6x12
//     Bold: no
//     Italic: no
//     Memory usage: 1512 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidabright6x12Data[1312] =
{
      4,   8,   0,  10,  11,   8,   1, 113, 113, 113, 113, 113,
    241, 240, 128,   8,   8,   2,  98,  98,   0,   7,  96,  18,
      8,  33,  17,  81,  17,  54,  65,  17,  65,  17,  70,  49,
     17,  81,  17, 240,  80,  12,   8,  18,  83,  82,  98, 114,
     98,  83,  82, 113, 224,  22,   8,  17,  49,  33,  17,  17,
     49,  19,  65,  17,  97,  17,  67,  17,  49,  17,  17,  33,
     49, 240,  64,  19,   8,  19,  81,  17,  81,  17,  82,  81,
     17,  18,  33,  19,  49,  33,  82,  18, 240,  48,   8,   8,
      1, 113, 113,   0,   7, 112,  13,   8,  17,  97, 113, 113,
    113, 113, 113, 113, 113, 129,  96,  13,   8,   1, 129, 113,
    113, 113, 113, 113, 113, 113,  97, 112,   9,   8,  17, 100,
     82,  98,   0,   6,  80,  11,   8, 177, 113, 113,  71,  65,
    113, 113, 240,  80,   8,   8,   0,   7,   1, 113, 113, 112,
      8,   8, 240, 240, 162, 240, 240, 128,   7,   8,   0,   7,
      1, 240, 128,  13,   8,  65,  98,  97, 113,  97, 113,  97,
    113,  98,  97, 112,  18,   8,  19,  65,  49,  49,  49,  49,
     49,  49,  49,  49,  49,  49,  49,  67, 240,  80,  12,   8,
      2, 113, 113, 113, 113, 113, 113,  99, 240,  96,  13,   8,
      3,  81,  33, 113, 113,  97,  97,  97, 116, 240,  80,  14,
      8,   3,  81,  33, 113,  82, 114, 113,  65,  33,  67, 240,
     96,  14,   8,  49,  98,  81,  17,  65,  33,  69,  97, 113,
     99, 240,  64,  13,   8,   4,  65, 113, 115, 129, 113,  65,
     33,  67, 240,  96,  16,   8,  20,  65,  33,  49, 116,  65,
     49,  49,  49,  50,  33,  67, 240,  80,  12,   8,   5, 113,
     97,  97,  98,  97,  98,  97, 240, 128,  17,   8,  19,  65,
     49,  49,  34,  66,  81,  33,  65,  49,  49,  49,  67, 240,
     80,  16,   8,  19,  65,  34,  49,  49,  49,  49,  68, 113,
     49,  33,  67, 240,  96,   9,   8, 240, 145, 240, 240,  17,
    240, 128,  10,   8, 240, 145, 240, 240,  17, 113, 113, 112,
     11,   8, 209,  82,  66,  82, 114, 130, 129, 240,  48,   8,
      8, 240, 240,  38, 166, 240, 176,  11,   8, 129, 130, 130,
    114,  82,  66,  81, 240, 128,  12,   8,   3,  81,  17, 113,
     97, 113, 113, 241, 240, 112,  20,   8,  52,  34,  50,  17,
     19,  18,  17,  17,  34,  17,  18,  18,  18,  18,  18, 116,
    240,  64,  16,   8,  49,  98,  99,  81,  17,  68,  65,  49,
     33,  65,  34,  35, 240,  32,  17,   8,   5,  65,  33,  65,
     33,  67,  81,  18,  65,  33,  65,  33,  53, 240,  64,  14,
      8,  36,  49,  49,  33, 113, 113, 113, 129,  49,  67, 240,
     64,  18,   8,   5,  65,  49,  49,  65,  33,  65,  33,  65,
     33,  65,  33,  49,  37, 240,  64,  16,   8,   5,  65,  33,
     65,  17,  83,  81,  17,  81, 113,  33,  53, 240,  64,  15,
      8,   5,  65,  33,  65,  17,  83,  81,  17,  81, 113,  98,
    240, 112,  16,   8,  36,  49,  49,  33, 113, 113,  51,  17,
     65,  49,  49,  68, 240,  48,  19,   8,   3,  19,  33,  49,
     49,  49,  53,  49,  49,  49,  49,  49,  49,  35,  19, 240,
     32,  12,   8,   3,  97, 113, 113, 113, 113, 113,  99, 240,
     96,  14,   8,  34,  97, 113, 113, 113, 113, 113, 113,  81,
     17,  82,  96,  18,   8,   3,  18,  49,  34,  49,  18,  66,
     99,  81,  18,  65,  34,  35,  19, 240,  32,  13,   8,   3,
     97, 113, 113, 113, 113, 113,  33,  53, 240,  64,  24,   8,
      2,  66,  18,  34,  34,  34,  33,  17,  18,  33,  18,  17,
     33,  18,  17,  33,  33,  17,  19,  35, 240,  16,  22,   8,
      2,  35,  34,  33,  50,  33,  49,  17,  17,  49,  17,  17,
     49,  34,  49,  49,  35,  33, 240,  48,  18,   8,  35,  65,
     49,  33,  81,  17,  81,  17,  81,  17,  81,  33,  49,  67,
    240,  64,  15,   8,   4,  81,  33,  65,  33,  65,  33,  67,
     81, 113,  99, 240,  96,  18,   8,  35,  65,  49,  33,  81,
     17,  81,  17,  81,  17,  81,  33,  50,  52,  98, 130,  18,
      8,   4,  81,  33,  65,  33,  65,  33,  67,  81,  17,  81,
     33,  51,  18, 240,  48,  14,   8,  19,  65,  33,  65, 129,
    130, 113,  65,  33,  67, 240,  96,  12,   8,   7,  65, 113,
    113, 113, 113, 113,  99, 240,  64,  19,   8,   3,  19,  33,
     49,  49,  49,  49,  49,  49,  49,  49,  49,  49,  49,  67,
    240,  64,  18,   8,   3,  34,  33,  65,  33,  49,  65,  33,
     65,  17,  81,  17,  98,  97, 240,  80,  26,   8,   3,  17,
     33,  17,  33,  65,  33,  33,  17,  17,  17,  17,  17,  17,
     17,  17,  34,  18,  49,  49,  49,  49, 240,  32,  18,   8,
      3,  34,  33,  49,  65,  17,  98,  83,  66,  17,  65,  49,
     34,  35, 240,  32,  15,   8,   3,  34,  33,  49,  65,  33,
     67,  97, 113, 113,  99, 240,  64,  14,   8,   5,  49,  33,
    113,  97, 113,  97, 113,  33,  53, 240,  64,  13,   8,   2,
     97, 113, 113, 113, 113, 113, 113, 113, 114,  96,  13,   8,
      1, 114, 113, 113, 129, 113, 129, 113, 114, 113,  48,  13,
      8,   2, 113, 113, 113, 113, 113, 113, 113, 113,  98,  96,
     15,   8,  49,  98,  98,  81,  33,  65,  33,  50,  49,  33,
     65, 240, 176,   6,   8,   0,   8,   4, 192,   6,   8,   2,
      0,   9,  96,  12,   8, 240, 148, 113,  83,  65,  33,  67,
     17, 240,  64,  15,   8,   2, 113, 113, 116,  65,  49,  49,
     49,  49,  49,  52, 240,  64,  11,   8, 240, 163,  65,  33,
     65, 113, 131, 240,  80,  15,   8,  50, 113, 113,  68,  49,
     49,  49,  49,  49,  49,  69, 240,  48,  11,   8, 240, 162,
     81,  33,  68,  65, 131, 240,  80,  13,   8,  19,  81,  17,
     81,  99,  97, 113, 113,  99, 240,  96,  14,   8, 240, 164,
     49,  33,  65,  33,  82,  85,  49,  49,  52,  64,  15,   8,
      2, 113, 113, 116,  65,  33,  65,  33,  65,  33,  54, 240,
     48,  11,   8,  17, 240, 114, 113, 113, 113,  99, 240,  96,
     13,   8,  33, 240, 114, 113, 113, 113, 113,  81,  17,  83,
     80,  16,   8,   2, 113, 113, 113,  34,  49,  18,  66,  97,
     18,  51,  18, 240,  48,  12,   8,   2, 113, 113, 113, 113,
    113, 113,  99, 240,  96,  15,   8, 240, 152,  17,  33,  33,
     17,  33,  33,  17,  33,  41, 240,  16,  13,   8, 240, 149,
     65,  33,  65,  33,  65,  33,  54, 240,  48,  13,   8, 240,
    163,  65,  49,  49,  49,  49,  49,  67, 240,  80,  14,   8,
    240, 149,  65,  49,  49,  49,  49,  49,  52,  65,  99,  80,
     14,   8, 240, 164,  49,  49,  49,  49,  49,  49,  68, 113,
     99,  32,  11,   8, 240, 148,  81,  17,  81, 113,  99, 240,
     96,  12,   8, 240, 148,  65,  33,  82,  81,  33,  68, 240,
     80,  12,   8,  17, 113, 113,  99,  97, 113, 113, 114, 240,
     96,  14,   8, 240, 146,  18,  65,  33,  65,  33,  65,  33,
     69, 240,  48,  13,   8, 240, 146,  33,  65,  33,  65,  17,
     98,  97, 240,  96,  18,   8, 240, 146,  33,  18,  17,  18,
     33,  17,  18,  17,  34,  34,  49,  33, 240,  48,  14,   8,
    240, 147,  18,  50,  17,  82,  81,  18,  50,  19, 240,  48,
     14,   8, 240, 147,  18,  49,  49,  49,  33,  83,  82,  97,
     98,  80,  12,   8, 240, 148,  65,  17,  98,  97,  17,  68,
    240,  80,  13,   8,  33,  97, 113, 113, 113,  98, 113, 113,
    113, 114,  80,  13,   8,   1, 113, 113, 113, 113, 113, 113,
    113, 113, 113, 112,  13,   8,   1, 129, 113, 113, 113, 114,
     97, 113, 113,  98,  96,  11,   8, 240, 240,  51,  33,  17,
     51, 240, 240,  48,
};

const tFont g_sFontlucidabright6x12 =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    8,

    //
    // The height of the font.
    //
    10,

    //
    // The baseline of the font.
    //
    8,

    //
    // The offset to each character in the font.
    //
    {
           0,    4,   15,   23,   41,   53,   75,   94,
         102,  115,  128,  137,  148,  156,  164,  171,
         184,  202,  214,  227,  241,  255,  268,  284,
         296,  313,  329,  338,  348,  359,  367,  378,
         390,  410,  426,  443,  457,  475,  491,  506,
         522,  541,  553,  567,  585,  598,  622,  644,
         662,  677,  695,  713,  727,  739,  758,  776,
         802,  820,  835,  849,  862,  875,  888,  903,
         909,  915,  927,  942,  953,  968,  979,  992,
        1006, 1021, 1032, 1045, 1061, 1073, 1088, 1101,
        1114, 1128, 1142, 1153, 1165, 1177, 1191, 1204,
        1222, 1236, 1250, 1262, 1275, 1288, 1301,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidabright6x12Data
};
