//*****************************************************************************
//
// Copyright 1988 Bitstream, Inc., Cambridge, Massachusetts, USA
// Bitstream and Charter are registered trademarks of Bitstream, Inc.
// 
// The names "Bitstream" and "Charter" are registered trademarks of
// Bitstream, Inc.  Permission to use these trademarks is hereby
// granted only in association with the images described in this file.
// 
// Permission to use, copy, modify, and distribute this software and
// its documentation for any purpose and without fee is hereby
// granted, provided that the above copyright notice appear in all
// copies and that both that copyright notice and this permission
// notice appear in supporting documentation, and that the name of
// Bitstream not be used in advertising or publicity pertaining to
// distribution of the software without specific, written prior
// permission.  Bitstream makes no representations about the
// suitability of this software for any purpose.  It is provided "as
// is" without express or implied warranty.
// 
// BITSTREAM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN
// NO EVENT SHALL BITSTREAM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
// OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
// NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
// CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
// 
// Copyright (c) 1987, 1994 Digital Equipment Corporation
// 
// The X Consortium, and any party obtaining a copy of these files from
// the X Consortium, directly or indirectly, is granted, free of charge, a
// full and unrestricted irrevocable, world-wide, paid up, royalty-free,
// nonexclusive right and license to deal in this software and
// documentation files (the "Software"), including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons who receive
// copies from any such party to do so.  This license includes without
// limitation a license to do the foregoing actions under any patents of
// the party supplying this software to the X Consortium.
// 
// Digital Equipment Corporation make no representations about the
// suitability of this software for any purpose.  It is provided "as
// is" without express or implied warranty.
// 
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Charter
//     Size: 5x10
//     Bold: yes
//     Italic: yes
//     Memory usage: 1292 bytes
//
//*****************************************************************************

static const uint8_t g_pui8charter5x10biData[1089] =
{
      4,   8,   0,   8,   9,   8,  17, 113, 113,  97, 241, 240,
    128,   9,   8,   1,  17,  81,  17,   0,   6,  80,  13,   8,
     33,  17,  82,  69,  65,  17,  69,  66,  81,  17, 208,  11,
      8,  34,  83,  82, 114,  66,  17,  67,  97, 224,  20,   8,
     17,  49,  33,  17,  17,  49,  18,  17,  49,  18,  17,  49,
     17,  17,  33,  49, 240,  48,  16,   8,  34,  81,  18,  66,
     34,  17,  18,  17,  34,  18,  66,  19, 240,  32,   8,   8,
    146, 113,  82, 240, 240, 128,  10,   8,  33,  97,  97, 113,
    113, 113, 129, 224,  10,   8,  17, 129, 113, 113, 113,  97,
     97, 240,   9,   8,  17,  97,  17,  82,   0,   5,  96,   9,
      8, 161, 113,  85,  81, 113, 240,  96,   8,   8, 240, 240,
    161, 113, 113, 112,   7,   8, 240, 240,  35, 240, 224,   7,
      8, 240, 240, 161, 240, 128,  10,   8,  81,  97,  97, 113,
     97,  97,  97, 240,  14,   8,  18,  97,  17,  65,  33,  65,
     33,  65,  17,  98, 240,  96,  10,   8,  18,  98, 113,  97,
    113,  99, 240,  96,  12,   8,  34,  81,  17, 113,  97,  97,
     17,  68, 240,  80,  11,   8,  34,  81,  17, 113,  82, 129,
     67, 240,  96,  12,   8,  49,  98,  81,  17,  65,  33,  69,
     82, 240,  80,  11,   8,  20,  65, 115, 113,  65,  33,  82,
    240,  96,  12,   8,  34,  81, 100,  65,  33,  65,  33,  82,
    240,  96,  11,   8,   4,  65,  33,  97,  97, 113,  97, 240,
    128,  14,   8,  19,  81,  17,  66,  17,  65,  18,  65,  33,
     82, 240,  96,  12,   8,  18,  81,  33,  65,  33,  68,  97,
     82, 240, 112,   8,   8, 240,  18, 240, 114, 240, 112,   9,
      8, 240,  33, 240, 129, 113,  97, 112,   9,   8, 240,  66,
     51,  98, 130, 240,  64,   7,   8, 240,  21, 181, 240, 192,
      9,   8, 240,  18, 131,  82,  66, 240, 112,  10,   8,  19,
     65,  33,  98,  81, 226, 240, 112,  18,   8,  50,  66,  33,
     49,  18,  17,  17,  17,  17,  17,  17,  20,  49,  49,  67,
    176,  13,   8,  50,  83,  81,  17,  68,  65,  33,  50,  19,
    240,  48,  13,   8,  20,  66,  17,  67,  81,  33,  65,  33,
     52, 240,  80,  12,   8,  36,  49,  49,  33, 113, 114,  33,
     68, 240,  64,  14,   8,  21,  66,  33,  49,  49,  34,  49,
     34,  33,  37, 240,  64,  12,   8,  20,  66,  99,  81,  17,
     81,  33,  52, 240,  80,  11,   8,  20,  66,  99,  81,  17,
     81,  99, 240,  96,  13,   8,  36,  49,  49,  33, 113,  35,
     33,  34,  67, 240,  80,  13,   8,  22,  34,  33,  53,  49,
     34,  49,  34,  38, 240,  48,  10,   8,  19,  97,  98,  98,
     97,  99, 240,  96,  11,   8,  35,  97, 113,  98,  65,  17,
     82, 240, 112,  15,   8,  18,  18,  50,  17,  65,  17,  83,
     81,  18,  50,  34, 240,  48,  11,   8,  19,  97,  98,  98,
     97,  33,  53, 240,  64,  19,   8,  18,  50,  19,  18,  36,
     17,  33,  18,  17,  33,  17,  18,  18,  17,  18, 240,  32,
     17,   8,  18,  34,  35,  17,  49,  17,  17,  49,  19,  49,
     19,  34,  33, 240,  64,  14,   8,  35,  65,  49,  33,  65,
     33,  65,  33,  49,  67, 240,  80,  12,   8,  21,  66,  17,
     65,  33,  52,  66,  83, 240,  96,  15,   8,  35,  65,  49,
     33,  65,  33,  65,  33,  49,  68,  98,  99,  32,  14,   8,
     20,  66,  17,  66,  17,  67,  81,  18,  51,  18, 240,  48,
     12,   8,  35,  65,  17,  82, 114,  65,  33,  67, 240,  96,
     12,   8,   6,  33,  18,  17,  65, 113,  98,  84, 240,  80,
     15,   8,   2,  34,  34,  33,  49,  49,  49,  49,  49,  33,
     67, 240,  96,  14,   8,   3,  18,  49,  33,  65,  33,  65,
     17,  83,  82, 240,  96,  19,   8,   3,  18,  17,  17,  34,
     17,  17,  19,  17,  17,  20,  34,  34,  33,  49, 240,  48,
     14,   8,  18,  18,  65,  17,  82,  98,  81,  18,  50,  18,
    240,  64,  12,   8,   3,  18,  49,  33,  67,  97, 113,  99,
    240,  80,  12,   8,  20,  65,  17,  98,  82,  97,  33,  52,
    240,  80,  10,   8,  19,  81, 113, 113,  98,  98,  99, 208,
     10,   8,   1, 129, 113, 129, 113, 113, 129, 192,  10,   8,
     18, 113, 113, 113,  97, 113,  98, 224,   8,   8,  19,  65,
     49,   0,   6,  48,   6,   8,   0,   7,   4,  64,   8,   8,
    145,  97, 114, 240, 240, 128,  11,   8, 240,  36,  49,  34,
     49,  33,  69, 240,  64,  12,   8,   2, 113, 100,  65,  33,
     65,  33,  67, 240,  96,  10,   8, 240,  34,  81,  17,  81,
    115, 240,  96,  12,   8,  50,  98,  68,  49,  33,  65,  33,
     69, 240,  64,  10,   8, 240,  35,  65,  33,  67,  84, 240,
     80,  12,   8,  66,  81,  17,  67,  82,  98,  97, 113,  82,
     96,  12,   8, 240,  51,  65,  17,  82,  98,  81,  33,  82,
     80,  13,   8,  18,  98, 100,  65,  33,  65,  18,  50,  19,
    240,  48,   9,   8,  17, 226,  97, 113, 114, 240, 112,  10,
      8,  49, 226,  97, 113, 113, 113,  82,  96,  13,   8,   3,
     97, 113,  18,  66,  97,  17,  66,  18, 240,  64,  10,   8,
      2, 113,  98,  97, 113, 114, 240, 112,  16,   8, 240,  20,
     18,  33,  18,  17,  18,  17,  18,  17,  33,  19, 240,  16,
     12,   8, 240,  21,  65,  33,  50,  18,  50,  19, 240,  48,
     11,   8, 240,  34,  81,  33,  65,  33,  82, 240,  96,  12,
      8, 240,  37,  65,  33,  50,  33,  52,  66,  84,  64,  12,
      8, 240,  35,  65,  33,  65,  33,  68,  97,  99,  64,  10,
      8, 240,  20,  81,  17,  66,  97, 240, 128,  11,   8, 240,
     35,  66,  17,  65,  18,  82, 240,  96,   9,   8, 145,  99,
     82,  97, 115, 240,  96,  12,   8, 240,  18,  18,  50,  18,
     50,  17,  70, 240,  48,  12,   8, 240,  18,  18,  65,  33,
     65,  17,  82, 240,  96,  15,   8, 240,  18,  18,  17,  33,
     18,  17,  34,  18,  49,  33, 240,  64,  10,   8, 240,  36,
     81,  83,  81,  34, 240,  64,  12,   8, 240,  18,  33,  65,
     17,  83,  97, 113,  82,  96,  11,   8, 240,  35,  65,  17,
     97,  17,  67, 240,  96,  10,   8,  18,  97, 113,  97, 129,
    113, 114, 208,  11,   8,   1, 113, 113, 113, 113, 113, 113,
    113, 112,  10,   8,   2, 113, 113, 129,  97, 113,  98, 224,
      9,   8, 146,  33,  33,  34, 240, 240, 208,
};

const tFont g_sFontcharter5x10bi =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    8,

    //
    // The height of the font.
    //
    8,

    //
    // The baseline of the font.
    //
    6,

    //
    // The offset to each character in the font.
    //
    {
           0,    4,   13,   22,   35,   46,   66,   82,
          90,  100,  110,  119,  128,  136,  143,  150,
         160,  174,  184,  196,  207,  219,  230,  242,
         253,  267,  279,  287,  296,  305,  312,  321,
         331,  349,  362,  375,  387,  401,  413,  424,
         437,  450,  460,  471,  486,  497,  516,  533,
         547,  559,  574,  588,  600,  612,  627,  641,
         660,  674,  686,  698,  708,  718,  728,  736,
         742,  750,  761,  773,  783,  795,  805,  817,
         829,  842,  851,  861,  874,  884,  900,  912,
         923,  935,  947,  957,  968,  977,  989, 1001,
        1016, 1026, 1038, 1049, 1059, 1070, 1080,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8charter5x10biData
};
