//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidabright
//     Size: 5x9
//     Bold: yes
//     Italic: yes
//     Memory usage: 1280 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidabright5x9biData[1078] =
{
      5,   7,   0,   7, 112,   9,   7, 129,  97,  97,  97, 193,
    240,  80,   9,   7, 113,  17,  65,  17,   0,   5,  96,  14,
      7, 145,  17,  37,  49,  17,  53,  33,  17,  65,  17, 240,
     48,  10,   7, 131,  67,  65,  98,  67,  67,  81, 192,  15,
      7, 130,  18,  17,  18,  50,  17,  83,  49,  19,  17,  34,
    240,  16,  13,   7, 162,  65,  17,  53,  17,  33,  17,  17,
     49,  53, 240,   8,   7, 113,  97,  97, 240, 240, 176,  11,
      7, 145,  81,  97,  81,  97,  97,  97,  97,  96,  12,   7,
     17, 113,  97,  97,  97,  97,  81,  97,  81,  96,   8,   7,
    129,  83,  66, 240, 240, 160,  10,   7, 240,  17,  97,  69,
     65,  97, 240,  48,   8,   7, 240, 240, 194,  97,  81,  96,
      7,   7, 240, 210, 240, 240,  48,   7,   7, 240, 240, 194,
    240,  64,  11,   7, 177,  81,  97,  81,  97,  81,  97,  81,
     96,  14,   7, 146,  65,  18,  33,  34,  33,  33,  49,  33,
     66, 240,  48,  10,   7, 130,  97,  97,  81,  97,  83, 240,
     48,  11,   7, 132,  49,  33,  82,  66,  65,  84, 240,  32,
     12,   7, 131,  65,  17,  66, 113,  49,  33,  51, 240,  48,
     11,   7, 162,  67,  49,  17,  53,  81,  83, 240,  16,  11,
      7, 132,  49,  98, 113,  49,  33,  51, 240,  48,  12,   7,
    147,  49,  84,  49,  33,  49,  33,  66, 240,  48,  10,   7,
    116,  81,  97,  81,  97,  81, 240,  80,  13,   7, 146,  65,
     33,  51,  49,  33,  49,  33,  52, 240,  32,  12,   7, 131,
     65,  18,  34,  18,  52,  81,  51, 240,  48,   8,   7, 240,
    113, 240,  65, 240,  80,   9,   7, 240, 113, 240,  65,  97,
     97,  96,  10,   7, 240,  49,  66,  50, 113, 113, 240,  32,
      7,   7, 240, 213,  37, 240, 128,   9,   7, 241, 114, 113,
     51,  49, 240,  80,  11,   7, 116,  49,  33,  81,  81,  82,
     81, 240,  80,  14,   7, 147,  51,  17,  18,  19,  18,  19,
     19,  18,  35, 240,  32,  13,   7, 162,  65,  17,  65,  17,
     52,  49,  33,  34,  34, 240,  13,   7, 132,  49,  33,  51,
     65,  17,  65,  18,  36, 240,  32,  11,   7, 148,  33,  49,
     18,  81,  98, 100, 240,  16,  14,   7, 133,  49,  49,  18,
     49,  18,  49,  17,  49,  21, 240,  16,  12,   7, 132,  50,
     17,  51,  65,  97,  17,  52, 240,  32,  11,   7, 132,  49,
     33,  51,  65,  97,  82, 240,  64,  13,   7, 148,  34,  33,
     18,  81,  35,  18,  33,  52, 240,  16,  14,   7, 131,  18,
     33,  33,  37,  33,  34,  33,  33,  34,  19, 240,  10,   7,
    131,  81,  97,  82,  81,  83, 240,  48,  12,   7, 147,  81,
     97,  82,  82,  81,  65,  17,  66,  80,  13,   7, 130,  18,
     51,  49,  17,  67,  65,  18,  34,  19, 240,  11,   7, 131,
     81,  82,  81,  97,  33,  37, 240,  16,  18,   7, 130,  49,
     33,  34,  18,  17,  17,  17,  18,  17,  17,  17,  17,  18,
     35, 224,  18,   7, 130,  34,  33,  33,  33,  17,  17,  33,
     17,  17,  33,  34,  18,  33, 240,  16,  14,   7, 147,  49,
     49,  18,  49,  17,  65,  17,  49,  51, 240,  32,  12,   7,
    132,  49,  33,  49,  18,  51,  65,  82, 240,  64,  14,   7,
    147,  49,  49,  18,  49,  17,  65,  17,  49,  52,  81, 115,
     14,   7, 132,  49,  33,  51,  65,  17,  65,  17,  50,  18,
    240,  16,  12,   7, 147,  49,  33,  50,  98,  49,  33,  52,
    240,  32,  10,   7, 118,  50,  81,  97,  82,  67, 240,  48,
     15,   7, 115,  18,  33,  33,  34,  33,  33,  49,  33,  34,
     51, 240,  32,  14,   7, 114,  34,  33,  34,  33,  33,  49,
     17,  67,  81, 240,  48,  18,   7, 114,  17,  34,  33,  17,
     20,  17,  33,  17,  17,  33,  18,  49,  17, 240,  32,  14,
      7, 130,  33,  49,  17,  66,  82,  65,  18,  33,  34, 240,
     16,  13,   7, 114,  33,  49,  33,  49,  17,  66,  81,  83,
    240,  48,  12,   7, 132,  49,  17,  82,  66,  81,  17,  52,
    240,  32,  11,   7, 130,  81,  97,  97,  97,  81,  97,  98,
     80,  11,   7, 113,  97,  97,  97, 113,  97,  97,  97,  80,
     11,   7, 130,  97,  97,  81,  97,  97,  97,  82,  80,  12,
      7, 161,  82,  65,  17,  65,  33,  33,  49, 240, 128,   6,
      7,   0,   6,  19, 176,   6,   7, 114,   0,   6,  96,  11,
      7, 240, 131,  49,  33,  33,  33,  53, 240,  16,  12,   7,
    130,  81, 100,  50,  17,  34,  17,  51, 240,  48,  10,   7,
    240, 115,  50,  17,  49,  99, 240,  48,  12,   7, 162,  97,
     51,  50,  17,  49,  18,  52, 240,  32,  10,   7, 240, 115,
     49,  33,  52,  51, 240,  48,  12,   7, 146,  65,  17,  51,
     81,  97,  82,  81,  97,  96,  13,   7, 240, 131,  49,  18,
     33,  19,  36,  49,  33,  51,  64,  13,   7, 130,  81,  97,
     18,  50,  17,  34,  18,  33,  35, 240,   9,   7, 129, 194,
     82,  81,  98, 240,  64,  11,   7, 161, 194,  81,  97,  97,
     65,  17,  66,  80,  13,   7, 114,  97,  97,  17,  51,  65,
     17,  65,  18, 240,  32,  10,   7, 114,  97,  97,  81,  97,
     98, 240,  64,  13,   7, 240,  98,  17,  18,  20,  18,  33,
     34,  33,  18, 224,  12,   7, 240,  98,  18,  50,  17,  34,
     18,  33,  35, 240,  11,   7, 240, 115,  50,  17,  49,  33,
     51, 240,  48,  12,   7, 240, 101,  50,  17,  49,  18,  36,
     49,  97,  96,  12,   7, 240, 131,  49,  18,  33,  18,  52,
     97,  97,  48,   9,   7, 240, 100,  66,  66,  81, 240,  80,
     11,   7, 240, 115,  65,  17,  49,  17,  67, 240,  48,  10,
      7, 129,  97,  83,  66,  81,  98, 240,  64,  12,   7, 240,
     98,  18,  34,  18,  33,  33,  53, 240,  16,  11,   7, 240,
     98,  18,  49,  18,  51,  65, 240,  64,  12,   7, 240,  98,
     17,  17,  37,  36,  49,  17, 240,  32,  11,   7, 240,  98,
     17,  66,  82,  65,  18, 240,  32,  12,   7, 240, 113,  33,
     50,  17,  66,  81,  97,  66,  80,  10,   7, 240, 116,  51,
     66,  17,  36, 240,  32,  11,   7, 130,  81,  97,  97,  81,
    113,  81,  98,  80,  11,   7, 129,  97,  97,  81,  97,  97,
     97,  97,  96,  11,   7, 130,  97,  81, 113,  81,  97,  97,
     82,  80,   8,   7, 240, 226,  50,  35, 240, 112,
};

const tFont g_sFontlucidabright5x9bi =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    7,

    //
    // The height of the font.
    //
    9,

    //
    // The baseline of the font.
    //
    7,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   14,   23,   37,   47,   62,   75,
          83,   94,  106,  114,  124,  132,  139,  146,
         157,  171,  181,  192,  204,  215,  226,  238,
         248,  261,  273,  281,  290,  300,  307,  316,
         327,  341,  354,  367,  378,  392,  404,  415,
         428,  442,  452,  464,  477,  488,  506,  524,
         538,  550,  564,  578,  590,  600,  615,  629,
         647,  661,  674,  686,  697,  708,  719,  731,
         737,  743,  754,  766,  776,  788,  798,  810,
         823,  836,  845,  856,  869,  879,  892,  904,
         915,  927,  939,  948,  959,  969,  981,  992,
        1004, 1015, 1027, 1037, 1048, 1059, 1070,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidabright5x9biData
};
