//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidasans
//     Size: 5x9
//     Bold: no
//     Italic: yes
//     Memory usage: 1244 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidasans5x9iData[1041] =
{
      5,   6,   0,   7,  64,  10,   6, 113,  81,  81,  81,  65,
     81, 240, 128,   7,   6,  98,  66,   0,   5,  96,  13,   6,
    129,  17,  21,  33,  17,  37,  17,  17,  51, 240,  96,  11,
      6, 115,  50,  65,  82,  66,  51,  65, 240,  16,  14,   6,
    114,  18,  19,  49,  17,  67,  34,  17,  17,  34, 240,  64,
     12,   6, 130,  66,  66,  35,  17,  17,  33,  36, 240,  80,
      7,   6,  97,  81,   0,   5, 112,  11,   6, 129,  65,  65,
     81,  81,  81,  81,  81, 176,  11,   6, 113,  97,  81,  81,
     81,  65,  65,  81, 176,   8,   6, 113,  67,  50, 240, 240,
    160,   9,   6, 225,  81,  53,  49,  81, 240,  96,   8,   6,
    240, 240,  97,  81,  81, 176,   7,   6, 240, 146, 240, 240,
     64,   7,   6, 240, 240,  97, 240, 128,  11,   6, 161,  65,
     81,  65,  81,  65,  65,  81, 176,  14,   6, 115,  49,  17,
     33,  33,  33,  33,  33,  33,  50, 240,  96,  10,   6,  98,
     81,  81,  65,  81,  81, 240, 128,  10,   6, 115,  81,  81,
     50,  49,  83, 240,  96,  10,   6, 115,  81,  50,  97,  81,
     35, 240,  96,  12,   6, 145,  66,  49,  17,  49,  17,  36,
     65, 240,  96,  10,   6, 115,  49,  82,  97,  65,  51, 240,
     96,  12,   6, 115,  33,  84,  33,  33,  33,  33,  50, 240,
     96,  10,   6, 115,  66,  65,  65,  65,  81, 240, 128,  12,
      6, 115,  49,  17,  50,  51,  49,  17,  51, 240,  96,  12,
      6, 115,  33,  33,  33,  33,  51,  81,  35, 240,  96,   8,
      6, 240,  65, 240,  17, 240, 128,   9,   6, 240,  65, 240,
     17,  81,  81, 176,  10,   6, 240,  17,  50,  34,  82,  97,
    240,  80,   7,   6, 240, 149,  21, 240, 160,   9,   6, 209,
     98,  82,  35,  33, 240, 128,  10,   6,  99,  81,  81,  65,
     65,  81, 240, 128,  12,   6, 131,  33,  21,  36,  20,  17,
     18,  19, 240,  80,  12,   6, 145,  66,  66,  49,  33,  36,
     17,  49, 240,  64,  13,   6, 115,  49,  17,  50,  49,  33,
     33,  33,  35, 240,  96,  10,   6, 131,  33,  65,  81,  81,
     99, 240,  80,  13,   6, 117,  17,  49,  17,  49,  17,  50,
     49,  20, 240,  80,  10,   6, 115,  49,  82,  49,  81,  83,
    240,  96,  10,   6, 115,  49,  81,  67,  49,  81, 240, 128,
     12,   6, 131,  33,  65,  81,  33,  33,  33,  51, 240,  80,
     15,   6, 113,  49,  17,  49,  20,  33,  33,  17,  49,  17,
     49, 240,  64,  10,   6, 113,  81,  81,  65,  81,  81, 240,
    128,  11,   6, 145,  81,  81,  81,  65,  81,  81,  50, 160,
     15,   6, 113,  33,  33,  17,  50,  49,  17,  49,  17,  49,
     33, 240,  80,  10,   6, 113,  81,  81,  81,  65,  84, 240,
     80,  16,   6, 113,  50,  17,  19,  18,  18,  19,  17,  17,
     17,  17,  49, 240,  64,  15,   6, 113,  49,  18,  34,  17,
     34,  33,  18,  34,  17,  49, 240,  64,  12,   6, 131,  33,
     35,  66,  49,  17,  49,  35, 240,  80,  12,   6, 115,  49,
     17,  49,  17,  35,  49,  81, 240, 128,  13,   6, 131,  33,
     35,  66,  49,  17,  49,  35,  82,  82,  96,  14,   6, 115,
     49,  17,  49,  17,  35,  49,  17,  49,  33, 240,  80,  10,
      6, 115,  49,  81,  98,  81,  35, 240,  96,  10,   6, 101,
     49,  81,  65,  81,  81, 240, 112,  15,   6, 113,  33,  17,
     49,  17,  49,  17,  49,  17,  33,  36, 240,  80,  14,   6,
     97,  49,  17,  33,  33,  33,  33,  17,  66,  65, 240, 112,
     16,   6,  97,  33,  33,  18,  18,  18,  18,  34,  18,  18,
     17,  33, 240,  80,  15,   6,  17,  97,  33,  33,  17,  65,
     66,  49,  17,  33,  49, 240,  64,  12,   6,  97,  49,  33,
     17,  50,  65,  81,  81, 240, 112,  10,   6, 116,  65,  65,
     81,  65,  68, 240,  80,  11,   6, 114,  65,  81,  81,  81,
     65,  81,  82, 160,  11,   6,  97,  81,  81,  97,  81,  81,
     81,  81, 160,  11,   6, 114,  81,  81,  65,  81,  81,  81,
     66, 160,  11,   6, 145,  66,  51,  49,  33,  17,  49, 240,
    160,   6,   6, 240, 240, 195, 240,   6,   6,  97,   0,   6,
     80,  11,   6, 240,  67,  33,  33,  33,  17,  51, 240,  96,
     12,   6, 113,  81,  83,  34,  17,  33,  33,  35, 240,  96,
      9,   6, 240,  67,  33,  81,  83, 240,  96,  12,   6, 161,
     81,  35,  33,  33,  33,  18,  36, 240,  80,  10,   6, 240,
     66,  49,  17,  51,  51, 240,  96,  11,   6, 130,  49,  67,
     65,  65,  81,  81,  81, 176,  12,   6, 240,  83,  33,  33,
     17,  33,  51,  81,  35, 144,  13,   6, 113,  81,  83,  34,
     17,  34,  17,  33,  33, 240,  80,   9,   6, 113, 177,  65,
     81,  81, 240, 128,  10,   6, 145, 177,  65,  81,  81,  81,
     50, 160,  13,   6, 113,  81,  81,  17,  33,  17,  51,  49,
     18, 240,  80,  10,   6, 113,  81,  65,  81,  81,  81, 240,
    128,  12,   6, 240,  67,  17,  20,  18,  17,  33,  33, 240,
     80,  12,   6, 240,  67,  49,  17,  34,  17,  33,  33, 240,
     80,  11,   6, 240,  67,  33,  33,  33,  33,  35, 240,  96,
     12,   6, 240,  68,  34,  17,  33,  33,  35,  33,  81, 176,
     12,   6, 240,  67,  33,  33,  33,  18,  35,  81,  81, 144,
      9,   6, 240,  67,  49,  65,  81, 240, 128,   9,   6, 240,
     66,  65,  97,  50, 240, 112,  10,   6, 113,  81,  67,  49,
     81,  82, 240, 112,  12,   6, 240,  50,  17,  33,  33,  33,
     17,  51, 240,  96,  12,   6, 240,  49,  33,  33,  17,  49,
     17,  50, 240, 112,  13,   6, 240,  49,  17,  34,  19,  18,
     18,  18,  17, 240,  80,  12,   6, 240,  65,  33,  50,  65,
     65,  17,  33, 240,  32,  13,   6, 240,  49,  33,  33,  17,
     66,  65,  81,  81,  65,  80,   9,   6, 240,  67,  65,  65,
     68, 240,  80,  11,   6, 114,  65,  81,  81,  65,  81,  81,
     81, 176,  11,   6, 113,  81,  81,  65,  81,  81,  81,  81,
    176,  11,   6, 114,  81,  66,  81,  65,  81,  81,  65, 176,
      9,   6, 240, 162,  17,  17,  18, 240, 176,
};

const tFont g_sFontlucidasans5x9i =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    6,

    //
    // The height of the font.
    //
    10,

    //
    // The baseline of the font.
    //
    7,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   15,   22,   35,   46,   60,   72,
          79,   90,  101,  109,  118,  126,  133,  140,
         151,  165,  175,  185,  195,  207,  217,  229,
         239,  251,  263,  271,  280,  290,  297,  306,
         316,  328,  340,  353,  363,  376,  386,  396,
         408,  423,  433,  444,  459,  469,  485,  500,
         512,  524,  537,  551,  561,  571,  586,  600,
         616,  631,  643,  653,  664,  675,  686,  697,
         703,  709,  720,  732,  741,  753,  763,  774,
         786,  799,  808,  818,  831,  841,  853,  865,
         876,  888,  900,  909,  918,  928,  940,  952,
         965,  977,  990,  999, 1010, 1021, 1032,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidasans5x9iData
};
