//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidasans
//     Size: 7x11
//     Bold: yes
//     Italic: no
//     Memory usage: 1496 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidasans7x11bData[1296] =
{
      4,   8,   0,  11,  11,   8, 240,  18,  98,  98, 113, 226,
     98, 240, 112,  13,   8, 130,  18,  50,  18,  49,  33,  65,
     33,   0,   6,  64,  19,   8, 240,  34,  17,  66,  17,  51,
     18,  50,  17,  51,  18,  50,  17,  66,  17, 240,  64,  16,
      8, 177,  85,  34,  17,  66,  17,  84,  81,  18,  65,  18,
     37,  81, 208,  20,   8, 240,  34,  49,  17,  18,  18,  34,
     33,  97,  97,  34,  34,  17,  17,  33,  50, 240,  16,  17,
      8, 240,  35,  66,  18,  67,  83,  17,  34,  18,  50,  34,
     51,  17, 240,  48,   9,   8, 130,  98,  97, 113,   0,   6,
    112,  12,   8, 161,  98,  82,  98,  98,  98,  98, 114, 113,
    208,  12,   8, 129, 114, 114,  98,  98,  98,  98,  82,  97,
    240,  11,   8, 240,  18,  18,  66,  82,  18,   0,   6,  48,
     10,   8, 240, 177, 113,  85,  81, 113, 240, 224,   9,   8,
      0,   7,   2,  98, 113,  97, 112,   8,   8, 240, 240, 162,
      0,   5,  96,   8,   8,   0,   7,   2,  98, 240, 112,  12,
      8, 194,  98,  82,  98,  82,  82,  98,  82,  98, 224,  17,
      8, 240,  36,  50,  34,  34,  34,  34,  34,  34,  34,  34,
     34,  52, 240,  64,  12,   8, 240,  50,  68,  98,  98,  98,
     98,  98, 240,  80,  13,   8, 240,  36,  50,  34,  98,  67,
     66,  82, 102, 240,  48,  14,   8, 240,  36,  50,  34,  98,
     67, 114,  34,  34,  52, 240,  64,  14,   8, 240,  66,  83,
     65,  18,  49,  34,  54,  82,  98, 240,  64,  13,   8, 240,
     22,  34,  98, 101, 114,  34,  34,  52, 240,  64,  15,   8,
    240,  36,  50,  34,  34, 101,  50,  34,  34,  34,  52, 240,
     64,  12,   8, 240,  22,  38,  98,  82,  82,  82,  98, 240,
     96,  16,   8, 240,  36,  50,  34,  34,  34,  52,  50,  34,
     34,  34,  52, 240,  64,  15,   8, 240,  36,  50,  34,  34,
     34,  53,  98,  34,  34,  52, 240,  64,  10,   8, 240, 146,
     98, 240, 114,  98, 240, 112,  11,   8, 240, 146,  98, 240,
    114,  98, 113,  97, 112,  10,   8, 240, 194,  66,  82, 114,
    130, 240, 192,   9,   8, 240, 240,  37, 181, 240, 240,  80,
     10,   8, 240, 146, 130, 114,  82,  66, 240, 240,  11,   8,
    240,  20, 114,  98,  67, 210,  98, 240,  96,  17,   8, 240,
     36,  50,  34,  33,  35,  33,  17,  18,  33,  36,  18, 117,
    240,  48,  16,   8, 240,  50,  98,  81,  18,  65,  18,  54,
     33,  50,  33,  50, 240,  48,  16,   8, 240,  20,  66,  18,
     50,  18,  52,  66,  18,  50,  18,  52, 240,  80,  12,   8,
    240,  52,  50,  82,  98,  98, 114, 116, 240,  48,  17,   8,
    240,  20,  66,  18,  50,  34,  34,  34,  34,  34,  34,  18,
     52, 240,  80,  12,   8, 240,  21,  50,  98, 100,  66,  98,
    101, 240,  64,  12,   8, 240,  21,  50,  98, 100,  66,  98,
     98, 240, 112,  15,   8, 240,  52,  50,  82,  98,  34,  34,
     34,  50,  18,  68, 240,  48,  18,   8, 240,  18,  34,  34,
     34,  34,  34,  38,  34,  34,  34,  34,  34,  34, 240,  48,
     12,   8, 240,  18,  98,  98,  98,  98,  98,  98, 240, 112,
     13,   8, 240,  50,  98,  98,  98,  98,  98,  98,  98,  67,
     80,  18,   8, 240,  18,  34,  34,  18,  50,  17,  68,  66,
     18,  50,  34,  34,  50, 240,  32,  12,   8, 240,  18,  98,
     98,  98,  98,  98, 101, 240,  64,  16,   8, 240,  18,  69,
     39,  20,  19,  19,  33,  35,  33,  35,  82, 240,  16,  19,
      8, 240,  18,  49,  35,  33,  36,  17,  33,  20,  33,  35,
     33,  50,  33,  65, 240,  48,  17,   8, 240,  51,  66,  18,
     34,  50,  18,  50,  18,  50,  34,  18,  67, 240,  64,  14,
      8, 240,  20,  66,  18,  50,  18,  52,  66,  98,  98, 240,
    112,  17,   8, 240,  51,  66,  18,  34,  50,  18,  50,  18,
     50,  34,  18,  67, 114, 114,  17,   8, 240,  20,  66,  18,
     50,  18,  52,  66,  18,  50,  18,  50,  34, 240,  48,  12,
      8, 240,  36,  50,  99,  99,  99,  98,  52, 240,  80,  12,
      8, 240,  22,  66,  98,  98,  98,  98,  98, 240,  80,  18,
      8, 240,  18,  34,  34,  34,  34,  34,  34,  34,  34,  34,
     34,  34,  52, 240,  64,  16,   8, 240,  18,  34,  34,  34,
     34,  34,  50,  17,  68,  82,  98, 240,  80,  21,   8, 240,
     18,  83,  33,  35,  33,  33,  18,  18,  17,  18,  18,  17,
     34,  18,  50,  18, 240,  32,  16,   8, 240,  18,  18,  50,
     18,  67,  97,  99,  66,  18,  50,  18, 240,  64,  15,   8,
    240,  18,  34,  34,  34,  50,  17,  82,  98,  98,  98, 240,
     80,  12,   8, 240,  21,  98,  82,  83,  82,  82, 101, 240,
     64,  12,   8, 131,  82,  98,  98,  98,  98,  98,  98,  99,
    208,  12,   8, 130,  98, 114,  98, 114, 114,  98, 114,  98,
    160,  12,   8, 131,  98,  98,  98,  98,  98,  98,  98,  83,
    208,  15,   8, 240,  50,  98,  81,  18,  65,  18,  49,  50,
     33,  50, 240, 176,   6,   8,   0,   9,   6, 160,   7,   8,
      2, 114,   0,   9,  80,  14,   8, 240, 163, 114,  68,  50,
     18,  50,  18,  66,  18, 240,  48,  16,   8, 130,  98, 100,
     66,  18,  50,  18,  50,  18,  50,  18,  52, 240,  80,  11,
      8, 240, 163,  66,  98,  98,  98, 115, 240,  80,  17,   8,
    178,  98,  68,  50,  18,  50,  18,  50,  18,  50,  18,  66,
     17, 240,  64,  13,   8, 240, 163,  66,  18,  50,  18,  53,
     50, 116, 240,  64,  12,   8, 163,  66,  85,  66,  98,  98,
     98,  98, 240,  96,  16,   8, 240, 164,  50,  18,  50,  18,
     50,  18,  50,  18,  68,  98,  52,  64,  17,   8, 130,  98,
     98,  17,  69,  50,  18,  50,  18,  50,  18,  50,  18, 240,
     64,  11,   8, 130, 226,  98,  98,  98,  98,  98, 240, 112,
     12,   8, 162, 226,  98,  98,  98,  98,  98,  98,  67,  80,
     16,   8, 130,  98,  98,  33,  50,  17,  67,  84,  66,  18,
     50,  34, 240,  48,  12,   8, 130,  98,  98,  98,  98,  98,
     98,  98, 240, 112,  19,   8, 240, 145,  18,  18,  18,  18,
     20,  18,  20,  18,  20,  18,  20,  18,  18, 240,  16,  17,
      8, 240, 145,  18,  66,  18,  50,  18,  50,  18,  50,  18,
     50,  18, 240,  64,  15,   8, 240, 163,  66,  18,  50,  18,
     50,  18,  50,  18,  67, 240,  80,  17,   8, 240, 145,  18,
     66,  18,  50,  18,  50,  18,  50,  18,  52,  66,  98,  96,
     16,   8, 240, 164,  50,  18,  50,  18,  50,  18,  50,  18,
     68,  98,  98,  48,  12,   8, 240, 146,  17,  68,  66,  98,
     98,  98, 240, 112,  11,   8, 240, 163,  66,  99,  99,  98,
     67, 240,  96,  12,   8, 240,  34,  84,  82,  98,  98,  98,
    114, 240,  80,  17,   8, 240, 146,  18,  50,  18,  50,  18,
     50,  18,  50,  18,  66,  17, 240,  64,  15,   8, 240, 146,
     34,  34,  34,  50,  17,  66,  17,  82,  98, 240,  80,  20,
      8, 240, 146,  65,  18,  18,  17,  18,  18,  17,  18,  18,
     17,  34,  18,  50,  18, 240,  48,  15,   8, 240, 146,  17,
     66,  17,  82,  98,  81,  18,  65,  18, 240,  80,  16,   8,
    240, 146,  34,  34,  34,  50,  17,  66,  17,  82,  98,  82,
     98,  80,  11,   8, 240, 148,  98,  82,  98,  82, 100, 240,
     80,  12,   8, 162,  82,  98, 113,  82, 129,  98,  98, 114,
    192,  12,   8, 130,  98,  98,  98,  98,  98,  98,  98,  98,
    224,  12,   8, 130, 114,  98,  97, 130,  81, 114,  98,  82,
    224,  11,   8, 240, 240,  51,  17,  33,  19, 240, 240, 208,};

const tFont g_sFontlucidasans7x11b =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    8,

    //
    // The height of the font.
    //
    11,

    //
    // The baseline of the font.
    //
    9,

    //
    // The offset to each character in the font.
    //
    {
           0,    4,   15,   28,   47,   63,   83,  100,
         109,  121,  133,  144,  154,  163,  171,  179,
         191,  208,  220,  233,  247,  261,  274,  289,
         301,  317,  332,  342,  353,  363,  372,  382,
         393,  410,  426,  442,  454,  471,  483,  495,
         510,  528,  540,  553,  571,  583,  599,  618,
         635,  649,  666,  683,  695,  707,  725,  741,
         762,  778,  793,  805,  817,  829,  841,  856,
         862,  869,  883,  899,  910,  927,  940,  952,
         968,  985,  996, 1008, 1024, 1036, 1055, 1072,
        1087, 1104, 1120, 1132, 1143, 1155, 1172, 1187,
        1207, 1222, 1238, 1249, 1261, 1273, 1285,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidasans7x11bData
};
