//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidatypewriter
//     Size: 7x13
//     Bold: yes
//     Italic: no
//     Memory usage: 1668 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidatypewriter7x13bData[1466] =
{
      5,   7,   0,  11,  48,  12,   7, 226,  82,  82,  82,  82,
     97, 194,  82, 240,  64,  13,   7, 114,  18,  34,  18,  33,
     33,  49,  33,   0,   7,  48,  19,   7, 242,  18,  34,  18,
     23,  18,  18,  34,  18,  23,  18,  18,  34,  18,  34,  18,
    240,  18,   7,  49,  97,  68,  34,  49,  18,  83,  84,  83,
     82,  17,  50,  36,  65,  97,  64,  20,   7, 242,  50,  18,
     19,  18,  17,  34,  17,  81,  81,  18,  33,  17,  20,  17,
     19,  50, 240,  20,   7, 243,  50,  18,  34,  18,  34,  17,
     66,  33,  20,  17,  18,  18,  34,  34,  35,  17, 240,   9,
      7, 114,  82,  81,  97,   0,   7,  96,  14,   7, 146,  66,
     66,  82,  82,  82,  82,  82,  82,  98,  98, 160,  14,   7,
    114,  98,  98,  82,  82,  82,  82,  82,  82,  66,  66, 192,
     15,   7, 240,  17,  65,  17,  17,  51,  49,  17,  17,  65,
      0,   5,  96,  12,   7, 240, 145,  97,  97,  55,  49,  97,
     97, 240, 144,   9,   7,   0,   7, 114,  82,  97,  81,  96,
      8,   7, 240, 240, 198, 240, 240, 208,   8,   7,   0,   7,
    114,  82, 240,  64,  14,   7, 194,  82,  66,  82,  66,  82,
     66,  66,  82,  66,  82, 192,  20,   7, 244,  34,  34,  18,
     34,  18,  34,  18,  34,  18,  34,  18,  34,  18,  34,  36,
    240,  16,  14,   7, 240,  18,  52,  82,  82,  82,  82,  82,
     82,  82, 240,  32,  13,   7, 244,  34,  34,  82,  67,  51,
     50,  66,  86,  22, 240,  15,   7, 244,  34,  34,  82,  82,
     36,  98,  82,  18,  34,  36, 240,  16,  17,   7, 240,  34,
     67,  49,  18,  49,  18,  33,  34,  38,  22,  66,  82, 240,
     16,  14,   7, 245,  37,  33,  97, 100,  98,  82,  18,  34,
     36, 240,  16,  17,   7, 244,  34,  34,  18,  82,  85,  34,
     34,  18,  34,  18,  34,  36, 240,  16,  13,   7, 230,  22,
     82,  66,  66,  82,  66,  82,  82, 240,  48,  19,   7, 244,
     34,  34,  18,  34,  19,  18,  36,  34,  19,  18,  34,  18,
     34,  36, 240,  16,  17,   7, 244,  34,  34,  18,  34,  18,
     34,  37,  82,  82,  18,  34,  36, 240,  16,  10,   7, 240,
    210,  82, 240, 178,  82, 240,  64,  11,   7, 240, 210,  82,
    240, 178,  82,  97,  81,  96,  12,   7, 240, 162,  51,  50,
     66,  98,  99,  98, 240, 112,   9,   7, 240, 240,  86, 134,
    240, 240,  96,  12,   7, 240,  98,  99,  98,  98,  66,  51,
     50, 240, 176,  13,   7, 243,  49,  34,  82,  66,  66,  82,
    194,  82, 240,  48,  16,   7, 245,  18,  51,  37,  18,  19,
     18,  19,  18,  19,  34,  19, 101, 240,  19,   7, 240,  18,
     82,  65,  18,  49,  18,  49,  18,  38,  17,  50,  17,  50,
     17,  50, 240,  19,   7, 229,  34,  34,  18,  34,  18,  33,
     36,  50,  33,  34,  34,  18,  34,  21, 240,  16,  16,   7,
    240,  19,  50,  18,  18,  82,  82,  82,  82,  98,  33,  51,
    240,  16,  20,   7, 228,  50,  18,  34,  34,  18,  34,  18,
     34,  18,  34,  18,  34,  18,  18,  36, 240,  32,  13,   7,
    229,  34,  82,  82,  84,  50,  82,  82,  85, 240,  16,  13,
      7, 229,  34,  82,  82,  84,  50,  82,  82,  82, 240,  64,
     17,   7, 240,  19,  50,  18,  18,  82,  82,  82,  34,  18,
     34,  34,  18,  52, 240,  20,   7, 226,  34,  18,  34,  18,
     34,  18,  34,  22,  18,  34,  18,  34,  18,  34,  18,  34,
    240,  12,   7, 230,  50,  82,  82,  82,  82,  82,  82,  54,
    240,  13,   7, 229,  82,  82,  82,  82,  82,  82,  82,  36,
    240,  32,  19,   7, 226,  49,  18,  34,  18,  33,  34,  17,
     51,  68,  50,  18,  34,  34,  18,  34, 240,  13,   7, 226,
     82,  82,  82,  82,  82,  82,  82,  85, 240,  16,  23,   7,
    226,  34,  18,  34,  22,  22,  17,  17,  18,  17,  17,  18,
     17,  17,  18,  17,  17,  18,  17,  50, 240,  22,   7, 226,
     49,  18,  49,  19,  33,  20,  17,  17,  18,  17,  17,  20,
     17,  35,  17,  50,  17,  50, 240,  20,   7, 244,  49,  33,
     34,  34,  18,  34,  18,  34,  18,  34,  18,  34,  33,  33,
     52, 240,  16,  17,   7, 229,  34,  34,  18,  34,  18,  34,
     18,  33,  36,  50,  82,  82, 240,  64,  20,   7, 244,  49,
     33,  34,  34,  18,  34,  18,  34,  18,  34,  18,  34,  33,
     33,  52,  82,  98,  19,   7, 229,  34,  34,  18,  34,  18,
     33,  36,  50,  18,  34,  18,  34,  34,  18,  34, 240,  15,
      7, 244,  34,  34,  18,  83,  84,  83,  82,  18,  34,  36,
    240,  16,  13,   7, 230,  50,  82,  82,  82,  82,  82,  82,
     82, 240,  32,  21,   7, 226,  49,  18,  49,  18,  49,  18,
     49,  18,  49,  18,  49,  18,  49,  34,  17,  66, 240,  32,
     19,   7, 226,  34,  18,  34,  18,  34,  18,  33,  50,  17,
     50,  17,  51,  82,  82, 240,  32,  24,   7, 226,  49,  18,
     49,  18,  17,  17,  18,  17,  17,  18,  17,  17,  37,  34,
     17,  50,  17,  50,  17, 240,  16,  18,   7, 226,  34,  18,
     34,  34,  17,  51,  82,  83,  49,  18,  34,  34,  18,  34,
    240,  17,   7, 226,  34,  18,  34,  18,  34,  33,  33,  52,
     66,  82,  82,  82, 240,  32,  12,   7, 230,  82,  67,  51,
     66,  67,  51,  66,  86, 240,  14,   7, 116,  50,  82,  82,
     82,  82,  82,  82,  82,  82,  84, 160,  14,   7, 114,  82,
     98,  82,  98,  82,  98,  98,  82,  98,  82, 112,  14,   7,
    116,  82,  82,  82,  82,  82,  82,  82,  82,  82,  52, 160,
     16,   7, 240,  33,  83,  65,  17,  50,  18,  33,  49,  18,
     51,  81, 240, 208,   6,   7,   0,   9,  87, 112,   7,   7,
    114,  98,   0,   9,  32,  15,   7, 240, 228,  34,  34,  82,
     37,  18,  34,  18,  34,  35,  17, 240,  20,   7, 114,  82,
     82,  82,  18,  35,  18,  18,  34,  18,  34,  18,  34,  18,
     34,  21, 240,  16,  14,   7, 240, 228,  34,  34,  18,  82,
     82,  82,  49,  36, 240,  16,  19,   7, 178,  82,  82,  37,
     18,  34,  18,  34,  18,  34,  18,  34,  18,  19,  34,  18,
    240,  15,   7, 240, 228,  34,  34,  18,  34,  22,  18,  82,
     49,  36, 240,  16,  14,   7, 148,  34,  82,  70,  34,  82,
     82,  82,  82,  82, 240,  48,  19,   7, 240, 229,  18,  34,
     18,  34,  18,  34,  18,  19,  34,  18,  82,  18,  34,  36,
     32,  20,   7, 114,  82,  82,  82,  18,  35,  18,  18,  34,
     18,  34,  18,  34,  18,  34,  18,  34, 240,  13,   7, 146,
     82, 164,  82,  82,  82,  82,  82,  82, 240,  32,  14,   7,
    146,  82, 164,  82,  82,  82,  82,  82,  82,  82,  51,  64,
     19,   7, 114,  82,  82,  82,  34,  18,  33,  34,  17,  52,
     50,  18,  34,  34,  18,  34, 240,  14,   7, 116,  82,  82,
     82,  82,  82,  82,  82,  82,  82, 240,  32,  23,   7, 240,
    213,  34,  17,  17,  18,  17,  17,  18,  17,  17,  18,  17,
     17,  18,  17,  17,  18,  17,  17, 240,  18,   7, 240, 210,
     18,  35,  18,  18,  34,  18,  34,  18,  34,  18,  34,  18,
     34, 240,  17,   7, 240, 228,  34,  34,  18,  34,  18,  34,
     18,  34,  18,  34,  36, 240,  16,  19,   7, 240, 210,  18,
     35,  18,  18,  34,  18,  34,  18,  34,  18,  34,  21,  34,
     82,  80,  18,   7, 240, 229,  18,  34,  18,  34,  18,  34,
     18,  34,  18,  19,  34,  18,  82,  82,  14,   7, 240, 210,
     18,  34,  18,  35,  66,  82,  82,  82, 240,  64,  12,   7,
    240, 229,  18,  83,  84,  83,  82,  21, 240,  16,  13,   7,
    240,  17,  82,  70,  34,  82,  82,  82,  82, 100, 240,  18,
      7, 240, 210,  34,  18,  34,  18,  34,  18,  34,  18,  34,
     18,  19,  34,  18, 240,  17,   7, 240, 210,  34,  18,  34,
     18,  34,  34,  17,  50,  17,  66,  82, 240,  32,  22,   7,
    240, 210,  49,  18,  17,  17,  18,  17,  17,  18,  17,  17,
     34,  17,  50,  17,  50,  17, 240,  16,  17,   7, 240, 210,
     34,  18,  34,  34,  17,  66,  65,  18,  34,  34,  18,  34,
    240,  18,   7, 240, 210,  34,  18,  34,  18,  34,  34,  17,
     50,  17,  66,  82,  81,  82,  64,  11,   7, 240, 214,  67,
     51,  51,  51,  66,  86, 240,  14,   7, 131,  50,  82,  98,
     97,  66, 113,  82,  66,  82,  99, 160,  14,   7, 114,  82,
     82,  82,  82,  82,  82,  82,  82,  82,  82, 192,  14,   7,
    115,  98,  82,  66,  81, 114,  65,  98,  98,  82,  51, 176,
     14,   7, 240, 240,  98,  33,  17,  18,  17,  17,  34, 240,
    240, 112,
};

const tFont g_sFontlucidatypewriter7x13b =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    7,

    //
    // The height of the font.
    //
    13,

    //
    // The baseline of the font.
    //
    11,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   17,   30,   49,   67,   87,  107,
         116,  130,  144,  159,  171,  180,  188,  196,
         210,  230,  244,  257,  272,  289,  303,  320,
         333,  352,  369,  379,  390,  402,  411,  423,
         436,  452,  471,  490,  506,  526,  539,  552,
         569,  589,  601,  614,  633,  646,  669,  691,
         711,  728,  748,  767,  782,  795,  816,  835,
         859,  877,  894,  906,  920,  934,  948,  964,
         970,  977,  992, 1012, 1026, 1045, 1060, 1074,
        1093, 1113, 1126, 1140, 1159, 1173, 1196, 1214,
        1231, 1250, 1268, 1282, 1294, 1307, 1325, 1342,
        1364, 1381, 1399, 1410, 1424, 1438, 1452,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidatypewriter7x13bData
};
