//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidasans
//     Size: 7x13
//     Bold: no
//     Italic: no
//     Memory usage: 1680 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidasans7x13Data[1478] =
{
      4,   8,   0,  12,  12,   8, 129, 113, 113, 113, 113, 113,
    241, 113, 240, 128,  11,   8,   1,  17,  81,  17,  81,  17,
      0,   9,  80,  20,   8, 145,  33,  65,  33,  54,  49,  33,
     65,  33,  54,  49,  33,  65,  33,  65,  33, 240,  64,  22,
      8,  49,  84,  49,  33,  17,  33,  33,  66,  17,  98,  97,
     18,  65,  33,  33,  17,  33,  52,  81, 208,  23,   8, 146,
     81,  33,  33,  17,  33,  17,  50,  17,  97,  97,  18,  49,
     17,  33,  17,  33,  33,  82, 240,  48,  20,   8, 163,  65,
     49,  49,  49,  65,  17,  67,  50,  49,  34,  66,  17,  66,
     36,  33, 240,  16,   8,   8,   1, 113, 113,   0,   9, 112,
     14,   8,  33,  97, 113,  97, 113, 113, 113, 113, 129, 113,
    129, 208,  14,   8,   1, 129, 113, 129, 113, 113, 113, 113,
     97, 113,  97, 240,  15,   8, 161,  81,  17,  17,  65,  17,
     65,  17,  17,  81,   0,   6,  80,  12,   8, 240,  65, 113,
    113,  71,  65, 113, 113, 240, 208,   8,   8,   0,   8,  17,
    113,  97, 240,   8,   8, 240, 240, 163,   0,   6,  80,   8,
      8,   0,   8,   1, 113, 240, 128,  14,   8,  65, 113,  97,
    113,  97, 113, 113,  97, 113,  97, 113, 240,  20,   8, 162,
     81,  33,  49,  65,  33,  65,  33,  65,  33,  65,  33,  65,
     49,  33,  82, 240,  80,  13,   8, 161,  83, 113, 113, 113,
    113, 113, 113, 113, 240,  96,  14,   8, 148,  49,  65, 113,
    113,  97,  97,  97,  97, 102, 240,  48,  15,   8, 148,  49,
     65, 113, 113,  67, 129, 113,  33,  65,  52, 240,  64,  17,
      8, 194,  81,  17,  65,  33,  49,  49,  33,  65,  39,  97,
    113, 113, 240,  48,  14,   8, 134,  33, 113, 117, 129, 113,
    113,  33,  65,  52, 240,  64,  17,   8, 148,  49,  65,  33,
    113, 117,  49,  65,  33,  65,  33,  65,  52, 240,  64,  13,
      8, 134, 113,  97,  97, 113,  97, 113,  97, 113, 240, 112,
     19,   8, 148,  49,  65,  33,  65,  33,  65,  52,  49,  65,
     33,  65,  33,  65,  52, 240,  64,  17,   8, 148,  49,  65,
     33,  65,  33,  65,  53, 113, 113,  33,  65,  52, 240,  64,
     11,   8, 240, 145, 113, 240, 240,  17, 113, 240, 128,  11,
      8, 240, 161, 113, 240, 240,  17, 113,  97, 240,  12,   8,
    240,  82,  66,  81,  97, 129, 130, 130, 240, 176,   9,   8,
    240, 240,  39, 151, 240, 240, 176,  12,   8, 240,  18, 130,
    129, 129,  97,  82,  66, 240, 240,  12,   8, 132, 129, 113,
    113,  67,  81, 241, 113, 240, 112,  17,   8, 165,  33,  82,
     53,  33,  50,  33,  50,  33,  35,  50,  49, 134, 240,  16,
     19,   8, 162,  98,  81,  33,  65,  33,  65,  33,  54,  33,
     65,  33,  65,  33,  65, 240,  48,  19,   8, 132,  65,  49,
     49,  49,  49,  49,  52,  65,  49,  49,  49,  49,  49,  52,
    240,  80,  15,   8, 164,  49,  65,  17, 113, 113, 113, 113,
    129,  65,  52, 240,  48,  20,   8, 133,  49,  65,  33,  81,
     17,  81,  17,  81,  17,  81,  17,  81,  17,  65,  37, 240,
     64,  13,   8, 133,  49, 113, 113, 116,  65, 113, 113, 117,
    240,  64,  13,   8, 132,  65, 113, 113, 116,  65, 113, 113,
    113, 240, 128,  17,   8, 164,  49,  65,  17, 113, 113, 113,
     81,  17,  81,  33,  65,  53, 240,  32,  21,   8, 129,  65,
     33,  65,  33,  65,  33,  65,  38,  33,  65,  33,  65,  33,
     65,  33,  65, 240,  48,  13,   8, 129, 113, 113, 113, 113,
    113, 113, 113, 113, 240, 128,  13,   8, 161, 113, 113, 113,
    113, 113, 113, 113, 113,  82, 224,  21,   8, 129,  65,  33,
     49,  49,  33,  65,  17,  83,  81,  33,  65,  49,  49,  65,
     33,  65, 240,  48,  13,   8, 129, 113, 113, 113, 113, 113,
    113, 113, 116, 240,  80,  28,   8, 129,  81,  18,  50,  18,
     50,  17,  17,  17,  17,  17,  17,  17,  17,  17,  33,  33,
     17,  33,  33,  17,  81,  17,  81, 240,  32,  25,   8, 129,
     65,  34,  49,  34,  49,  33,  17,  33,  33,  18,  17,  33,
     33,  17,  33,  50,  33,  50,  33,  65, 240,  48,  16,   8,
    164,  49,  65,  17,  98,  98,  98,  98,  97,  17,  65,  52,
    240,  48,  17,   8, 132,  65,  49,  49,  49,  49,  49,  49,
     49,  52,  65, 113, 113, 240, 128,  16,   8, 164,  49,  65,
     17,  98,  98,  98,  98,  97,  17,  65,  52, 130, 113,  20,
      8, 132,  65,  49,  49,  49,  49,  49,  52,  65,  33,  65,
     49,  49,  49,  49,  49, 240,  64,  13,   8, 148,  49, 113,
    114, 115, 114, 113, 113,  52, 240,  80,  13,   8, 135,  65,
    113, 113, 113, 113, 113, 113, 113, 240,  80,  21,   8, 129,
     65,  33,  65,  33,  65,  33,  65,  33,  65,  33,  65,  33,
     65,  33,  65,  52, 240,  64,  20,   8, 129,  65,  33,  65,
     33,  65,  33,  65,  49,  33,  65,  33,  65,  33,  82,  98,
    240,  80,  26,   8, 129, 113, 113,  49,  49,  49,  65,  17,
     17,  17,  17,  17,  17,  17,  17,  17,  17,  17,  33,  49,
     49,  49, 240,  32,  21,   8, 129,  65,  33,  65,  49,  33,
     81,  17,  82,  81,  17,  81,  33,  49,  65,  33,  65, 240,
     48,  18,   8, 129,  81,  17,  81,  33,  49,  49,  49,  65,
     17,  97, 113, 113, 113, 240,  80,  13,   8, 134, 113,  97,
     97,  98,  97,  97,  97, 118, 240,  48,  14,   8,   3,  81,
    113, 113, 113, 113, 113, 113, 113, 113, 115, 208,  14,   8,
      1, 113, 129, 113, 113, 129, 113, 129, 113, 129, 113, 176,
     14,   8,   3, 113, 113, 113, 113, 113, 113, 113, 113, 113,
     83, 208,  15,   8, 161, 113,  97,  17,  81,  17,  65,  49,
     49,  49, 240, 240, 208,   6,   8,   0,  10,   6, 160,   7,
      8,   2, 129,   0,  10,  80,  16,   8, 240, 163,  65,  49,
    113,  68,  49,  49,  49,  49,  67,  17, 240,  48,  20,   8,
      1, 113, 113, 113,  18,  66,  33,  49,  49,  49,  49,  49,
     49,  49,  49,  52, 240,  80,  12,   8, 240, 179,  65,  97,
    113, 113, 129, 131, 240,  64,  20,   8,  65, 113, 113,  68,
     49,  49,  49,  49,  49,  49,  49,  49,  49,  34,  66,  17,
    240,  64,  15,   8, 240, 163,  65,  49,  49,  49,  53,  49,
    113,  49,  67, 240,  80,  14,   8,  34,  81, 113, 100,  81,
    113, 113, 113, 113, 113, 240, 112,  18,   8, 240, 164,  49,
     49,  49,  49,  49,  49,  49,  34,  66,  17, 113, 113,  67,
     64,  21,   8,   1, 113, 113, 113,  18,  66,  33,  49,  49,
     49,  49,  49,  49,  49,  49,  49,  49, 240,  64,  13,   8,
      1, 113, 241, 113, 113, 113, 113, 113, 113, 240, 128,  14,
      8,  33, 113, 241, 113, 113, 113, 113, 113, 113, 113,  82,
     96,  20,   8,   1, 113, 113, 113,  49,  49,  33,  65,  17,
     83,  81,  33,  65,  34,  49,  49, 240,  64,  14,   8,   1,
    113, 113, 113, 113, 113, 113, 113, 113, 113, 240, 128,  19,
      8, 240, 145,  18,  36,  34,  33,  49,  49,  49,  49,  49,
     49,  49,  49,  49, 240,  64,  19,   8, 240, 145,  18,  66,
     33,  49,  49,  49,  49,  49,  49,  49,  49,  49,  49, 240,
     64,  17,   8, 240, 178,  81,  33,  49,  65,  33,  65,  33,
     65,  49,  33,  82, 240,  80,  19,   8, 240, 145,  18,  66,
     33,  49,  49,  49,  49,  49,  49,  49,  49,  52,  65, 113,
    112,  19,   8, 240, 164,  49,  49,  49,  49,  49,  49,  49,
     49,  49,  34,  66,  17, 113, 113,  48,  13,   8, 240, 145,
     18,  66,  97, 113, 113, 113, 113, 240, 128,  12,   8, 240,
    163,  65, 113, 130, 129, 113,  67, 240,  96,  13,   8, 145,
    113, 100,  81, 113, 113, 113, 113, 130, 240,  80,  19,   8,
    240, 145,  49,  49,  49,  49,  49,  49,  49,  49,  49,  49,
     34,  66,  17, 240,  64,  17,   8, 240, 145,  49,  49,  49,
     49,  49,  65,  17,  81,  17,  97, 113, 240,  96,  23,   8,
    240, 145, 113,  49,  65,  33,  33,  17,  17,  17,  17,  17,
     17,  17,  17,  33,  49,  49,  49, 240,  32,  18,   8, 240,
    145,  49,  49,  49,  65,  17,  97,  97,  17,  65,  49,  49,
     49, 240,  64,  18,   8, 240, 145,  49,  49,  49,  49,  49,
     65,  17,  81,  17,  97, 113,  97,  98,  96,  12,   8, 240,
    149, 113,  97,  97,  97,  97, 117, 240,  64,  14,   8,  34,
     81, 113, 113, 129,  82, 129,  97, 113, 113, 130, 192,  14,
      8,   1, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113,
    240,  14,   8,   2, 129, 113, 113,  97, 130,  81, 129, 113,
    113,  82, 224,  11,   8, 240, 240,  51,  33,  17,  35,   0,
      6,  32,
};

const tFont g_sFontlucidasans7x13 =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    8,

    //
    // The height of the font.
    //
    12,

    //
    // The baseline of the font.
    //
    10,

    //
    // The offset to each character in the font.
    //
    {
           0,    4,   16,   27,   47,   69,   92,  112,
         120,  134,  148,  163,  175,  183,  191,  199,
         213,  233,  246,  260,  275,  292,  306,  323,
         336,  355,  372,  383,  394,  406,  415,  427,
         439,  456,  475,  494,  509,  529,  542,  555,
         572,  593,  606,  619,  640,  653,  681,  706,
         722,  739,  755,  775,  788,  801,  822,  842,
         868,  889,  907,  920,  934,  948,  962,  977,
         983,  990, 1006, 1026, 1038, 1058, 1073, 1087,
        1105, 1126, 1139, 1153, 1173, 1187, 1206, 1225,
        1242, 1261, 1280, 1293, 1305, 1318, 1337, 1354,
        1377, 1395, 1413, 1425, 1439, 1453, 1467,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidasans7x13Data
};
