//*****************************************************************************
//
// Copyright (c) 2014 Dimitar Toshkov Zhekov,
// with Reserved Font Name "Terminus Font".
// 
// This Font Software is licensed under the SIL Open Font License, Version 1.1.
// This license is copied below, and is also available with a FAQ at:
// http://scripts.sil.org/OFL
// 
// 
// -----------------------------------------------------------
// SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007
// -----------------------------------------------------------
// 
// PREAMBLE
// The goals of the Open Font License (OFL) are to stimulate worldwide
// development of collaborative font projects, to support the font creation
// efforts of academic and linguistic communities, and to provide a free and
// open framework in which fonts may be shared and improved in partnership
// with others.
// 
// The OFL allows the licensed fonts to be used, studied, modified and
// redistributed freely as long as they are not sold by themselves. The
// fonts, including any derivative works, can be bundled, embedded, 
// redistributed and/or sold with any software provided that any reserved
// names are not used by derivative works. The fonts and derivatives,
// however, cannot be released under any other type of license. The
// requirement for fonts to remain under this license does not apply
// to any document created using the fonts or their derivatives.
// 
// DEFINITIONS
// "Font Software" refers to the set of files released by the Copyright
// Holder(s) under this license and clearly marked as such. This may
// include source files, build scripts and documentation.
// 
// "Reserved Font Name" refers to any names specified as such after the
// copyright statement(s).
// 
// "Original Version" refers to the collection of Font Software components as
// distributed by the Copyright Holder(s).
// 
// "Modified Version" refers to any derivative made by adding to, deleting,
// or substituting -- in part or in whole -- any of the components of the
// Original Version, by changing formats or by porting the Font Software to a
// new environment.
// 
// "Author" refers to any designer, engineer, programmer, technical
// writer or other person who contributed to the Font Software.
// 
// PERMISSION & CONDITIONS
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of the Font Software, to use, study, copy, merge, embed, modify,
// redistribute, and sell modified and unmodified copies of the Font
// Software, subject to the following conditions:
// 
// 1) Neither the Font Software nor any of its individual components,
// in Original or Modified Versions, may be sold by itself.
// 
// 2) Original or Modified Versions of the Font Software may be bundled,
// redistributed and/or sold with any software, provided that each copy
// contains the above copyright notice and this license. These can be
// included either as stand-alone text files, human-readable headers or
// in the appropriate machine-readable metadata fields within text or
// binary files as long as those fields can be easily viewed by the user.
// 
// 3) No Modified Version of the Font Software may use the Reserved Font
// Name(s) unless explicit written permission is granted by the corresponding
// Copyright Holder. This restriction only applies to the primary font name as
// presented to the users.
// 
// 4) The name(s) of the Copyright Holder(s) or the Author(s) of the Font
// Software shall not be used to promote, endorse or advertise any
// Modified Version, except to acknowledge the contribution(s) of the
// Copyright Holder(s) and the Author(s) or with their explicit written
// permission.
// 
// 5) The Font Software, modified or unmodified, in part or in whole,
// must be distributed entirely under this license, and must not be
// distributed under any other license. The requirement for fonts to
// remain under this license does not apply to any document created
// using the Font Software.
// 
// TERMINATION
// This license becomes null and void if any of the above conditions are
// not met.
// 
// DISCLAIMER
// THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
// OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL THE
// COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL
// DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM
// OTHER DEALINGS IN THE FONT SOFTWARE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Terminus
//     Size: 10x20
//     Bold: no
//     Italic: no
//     Memory usage: 2304 bytes
//
//*****************************************************************************

static const uint8_t g_pui8terminus10x20Data[2102] =
{
      4,  10,   0,  25,  17,   6, 240,  49,  81,  81,  81,  81,
     81,  81,  81,  81, 240,  33,  81, 240, 224,  13,   8, 129,
     49,  49,  49,  49,  49,  49,  49,   0,  15,  48,  30,   9,
    240, 209,  49,  65,  49,  65,  49,  65,  49,  55,  49,  49,
     65,  49,  65,  49,  55,  49,  49,  65,  49,  65,  49,  65,
     49, 240, 240, 144,  31,   9, 240,  97, 129, 101,  49,  33,
     33,  33,  33,  81,  33,  81,  33, 101,  97,  33,  81,  33,
     81,  33,  33,  33,  33,  53,  97, 129, 240, 240,  32,  27,
      9, 240, 240,  99,  49,  33,  17,  49,  35,  33, 129, 113,
    129, 113, 129, 113, 129,  35,  33,  49,  17,  33,  51, 240,
    240, 112,  33,   9, 240, 227,  81,  49,  65,  49,  65,  49,
     81,  17, 113, 113,  17,  33,  33,  49,  17,  17,  81,  33,
     81,  33,  81,  49,  49,  17,  51,  33, 240, 240, 112,   9,
      6,  97,  81,  81,  81,   0,  11, 112,  19,   7, 240, 129,
     81,  97,  81,  97,  97,  97,  97,  97,  97, 113,  97, 113,
    240, 240,  32,  19,   7, 240,  97, 113,  97, 113,  97,  97,
     97,  97,  97,  97,  81,  97,  81, 240, 240,  64,  18,   9,
      0,   6, 113,  49,  81,  17, 113,  87,  81, 113,  17,  81,
     49,   0,   8,  32,  14,   9,   0,   7,  17, 129, 129,  87,
     81, 129, 129,   0,   8,  64,  10,   7,   0,  11,  65,  97,
     97,  81, 240, 192,   8,   9,   0,  10,  23,   0,  11,  64,
      8,   6,   0,  10,  65,  81, 240, 224,  19,   8, 240, 240,
    113, 113,  97, 113,  97, 113,  97, 113,  97, 113,  97, 113,
    240, 240, 144,  33,   9, 240, 213,  49,  81,  33,  81,  33,
     81,  33,  66,  33,  49,  17,  33,  33,  33,  33,  17,  49,
     34,  65,  33,  81,  33,  81,  33,  81,  53, 240, 240, 144,
     20,   8, 240, 177,  98,  81,  17, 113, 113, 113, 113, 113,
    113, 113, 113, 113,  85, 240, 240,  80,  22,   9, 240, 213,
     49,  81,  33,  81,  33,  81, 129, 129, 113, 113, 113, 113,
    113, 113, 135, 240, 240, 128,  23,   9, 240, 213,  49,  81,
     33,  81, 129, 129, 129,  68, 145, 129, 129,  33,  81,  33,
     81,  53, 240, 240, 144,  27,   9, 240, 240,  49, 114,  97,
     17,  81,  33,  65,  49,  49,  65,  33,  81,  33,  81,  33,
     81,  39, 129, 129, 129, 240, 240, 128,  21,   9, 240, 199,
     33, 129, 129, 129, 134, 145, 129, 129, 129,  33,  81,  33,
     81,  53, 240, 240, 144,  25,   9, 240, 228,  65, 113, 129,
    129, 134,  49,  81,  33,  81,  33,  81,  33,  81,  33,  81,
     33,  81,  53, 240, 240, 144,  21,   9, 240, 199,  33,  81,
     33,  81, 129, 113, 129, 113, 129, 113, 129, 129, 129, 129,
    240, 240, 176,  29,   9, 240, 213,  49,  81,  33,  81,  33,
     81,  33,  81,  33,  81,  53,  49,  81,  33,  81,  33,  81,
     33,  81,  33,  81,  53, 240, 240, 144,  25,   9, 240, 213,
     49,  81,  33,  81,  33,  81,  33,  81,  33,  81,  33,  81,
     54, 129, 129, 129, 113,  68, 240, 240, 160,  12,   6, 240,
    240, 193,  81, 240, 225,  81, 240, 240,  80,  14,   7,   0,
      6,  33,  97, 240, 240,  65,  97,  97,  81, 240, 192,  20,
      9, 240, 240,  49, 113, 113, 113, 113, 113, 113, 145, 145,
    145, 145, 145, 145, 240, 240, 128,  10,   9,   0,   7, 119,
    240, 231,   0,   9,  32,  19,   9, 240, 193, 145, 145, 145,
    145, 145, 145, 113, 113, 113, 113, 113, 113, 240, 240, 224,
     21,   9, 240, 227,  81,  49,  49,  81,  33,  81, 129, 113,
    113, 113, 129, 240, 177, 129, 240, 240, 176,  34,   9, 240,
    214,  33,  97,  17,  97,  17,  52,  17,  33,  49,  17,  33,
     49,  17,  33,  49,  17,  33,  49,  17,  33,  34,  17,  50,
     17,  17, 129, 151, 240, 240, 112,  30,   9, 240, 213,  49,
     81,  33,  81,  33,  81,  33,  81,  33,  81,  39,  33,  81,
     33,  81,  33,  81,  33,  81,  33,  81,  33,  81, 240, 240,
    128,  29,   9, 240, 198,  49,  81,  33,  81,  33,  81,  33,
     81,  38,  49,  81,  33,  81,  33,  81,  33,  81,  33,  81,
     33,  81,  38, 240, 240, 144,  23,   9, 240, 213,  49,  81,
     33,  81,  33, 129, 129, 129, 129, 129, 129, 129,  81,  33,
     81,  53, 240, 240, 144,  30,   9, 240, 197,  65,  65,  49,
     81,  33,  81,  33,  81,  33,  81,  33,  81,  33,  81,  33,
     81,  33,  81,  33,  81,  33,  65,  53, 240, 240, 160,  19,
      9, 240, 199,  33, 129, 129, 129, 129, 133,  65, 129, 129,
    129, 129, 135, 240, 240, 128,  19,   9, 240, 199,  33, 129,
    129, 129, 129, 133,  65, 129, 129, 129, 129, 129, 240, 240,
    224,  27,   9, 240, 213,  49,  81,  33,  81,  33, 129, 129,
    129,  36,  33,  81,  33,  81,  33,  81,  33,  81,  33,  81,
     53, 240, 240, 144,  31,   9, 240, 193,  81,  33,  81,  33,
     81,  33,  81,  33,  81,  33,  81,  39,  33,  81,  33,  81,
     33,  81,  33,  81,  33,  81,  33,  81, 240, 240, 128,  19,
      7, 240,  99,  81,  97,  97,  97,  97,  97,  97,  97,  97,
     97,  97,  83, 240, 240,  32,  22,   8, 240, 211,  97, 113,
    113, 113, 113, 113, 113, 113,  33,  65,  33,  65,  33,  65,
     52, 240, 240,  80,  31,   9, 240, 193,  81,  33,  81,  33,
     65,  49,  49,  65,  33,  81,  17,  98, 113,  17,  97,  33,
     81,  49,  65,  65,  49,  81,  33,  81, 240, 240, 128,  19,
      9, 240, 193, 129, 129, 129, 129, 129, 129, 129, 129, 129,
    129, 129, 135, 240, 240, 128,  38,   9, 240, 193,  97,  18,
     66,  17,  17,  33,  17,  17,  17,  33,  17,  17,  34,  33,
     17,  34,  33,  17,  97,  17,  97,  17,  97,  17,  97,  17,
     97,  17,  97,  17,  97, 240, 240, 112,  35,   9, 240, 193,
     81,  33,  81,  33,  81,  33,  81,  34,  65,  33,  17,  49,
     33,  33,  33,  33,  49,  17,  33,  66,  33,  81,  33,  81,
     33,  81,  33,  81, 240, 240, 128,  30,   9, 240, 213,  49,
     81,  33,  81,  33,  81,  33,  81,  33,  81,  33,  81,  33,
     81,  33,  81,  33,  81,  33,  81,  33,  81,  53, 240, 240,
    144,  24,   9, 240, 198,  49,  81,  33,  81,  33,  81,  33,
     81,  33,  81,  38,  49, 129, 129, 129, 129, 129, 240, 240,
    224,  32,   9, 240, 213,  49,  81,  33,  81,  33,  81,  33,
     81,  33,  81,  33,  81,  33,  81,  33,  81,  33,  81,  33,
     81,  33,  33,  33,  53, 129, 145, 240,  80,  29,   9, 240,
    198,  49,  81,  33,  81,  33,  81,  33,  81,  33,  81,  38,
     50, 113,  17,  97,  33,  81,  49,  65,  65,  49,  81, 240,
    240, 128,  23,   9, 240, 213,  49,  81,  33,  81,  33, 129,
    129, 149, 145, 129, 129,  33,  81,  33,  81,  53, 240, 240,
    144,  19,   9, 240, 199,  81, 129, 129, 129, 129, 129, 129,
    129, 129, 129, 129, 129, 240, 240, 176,  31,   9, 240, 193,
     81,  33,  81,  33,  81,  33,  81,  33,  81,  33,  81,  33,
     81,  33,  81,  33,  81,  33,  81,  33,  81,  33,  81,  53,
    240, 240, 144,  30,   9, 240, 193,  81,  33,  81,  33,  81,
     33,  81,  49,  49,  65,  49,  65,  49,  65,  49,  81,  17,
     97,  17,  97,  17, 113, 129, 240, 240, 176,  38,   9, 240,
    193,  97,  17,  97,  17,  97,  17,  97,  17,  97,  17,  97,
     17,  97,  17,  34,  33,  17,  34,  33,  17,  17,  33,  17,
     17,  17,  33,  17,  18,  66,  17,  97, 240, 240, 112,  31,
      9, 240, 193,  81,  33,  81,  49,  49,  65,  49,  81,  17,
     97,  17, 113, 113,  17,  97,  17,  81,  49,  65,  49,  49,
     81,  33,  81, 240, 240, 128,  25,   9, 240, 193,  81,  33,
     81,  49,  49,  65,  49,  81,  17,  97,  17, 113, 129, 129,
    129, 129, 129, 129, 240, 240, 176,  19,   9, 240, 199, 129,
    129, 129, 113, 113, 113, 113, 113, 113, 129, 129, 135, 240,
    240, 128,  19,   7, 240,  99,  65,  97,  97,  97,  97,  97,
     97,  97,  97,  97,  97,  99, 240, 240,  32,  19,   8, 240,
    240,  33, 113, 129, 113, 129, 113, 129, 113, 129, 113, 129,
    113, 240, 240,  64,  19,   7, 240,  99,  97,  97,  97,  97,
     97,  97,  97,  97,  97,  97,  97,  67, 240, 240,  32,  12,
      9, 193, 113,  17,  81,  49,  49,  81,   0,  17,  16,   7,
      9,   0,  19,  23, 240,  80,   7,   7,   1, 113,   0,  16,
     48,  20,   9,   0,   8,   5, 145, 129,  54,  33,  81,  33,
     81,  33,  81,  33,  81,  54, 240, 240, 128,  26,   9, 240,
    193, 129, 129, 129, 134,  49,  81,  33,  81,  33,  81,  33,
     81,  33,  81,  33,  81,  33,  81,  38, 240, 240, 144,  18,
      9,   0,   8,   5,  49,  81,  33, 129, 129, 129, 129, 129,
     81,  53, 240, 240, 144,  27,   9, 240, 240,  49, 129, 129,
    129,  54,  33,  81,  33,  81,  33,  81,  33,  81,  33,  81,
     33,  81,  33,  81,  54, 240, 240, 128,  20,   9,   0,   8,
      5,  49,  81,  33,  81,  33,  81,  39,  33, 129, 129,  81,
     53, 240, 240, 144,  19,   8, 240, 195,  65, 113, 113,  85,
     81, 113, 113, 113, 113, 113, 113, 113, 240, 240, 112,  24,
      9,   0,   8,   6,  33,  81,  33,  81,  33,  81,  33,  81,
     33,  81,  33,  81,  33,  81,  54, 129, 129,  53, 192,  27,
      9, 240, 193, 129, 129, 129, 134,  49,  81,  33,  81,  33,
     81,  33,  81,  33,  81,  33,  81,  33,  81,  33,  81, 240,
    240, 128,  18,   7, 240, 113,  97, 240,  66,  97,  97,  97,
     97,  97,  97,  97,  83, 240, 240,  32,  21,   8, 240, 209,
    113, 240, 114, 113, 113, 113, 113, 113, 113, 113, 113,  49,
     49,  49,  49,  67, 192,  27,   9, 240, 193, 129, 129, 129,
    129,  81,  33,  65,  49,  49,  65,  33,  83,  97,  33,  81,
     49,  65,  65,  49,  81, 240, 240, 128,  19,   7, 240,  98,
     97,  97,  97,  97,  97,  97,  97,  97,  97,  97,  97,  83,
    240, 240,  32,  32,   9,   0,   7, 118,  49,  33,  33,  33,
     33,  33,  33,  33,  33,  33,  33,  33,  33,  33,  33,  33,
     33,  33,  33,  33,  33,  33,  33,  33, 240, 240, 128,  24,
      9,   0,   7, 118,  49,  81,  33,  81,  33,  81,  33,  81,
     33,  81,  33,  81,  33,  81,  33,  81, 240, 240, 128,  23,
      9,   0,   8,   5,  49,  81,  33,  81,  33,  81,  33,  81,
     33,  81,  33,  81,  33,  81,  53, 240, 240, 144,  25,   9,
      0,   7, 118,  49,  81,  33,  81,  33,  81,  33,  81,  33,
     81,  33,  81,  33,  81,  38,  49, 129, 129, 240,  32,  24,
      9,   0,   8,   6,  33,  81,  33,  81,  33,  81,  33,  81,
     33,  81,  33,  81,  33,  81,  54, 129, 129, 129, 176,  18,
      9,   0,   7, 113,  36,  33,  17,  98, 113, 129, 129, 129,
    129, 129, 240, 240, 224,  18,   9,   0,   8,   5,  49,  81,
     33, 129, 149, 145, 129,  33,  81,  53, 240, 240, 144,  19,
      8, 240, 177, 113, 113, 113,  85,  81, 113, 113, 113, 113,
    113, 113, 131, 240, 240,  64,  24,   9,   0,   7, 113,  81,
     33,  81,  33,  81,  33,  81,  33,  81,  33,  81,  33,  81,
     33,  81,  54, 240, 240, 128,  23,   9,   0,   7, 113,  81,
     33,  81,  33,  81,  49,  49,  65,  49,  81,  17,  97,  17,
    113, 129, 240, 240, 176,  29,   9,   0,   7, 113,  81,  33,
     81,  33,  81,  33,  33,  33,  33,  33,  33,  33,  33,  33,
     33,  33,  33,  33,  33,  33,  53, 240, 240, 144,  24,   9,
      0,   7, 113,  81,  33,  81,  49,  49,  81,  17, 113, 113,
     17,  81,  49,  49,  81,  33,  81, 240, 240, 128,  25,   9,
      0,   7, 113,  81,  33,  81,  33,  81,  33,  81,  33,  81,
     33,  81,  33,  81,  33,  81,  54, 129, 129,  53, 192,  16,
      9,   0,   7, 119, 129, 113, 113, 113, 113, 113, 113, 135,
    240, 240, 128,  19,   8, 240, 194,  81, 113, 113, 113, 113,
     82, 129, 113, 113, 113, 113, 130, 240, 240,  80,  18,   6,
    240,  49,  81,  81,  81,  81,  81,  81,  81,  81,  81,  81,
     81,  81, 240, 224,  19,   8, 240, 146, 129, 113, 113, 113,
    113, 130,  81, 113, 113, 113, 113,  82, 240, 240, 128,  15,
      9, 162,  49,  33,  33,  33,  33,  33,  33,  33,  50,   0,
     17,  32,
};

const tFont g_sFontterminus10x20 =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    10,

    //
    // The height of the font.
    //
    20,

    //
    // The baseline of the font.
    //
    16,

    //
    // The offset to each character in the font.
    //
    {
           0,    4,   21,   34,   64,   95,  122,  155,
         164,  183,  202,  220,  234,  244,  252,  260,
         279,  312,  332,  354,  377,  404,  425,  450,
         471,  500,  525,  537,  551,  571,  581,  600,
         621,  655,  685,  714,  737,  767,  786,  805,
         832,  863,  882,  904,  935,  954,  992, 1027,
        1057, 1081, 1113, 1142, 1165, 1184, 1215, 1245,
        1283, 1314, 1339, 1358, 1377, 1396, 1415, 1427,
        1434, 1441, 1461, 1487, 1505, 1532, 1552, 1571,
        1595, 1622, 1640, 1661, 1688, 1707, 1739, 1763,
        1786, 1811, 1835, 1853, 1871, 1890, 1914, 1937,
        1966, 1990, 2015, 2031, 2050, 2068, 2087,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8terminus10x20Data
};
