//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidatypewriter
//     Size: 7x13
//     Bold: no
//     Italic: no
//     Memory usage: 1668 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidatypewriter7x13Data[1466] =
{
      5,   7,   0,  10,  64,  12,   7, 114,  82,  82,  82,  82,
     81, 210,  82, 240,  64,  11,   7,   1,  17,  65,  17,  65,
     17,   0,   8,  48,  20,   7, 129,  33,  49,  33,  38,  33,
     33,  49,  33,  38,  33,  33,  49,  33,  49,  33, 240,  16,
     21,   7,  33,  83,  49,  17,  17,  33,  17,  82,  98,  81,
     17,  65,  17,  33,  17,  17,  51,  81, 176,  20,   7, 130,
     65,  33,  34,  33,  17,  34,  17,  81,  81,  18,  33,  17,
     34,  33,  33,  66, 240,  20,   7, 146,  65,  33,  49,  33,
     66,  66,  33,  17,  33,  17,  17,  49,  33,  49,  51,  17,
    240,   8,   7,   1,  97,  97,   0,   8,  80,  14,   7,  34,
     65,  97,  81,  97,  97,  97,  97, 113,  97, 114, 160,  14,
      7,   2, 113,  97, 113,  97,  97,  97,  97,  81,  97,  66,
    192,  15,   7, 145,  65,  17,  17,  49,  17,  49,  17,  17,
     65,   0,   5,  96,  12,   7, 240,  33,  97,  97,  55,  49,
     97,  97, 240, 144,   8,   7,   0,   7,  18,  82,  66, 192,
      8,   7, 240, 240,  87, 240, 240, 192,   8,   7,   0,   7,
      2,  82, 240,  64,  14,   7,  65,  97,  81,  97,  81,  97,
     97,  81,  97,  81,  97, 208,  20,   7, 131,  49,  49,  33,
     49,  33,  49,  33,  49,  33,  49,  33,  49,  33,  49,  51,
    240,  32,  14,   7, 145,  82,  65,  17,  97,  97,  97,  97,
     97,  97, 240,  48,  14,   7, 131,  49,  49,  97,  97,  81,
     81,  81,  81, 101, 240,  16,  15,   7, 131,  49,  49,  97,
     97,  66, 113,  97,  33,  49,  51, 240,  32,  16,   7, 177,
     82,  65,  17,  49,  33,  33,  49,  38,  81,  97,  97, 240,
     16,  14,   7, 117,  33,  97, 100, 113,  97,  97,  33,  49,
     51, 240,  32,  17,   7, 131,  49,  49,  33,  97, 100,  49,
     49,  33,  49,  33,  49,  51, 240,  32,  13,   7, 117,  97,
     97,  81,  81,  97,  81,  97,  97, 240,  64,  19,   7, 131,
     49,  49,  33,  49,  33,  49,  51,  49,  49,  33,  49,  33,
     49,  51, 240,  32,  17,   7, 131,  49,  49,  33,  49,  33,
     49,  52,  97,  97,  33,  49,  51, 240,  32,  10,   7, 240,
     98,  82, 240, 178,  82, 240,  64,  10,   7, 240, 114,  82,
    240, 178,  82,  66, 192,  12,   7, 240,  33,  81,  81,  81,
    113, 113, 113, 240, 144,   8,   7, 240, 215, 119, 240, 240,
     80,  11,   7, 225, 113, 113, 113,  81,  81,  81, 240, 192,
     12,   7, 116, 113,  97,  97,  51,  65, 209,  97, 240,  64,
     23,   7, 147,  49,  49,  17,  35,  17,  17,  33,  17,  17,
     33,  17,  17,  18,  17,  33,  33,  17, 115, 240,  16,  18,
      7, 146,  82,  65,  33,  49,  33,  49,  33,  38,  17,  65,
     17,  65,  17,  65, 240,  19,   7, 116,  49,  49,  33,  49,
     33,  49,  36,  49,  49,  33,  49,  33,  49,  36, 240,  32,
     14,   7, 147,  49,  33,  33,  97,  97,  97,  97, 113, 115,
    240,  16,  20,   7, 115,  65,  33,  49,  49,  33,  49,  33,
     49,  33,  49,  33,  49,  33,  33,  51, 240,  48,  13,   7,
    117,  33,  97,  97, 100,  49,  97,  97, 101, 240,  16,  13,
      7, 116,  49,  97,  97, 100,  49,  97,  97,  97, 240,  80,
     17,   7, 147,  49,  33,  33,  97,  97,  97,  49,  33,  49,
     49,  33,  67, 240,  16,  21,   7, 113,  49,  33,  49,  33,
     49,  33,  49,  37,  33,  49,  33,  49,  33,  49,  33,  49,
    240,  16,  13,   7, 117,  65,  97,  97,  97,  97,  97,  97,
     69, 240,  16,  13,   7, 133,  65,  97,  97,  97,  97,  97,
     97,  51, 240,  48,  20,   7, 113,  65,  17,  49,  33,  33,
     49,  17,  67,  65,  33,  49,  49,  33,  65,  17,  65, 240,
     13,   7, 113,  97,  97,  97,  97,  97,  97,  97, 100, 240,
     32,  24,   7, 113,  65,  18,  34,  18,  34,  17,  18,  17,
     17,  18,  17,  17,  18,  17,  17,  65,  17,  65,  17,  65,
    240,  24,   7, 113,  49,  34,  33,  34,  33,  33,  17,  17,
     33,  17,  17,  33,  34,  33,  34,  33,  49,  33,  49, 240,
     16,  20,   7, 146,  65,  33,  33,  65,  17,  65,  17,  65,
     17,  65,  17,  65,  33,  33,  66, 240,  32,  17,   7, 116,
     49,  49,  33,  49,  33,  49,  33,  49,  36,  49,  97,  97,
    240,  80,  20,   7, 146,  65,  33,  33,  65,  17,  65,  17,
     65,  17,  65,  17,  65,  33,  33,  66,  98,  98,  20,   7,
    116,  49,  49,  33,  49,  33,  49,  36,  49,  33,  49,  49,
     33,  49,  33,  49, 240,  16,  13,   7, 132,  33,  97,  98,
     99,  98,  97,  97,  36, 240,  32,  13,   7, 119,  49,  97,
     97,  97,  97,  97,  97,  97, 240,  32,  21,   7, 113,  49,
     33,  49,  33,  49,  33,  49,  33,  49,  33,  49,  33,  49,
     33,  49,  51, 240,  32,  20,   7, 113,  65,  17,  65,  17,
     65,  17,  65,  33,  33,  49,  33,  49,  33,  66,  82, 240,
     32,  22,   7, 113,  82,  33,  34,  33,  34,  33,  34,  17,
     17,  17,  18,  18,  33,  49,  33,  49,  33,  49, 240,  21,
      7, 113,  49,  33,  49,  49,  17,  65,  17,  81,  81,  17,
     65,  17,  49,  49,  33,  49, 240,  16,  18,   7, 113,  49,
     33,  49,  33,  49,  49,  17,  65,  17,  81,  97,  97,  97,
    240,  48,  13,   7, 117,  97,  81,  97,  81,  81,  97,  81,
    101, 240,  16,  14,   7,   3,  65,  97,  97,  97,  97,  97,
     97,  97,  97,  99, 176,  14,   7,   1,  97, 113,  97, 113,
     97,  97, 113,  97, 113,  97, 144,  14,   7,   3,  97,  97,
     97,  97,  97,  97,  97,  97,  97,  67, 176,  15,   7, 145,
     97,  81,  17,  65,  17,  49,  49,  33,  49, 240, 240, 112,
      6,   7,   0,   8, 103, 112,   7,   7,   1, 113,   0,   9,
     48,  15,   7, 240, 115,  49,  49,  97,  52,  33,  49,  33,
     49,  51,  17, 240,  20,   7,   1,  97,  97,  97,  18,  50,
     33,  33,  49,  33,  49,  33,  49,  33,  49,  36, 240,  32,
     12,   7, 240, 131,  49,  81,  97,  97, 113, 115, 240,  16,
     20,   7,  65,  97,  97,  52,  33,  49,  33,  49,  33,  49,
     33,  49,  33,  34,  50,  17, 240,  16,  15,   7, 240, 115,
     49,  49,  33,  49,  37,  33,  97,  49,  51, 240,  32,  14,
      7,  35,  49,  97,  85,  49,  97,  97,  97,  97,  97, 240,
     64,  18,   7, 240, 116,  33,  49,  33,  49,  33,  49,  33,
     34,  50,  17,  97,  97,  51,  48,  21,   7,   1,  97,  97,
     97,  18,  50,  33,  33,  49,  33,  49,  33,  49,  33,  49,
     33,  49, 240,  16,  13,   7,  33,  97, 179,  97,  97,  97,
     97,  97,  97, 240,  48,  14,   7,  49,  97, 164,  97,  97,
     97,  97,  97,  97,  97,  51,  64,  19,   7,   1,  97,  97,
     97,  49,  33,  33,  49,  17,  67,  65,  33,  49,  49,  33,
     65, 240,  14,   7,   3,  97,  97,  97,  97,  97,  97,  97,
     97,  97, 240,  48,  20,   7, 240,  97,  17,  33,  18,  18,
     18,  33,  34,  33,  34,  33,  34,  33,  34,  33,  33, 224,
     19,   7, 240,  97,  18,  50,  33,  33,  49,  33,  49,  33,
     49,  33,  49,  33,  49, 240,  16,  17,   7, 240, 115,  49,
     49,  33,  49,  33,  49,  33,  49,  33,  49,  51, 240,  32,
     19,   7, 240,  97,  18,  50,  33,  33,  49,  33,  49,  33,
     49,  33,  49,  36,  49,  97,  96,  19,   7, 240, 116,  33,
     49,  33,  49,  33,  49,  33,  49,  33,  34,  50,  17,  97,
     97,  32,  13,   7, 240,  97,  18,  50,  81,  97,  97,  97,
     97, 240,  80,  12,   7, 240, 116,  33,  97, 115, 113,  97,
     36, 240,  32,  13,   7, 129,  97,  85,  49,  97,  97,  97,
     97, 115, 240,  16,  19,   7, 240,  97,  49,  33,  49,  33,
     49,  33,  49,  33,  49,  33,  34,  50,  17, 240,  16,  17,
      7, 240,  97,  49,  33,  49,  33,  49,  49,  17,  65,  17,
     81,  97, 240,  48,  19,   7, 240,  97,  82,  33,  34,  33,
     34,  17,  17,  17,  17,  49,  33,  49,  33,  49, 240,  18,
      7, 240,  97,  49,  33,  49,  49,  17,  81,  81,  17,  49,
     49,  33,  49, 240,  16,  18,   7, 240,  97,  49,  33,  49,
     33,  49,  49,  17,  65,  17,  81,  97,  81,  82,  80,  12,
      7, 240, 101,  97,  81,  81,  81,  81, 101, 240,  16,  14,
      7,  34,  65,  97,  97, 113,  66, 113,  81,  97,  97, 114,
    160,  14,   7,   1,  97,  97,  97,  97,  97,  97,  97,  97,
     97,  97, 208,  14,   7,   2, 113,  97,  97,  81, 114,  65,
    113,  97,  97,  66, 192,   9,   7, 240, 227,  34,  35, 240,
    240, 208,
};

const tFont g_sFontlucidatypewriter7x13 =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    7,

    //
    // The height of the font.
    //
    12,

    //
    // The baseline of the font.
    //
    10,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   17,   28,   48,   69,   89,  109,
         117,  131,  145,  160,  172,  180,  188,  196,
         210,  230,  244,  258,  273,  289,  303,  320,
         333,  352,  369,  379,  389,  401,  409,  420,
         432,  455,  473,  492,  506,  526,  539,  552,
         569,  590,  603,  616,  636,  649,  673,  697,
         717,  734,  754,  774,  787,  800,  821,  841,
         863,  884,  902,  915,  929,  943,  957,  972,
         978,  985, 1000, 1020, 1032, 1052, 1067, 1081,
        1099, 1120, 1133, 1147, 1166, 1180, 1200, 1219,
        1236, 1255, 1274, 1287, 1299, 1312, 1331, 1348,
        1367, 1385, 1403, 1415, 1429, 1443, 1457,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidatypewriter7x13Data
};
