//*****************************************************************************
//
// Copyright (c) 2014 Dimitar Toshkov Zhekov,
// with Reserved Font Name "Terminus Font".
// 
// This Font Software is licensed under the SIL Open Font License, Version 1.1.
// This license is copied below, and is also available with a FAQ at:
// http://scripts.sil.org/OFL
// 
// 
// -----------------------------------------------------------
// SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007
// -----------------------------------------------------------
// 
// PREAMBLE
// The goals of the Open Font License (OFL) are to stimulate worldwide
// development of collaborative font projects, to support the font creation
// efforts of academic and linguistic communities, and to provide a free and
// open framework in which fonts may be shared and improved in partnership
// with others.
// 
// The OFL allows the licensed fonts to be used, studied, modified and
// redistributed freely as long as they are not sold by themselves. The
// fonts, including any derivative works, can be bundled, embedded, 
// redistributed and/or sold with any software provided that any reserved
// names are not used by derivative works. The fonts and derivatives,
// however, cannot be released under any other type of license. The
// requirement for fonts to remain under this license does not apply
// to any document created using the fonts or their derivatives.
// 
// DEFINITIONS
// "Font Software" refers to the set of files released by the Copyright
// Holder(s) under this license and clearly marked as such. This may
// include source files, build scripts and documentation.
// 
// "Reserved Font Name" refers to any names specified as such after the
// copyright statement(s).
// 
// "Original Version" refers to the collection of Font Software components as
// distributed by the Copyright Holder(s).
// 
// "Modified Version" refers to any derivative made by adding to, deleting,
// or substituting -- in part or in whole -- any of the components of the
// Original Version, by changing formats or by porting the Font Software to a
// new environment.
// 
// "Author" refers to any designer, engineer, programmer, technical
// writer or other person who contributed to the Font Software.
// 
// PERMISSION & CONDITIONS
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of the Font Software, to use, study, copy, merge, embed, modify,
// redistribute, and sell modified and unmodified copies of the Font
// Software, subject to the following conditions:
// 
// 1) Neither the Font Software nor any of its individual components,
// in Original or Modified Versions, may be sold by itself.
// 
// 2) Original or Modified Versions of the Font Software may be bundled,
// redistributed and/or sold with any software, provided that each copy
// contains the above copyright notice and this license. These can be
// included either as stand-alone text files, human-readable headers or
// in the appropriate machine-readable metadata fields within text or
// binary files as long as those fields can be easily viewed by the user.
// 
// 3) No Modified Version of the Font Software may use the Reserved Font
// Name(s) unless explicit written permission is granted by the corresponding
// Copyright Holder. This restriction only applies to the primary font name as
// presented to the users.
// 
// 4) The name(s) of the Copyright Holder(s) or the Author(s) of the Font
// Software shall not be used to promote, endorse or advertise any
// Modified Version, except to acknowledge the contribution(s) of the
// Copyright Holder(s) and the Author(s) or with their explicit written
// permission.
// 
// 5) The Font Software, modified or unmodified, in part or in whole,
// must be distributed entirely under this license, and must not be
// distributed under any other license. The requirement for fonts to
// remain under this license does not apply to any document created
// using the Font Software.
// 
// TERMINATION
// This license becomes null and void if any of the above conditions are
// not met.
// 
// DISCLAIMER
// THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
// OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL THE
// COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL
// DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM
// OTHER DEALINGS IN THE FONT SOFTWARE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Terminus
//     Size: 11x22
//     Bold: yes
//     Italic: no
//     Memory usage: 2472 bytes
//
//*****************************************************************************

static const uint8_t g_pui8terminus11x22bData[2272] =
{
      5,  11,   0,  30,  32,  19,   7, 240,  98,  82,  82,  82,
     82,  82,  82,  82,  82, 240,  66,  82,  82, 240, 240, 160,
     15,   9, 146,  34,  50,  34,  50,  34,  50,  34,  50,  34,
      0,  18,  48,  33,  11, 240, 240,  82,  34,  82,  34,  82,
     34,  82,  34,  58,  50,  34,  82,  34,  82,  34,  82,  34,
     58,  50,  34,  82,  34,  82,  34,  82,  34,   0,   7,  32,
     37,  11, 240, 178, 146, 118,  66,  18,  18,  34,  34,  34,
     18,  34,  82,  34,  98,  18, 118, 114,  18,  98,  34,  82,
     34,  18,  34,  34,  34,  18,  18,  70, 114, 146, 240, 240,
    128,  33,  11, 240, 240,  67,  50,  34,  18,  34,  34,  18,
     18,  67,  34, 130, 146, 130, 146, 130, 146, 130,  35,  66,
     18,  18,  34,  34,  18,  34,  51,   0,   7,  16,  32,  11,
    240, 240,  85,  82,  50,  66,  50,  66,  50,  82,  18, 115,
    116,  98,  34,  18,  18,  68,  18,  82,  34,  82,  34,  82,
     50,  52,  53,  18,   0,   7,  10,   7, 114,  82,  82,  82,
     82,   0,  14,  80,  20,   8, 240, 194,  82,  82,  98,  82,
     98,  98,  98,  98,  98, 114,  98, 114, 114, 240, 240, 208,
     20,   8, 240, 146, 114, 114,  98, 114,  98,  98,  98,  98,
     98,  82,  98,  82,  82,   0,   5,  96,  20,  11,   0,   8,
     50,  66,  66,  34, 100, 130,  90,  82, 132,  98,  34,  66,
     66,   0,   9, 112,  16,  11,   0,   8,  98, 146, 146, 146,
     90,  82, 146, 146, 146,   0,  10,  32,  12,   8,   0,  13,
     18,  98,  98,  98,  82, 240, 240, 128,   8,  10,   0,  12,
     73,   0,  13, 112,  10,   7,   0,  12,  34,  82,  82, 240,
    240, 160,  21,  10, 240, 240,  98, 130, 114, 130, 114, 130,
    114, 130, 114, 130, 114, 130, 114, 130,   0,   7,  32,  35,
     10, 240, 240,  37,  66,  50,  34,  82,  18,  82,  18,  67,
     18,  52,  18,  34,  18,  18,  18,  34,  20,  50,  19,  66,
     18,  82,  18,  82,  34,  50,  69,   0,   6,  80,  21,   9,
    240, 242,  99,  84,  66,  18, 114, 114, 114, 114, 114, 114,
    114, 114, 114,  72,   0,   5,  96,  25,  10, 240, 240,  37,
     66,  50,  34,  82,  18,  82,  18,  82, 130, 114, 114, 114,
    114, 114, 114, 114, 137,   0,   6,  48,  25,  10, 240, 240,
     37,  66,  50,  34,  82, 130, 130, 114,  84, 146, 146, 130,
    130,  18,  82,  34,  50,  69,   0,   6,  80,  28,  10, 240,
    240, 114, 115, 100,  82,  18,  66,  34,  50,  50,  34,  66,
     18,  82,  18,  82,  18,  82,  25, 130, 130, 130,   0,   6,
     48,  23,  10, 240, 249,  18, 130, 130, 130, 135, 146, 146,
    130, 130,  18,  82,  18,  82,  34,  50,  69,   0,   6,  80,
     28,  10, 240, 240,  38,  50, 114, 130, 130, 135,  50,  66,
     34,  82,  18,  82,  18,  82,  18,  82,  18,  82,  34,  50,
     69,   0,   6,  80,  22,  10, 240, 249,  18,  82,  18,  82,
    130, 114, 130, 114, 130, 114, 130, 114, 130, 130, 130,   0,
      6, 112,  32,  10, 240, 240,  37,  66,  50,  34,  82,  18,
     82,  18,  82,  34,  50,  69,  66,  50,  34,  82,  18,  82,
     18,  82,  18,  82,  34,  50,  69,   0,   6,  80,  28,  10,
    240, 240,  37,  66,  50,  34,  82,  18,  82,  18,  82,  18,
     82,  18,  82,  34,  66,  55, 130, 130, 130, 114,  54,   0,
      6,  80,  15,   7, 240, 240, 194,  82,  82, 240, 240,  50,
     82,  82,   0,   5, 112,  17,   8,   0,   6,  18,  98,  98,
    240, 240, 130,  98,  98,  98,  82, 240, 240, 128,  21,  10,
    240, 240,  98, 114, 114, 114, 114, 114, 114, 130, 146, 146,
    146, 146, 146, 146,   0,   6,  64,  11,  10,   0,   8, 105,
    240, 240, 185,   0,  11,  48,  20,  10, 240, 242, 146, 146,
    146, 146, 146, 146, 130, 114, 114, 114, 114, 114, 114,   0,
      7,  32,  23,  10, 240, 240,  37,  66,  50,  34,  82,  18,
     82, 130, 114, 114, 114, 130, 240, 210, 130, 130,   0,   6,
     96,  36,  11, 240, 240,  86,  66,  66,  34,  98,  18,  53,
     18,  34,  34,  18,  18,  50,  18,  18,  50,  18,  18,  50,
     18,  18,  50,  18,  34,  34,  18,  53,  18, 162, 168,   0,
      7,  33,  10, 240, 240,  37,  66,  50,  34,  82,  18,  82,
     18,  82,  18,  82,  18,  82,  25,  18,  82,  18,  82,  18,
     82,  18,  82,  18,  82,  18,  82,   0,   6,  48,  31,  10,
    240, 247,  50,  66,  34,  82,  18,  82,  18,  82,  18,  66,
     39,  50,  66,  34,  82,  18,  82,  18,  82,  18,  82,  18,
     66,  39,   0,   6,  80,  27,  10, 240, 240,  37,  66,  50,
     34,  82,  18,  82,  18, 130, 130, 130, 130, 130, 130,  82,
     18,  82,  34,  50,  69,   0,   6,  80,  32,  10, 240, 247,
     50,  66,  34,  82,  18,  82,  18,  82,  18,  82,  18,  82,
     18,  82,  18,  82,  18,  82,  18,  82,  18,  82,  18,  66,
     39,   0,   6,  80,  20,  10, 240, 249,  18, 130, 130, 130,
    130, 135,  50, 130, 130, 130, 130, 130, 137,   0,   6,  48,
     20,  10, 240, 249,  18, 130, 130, 130, 130, 135,  50, 130,
    130, 130, 130, 130, 130,   0,   7,  32,  30,  10, 240, 240,
     37,  66,  50,  34,  82,  18,  82,  18, 130, 130, 130,  37,
     18,  82,  18,  82,  18,  82,  18,  82,  34,  50,  69,   0,
      6,  80,  33,  10, 240, 242,  82,  18,  82,  18,  82,  18,
     82,  18,  82,  18,  82,  25,  18,  82,  18,  82,  18,  82,
     18,  82,  18,  82,  18,  82,  18,  82,   0,   6,  48,  19,
      9, 240, 198,  82, 114, 114, 114, 114, 114, 114, 114, 114,
    114, 114, 114,  86,   0,   6,  25,  10, 240, 240,  70,  98,
    130, 130, 130, 130, 130, 130, 130,  34,  66,  34,  66,  34,
     66,  50,  34,  84,   0,   6,  96,  32,  10, 240, 242,  82,
     18,  82,  18,  66,  34,  50,  50,  34,  66,  18,  84, 100,
     98,  18,  82,  34,  66,  50,  50,  66,  34,  82,  18,  82,
      0,   6,  48,  20,  10, 240, 242, 130, 130, 130, 130, 130,
    130, 130, 130, 130, 130, 130, 130, 137,   0,   6,  48,  36,
     11, 240, 240,  49, 129,  18,  98,  19,  67,  20,  36,  18,
     20,  18,  18,  34,  34,  18,  98,  18,  98,  18,  98,  18,
     98,  18,  98,  18,  98,  18,  98,  18,  98,   0,   7,  36,
     10, 240, 242,  82,  18,  82,  18,  82,  18,  82,  19,  66,
     20,  50,  18,  18,  34,  18,  34,  18,  18,  52,  18,  67,
     18,  82,  18,  82,  18,  82,  18,  82,   0,   6,  48,  33,
     10, 240, 240,  37,  66,  50,  34,  82,  18,  82,  18,  82,
     18,  82,  18,  82,  18,  82,  18,  82,  18,  82,  18,  82,
     18,  82,  34,  50,  69,   0,   6,  80,  26,  10, 240, 247,
     50,  66,  34,  82,  18,  82,  18,  82,  18,  82,  18,  66,
     39,  50, 130, 130, 130, 130, 130,   0,   7,  32,  35,  10,
    240, 240,  37,  66,  50,  34,  82,  18,  82,  18,  82,  18,
     82,  18,  82,  18,  82,  18,  82,  18,  82,  18,  82,  18,
     82,  34,  20,  69, 146, 146, 240, 240,  16,  31,  10, 240,
    247,  50,  66,  34,  82,  18,  82,  18,  82,  18,  82,  18,
     66,  39,  52,  98,  18,  82,  34,  66,  50,  50,  66,  34,
     82,   0,   6,  48,  25,  10, 240, 240,  37,  66,  50,  34,
     82,  18, 130, 146, 149, 146, 146, 130, 130,  18,  82,  34,
     50,  69,   0,   6,  80,  21,  11, 240, 240,  58,  82, 146,
    146, 146, 146, 146, 146, 146, 146, 146, 146, 146, 146,   0,
      7,  64,  33,  10, 240, 242,  82,  18,  82,  18,  82,  18,
     82,  18,  82,  18,  82,  18,  82,  18,  82,  18,  82,  18,
     82,  18,  82,  18,  82,  34,  50,  69,   0,   6,  80,  31,
     10, 240, 242,  82,  18,  82,  18,  82,  18,  82,  18,  82,
     34,  50,  50,  50,  50,  50,  50,  50,  66,  18,  82,  18,
     99, 115, 115,   0,   6,  96,  37,  11, 240, 240,  50,  98,
     18,  98,  18,  98,  18,  98,  18,  98,  18,  98,  18,  98,
     18,  34,  34,  18,  34,  34,  18,  20,  18,  20,  36,  19,
     67,  18,  98,  17, 129,   0,   7,  32,  10, 240, 242,  82,
     18,  82,  34,  50,  50,  50,  66,  18,  82,  18,  99, 115,
     98,  18,  82,  18,  66,  50,  50,  50,  34,  82,  18,  82,
      0,   6,  48,  27,  11, 240, 240,  50,  98,  18,  98,  34,
     66,  50,  66,  66,  34,  82,  34, 100, 116, 130, 146, 146,
    146, 146, 146,   0,   7,  64,  20,  10, 240, 249, 130, 130,
    130, 114, 114, 114, 114, 114, 114, 114, 130, 130, 137,   0,
      6,  48,  20,   8, 240, 149,  50,  98,  98,  98,  98,  98,
     98,  98,  98,  98,  98,  98, 101, 240, 240, 208,  20,  10,
    240, 242, 130, 146, 130, 146, 130, 146, 130, 146, 130, 146,
    130, 146, 130,   0,   6,  64,  20,   8, 240, 149,  98,  98,
     98,  98,  98,  98,  98,  98,  98,  98,  98,  98,  53, 240,
    240, 208,  13,  10, 225, 131,  98,  18,  66,  50,  34,  82,
      0,  20,  16,   8,  10,   0,  22,  73, 240, 240,  16,   8,
      8,   2, 114, 114,   0,  19,  64,  21,  10,   0,   8, 118,
    146, 146, 130,  40,  18,  82,  18,  82,  18,  82,  18,  82,
     40,   0,   6,  48,  28,  10, 240, 242, 130, 130, 130, 135,
     50,  66,  34,  82,  18,  82,  18,  82,  18,  82,  18,  82,
     18,  82,  18,  66,  39,   0,   6,  80,  21,  10,   0,   9,
      5,  66,  50,  34,  82,  18, 130, 130, 130, 130,  82,  34,
     50,  69,   0,   6,  80,  29,  10, 240, 240, 114, 130, 130,
    130,  55,  34,  66,  18,  82,  18,  82,  18,  82,  18,  82,
     18,  82,  18,  82,  34,  66,  55,   0,   6,  48,  21,  10,
      0,   9,   5,  66,  50,  34,  82,  18,  82,  25,  18, 130,
    130, 146,  66,  54,   0,   6,  64,  21,  10, 240, 240,  69,
     66, 130, 130,  88,  82, 130, 130, 130, 130, 130, 130, 130,
    130,   0,   6, 112,  27,  10,   0,   9,   7,  34,  66,  18,
     82,  18,  82,  18,  82,  18,  82,  18,  82,  18,  82,  34,
     66,  55, 130, 130, 114,  54, 208,  29,  10, 240, 242, 130,
    130, 130, 135,  50,  66,  34,  82,  18,  82,  18,  82,  18,
     82,  18,  82,  18,  82,  18,  82,  18,  82,   0,   6,  48,
     19,   8, 240, 178,  98,  98, 196,  98,  98,  98,  98,  98,
     98,  98,  98,  70, 240, 240, 192,  25,   9, 240, 240,  34,
    114, 114, 228, 114, 114, 114, 114, 114, 114, 114, 114, 114,
     34,  50,  34,  50,  34,  50,  53, 192,  28,   9, 240, 194,
    114, 114, 114, 114,  66,  18,  50,  34,  34,  50,  18,  68,
     84,  82,  18,  66,  34,  50,  50,  34,  66,   0,   5,  96,
     20,   8, 240, 148,  98,  98,  98,  98,  98,  98,  98,  98,
     98,  98,  98,  98,  70, 240, 240, 192,  34,  11,   0,   9,
     88,  50,  34,  18,  34,  34,  34,  18,  34,  34,  18,  34,
     34,  18,  34,  34,  18,  34,  34,  18,  34,  34,  18,  34,
     34,  18,  34,  34,   0,   7,  26,  10,   0,   8, 103,  50,
     66,  34,  82,  18,  82,  18,  82,  18,  82,  18,  82,  18,
     82,  18,  82,  18,  82,   0,   6,  48,  25,  10,   0,   9,
      5,  66,  50,  34,  82,  18,  82,  18,  82,  18,  82,  18,
     82,  18,  82,  34,  50,  69,   0,   6,  80,  28,  10,   0,
      8, 103,  50,  66,  34,  82,  18,  82,  18,  82,  18,  82,
     18,  82,  18,  82,  18,  66,  39,  50, 130, 130, 130, 240,
     48,  27,  10,   0,   9,   7,  34,  66,  18,  82,  18,  82,
     18,  82,  18,  82,  18,  82,  18,  82,  34,  66,  55, 130,
    130, 130, 130, 176,  19,  10,   0,   8,  98,  37,  18,  18,
     84,  99, 114, 130, 130, 130, 130, 130,   0,   7,  32,  19,
     10,   0,   8, 119,  34,  82,  18, 130, 151, 146, 130, 130,
     18,  82,  39,   0,   6,  64,  21,  10, 240, 240,  50, 130,
    130, 130,  88,  82, 130, 130, 130, 130, 130, 130, 130, 149,
      0,   6,  48,  26,  10,   0,   8,  98,  82,  18,  82,  18,
     82,  18,  82,  18,  82,  18,  82,  18,  82,  18,  82,  34,
     66,  55,   0,   6,  48,  25,  10,   0,   8,  98,  82,  18,
     82,  18,  82,  34,  50,  50,  50,  50,  50,  66,  18,  82,
     18,  99, 115,   0,   6,  96,  32,  11,   0,   9,  82,  98,
     18,  98,  18,  98,  18,  34,  34,  18,  34,  34,  18,  34,
     34,  18,  34,  34,  18,  34,  34,  18,  34,  34,  40,   0,
      7,  16,  25,  10,   0,   8,  98,  82,  18,  82,  34,  50,
     66,  18,  99, 115,  98,  18,  66,  50,  34,  82,  18,  82,
      0,   6,  48,  28,  10,   0,   8,  98,  82,  18,  82,  18,
     82,  18,  82,  18,  82,  18,  82,  18,  82,  18,  82,  34,
     66,  55, 130, 130, 114,  54, 208,  17,  10,   0,   8, 105,
    130, 114, 114, 114, 114, 114, 114, 114, 137,   0,   6,  48,
     21,   9, 240, 240,  19,  82,  98, 114, 114, 114,  83, 130,
    114, 114, 114, 114, 130, 131,   0,   5, 112,  20,   7, 240,
     98,  82,  82,  82,  82,  82,  82,  82,  82,  82,  82,  82,
     82,  82, 240, 240, 160,  20,   9, 240, 195, 130, 130, 114,
    114, 114, 131,  82, 114, 114, 114, 114,  98,  83,   0,   6,
     48,  15,  10, 179,  50,  18,  18,  34,  18,  34,  18,  18,
     51,   0,  21,  64,
};

const tFont g_sFontterminus11x22b =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    11,

    //
    // The height of the font.
    //
    22,

    //
    // The baseline of the font.
    //
    17,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   24,   39,   72,  109,  142,  174,
         184,  204,  224,  244,  260,  272,  280,  290,
         311,  346,  367,  392,  417,  445,  468,  496,
         518,  550,  578,  593,  610,  631,  642,  662,
         685,  721,  754,  785,  812,  844,  864,  884,
         914,  947,  966,  991, 1023, 1043, 1079, 1115,
        1148, 1174, 1209, 1240, 1265, 1286, 1319, 1350,
        1387, 1419, 1446, 1466, 1486, 1506, 1526, 1539,
        1547, 1555, 1576, 1604, 1625, 1654, 1675, 1696,
        1723, 1752, 1771, 1796, 1824, 1844, 1878, 1904,
        1929, 1957, 1984, 2003, 2022, 2043, 2069, 2094,
        2126, 2151, 2179, 2196, 2217, 2237, 2257,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8terminus11x22bData
};
