//*****************************************************************************
//
// Copyright (c) 2014 Dimitar Toshkov Zhekov,
// with Reserved Font Name "Terminus Font".
// 
// This Font Software is licensed under the SIL Open Font License, Version 1.1.
// This license is copied below, and is also available with a FAQ at:
// http://scripts.sil.org/OFL
// 
// 
// -----------------------------------------------------------
// SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007
// -----------------------------------------------------------
// 
// PREAMBLE
// The goals of the Open Font License (OFL) are to stimulate worldwide
// development of collaborative font projects, to support the font creation
// efforts of academic and linguistic communities, and to provide a free and
// open framework in which fonts may be shared and improved in partnership
// with others.
// 
// The OFL allows the licensed fonts to be used, studied, modified and
// redistributed freely as long as they are not sold by themselves. The
// fonts, including any derivative works, can be bundled, embedded, 
// redistributed and/or sold with any software provided that any reserved
// names are not used by derivative works. The fonts and derivatives,
// however, cannot be released under any other type of license. The
// requirement for fonts to remain under this license does not apply
// to any document created using the fonts or their derivatives.
// 
// DEFINITIONS
// "Font Software" refers to the set of files released by the Copyright
// Holder(s) under this license and clearly marked as such. This may
// include source files, build scripts and documentation.
// 
// "Reserved Font Name" refers to any names specified as such after the
// copyright statement(s).
// 
// "Original Version" refers to the collection of Font Software components as
// distributed by the Copyright Holder(s).
// 
// "Modified Version" refers to any derivative made by adding to, deleting,
// or substituting -- in part or in whole -- any of the components of the
// Original Version, by changing formats or by porting the Font Software to a
// new environment.
// 
// "Author" refers to any designer, engineer, programmer, technical
// writer or other person who contributed to the Font Software.
// 
// PERMISSION & CONDITIONS
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of the Font Software, to use, study, copy, merge, embed, modify,
// redistribute, and sell modified and unmodified copies of the Font
// Software, subject to the following conditions:
// 
// 1) Neither the Font Software nor any of its individual components,
// in Original or Modified Versions, may be sold by itself.
// 
// 2) Original or Modified Versions of the Font Software may be bundled,
// redistributed and/or sold with any software, provided that each copy
// contains the above copyright notice and this license. These can be
// included either as stand-alone text files, human-readable headers or
// in the appropriate machine-readable metadata fields within text or
// binary files as long as those fields can be easily viewed by the user.
// 
// 3) No Modified Version of the Font Software may use the Reserved Font
// Name(s) unless explicit written permission is granted by the corresponding
// Copyright Holder. This restriction only applies to the primary font name as
// presented to the users.
// 
// 4) The name(s) of the Copyright Holder(s) or the Author(s) of the Font
// Software shall not be used to promote, endorse or advertise any
// Modified Version, except to acknowledge the contribution(s) of the
// Copyright Holder(s) and the Author(s) or with their explicit written
// permission.
// 
// 5) The Font Software, modified or unmodified, in part or in whole,
// must be distributed entirely under this license, and must not be
// distributed under any other license. The requirement for fonts to
// remain under this license does not apply to any document created
// using the Font Software.
// 
// TERMINATION
// This license becomes null and void if any of the above conditions are
// not met.
// 
// DISCLAIMER
// THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
// OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL THE
// COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL
// DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM
// OTHER DEALINGS IN THE FONT SOFTWARE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Terminus
//     Size: 10x18
//     Bold: yes
//     Italic: no
//     Memory usage: 2128 bytes
//
//*****************************************************************************

static const uint8_t g_pui8terminus10x18bData[1928] =
{
      5,  10,   0,  22,  64,  16,   6, 240,  50,  66,  66,  66,
     66,  66,  66,  66, 240,  18,  66, 240, 112,  13,   8, 130,
     34,  34,  34,  34,  34,  34,  34,   0,  13,  32,  27,   9,
    240, 210,  34,  50,  34,  50,  34,  40,  34,  34,  50,  34,
     50,  34,  50,  34,  40,  34,  34,  50,  34,  50,  34, 240,
    224,  29,   9, 240,  98, 114,  86,  34,  18,  18,  18,  18,
     66,  18,  66,  18,  86,  82,  18,  66,  18,  66,  18,  18,
     18,  18,  38,  82, 114, 208,  25,   9, 240, 195,  34,  33,
     17,  34,  35,  18, 114,  98, 114,  98, 114,  98, 114,  19,
     34,  33,  17,  34,  35, 240, 224,  30,  10, 240, 240,  36,
     82,  34,  66,  34,  66,  34,  84,  99,  34,  34,  18,  18,
     18,  51,  34,  66,  34,  66,  50,  36,  52,  18, 240, 240,
     16,   9,   6,  98,  66,  66,  66,   0,  10,  32,  17,   7,
    240, 130,  66,  82,  66,  82,  82,  82,  82,  82,  98,  82,
     98, 240, 144,  17,   7, 240,  98,  98,  82,  98,  82,  82,
     82,  82,  82,  66,  82,  66, 240, 176,  18,  10,   0,   6,
     50,  50,  66,  18,  99,  73,  67,  98,  18,  66,  50,   0,
      7,  96,  14,   9,   0,   6,   2, 114, 114,  72,  66, 114,
    114,   0,   7,  32,  10,   7,   0,  10,  82,  82,  82,  66,
    240,  64,   8,   9,   0,   9,   8,   0,  10,  32,   8,   6,
      0,   9,  98,  66, 240, 112,  19,   9, 240, 240,  34, 114,
     98, 114,  98, 114,  98, 114,  98, 114,  98, 114, 240, 240,
     64,  28,   9, 240, 214,  34,  66,  18,  66,  18,  51,  18,
     36,  18,  18,  18,  20,  34,  19,  50,  18,  66,  18,  66,
     18,  66,  38, 240, 224,  17,   8, 240, 178,  83,  68,  98,
     98,  98,  98,  98,  98,  98,  98,  70, 240, 176,  20,   9,
    240, 214,  34,  66,  18,  66,  18,  66, 114,  98,  98,  98,
     98,  98,  98, 120, 240, 208,  21,   9, 240, 214,  34,  66,
     18,  66, 114, 114,  53, 130, 114, 114,  18,  66,  18,  66,
     38, 240, 224,  23,   9, 240, 240,  50,  99,  84,  66,  18,
     50,  34,  34,  50,  18,  66,  18,  66,  24, 114, 114, 114,
    240, 208,  19,   9, 240, 200,  18, 114, 114, 114, 119, 130,
    114, 114,  18,  66,  18,  66,  38, 240, 224,  22,   9, 240,
    229,  50,  98, 114, 114, 119,  34,  66,  18,  66,  18,  66,
     18,  66,  18,  66,  38, 240, 224,  20,   9, 240, 200,  18,
     66,  18,  66, 114,  98, 114,  98, 114,  98, 114, 114, 114,
    240, 240,  16,  26,   9, 240, 214,  34,  66,  18,  66,  18,
     66,  18,  66,  38,  34,  66,  18,  66,  18,  66,  18,  66,
     18,  66,  38, 240, 224,  22,   9, 240, 214,  34,  66,  18,
     66,  18,  66,  18,  66,  18,  66,  39, 114, 114, 114,  98,
     53, 240, 240,  11,   6, 240, 240,  98,  66, 240, 210,  66,
    240, 208,  14,   7, 240, 240, 210,  82, 240, 240,  50,  82,
     82,  66, 240,  64,  18,   9, 240, 240,  34,  98,  98,  98,
     98,  98, 114, 130, 130, 130, 130, 130, 240, 224,   9,   9,
      0,   6, 104, 240, 216,   0,   8,  18,   9, 240, 194, 130,
    130, 130, 130, 130, 114,  98,  98,  98,  98,  98, 240, 240,
     64,  21,   9, 240, 228,  66,  34,  34,  66,  18,  66, 114,
     98,  98,  98, 114, 240,  18, 114, 240, 240,  16,  31,  10,
    240, 240,  23,  34,  82,  18,  82,  18,  37,  18,  18,  34,
     18,  18,  34,  18,  18,  34,  18,  18,  34,  18,  37,  18,
    130, 152, 240, 240,  16,  27,   9, 240, 214,  34,  66,  18,
     66,  18,  66,  18,  66,  18,  66,  24,  18,  66,  18,  66,
     18,  66,  18,  66,  18,  66, 240, 208,  26,   9, 240, 199,
     34,  66,  18,  66,  18,  66,  18,  66,  23,  34,  66,  18,
     66,  18,  66,  18,  66,  18,  66,  23, 240, 224,  21,   9,
    240, 214,  34,  66,  18,  66,  18, 114, 114, 114, 114, 114,
    114,  66,  18,  66,  38, 240, 224,  27,   9, 240, 198,  50,
     50,  34,  66,  18,  66,  18,  66,  18,  66,  18,  66,  18,
     66,  18,  66,  18,  66,  18,  50,  38, 240, 240,  17,   9,
    240, 200,  18, 114, 114, 114, 118,  50, 114, 114, 114, 114,
    120, 240, 208,  18,   9, 240, 200,  18, 114, 114, 114, 118,
     50, 114, 114, 114, 114, 114, 240, 240,  64,  24,   9, 240,
    214,  34,  66,  18,  66,  18, 114, 114, 114,  36,  18,  66,
     18,  66,  18,  66,  18,  66,  38, 240, 224,  28,   9, 240,
    194,  66,  18,  66,  18,  66,  18,  66,  18,  66,  24,  18,
     66,  18,  66,  18,  66,  18,  66,  18,  66,  18,  66, 240,
    208,  17,   7, 240, 100,  66,  82,  82,  82,  82,  82,  82,
     82,  82,  82,  68, 240, 144,  21,   9, 240, 240,  20,  98,
    114, 114, 114, 114, 114, 114,  34,  50,  34,  50,  34,  50,
     53, 240, 240,  27,   9, 240, 194,  66,  18,  66,  18,  50,
     34,  34,  50,  18,  68,  84,  82,  18,  66,  34,  50,  50,
     34,  66,  18,  66, 240, 208,  17,   9, 240, 194, 114, 114,
    114, 114, 114, 114, 114, 114, 114, 114, 120, 240, 208,  32,
     10, 240, 241, 113,  18,  82,  19,  51,  20,  20,  18,  19,
     18,  18,  33,  34,  18,  82,  18,  82,  18,  82,  18,  82,
     18,  82,  18,  82, 240, 240,  16,  30,   9, 240, 194,  66,
     18,  66,  18,  66,  19,  50,  20,  34,  18,  18,  18,  18,
     36,  18,  51,  18,  66,  18,  66,  18,  66,  18,  66, 240,
    208,  27,   9, 240, 214,  34,  66,  18,  66,  18,  66,  18,
     66,  18,  66,  18,  66,  18,  66,  18,  66,  18,  66,  18,
     66,  38, 240, 224,  23,   9, 240, 199,  34,  66,  18,  66,
     18,  66,  18,  66,  18,  66,  23,  34, 114, 114, 114, 114,
    240, 240,  64,  28,   9, 240, 214,  34,  66,  18,  66,  18,
     66,  18,  66,  18,  66,  18,  66,  18,  66,  18,  66,  18,
     66,  18,  36,  38, 114, 130, 160,  26,   9, 240, 199,  34,
     66,  18,  66,  18,  66,  18,  66,  18,  66,  23,  36,  82,
     18,  66,  34,  50,  50,  34,  66, 240, 208,  21,   9, 240,
    214,  34,  66,  18,  66,  18, 114, 134, 130, 114, 114,  18,
     66,  18,  66,  38, 240, 224,  18,   9, 240, 200,  66, 114,
    114, 114, 114, 114, 114, 114, 114, 114, 114, 240, 240,  16,
     28,   9, 240, 194,  66,  18,  66,  18,  66,  18,  66,  18,
     66,  18,  66,  18,  66,  18,  66,  18,  66,  18,  66,  18,
     66,  38, 240, 224,  26,   9, 240, 194,  66,  18,  66,  18,
     66,  18,  66,  34,  34,  50,  34,  50,  34,  50,  34,  68,
     84,  98, 114, 240, 240,  16,  32,  10, 240, 242,  82,  18,
     82,  18,  82,  18,  82,  18,  82,  18,  82,  18,  33,  34,
     18,  19,  18,  20,  20,  19,  51,  18,  82,  17, 113, 240,
    240,  16,  25,   9, 240, 194,  66,  18,  66,  34,  34,  50,
     34,  68,  98, 114, 100,  66,  34,  50,  34,  34,  66,  18,
     66, 240, 208,  23,   9, 240, 194,  66,  18,  66,  18,  66,
     34,  34,  50,  34,  68,  98, 114, 114, 114, 114, 114, 240,
    240,  16,  17,   9, 240, 200, 114, 114,  98,  98,  98,  98,
     98,  98, 114, 114, 120, 240, 208,  17,   7, 240, 100,  50,
     82,  82,  82,  82,  82,  82,  82,  82,  82,  84, 240, 144,
     17,   9, 240, 194, 114, 130, 114, 130, 114, 130, 114, 130,
    114, 130, 114, 240, 224,  17,   7, 240, 100,  82,  82,  82,
     82,  82,  82,  82,  82,  82,  82,  52, 240, 144,  11,   9,
    194, 100,  66,  34,  34,  66,   0,  14,  96,   6,   9,   0,
     18,   8, 160,   7,   7,   2,  98,   0,  14,  64,  19,   9,
      0,   6, 118, 130, 114,  39,  18,  66,  18,  66,  18,  66,
     18,  66,  39, 240, 208,  24,   9, 240, 194, 114, 114, 119,
     34,  66,  18,  66,  18,  66,  18,  66,  18,  66,  18,  66,
     18,  66,  23, 240, 224,  17,   9,   0,   6, 118,  34,  66,
     18, 114, 114, 114, 114, 114,  66,  38, 240, 224,  25,   9,
    240, 240,  50, 114, 114,  39,  18,  66,  18,  66,  18,  66,
     18,  66,  18,  66,  18,  66,  18,  66,  39, 240, 208,  19,
      9,   0,   6, 118,  34,  66,  18,  66,  18,  66,  24,  18,
    114, 114,  66,  38, 240, 224,  17,   8, 240, 196,  50,  98,
     70,  66,  98,  98,  98,  98,  98,  98,  98, 240, 208,  24,
      9,   0,   6, 119,  18,  66,  18,  66,  18,  66,  18,  66,
     18,  66,  18,  66,  18,  66,  39, 114, 114,  38,  32,  25,
      9, 240, 194, 114, 114, 119,  34,  66,  18,  66,  18,  66,
     18,  66,  18,  66,  18,  66,  18,  66,  18,  66, 240, 208,
     16,   7, 240, 114,  82, 179,  82,  82,  82,  82,  82,  82,
     82,  68, 240, 144,  20,   8, 240, 210,  98, 211,  98,  98,
     98,  98,  98,  98,  98,  98,  34,  34,  34,  34,  52,  48,
     25,   9, 240, 194, 114, 114, 114,  66,  18,  50,  34,  34,
     50,  18,  68,  82,  18,  66,  34,  50,  50,  34,  66, 240,
    208,  17,   7, 240,  99,  82,  82,  82,  82,  82,  82,  82,
     82,  82,  82,  68, 240, 144,  31,   9,   0,   6, 103,  34,
     18,  18,  18,  18,  18,  18,  18,  18,  18,  18,  18,  18,
     18,  18,  18,  18,  18,  18,  18,  18,  18,  18,  18, 240,
    208,  23,   9,   0,   6, 103,  34,  66,  18,  66,  18,  66,
     18,  66,  18,  66,  18,  66,  18,  66,  18,  66, 240, 208,
     22,   9,   0,   6, 118,  34,  66,  18,  66,  18,  66,  18,
     66,  18,  66,  18,  66,  18,  66,  38, 240, 224,  24,   9,
      0,   6, 103,  34,  66,  18,  66,  18,  66,  18,  66,  18,
     66,  18,  66,  18,  66,  23,  34, 114, 114, 112,  23,   9,
      0,   6, 119,  18,  66,  18,  66,  18,  66,  18,  66,  18,
     66,  18,  66,  18,  66,  39, 114, 114, 114,  17,   9,   0,
      6,  98,  21,  20,  83,  98, 114, 114, 114, 114, 114, 240,
    240,  64,  17,   9,   0,   6, 118,  34,  66,  18, 114, 134,
    130, 114,  18,  66,  38, 240, 224,  17,   9, 240, 226, 114,
    114,  86,  82, 114, 114, 114, 114, 114, 114, 132, 240, 224,
     23,   9,   0,   6,  98,  66,  18,  66,  18,  66,  18,  66,
     18,  66,  18,  66,  18,  66,  18,  66,  39, 240, 208,  22,
      9,   0,   6,  98,  66,  18,  66,  18,  66,  34,  34,  50,
     34,  50,  34,  68,  98, 114, 240, 240,  16,  28,   9,   0,
      6,  98,  66,  18,  66,  18,  66,  18,  18,  18,  18,  18,
     18,  18,  18,  18,  18,  18,  18,  18,  18,  18,  38, 240,
    224,  21,   9,   0,   6,  98,  66,  18,  66,  34,  34,  68,
     98, 100,  66,  34,  34,  66,  18,  66, 240, 208,  25,   9,
      0,   6,  98,  66,  18,  66,  18,  66,  18,  66,  18,  66,
     18,  66,  18,  66,  18,  66,  39, 114, 114,  38,  32,  15,
      9,   0,   6, 104, 114,  98,  98,  98,  98,  98,  98, 120,
    240, 208,  17,   8, 240, 195,  66,  98,  98,  98,  67, 114,
     98,  98,  98,  98, 115, 240, 176,  17,   6, 240,  50,  66,
     66,  66,  66,  66,  66,  66,  66,  66,  66,  66, 240, 112,
     17,   8, 240, 147, 114,  98,  98,  98, 115,  66,  98,  98,
     98,  98,  67, 240, 224,  15,   9, 163,  34,  18,  18,  18,
     18,  18,  18,  18,  35,   0,  14, 112,
};

const tFont g_sFontterminus10x18b =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    10,

    //
    // The height of the font.
    //
    18,

    //
    // The baseline of the font.
    //
    15,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   21,   34,   61,   90,  115,  145,
         154,  171,  188,  206,  220,  230,  238,  246,
         265,  293,  310,  330,  351,  374,  393,  415,
         435,  461,  483,  494,  508,  526,  535,  553,
         574,  605,  632,  658,  679,  706,  723,  741,
         765,  793,  810,  831,  858,  875,  907,  937,
         964,  987, 1015, 1041, 1062, 1080, 1108, 1134,
        1166, 1191, 1214, 1231, 1248, 1265, 1282, 1293,
        1299, 1306, 1325, 1349, 1366, 1391, 1410, 1427,
        1451, 1476, 1492, 1512, 1537, 1554, 1585, 1608,
        1630, 1654, 1677, 1694, 1711, 1728, 1751, 1773,
        1801, 1822, 1847, 1862, 1879, 1896, 1913,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8terminus10x18bData
};
