//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidabright
//     Size: 5x9
//     Bold: yes
//     Italic: no
//     Memory usage: 1288 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidabright5x9bData[1085] =
{
      4,   8,   0,   9,   9,   8, 129, 113, 113, 113, 241, 240,
    128,   7,   8, 130,  98,   0,   6,  96,  11,   8, 163,  53,
     65,  17,  69,  66,  83, 240,  96,  13,   8,  33,  84,  65,
     18,  82, 114,  65,  18,  68,  97, 208,  16,   8, 131,  33,
     33,  17,  17,  52, 100,  49,  17,  17,  33,  35, 240,  48,
     17,   8, 147,  81,  17,  65,  17,  18,  33,  17,  17,  49,
     33,  82,  18, 240,  48,   8,   8, 129, 113, 113,   0,   5,
    112,  11,   8, 145,  97, 113, 113, 113, 113, 113, 129,  96,
     11,   8, 129, 129, 113, 113, 113, 113, 113,  97, 112,  10,
      8, 145,  97,  17,  81,  17, 240, 240, 240,  10,   8, 240,
     49, 113,  85,  81, 113, 240,  96,   8,   8,   0,   6,   1,
    113, 113, 112,   8,   8, 240, 240,  34, 240, 240, 128,   7,
      8,   0,   6,   1, 240, 128,  11,   8, 177,  98,  97, 113,
     97, 113,  98,  97, 112,  14,   8, 146,  81,  33,  65,  33,
     65,  33,  65,  33,  82, 240,  96,  10,   8, 130, 113, 113,
    113, 113,  99, 240,  96,  11,   8, 131,  81,  33, 113,  82,
     97, 100, 240,  80,  12,   8, 132,  65,  33,  82, 129,  65,
     33,  67, 240,  96,  11,   8, 162,  83,  66,  17,  69,  97,
     99, 240,  64,  11,   8, 131,  81, 115, 113,  81,  17,  82,
    240, 112,  13,   8, 147,  65,  33,  67,  81,  33,  65,  33,
     82, 240,  96,  10,   8, 132,  98,  97,  97,  98,  97, 240,
    128,  14,   8, 147,  65,  33,  81,  17,  65,  18,  65,  33,
     82, 240,  96,  13,   8, 146,  81,  33,  65,  33,  83,  65,
     33,  67, 240,  96,   8,   8, 240, 145, 240, 129, 240, 128,
      9,   8, 240, 145, 240, 129, 113, 113, 112,  10,   8, 240,
     81,  82,  66, 130, 129, 240,  64,   8,   8, 240, 240,  37,
     53, 240, 192,  10,   8, 240,  17, 130, 130,  66,  81, 240,
    128,  11,   8, 131,  81,  33,  98,  81, 113, 113, 240, 112,
     16,   8, 164,  49,  20,  17,  17,  19,  17,  17,  17,  17,
     22,  52, 240,  64,  13,   8, 161, 114,  81,  17,  84,  49,
     49,  49,  50, 240,  48,  13,   8, 133,  65,  33,  67,  81,
     33,  65,  33,  52, 240,  80,  11,   8, 148,  50,  33,  49,
    113, 114, 116, 240,  64,  14,   8, 133,  65,  49,  49,  49,
     49,  49,  49,  49,  37, 240,  64,  12,   8, 133,  65,  33,
     67,  81, 113,  33,  53, 240,  64,  11,   8, 133,  65,  33,
     67,  81, 113,  98, 240, 112,  13,   8, 148,  50,  33,  49,
    113,  35,  34,  33,  68, 240,  64,  15,   8, 131,  19,  33,
     49,  53,  49,  49,  49,  49,  35,  19, 240,  32,  10,   8,
    131,  97, 113, 113, 113,  99, 240,  96,  12,   8, 147,  97,
    113, 113, 113, 113,  81,  17,  83,  80,  13,   8, 131,  18,
     49,  18,  67,  83,  81,  18,  54, 240,  48,  11,   8, 131,
     97, 113, 113, 113,  33,  53, 240,  64,  18,   8, 131,  50,
     18,  34,  35,  18,  33,  18,  17,  33,  17,  33,  19,  35,
    240,  16,  16,   8, 130,  35,  34,  33,  51,  17,  49,  19,
     49,  34,  35,  33, 240,  48,  14,   8, 148,  50,  34,  33,
     65,  33,  65,  34,  34,  52, 240,  64,  12,   8, 132,  81,
     33,  65,  33,  67,  81,  99, 240,  96,  14,   8, 148,  50,
     34,  33,  65,  33,  65,  34,  34,  52, 114, 114,  14,   8,
    133,  65,  33,  65,  33,  67,  81,  18,  51,  18, 240,  48,
     12,   8, 147,  65,  33,  67, 114,  65,  33,  67, 240,  96,
     10,   8, 133,  81, 113, 113, 113,  99, 240,  80,  15,   8,
    131,  19,  33,  49,  49,  49,  49,  49,  49,  49,  53, 240,
     48,  14,   8, 130,  34,  49,  34,  49,  33,  81,  17,  82,
    113, 240,  80,  20,   8, 130,  33,  18,  17,  18,  33,  17,
     18,  17,  33,  18,  17,  49,  34,  49,  33, 240,  48,  14,
      8, 131,  18,  49,  33,  83,  67,  81,  33,  50,  19, 240,
     48,  12,   8, 130,  33,  65,  18,  67,  97, 113,  99, 240,
     80,  12,   8, 132,  65,  17, 113,  97, 113,  17,  68, 240,
     80,  11,   8, 130,  97, 113, 113, 113, 113, 113, 114,  96,
     11,   8, 129, 114, 113, 113, 129, 113, 129, 113,  64,  11,
      8, 130, 113, 113, 113, 113, 113, 113,  98,  96,  12,   8,
    161, 113,  97,  17,  81,  17,  65,  49, 240, 192,   6,   8,
      0,   7,   3, 208,   6,   8, 130,   0,   7,  96,  11,   8,
    240, 147,  83,  81,  17,  82,  17, 240,  80,  12,   8, 130,
    113, 115,  81,  33,  65,  33,  67, 240,  80,  10,   8, 240,
    163,  65,  33,  65, 131, 240,  80,  12,   8, 162, 113,  83,
     65,  33,  65,  33,  84, 240,  64,   9,   8, 240, 162,  84,
     65, 131, 240,  80,  11,   8, 147,  81,  17,  67,  97, 113,
     99, 240,  96,  12,   8, 240, 164,  49,  33,  68,  69,  49,
     49,  52,  64,  12,   8, 130, 113, 116,  65,  33,  65,  33,
     54, 240,  48,   9,   8, 145, 226, 113, 113,  99, 240,  96,
     11,   8, 161, 226, 113, 113, 113,  81,  17,  83,  80,  11,
      8, 130, 113, 113,  18,  67,  83,  69, 240,  64,  10,   8,
    130, 113, 113, 113, 113,  99, 240,  96,  12,   8, 240, 152,
     17,  33,  33,  17,  33,  41, 240,  16,  11,   8, 240, 149,
     65,  33,  65,  33,  54, 240,  48,  11,   8, 240, 162,  81,
     33,  65,  33,  82, 240,  96,  12,   8, 240, 148,  81,  33,
     65,  33,  67,  81,  99,  80,  12,   8, 240, 163,  65,  33,
     65,  33,  83, 113,  99,  48,  10,   8, 240, 148,  81,  17,
     81,  99, 240,  96,   9,   8, 240, 147,  83,  83,  83, 240,
     96,  10,   8, 145, 113,  99,  97, 113, 114, 240,  96,  12,
      8, 240, 146,  18,  65,  33,  65,  33,  69, 240,  48,  11,
      8, 240, 146,  18,  65,  18,  67,  97, 240,  96,  14,   8,
    240, 146,  17,  18,  33,  20,  34,  18,  65,  18, 240,  48,
     10,   8, 240, 149,  67,  83,  66,  18, 240,  64,  13,   8,
    240, 146,  33,  65,  18,  65,  17,  98,  97,  97,  96,  11,
      8, 240, 148,  65,  17,  97,  17,  68, 240,  80,  11,   8,
    130,  97, 129,  98, 113, 113,  97, 114,  96,  11,   8, 129,
    113, 113, 113, 113, 113, 113, 113, 112,  11,   8, 130, 113,
     97, 114,  97, 113, 129,  98,  96,  10,   8, 240, 240,  35,
     17,  49,  19, 240, 192,
};

const tFont g_sFontlucidabright5x9b =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    8,

    //
    // The height of the font.
    //
    9,

    //
    // The baseline of the font.
    //
    7,

    //
    // The offset to each character in the font.
    //
    {
           0,    4,   13,   20,   31,   44,   60,   77,
          85,   96,  107,  117,  127,  135,  143,  150,
         161,  175,  185,  196,  208,  219,  230,  243,
         253,  267,  280,  288,  297,  307,  315,  325,
         336,  352,  365,  378,  389,  403,  415,  426,
         439,  454,  464,  476,  489,  500,  518,  534,
         548,  560,  574,  588,  600,  610,  625,  639,
         659,  673,  685,  697,  708,  719,  730,  742,
         748,  754,  765,  777,  787,  799,  808,  819,
         831,  843,  852,  863,  874,  884,  896,  907,
         918,  930,  942,  952,  961,  971,  983,  994,
        1008, 1018, 1031, 1042, 1053, 1064, 1075,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidabright5x9bData
};
