//*****************************************************************************
//
// Copyright (c) 2014 Dimitar Toshkov Zhekov,
// with Reserved Font Name "Terminus Font".
// 
// This Font Software is licensed under the SIL Open Font License, Version 1.1.
// This license is copied below, and is also available with a FAQ at:
// http://scripts.sil.org/OFL
// 
// 
// -----------------------------------------------------------
// SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007
// -----------------------------------------------------------
// 
// PREAMBLE
// The goals of the Open Font License (OFL) are to stimulate worldwide
// development of collaborative font projects, to support the font creation
// efforts of academic and linguistic communities, and to provide a free and
// open framework in which fonts may be shared and improved in partnership
// with others.
// 
// The OFL allows the licensed fonts to be used, studied, modified and
// redistributed freely as long as they are not sold by themselves. The
// fonts, including any derivative works, can be bundled, embedded, 
// redistributed and/or sold with any software provided that any reserved
// names are not used by derivative works. The fonts and derivatives,
// however, cannot be released under any other type of license. The
// requirement for fonts to remain under this license does not apply
// to any document created using the fonts or their derivatives.
// 
// DEFINITIONS
// "Font Software" refers to the set of files released by the Copyright
// Holder(s) under this license and clearly marked as such. This may
// include source files, build scripts and documentation.
// 
// "Reserved Font Name" refers to any names specified as such after the
// copyright statement(s).
// 
// "Original Version" refers to the collection of Font Software components as
// distributed by the Copyright Holder(s).
// 
// "Modified Version" refers to any derivative made by adding to, deleting,
// or substituting -- in part or in whole -- any of the components of the
// Original Version, by changing formats or by porting the Font Software to a
// new environment.
// 
// "Author" refers to any designer, engineer, programmer, technical
// writer or other person who contributed to the Font Software.
// 
// PERMISSION & CONDITIONS
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of the Font Software, to use, study, copy, merge, embed, modify,
// redistribute, and sell modified and unmodified copies of the Font
// Software, subject to the following conditions:
// 
// 1) Neither the Font Software nor any of its individual components,
// in Original or Modified Versions, may be sold by itself.
// 
// 2) Original or Modified Versions of the Font Software may be bundled,
// redistributed and/or sold with any software, provided that each copy
// contains the above copyright notice and this license. These can be
// included either as stand-alone text files, human-readable headers or
// in the appropriate machine-readable metadata fields within text or
// binary files as long as those fields can be easily viewed by the user.
// 
// 3) No Modified Version of the Font Software may use the Reserved Font
// Name(s) unless explicit written permission is granted by the corresponding
// Copyright Holder. This restriction only applies to the primary font name as
// presented to the users.
// 
// 4) The name(s) of the Copyright Holder(s) or the Author(s) of the Font
// Software shall not be used to promote, endorse or advertise any
// Modified Version, except to acknowledge the contribution(s) of the
// Copyright Holder(s) and the Author(s) or with their explicit written
// permission.
// 
// 5) The Font Software, modified or unmodified, in part or in whole,
// must be distributed entirely under this license, and must not be
// distributed under any other license. The requirement for fonts to
// remain under this license does not apply to any document created
// using the Font Software.
// 
// TERMINATION
// This license becomes null and void if any of the above conditions are
// not met.
// 
// DISCLAIMER
// THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
// OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL THE
// COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL
// DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM
// OTHER DEALINGS IN THE FONT SOFTWARE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Terminus
//     Size: 8x14
//     Bold: yes
//     Italic: no
//     Memory usage: 1800 bytes
//
//*****************************************************************************

static const uint8_t g_pui8terminus8x14bData[1599] =
{
      4,   8,   0,  14,  12,   5, 162,  50,  50,  50,  50,  50,
     50, 130,  50, 208,  11,   7, 114,  34,  18,  34,  18,  34,
      0,   8, 112,  23,   8, 240,  34,  18,  50,  18,  50,  18,
     39,  34,  18,  50,  18,  39,  34,  18,  50,  18,  50,  18,
    240,  48,  24,   8, 177, 113,  85,  34,  17,  18,  18,  17,
     66,  17,  85,  81,  18,  65,  18,  18,  17,  18,  37,  81,
    113,  64,  23,   8, 240,  34,  34,  18,  17,  18,  34,  18,
     98,  82,  98,  82,  98,  18,  34,  17,  18,  18,  34, 240,
     32,  23,   8, 240,  51,  66,  18,  50,  18,  67,  67,  18,
     18,  19,  34,  34,  34,  34,  34,  19,  51,  18, 240,  32,
      8,   5,  82,  50,  50,   0,   6,  80,  13,   6, 226,  50,
     50,  66,  66,  66,  66,  66,  82,  82, 224,  14,   6, 194,
     82,  82,  66,  66,  66,  66,  66,  50,  50, 240,  16,  14,
      8, 240, 240, 178,  18,  67,  55,  51,  66,  18, 240, 240,
     64,  12,   7, 240, 240, 114,  82,  54,  50,  82, 240, 240,
     16,   8,   6,   0,   7,  82,  66,  50, 160,   8,   8,   0,
      7,   7,   0,   6,  16,   7,   5,   0,   6,  34,  50, 208,
     15,   7, 240,  50,  82,  66,  82,  66,  82,  66,  82,  66,
     82, 240,  64,  23,   8, 240,  37,  34,  50,  18,  50,  18,
     35,  18,  20,  20,  18,  19,  34,  18,  50,  18,  50,  37,
    240,  48,  14,   7, 240,  18,  67,  52,  82,  82,  82,  82,
     82,  82,  54, 240,  17,   8, 240,  37,  34,  50,  18,  50,
     98,  82,  82,  82,  82,  82, 103, 240,  32,  19,   8, 240,
     37,  34,  50,  18,  50,  98,  52, 114,  98,  18,  50,  18,
     50,  37, 240,  48,  18,   8, 240,  98,  83,  68,  50,  18,
     34,  34,  18,  50,  23,  98,  98,  98, 240,  32,  16,   8,
    240,  23,  18,  98,  98, 102, 114,  98,  98,  18,  50,  37,
    240,  48,  19,   8, 240,  52,  50,  82,  98, 102,  34,  50,
     18,  50,  18,  50,  18,  50,  37, 240,  48,  15,   8, 240,
     23,  98,  98,  82,  98,  82,  98,  82,  98,  98, 240,  80,
     22,   8, 240,  37,  34,  50,  18,  50,  18,  50,  37,  34,
     50,  18,  50,  18,  50,  18,  50,  37, 240,  48,  19,   8,
    240,  37,  34,  50,  18,  50,  18,  50,  18,  50,  38,  98,
     98,  82,  52, 240,  64,   9,   5, 240, 162,  50, 240,  50,
     50, 208,  11,   6, 240, 240,  18,  66, 240, 114,  66,  50,
    160,  13,   7, 240, 162,  66,  66,  66,  66,  98,  98,  98,
     98, 240,  10,   8, 240, 240, 167, 240,  39, 240, 240, 176,
     14,   7, 240,  98,  98,  98,  98,  98,  66,  66,  66,  66,
    240,  64,  17,   8, 240,  37,  34,  50,  18,  50,  18,  50,
     82,  82,  98, 226,  98, 240,  64,  26,   8, 240,  37,  34,
     50,  18,  35,  18,  17,  18,  18,  17,  18,  18,  17,  18,
     18,  17,  18,  18,  35,  18, 118, 240,  32,  23,   8, 240,
     37,  34,  50,  18,  50,  18,  50,  18,  50,  23,  18,  50,
     18,  50,  18,  50,  18,  50, 240,  32,  22,   8, 240,  22,
     34,  50,  18,  50,  18,  50,  22,  34,  50,  18,  50,  18,
     50,  18,  50,  22, 240,  48,  19,   8, 240,  37,  34,  50,
     18,  50,  18,  98,  98,  98,  98,  50,  18,  50,  37, 240,
     48,  23,   8, 240,  21,  50,  34,  34,  50,  18,  50,  18,
     50,  18,  50,  18,  50,  18,  50,  18,  34,  37, 240,  64,
     15,   8, 240,  23,  18,  98,  98, 101,  50,  98,  98,  98,
    103, 240,  32,  15,   8, 240,  23,  18,  98,  98, 101,  50,
     98,  98,  98,  98, 240, 112,  21,   8, 240,  37,  34,  50,
     18,  50,  18,  98,  98,  20,  18,  50,  18,  50,  18,  50,
     37, 240,  48,  24,   8, 240,  18,  50,  18,  50,  18,  50,
     18,  50,  23,  18,  50,  18,  50,  18,  50,  18,  50,  18,
     50, 240,  32,  13,   6, 196,  50,  66,  66,  66,  66,  66,
     66,  66,  52, 224,  17,   8, 240,  68,  82,  98,  98,  98,
     98,  98,  34,  34,  34,  34,  52, 240,  64,  23,   8, 240,
     18,  50,  18,  50,  18,  34,  34,  18,  52,  68,  66,  18,
     50,  34,  34,  50,  18,  50, 240,  32,  15,   8, 240,  18,
     98,  98,  98,  98,  98,  98,  98,  98, 103, 240,  32,  25,
      8, 240,  17,  81,  18,  50,  19,  19,  23,  18,  17,  18,
     18,  50,  18,  50,  18,  50,  18,  50,  18,  50, 240,  32,
     25,   8, 240,  18,  50,  18,  50,  18,  50,  19,  34,  20,
     18,  18,  20,  18,  35,  18,  50,  18,  50,  18,  50, 240,
     32,  23,   8, 240,  37,  34,  50,  18,  50,  18,  50,  18,
     50,  18,  50,  18,  50,  18,  50,  18,  50,  37, 240,  48,
     19,   8, 240,  22,  34,  50,  18,  50,  18,  50,  18,  50,
     22,  34,  98,  98,  98, 240, 112,  23,   8, 240,  37,  34,
     50,  18,  50,  18,  50,  18,  50,  18,  50,  18,  50,  18,
     50,  18,  20,  37, 114, 144,  22,   8, 240,  22,  34,  50,
     18,  50,  18,  50,  18,  50,  22,  36,  66,  18,  50,  34,
     34,  50, 240,  32,  18,   8, 240,  37,  34,  50,  18,  98,
    117, 114,  98,  18,  50,  18,  50,  37, 240,  48,  15,   8,
    240,  24,  50,  98,  98,  98,  98,  98,  98,  98,  98, 240,
     64,  24,   8, 240,  18,  50,  18,  50,  18,  50,  18,  50,
     18,  50,  18,  50,  18,  50,  18,  50,  18,  50,  37, 240,
     48,  23,   8, 240,  18,  50,  18,  50,  18,  50,  18,  50,
     18,  50,  34,  18,  50,  18,  50,  18,  67,  83, 240,  64,
     25,   8, 240,  18,  50,  18,  50,  18,  50,  18,  50,  18,
     50,  18,  17,  18,  23,  19,  19,  18,  50,  17,  81, 240,
     32,  23,   8, 240,  18,  50,  18,  50,  34,  18,  50,  18,
     67,  83,  66,  18,  50,  18,  34,  50,  18,  50, 240,  32,
     18,   8, 240,  18,  68,  66,  18,  34,  34,  34,  52,  82,
     98,  98,  98,  98, 240,  64,  15,   8, 240,  23,  98,  98,
     82,  82,  82,  82,  82,  98, 103, 240,  32,  13,   6, 196,
     34,  66,  66,  66,  66,  66,  66,  66,  68, 224,  13,   7,
    226,  82,  98,  82,  98,  82,  98,  82,  98,  82, 240,  13,
      6, 196,  66,  66,  66,  66,  66,  66,  66,  66,  36, 224,
      9,   7, 146,  68,  34,  34,   0,   8, 112,   6,   8,   0,
     12,   7, 144,   7,   6,   2,  82,   0,   9,  48,  16,   8,
    240, 240, 181, 114,  38,  18,  50,  18,  50,  18,  50,  38,
    240,  32,  20,   8, 240,  18,  98,  98, 102,  34,  50,  18,
     50,  18,  50,  18,  50,  18,  50,  22, 240,  48,  15,   8,
    240, 240, 181,  34,  50,  18,  98,  98,  98,  50,  37, 240,
     48,  20,   8, 240,  98,  98,  98,  38,  18,  50,  18,  50,
     18,  50,  18,  50,  18,  50,  38, 240,  32,  15,   8, 240,
    240, 181,  34,  50,  18,  50,  23,  18,  98, 117, 240,  48,
     15,   8, 240,  68,  50,  98,  70,  66,  98,  98,  98,  98,
     98, 240,  80,  19,   8, 240, 240, 182,  18,  50,  18,  50,
     18,  50,  18,  50,  18,  50,  38,  98,  37,  32,  21,   8,
    240,  18,  98,  98, 102,  34,  50,  18,  50,  18,  50,  18,
     50,  18,  50,  18,  50, 240,  32,  12,   6, 210,  66, 147,
     66,  66,  66,  66,  66,  52, 224,  17,   7, 240,  50,  82,
    179,  82,  82,  82,  82,  82,  18,  34,  18,  34,  36,  32,
     21,   8, 240,  18,  98,  98,  98,  50,  18,  34,  34,  18,
     52,  66,  18,  50,  34,  34,  50, 240,  32,  13,   6, 195,
     66,  66,  66,  66,  66,  66,  66,  66,  52, 224,  25,   8,
    240, 240, 166,  34,  17,  18,  18,  17,  18,  18,  17,  18,
     18,  17,  18,  18,  17,  18,  18,  17,  18, 240,  32,  19,
      8, 240, 240, 166,  34,  50,  18,  50,  18,  50,  18,  50,
     18,  50,  18,  50, 240,  32,  18,   8, 240, 240, 181,  34,
     50,  18,  50,  18,  50,  18,  50,  18,  50,  37, 240,  48,
     19,   8, 240, 240, 166,  34,  50,  18,  50,  18,  50,  18,
     50,  18,  50,  22,  34,  98,  96,  18,   8, 240, 240, 182,
     18,  50,  18,  50,  18,  50,  18,  50,  18,  50,  38,  98,
     98,  14,   8, 240, 240, 162,  20,  20,  67,  82,  98,  98,
     98, 240, 112,  13,   8, 240, 240, 182,  18,  98, 117, 114,
     98,  22, 240,  48,  15,   8, 240,  50,  98,  98,  70,  66,
     98,  98,  98,  98, 116, 240,  32,  19,   8, 240, 240, 162,
     50,  18,  50,  18,  50,  18,  50,  18,  50,  18,  50,  38,
    240,  32,  18,   8, 240, 240, 162,  50,  18,  50,  18,  50,
     34,  18,  50,  18,  67,  83, 240,  64,  23,   8, 240, 240,
    162,  50,  18,  50,  18,  17,  18,  18,  17,  18,  18,  17,
     18,  18,  17,  18,  37, 240,  48,  19,   8, 240, 240, 162,
     50,  18,  50,  34,  18,  67,  66,  18,  34,  50,  18,  50,
    240,  32,  20,   8, 240, 240, 162,  50,  18,  50,  18,  50,
     18,  50,  18,  50,  18,  50,  38,  98,  37,  32,  13,   8,
    240, 240, 167,  82,  82,  82,  82,  82, 103, 240,  32,  15,
      7, 240,  19,  50,  82,  82,  66,  98,  82,  82,  82,  99,
    240,  16,  13,   5, 162,  50,  50,  50,  50,  50,  50,  50,
     50,  50, 208,  14,   7, 227,  98,  82,  82,  98,  66,  82,
     82,  82,  51, 240,  48,  10,   8, 147,  36,  18,  20,  35,
      0,  10,  16,
};

const tFont g_sFontterminus8x14b =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    8,

    //
    // The height of the font.
    //
    14,

    //
    // The baseline of the font.
    //
    12,

    //
    // The offset to each character in the font.
    //
    {
           0,    4,   16,   27,   50,   74,   97,  120,
         128,  141,  155,  169,  181,  189,  197,  204,
         219,  242,  256,  273,  292,  310,  326,  345,
         360,  382,  401,  410,  421,  434,  444,  458,
         475,  501,  524,  546,  565,  588,  603,  618,
         639,  663,  676,  693,  716,  731,  756,  781,
         804,  823,  846,  868,  886,  901,  925,  948,
         973,  996, 1014, 1029, 1042, 1055, 1068, 1077,
        1083, 1090, 1106, 1126, 1141, 1161, 1176, 1191,
        1210, 1231, 1243, 1260, 1281, 1294, 1319, 1338,
        1356, 1375, 1393, 1407, 1420, 1435, 1454, 1472,
        1495, 1514, 1534, 1547, 1562, 1575, 1589,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8terminus8x14bData
};
