//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidabright
//     Size: 6x12
//     Bold: no
//     Italic: yes
//     Memory usage: 1536 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidabright6x12iData[1336] =
{
      5,   9,   0,  11,  32,  12,   9,  17, 129, 129, 129, 129,
    129, 240,  17, 240, 176,   8,   9,   3,  98, 114,   0,   8,
     96,  16,   9,  49,  17,  97,  17,  54,  82, 114,  86,  49,
     17,  97,  17, 240, 144,  14,   9,  19,  99, 113, 113, 130,
    113,  17,  83,  98, 129, 240,  16,  24,   9,  19,  34,  33,
     17,  17,  65,  17,  17,  66,  17, 113,  18,  65,  17,  17,
     49,  33,  17,  33,  51, 240,  80,  19,   9,  50,  97,  33,
     81,  33,  68,  65,  33,  18,  33,  33,  17,  49,  50,  70,
    240,  80,   8,   9,   1, 129, 129,   0,   8, 112,  13,   9,
     34,  97, 129, 113, 129, 129, 129, 129, 129, 129, 128,  13,
      9,  33, 129, 129, 129, 129, 129, 129, 129, 113, 113, 128,
     10,   9,  33, 100,  98,  97,  17,   0,   7,  64,  11,   9,
    193, 129, 129,  86,  81, 129, 129, 240, 144,   8,   9,   0,
      7, 114, 129, 113, 128,   8,   9, 240, 240, 242, 240, 240,
    208,   7,   9,   0,   7, 113, 240, 176,  13,   9,  81, 113,
    129, 113, 129, 113, 129, 113, 113, 129, 128,  18,   9,  35,
     81,  33,  81,  33,  65,  49,  65,  49,  65,  49,  65,  33,
     98, 240, 144,  12,   9,  19, 129, 113, 129, 129, 129, 129,
    100, 240, 128,  13,   9,  35,  81,  49, 129, 113,  98,  97,
    113, 133, 240, 112,  14,   9,  20,  81,  33, 129,  83, 129,
    145,  65,  33,  83, 240, 144,  15,   9,  50,  97,  17,  81,
     33,  65,  33,  85, 113, 129, 114, 240, 128,  13,   9,  20,
     81, 129, 131, 129, 145,  65,  33,  83, 240, 144,  16,   9,
     35,  82,  17,  81, 116,  81,  49,  65,  49,  65,  33,  98,
    240, 144,  12,   9,  21, 129, 113,  98, 113, 113, 129, 113,
    240, 176,  17,   9,  35,  81,  33,  81,  33,  84,  65,  34,
     65,  49,  65,  34,  83, 240, 128,  16,   9,  35,  81,  33,
     66,  33,  81,  33,  84, 129,  65,  33,  83, 240, 144,   9,
      9, 240, 209, 240, 240,  65, 240, 176,  10,   9, 240, 210,
    240, 240,  50, 129, 113, 128,  11,   9, 210, 113,  98,  82,
    130, 145, 145, 240, 112,   8,   9, 240, 240, 102, 198, 240,
    240,  11,   9, 161, 146, 145, 145,  83,  97,  98, 240, 160,
     13,   9,   3,  97,  33, 129, 113, 113, 113, 240,  33, 240,
    176,  23,   9,  52,  50,  65,  33,  19,  17,  17,  17,  33,
     17,  17,  17,  18,  17,  17,  18,  18,  33, 148, 240, 112,
     17,   9,  65, 114, 113,  17,  81,  33,  69,  49,  65,  49,
     65,  50,  35, 240,  80,  17,   9,  21,  81,  33,  81,  33,
     83,  81,  33,  81,  49,  65,  33,  69, 240, 112,  13,   9,
     52,  50,  49,  49, 113, 129, 129, 130, 133, 240,  96,  18,
      9,  22,  65,  50,  49,  65,  49,  65,  49,  65,  33,  65,
     49,  50,  38, 240,  96,  16,   9,  21,  81,  33,  81,  17,
     99,  81,  33,  81, 129,  33,  69, 240, 112,  15,   9,  21,
     81,  33,  81,  17,  84,  81,  33,  81, 129, 115, 240, 144,
     16,   9,  52,  50,  49,  49, 113, 129,  51,  33,  65,  50,
     49,  69, 240,  96,  19,   9,  19,  35,  33,  65,  49,  50,
     53,  50,  49,  49,  65,  49,  65,  35,  35, 240,  64,  12,
      9,  19, 113, 129, 129, 113, 129, 129, 115, 240, 144,  14,
      9,  51, 113, 129, 113, 129, 129, 129, 129,  81,  17,  99,
     96,  18,   9,  20,  18,  49,  49,  65,  18,  83,  98,  97,
     33,  81,  49,  51,  19, 240,  80,  13,   9,  20,  97, 129,
    129, 129, 113, 129,  49,  54, 240,  96,  25,   9,  18,  66,
     34,  50,  34,  35,  17,  17,  34,  33,  17,  17,  17,  33,
     33,  33,  33,  33,  33,  18,  67, 240,  48,  23,   9,  18,
     51,  34,  49,  33,  17,  33,  49,  33,  17,  49,  33,  17,
     49,  50,  49,  50,  34,  49, 240,  96,  18,   9,  51,  66,
     34,  49,  65,  33,  81,  33,  81,  33,  65,  50,  34,  67,
    240, 128,  15,   9,  21,  81,  33,  81,  33,  81,  18,  68,
     81, 129, 115, 240, 144,  18,   9,  51,  66,  34,  49,  65,
     33,  81,  33,  81,  33,  65,  50,  34,  67, 145, 147,  18,
      9,  22,  65,  34,  65,  49,  65,  33,  83,  82,  17,  81,
     49,  51,  34, 240,  80,  14,   9,  35,  81,  33,  81, 145,
    145, 129,  81,  33,  83, 240, 144,  14,   9,   6,  49,  17,
     33,  81, 129, 129, 129, 114,  99, 240, 144,  19,   9,   3,
     34,  49,  49,  65,  49,  49,  65,  49,  65,  49,  65,  49,
     49,  83, 240, 128,  18,   9,   3,  34,  49,  50,  49,  49,
     65,  33,  81,  33,  81,  17, 114, 113, 240, 144,  25,   9,
      3,  17,  34,  17,  33,  33,  33,  18,  33,  33,  18,  17,
     50,  17,  17,  50,  18,  65,  34,  65,  33, 240, 112,  18,
      9,  34,  34,  50,  33,  81,  17,  98, 114,  97,  18,  65,
     49,  50,  35, 240,  80,  15,   9,   3,  34,  49,  49,  65,
     33,  98, 114, 113, 129, 115, 240, 128,  14,   9,  21,  65,
     33, 129, 113, 113, 113, 129,  33,  69, 240, 112,  13,   9,
     34, 113, 113, 129, 129, 129, 129, 113, 129, 130, 112,  13,
      9,   1, 129, 145, 129, 129, 129, 129, 129, 145, 129,  96,
     13,   9,  34, 129, 129, 113, 129, 129, 129, 129, 113, 114,
    112,  16,   9,  65, 114,  97,  17,  97,  17,  81,  49,  65,
     49,  49,  65, 240, 240,   6,   9,   0,   9,   4, 224,   5,
      9,   2,   0,  11,  13,   9, 240, 227,  81,  33,  65,  49,
     65,  33,  85, 240, 112,  15,   9,  17, 129, 129, 132,  82,
     17,  66,  33,  65,  33,  83, 240, 144,  11,   9, 240, 227,
     81,  17,  81, 129, 132, 240, 128,  15,   9,  66, 129, 113,
     99,  81,  33,  65,  49,  65,  19,  69, 240, 112,  12,   9,
    240, 226,  97,  17,  83,  97,  33,  84, 240, 128,  14,   9,
     50,  97,  17,  97, 115,  97, 129, 129, 129, 113, 129, 128,
     16,   9, 240, 228,  65,  49,  65,  33,  65,  34,  82,  17,
     65,  49,  68,  80,  17,   9,  17, 129, 129, 129,  18,  82,
     17,  66,  33,  65,  33,  81,  34, 240, 112,  11,   9,  17,
    240, 162, 113, 129, 129, 130, 240, 160,  13,   9,  65, 240,
    162, 113, 129, 129, 129,  81,  17,  98, 112,  15,   9,  17,
    129, 129, 129,  18,  82, 114,  97,  18,  81,  34, 240, 112,
     12,   9,  18, 129, 113, 129, 129, 129, 113, 130, 240, 160,
     18,   9, 240, 200,  34,  18,  17,  33,  33,  33,  17,  34,
     17,  33,  33,  34, 240,  64,  15,   9, 240, 194,  18,  82,
     17,  81,  33,  65,  33,  81,  34, 240, 112,  13,   9, 240,
    226,  97,  33,  65,  49,  65,  33,  83, 240, 144,  14,   9,
    240, 213,  52,  17,  66,  33,  65,  33,  83,  81, 129, 128,
     14,   9, 240, 227,  81,  33,  65,  49,  65,  33,  84, 129,
    129,  80,  12,   9, 240, 194,  18,  82,  17,  81, 114, 113,
    240, 176,  12,   9, 240, 211,  97,  17,  98,  97,  17,  99,
    240, 144,  12,   9,  17, 129, 129, 115, 113, 113, 129, 130,
    240, 160,  14,   9, 240, 194,  18,  81,  33,  65,  34,  65,
     18,  85, 240, 112,  13,   9, 240, 194,  34,  65,  33,  97,
     17,  98, 113, 240, 144,  18,   9, 240, 194,  33,  33,  33,
     18,  33,  33,  18,  17,  50,  18,  66,  18, 240,  96,  13,
      9, 240, 194,  33,  83, 113,  98,  17,  81,  34, 240, 112,
     14,   9, 240, 209,  49,  81,  33,  81,  18,  83,  97, 129,
     98, 112,  12,   9, 240, 212,  81,  17, 113, 113,  17,  84,
    240, 128,  13,   9,  33, 113, 129, 129, 129, 113, 145, 113,
    129, 130, 112,  13,   9,  17, 129, 129, 129, 113, 129, 129,
    129, 129, 129, 128,  13,   9,  33, 129, 129, 129, 129, 113,
    129, 129, 129, 114, 112,  11,   9, 240, 240, 115,  49,  17,
     51, 240, 240, 128,
};

const tFont g_sFontlucidabright6x12i =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    9,

    //
    // The height of the font.
    //
    10,

    //
    // The baseline of the font.
    //
    8,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   17,   25,   41,   55,   79,   98,
         106,  119,  132,  142,  153,  161,  169,  176,
         189,  207,  219,  232,  246,  261,  274,  290,
         302,  319,  335,  344,  354,  365,  373,  384,
         397,  420,  437,  454,  467,  485,  501,  516,
         532,  551,  563,  577,  595,  608,  633,  656,
         674,  689,  707,  725,  739,  753,  772,  790,
         815,  833,  848,  862,  875,  888,  901,  917,
         923,  928,  941,  956,  967,  982,  994, 1008,
        1024, 1041, 1052, 1065, 1080, 1092, 1110, 1125,
        1138, 1152, 1166, 1178, 1190, 1202, 1216, 1229,
        1247, 1260, 1274, 1286, 1299, 1312, 1325,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidabright6x12iData
};
