//*****************************************************************************
//
// Copyright (c) 2014 Dimitar Toshkov Zhekov,
// with Reserved Font Name "Terminus Font".
// 
// This Font Software is licensed under the SIL Open Font License, Version 1.1.
// This license is copied below, and is also available with a FAQ at:
// http://scripts.sil.org/OFL
// 
// 
// -----------------------------------------------------------
// SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007
// -----------------------------------------------------------
// 
// PREAMBLE
// The goals of the Open Font License (OFL) are to stimulate worldwide
// development of collaborative font projects, to support the font creation
// efforts of academic and linguistic communities, and to provide a free and
// open framework in which fonts may be shared and improved in partnership
// with others.
// 
// The OFL allows the licensed fonts to be used, studied, modified and
// redistributed freely as long as they are not sold by themselves. The
// fonts, including any derivative works, can be bundled, embedded, 
// redistributed and/or sold with any software provided that any reserved
// names are not used by derivative works. The fonts and derivatives,
// however, cannot be released under any other type of license. The
// requirement for fonts to remain under this license does not apply
// to any document created using the fonts or their derivatives.
// 
// DEFINITIONS
// "Font Software" refers to the set of files released by the Copyright
// Holder(s) under this license and clearly marked as such. This may
// include source files, build scripts and documentation.
// 
// "Reserved Font Name" refers to any names specified as such after the
// copyright statement(s).
// 
// "Original Version" refers to the collection of Font Software components as
// distributed by the Copyright Holder(s).
// 
// "Modified Version" refers to any derivative made by adding to, deleting,
// or substituting -- in part or in whole -- any of the components of the
// Original Version, by changing formats or by porting the Font Software to a
// new environment.
// 
// "Author" refers to any designer, engineer, programmer, technical
// writer or other person who contributed to the Font Software.
// 
// PERMISSION & CONDITIONS
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of the Font Software, to use, study, copy, merge, embed, modify,
// redistribute, and sell modified and unmodified copies of the Font
// Software, subject to the following conditions:
// 
// 1) Neither the Font Software nor any of its individual components,
// in Original or Modified Versions, may be sold by itself.
// 
// 2) Original or Modified Versions of the Font Software may be bundled,
// redistributed and/or sold with any software, provided that each copy
// contains the above copyright notice and this license. These can be
// included either as stand-alone text files, human-readable headers or
// in the appropriate machine-readable metadata fields within text or
// binary files as long as those fields can be easily viewed by the user.
// 
// 3) No Modified Version of the Font Software may use the Reserved Font
// Name(s) unless explicit written permission is granted by the corresponding
// Copyright Holder. This restriction only applies to the primary font name as
// presented to the users.
// 
// 4) The name(s) of the Copyright Holder(s) or the Author(s) of the Font
// Software shall not be used to promote, endorse or advertise any
// Modified Version, except to acknowledge the contribution(s) of the
// Copyright Holder(s) and the Author(s) or with their explicit written
// permission.
// 
// 5) The Font Software, modified or unmodified, in part or in whole,
// must be distributed entirely under this license, and must not be
// distributed under any other license. The requirement for fonts to
// remain under this license does not apply to any document created
// using the Font Software.
// 
// TERMINATION
// This license becomes null and void if any of the above conditions are
// not met.
// 
// DISCLAIMER
// THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
// OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL THE
// COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL
// DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM
// OTHER DEALINGS IN THE FONT SOFTWARE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Terminus
//     Size: 10x18
//     Bold: no
//     Italic: no
//     Memory usage: 2152 bytes
//
//*****************************************************************************

static const uint8_t g_pui8terminus10x18Data[1951] =
{
      5,  10,   0,  22,  64,  16,   6, 240,  49,  81,  81,  81,
     81,  81,  81,  81, 240,  33,  81, 240, 128,  13,   8, 129,
     49,  49,  49,  49,  49,  49,  49,   0,  13,  48,  27,   9,
    240, 209,  49,  65,  49,  65,  49,  55,  49,  49,  65,  49,
     65,  49,  65,  49,  55,  49,  49,  65,  49,  65,  49, 240,
    240,  29,   9, 240,  97, 129, 101,  49,  33,  33,  33,  33,
     81,  33,  81,  33, 101,  97,  33,  81,  33,  81,  33,  33,
     33,  33,  53,  97, 129, 224,  25,   9, 240, 195,  49,  33,
     17,  49,  35,  33, 129, 113, 129, 113, 129, 113, 129,  35,
     33,  49,  17,  33,  51, 240, 208,  30,   9, 240, 227,  81,
     49,  65,  49,  65,  49,  81,  17,  98,  49,  33,  33,  33,
     17,  66,  33,  81,  33,  81,  49,  49,  17,  51,  33, 240,
    208,   9,   6,  97,  81,  81,  81,   0,  10,  48,  17,   7,
    240, 129,  81,  97,  81,  97,  97,  97,  97,  97, 113,  97,
    113, 240, 160,  17,   7, 240,  97, 113,  97, 113,  97,  97,
     97,  97,  97,  81,  97,  81, 240, 192,  18,   9,   0,   5,
     97,  49,  81,  17, 113,  87,  81, 113,  17,  81,  49,   0,
      7,  16,  14,   9,   0,   6,   1, 129, 129,  87,  81, 129,
    129,   0,   7,  48,  10,   7,   0,  10,  81,  97,  97,  81,
    240,  80,   8,   9,   0,   9,   7,   0,  10,  48,   8,   6,
      0,   9,  97,  81, 240, 128,  18,   8, 240, 225, 113,  97,
    113,  97, 113,  97, 113,  97, 113,  97, 113, 240, 240,  16,
     30,   9, 240, 213,  49,  81,  33,  81,  33,  66,  33,  49,
     17,  33,  33,  33,  33,  17,  49,  34,  65,  33,  81,  33,
     81,  33,  81,  53, 240, 240,  18,   8, 240, 177,  98,  81,
     17, 113, 113, 113, 113, 113, 113, 113, 113,  85, 240, 192,
     20,   9, 240, 213,  49,  81,  33,  81,  33,  81, 129, 113,
    113, 113, 113, 113, 113, 135, 240, 224,  21,   9, 240, 213,
     49,  81,  33,  81, 129, 129,  68, 145, 129, 129,  33,  81,
     33,  81,  53, 240, 240,  24,   9, 240, 240,  49, 114,  97,
     17,  81,  33,  65,  49,  49,  65,  33,  81,  33,  81,  39,
    129, 129, 129, 240, 224,  19,   9, 240, 199,  33, 129, 129,
    129, 134, 145, 129, 129,  33,  81,  33,  81,  53, 240, 240,
     22,   9, 240, 228,  65, 113, 129, 129, 134,  49,  81,  33,
     81,  33,  81,  33,  81,  33,  81,  53, 240, 240,  20,   9,
    240, 199,  33,  81,  33,  81, 129, 113, 129, 113, 129, 113,
    129, 129, 129, 240, 240,  32,  26,   9, 240, 213,  49,  81,
     33,  81,  33,  81,  33,  81,  53,  49,  81,  33,  81,  33,
     81,  33,  81,  33,  81,  53, 240, 240,  23,   9, 240, 213,
     49,  81,  33,  81,  33,  81,  33,  81,  33,  81,  54, 129,
    129, 129, 113,  68, 240, 240,  16,  11,   6, 240, 240,  97,
     81, 240, 225,  81, 240, 224,  14,   7, 240, 240, 209,  97,
    240, 240,  65,  97,  97,  81, 240,  80,  17,   8, 240, 225,
     97,  97,  97,  97,  97, 113, 129, 129, 129, 129, 129, 240,
    176,  10,   9,   0,   6, 103, 240, 231,   0,   8,  16,  18,
      8, 240, 145, 129, 129, 129, 129, 129, 113,  97,  97,  97,
     97,  97, 240, 240,  16,  21,   9, 240, 227,  81,  49,  49,
     81,  33,  81, 129, 113, 113, 113, 129, 240,  33, 129, 240,
    240,  32,  30,   9, 240, 214,  33,  97,  17,  97,  17,  52,
     17,  33,  49,  17,  33,  49,  17,  33,  49,  17,  33,  34,
     17,  50,  17,  17, 129, 151, 240, 208,  27,   9, 240, 213,
     49,  81,  33,  81,  33,  81,  33,  81,  33,  81,  39,  33,
     81,  33,  81,  33,  81,  33,  81,  33,  81, 240, 224,  26,
      9, 240, 198,  49,  81,  33,  81,  33,  81,  33,  81,  38,
     49,  81,  33,  81,  33,  81,  33,  81,  33,  81,  38, 240,
    240,  21,   9, 240, 213,  49,  81,  33,  81,  33, 129, 129,
    129, 129, 129, 129,  81,  33,  81,  53, 240, 240,  28,   9,
    240, 197,  65,  65,  49,  81,  33,  81,  33,  81,  33,  81,
     33,  81,  33,  81,  33,  81,  33,  81,  33,  65,  53, 240,
    240,  16,  17,   9, 240, 199,  33, 129, 129, 129, 133,  65,
    129, 129, 129, 129, 135, 240, 224,  18,   9, 240, 199,  33,
    129, 129, 129, 133,  65, 129, 129, 129, 129, 129, 240, 240,
     80,  24,   9, 240, 213,  49,  81,  33,  81,  33, 129, 129,
    129,  36,  33,  81,  33,  81,  33,  81,  33,  81,  53, 240,
    240,  28,   9, 240, 193,  81,  33,  81,  33,  81,  33,  81,
     33,  81,  39,  33,  81,  33,  81,  33,  81,  33,  81,  33,
     81,  33,  81, 240, 224,  17,   7, 240,  99,  81,  97,  97,
     97,  97,  97,  97,  97,  97,  97,  83, 240, 160,  20,   8,
    240, 211,  97, 113, 113, 113, 113, 113, 113,  33,  65,  33,
     65,  33,  65,  52, 240, 192,  27,   9, 240, 193,  81,  33,
     65,  49,  49,  65,  33,  81,  17,  98, 114, 113,  17,  97,
     33,  81,  49,  65,  65,  49,  81, 240, 224,  17,   9, 240,
    193, 129, 129, 129, 129, 129, 129, 129, 129, 129, 129, 135,
    240, 224,  35,   9, 240, 193,  97,  18,  66,  17,  17,  33,
     17,  17,  17,  33,  17,  17,  34,  33,  17,  34,  33,  17,
     97,  17,  97,  17,  97,  17,  97,  17,  97,  17,  97, 240,
    208,  32,   9, 240, 193,  81,  33,  81,  33,  81,  34,  65,
     33,  17,  49,  33,  33,  33,  33,  49,  17,  33,  66,  33,
     81,  33,  81,  33,  81,  33,  81, 240, 224,  27,   9, 240,
    213,  49,  81,  33,  81,  33,  81,  33,  81,  33,  81,  33,
     81,  33,  81,  33,  81,  33,  81,  33,  81,  53, 240, 240,
     23,   9, 240, 198,  49,  81,  33,  81,  33,  81,  33,  81,
     33,  81,  38,  49, 129, 129, 129, 129, 240, 240,  80,  29,
      9, 240, 213,  49,  81,  33,  81,  33,  81,  33,  81,  33,
     81,  33,  81,  33,  81,  33,  81,  33,  81,  33,  33,  33,
     53, 129, 145, 176,  27,   9, 240, 198,  49,  81,  33,  81,
     33,  81,  33,  81,  33,  81,  38,  49,  17,  97,  33,  81,
     49,  65,  65,  49,  81, 240, 224,  21,   9, 240, 213,  49,
     81,  33,  81,  33, 129, 149, 145, 129, 129,  33,  81,  33,
     81,  53, 240, 240,  18,   9, 240, 199,  81, 129, 129, 129,
    129, 129, 129, 129, 129, 129, 129, 240, 240,  32,  28,   9,
    240, 193,  81,  33,  81,  33,  81,  33,  81,  33,  81,  33,
     81,  33,  81,  33,  81,  33,  81,  33,  81,  33,  81,  53,
    240, 240,  28,   9, 240, 193,  81,  33,  81,  33,  81,  33,
     81,  49,  49,  65,  49,  65,  49,  81,  17,  97,  17,  97,
     17, 113, 129, 240, 240,  32,  35,   9, 240, 193,  97,  17,
     97,  17,  97,  17,  97,  17,  97,  17,  97,  17,  34,  33,
     17,  34,  33,  17,  17,  33,  17,  17,  17,  33,  17,  18,
     66,  17,  97, 240, 208,  27,   9, 240, 193,  81,  33,  81,
     49,  49,  65,  49,  81,  17, 113, 129, 113,  17,  81,  49,
     65,  49,  49,  81,  33,  81, 240, 224,  24,   9, 240, 193,
     81,  33,  81,  49,  49,  65,  49,  81,  17,  97,  17, 113,
    129, 129, 129, 129, 129, 240, 240,  32,  17,   9, 240, 199,
    129, 129, 113, 113, 113, 113, 113, 113, 129, 129, 135, 240,
    224,  17,   7, 240,  99,  65,  97,  97,  97,  97,  97,  97,
     97,  97,  97,  99, 240, 160,  17,   8, 240, 145, 113, 129,
    113, 129, 113, 129, 113, 129, 113, 129, 113, 240, 176,  17,
      7, 240,  99,  97,  97,  97,  97,  97,  97,  97,  97,  97,
     97,  67, 240, 160,  12,   9, 193, 113,  17,  81,  49,  49,
     81,   0,  14, 112,   6,   9,   0,  18,   7, 176,   7,   7,
      1, 113,   0,  14,  80,  19,   9,   0,   6, 117, 145, 129,
     54,  33,  81,  33,  81,  33,  81,  33,  81,  54, 240, 224,
     24,   9, 240, 193, 129, 129, 134,  49,  81,  33,  81,  33,
     81,  33,  81,  33,  81,  33,  81,  33,  81,  38, 240, 240,
     17,   9,   0,   6, 117,  49,  81,  33, 129, 129, 129, 129,
    129,  81,  53, 240, 240,  25,   9, 240, 240,  49, 129, 129,
     54,  33,  81,  33,  81,  33,  81,  33,  81,  33,  81,  33,
     81,  33,  81,  54, 240, 224,  19,   9,   0,   6, 117,  49,
     81,  33,  81,  33,  81,  39,  33, 129, 129,  81,  53, 240,
    240,  17,   8, 240, 195,  65, 113,  85,  81, 113, 113, 113,
    113, 113, 113, 113, 240, 224,  24,   9,   0,   6, 118,  33,
     81,  33,  81,  33,  81,  33,  81,  33,  81,  33,  81,  33,
     81,  54, 129, 129,  53,  48,  25,   9, 240, 193, 129, 129,
    134,  49,  81,  33,  81,  33,  81,  33,  81,  33,  81,  33,
     81,  33,  81,  33,  81, 240, 224,  16,   7, 240, 113,  97,
    194,  97,  97,  97,  97,  97,  97,  97,  83, 240, 160,  20,
      8, 240, 209, 113, 226, 113, 113, 113, 113, 113, 113, 113,
    113,  49,  49,  49,  49,  67,  64,  25,   9, 240, 193, 129,
    129, 129,  81,  33,  65,  49,  49,  65,  33,  83,  97,  33,
     81,  49,  65,  65,  49,  81, 240, 224,  17,   7, 240,  98,
     97,  97,  97,  97,  97,  97,  97,  97,  97,  97,  83, 240,
    160,  31,   9,   0,   6, 102,  49,  33,  33,  33,  33,  33,
     33,  33,  33,  33,  33,  33,  33,  33,  33,  33,  33,  33,
     33,  33,  33,  33,  33,  33, 240, 224,  23,   9,   0,   6,
    102,  49,  81,  33,  81,  33,  81,  33,  81,  33,  81,  33,
     81,  33,  81,  33,  81, 240, 224,  22,   9,   0,   6, 117,
     49,  81,  33,  81,  33,  81,  33,  81,  33,  81,  33,  81,
     33,  81,  53, 240, 240,  24,   9,   0,   6, 102,  49,  81,
     33,  81,  33,  81,  33,  81,  33,  81,  33,  81,  33,  81,
     38,  49, 129, 129, 128,  24,   9,   0,   6, 118,  33,  81,
     33,  81,  33,  81,  33,  81,  33,  81,  33,  81,  33,  81,
     54, 129, 129, 129,  32,  18,   9,   0,   6,  97,  36,  33,
     17,  98, 113, 129, 129, 129, 129, 129, 240, 240,  80,  17,
      9,   0,   6, 117,  49,  81,  33, 129, 149, 145, 129,  33,
     81,  53, 240, 240,  17,   8, 240, 177, 113, 113,  85,  81,
    113, 113, 113, 113, 113, 113, 131, 240, 176,  23,   9,   0,
      6,  97,  81,  33,  81,  33,  81,  33,  81,  33,  81,  33,
     81,  33,  81,  33,  81,  54, 240, 224,  23,   9,   0,   6,
     97,  81,  33,  81,  33,  81,  49,  49,  65,  49,  81,  17,
     97,  17, 113, 129, 240, 240,  32,  28,   9,   0,   6,  97,
     81,  33,  81,  33,  81,  33,  33,  33,  33,  33,  33,  33,
     33,  33,  33,  33,  33,  33,  33,  33,  53, 240, 240,  23,
      9,   0,   6,  97,  81,  33,  81,  49,  49,  81,  17, 113,
    113,  17,  81,  49,  49,  81,  33,  81, 240, 224,  25,   9,
      0,   6,  97,  81,  33,  81,  33,  81,  33,  81,  33,  81,
     33,  81,  33,  81,  33,  81,  54, 129, 129,  53,  48,  15,
      9,   0,   6, 103, 129, 113, 113, 113, 113, 113, 113, 135,
    240, 224,  17,   8, 240, 194,  81, 113, 113, 113,  82, 129,
    113, 113, 113, 113, 130, 240, 192,  17,   6, 240,  49,  81,
     81,  81,  81,  81,  81,  81,  81,  81,  81,  81, 240, 128,
     17,   8, 240, 146, 129, 113, 113, 113, 130,  81, 113, 113,
    113, 113,  82, 240, 240,  14,   9, 162,  49,  33,  33,  33,
     33,  33,  33,  33,  50,   0,  15,
};

const tFont g_sFontterminus10x18 =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    10,

    //
    // The height of the font.
    //
    18,

    //
    // The baseline of the font.
    //
    15,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   21,   34,   61,   90,  115,  145,
         154,  171,  188,  206,  220,  230,  238,  246,
         264,  294,  312,  332,  353,  377,  396,  418,
         438,  464,  487,  498,  512,  529,  539,  557,
         578,  608,  635,  661,  682,  710,  727,  745,
         769,  797,  814,  834,  861,  878,  913,  945,
         972,  995, 1024, 1051, 1072, 1090, 1118, 1146,
        1181, 1208, 1232, 1249, 1266, 1283, 1300, 1312,
        1318, 1325, 1344, 1368, 1385, 1410, 1429, 1446,
        1470, 1495, 1511, 1531, 1556, 1573, 1604, 1627,
        1649, 1673, 1697, 1715, 1732, 1749, 1772, 1795,
        1823, 1846, 1871, 1886, 1903, 1920, 1937,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8terminus10x18Data
};
