//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidatypewriter
//     Size: 6x11
//     Bold: yes
//     Italic: no
//     Memory usage: 1368 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidatypewriter6x11bData[1166] =
{
      5,   6,   0,   8,  32,  10,   6, 194,  66,  66,  81, 162,
     66, 240,  16,  11,   6,  97,  17,  49,  17,  49,  17, 240,
    240, 240,  17,   6, 210,  17,  34,  17,  19,  18,  18,  17,
     19,  18,  18,  17,  34,  17, 208,  14,   6,  49,  81,  52,
     18,  67,  67,  67,  66,  20,  49,  81,  64,  16,   6, 209,
     65,  17,  33,  17,  33,  50,  49,  33,  17,  33,  17,  65,
    208,  15,   6, 210,  50,  17,  34,  17,  50,  50,  18,  18,
     17,  50,  17, 208,   8,   6,  97,  81,  81,   0,   5, 112,
     12,   6, 130,  50,  50,  66,  66,  66,  66,  82,  82, 128,
     12,   6,  98,  82,  82,  66,  66,  66,  66,  50,  50, 160,
     10,   6, 194,  18,  34,  50,  18, 240, 240, 112,  10,   6,
    240,  81,  81,  53,  49,  81, 240,  96,   9,   6, 240, 240,
    194,  66,  81,  65,  80,   7,   6, 240, 245, 240, 240,  16,
      8,   6, 240, 240, 194,  66, 240,  16,  12,   6, 162,  66,
     50,  66,  50,  50,  66,  50,  66, 160,  15,   6, 211,  34,
     18,  18,  18,  18,  18,  18,  18,  18,  18,  35, 224,  10,
      6, 226,  36,  66,  66,  66,  66,  66, 224,  11,   6, 211,
     34,  18,  66,  50,  50,  50,  69, 208,  12,   6, 211,  34,
     18,  66,  35,  82,  18,  18,  35, 224,  12,   6, 226,  51,
     33,  18,  33,  18,  37,  50,  66, 224,  11,   6, 197,  18,
     66,  68,  82,  18,  18,  35, 224,  13,   6, 211,  34,  18,
     18,  68,  34,  18,  18,  18,  35, 224,  10,   6, 197,  21,
     81,  65,  66,  50,  66, 240,  14,   6, 211,  34,  18,  18,
     18,  35,  34,  18,  18,  18,  35, 224,  13,   6, 211,  34,
     18,  18,  18,  36,  66,  18,  18,  35, 224,  10,   6, 240,
     50,  66, 240,  18,  66, 240,  16,  11,   6, 240,  50,  66,
    240,  18,  66,  81,  65,  80,  10,   6, 240,  82,  50,  50,
     82,  82, 240,  80,   7,   6, 240, 149, 117, 240, 160,  10,
      6, 240,  50,  82,  82,  50,  50, 240, 112,   9,   6, 196,
     82,  66,  35, 146,  66, 240,  15,   6, 211,  33,  49,  17,
     19,  17,  17,  17,  17,  19,  17, 100, 208,  12,   6, 226,
     66,  49,  18,  33,  18,  23,  51,  50, 192,  14,   6, 196,
     34,  33,  18,  33,  20,  34,  33,  18,  33,  20, 224,  11,
      6, 212,  19,  17,  18,  66,  66,  67,  68, 208,  15,   6,
    196,  34,  18,  18,  33,  18,  33,  18,  33,  18,  18,  20,
    224,  10,   6, 196,  34,  66,  68,  34,  66,  68, 224,  11,
      6, 197,  18,  66,  68,  34,  66,  66, 240,  16,  13,   6,
    212,  19,  50,  66,  33,  18,  33,  19,  17,  36, 208,  16,
      6, 194,  33,  18,  33,  18,  33,  21,  18,  33,  18,  33,
     18,  33, 208,  10,   6, 196,  50,  66,  66,  66,  66,  52,
    224,  12,   6, 211,  66,  66,  66,  66,  66,  66,  66,  35,
     48,  16,   6, 194,  33,  18,  17,  34,  17,  35,  50,  17,
     34,  33,  18,  33, 208,  10,   6, 194,  66,  66,  66,  66,
     66,  69, 208,  11,   6, 193,  67,  47,  17,  19,  17,  19,
     50, 192,  16,   6, 193,  49,  18,  33,  19,  17,  21,  17,
     19,  17,  34,  17,  49, 208,  15,   6, 211,  34,  33,  18,
     33,  18,  33,  18,  33,  18,  33,  35, 224,  13,   6, 196,
     34,  33,  18,  33,  20,  34,  66,  66, 240,  16,  16,   6,
    211,  34,  33,  18,  33,  18,  33,  18,  33,  18,  33,  35,
     66,  82,  15,   6, 196,  34,  33,  18,  33,  20,  34,  17,
     34,  33,  18,  33, 208,  10,   6, 212,  18,  67,  67,  67,
     66,  20, 224,  10,   6, 198,  34,  66,  66,  66,  66,  66,
    224,  16,   6, 194,  33,  18,  33,  18,  33,  18,  33,  18,
     33,  18,  33,  35, 224,  12,   6, 194,  51,  51,  34,  18,
     17,  36,  50,  66, 224,  15,   6, 194,  51,  17,  19,  17,
     19,  17,  23,  18,  17,  34,  17, 208,  14,   6, 194,  33,
     18,  33,  35,  65,  67,  33,  34,  17,  34, 208,  12,   6,
    194,  51,  49,  18,  17,  50,  66,  66,  66, 224,  10,   6,
    197,  66,  50,  51,  50,  50,  69, 208,  12,   6, 100,  34,
     66,  66,  66,  66,  66,  66,  68, 128,  12,   6,  98,  66,
     82,  66,  82,  82,  66,  82,  66,  96,  12,   6, 100,  66,
     66,  66,  66,  66,  66,  66,  36, 128,  13,   6, 226,  66,
     49,  18,  33,  18,  17,  51,  50, 240,  48,   6,   6,   0,
      6, 102,  96,   7,   6,   2,  82,   0,   7,  16,  13,   6,
    240,  67,  82,  36,  18,  18,  18,  18,  34,  17, 208,  15,
      6,  98,  66,  68,  34,  18,  18,  18,  18,  18,  18,  18,
     20, 224,  10,   6, 240,  67,  34,  66,  66,  66,  83, 224,
     16,   6, 146,  66,  36,  18,  18,  18,  18,  18,  18,  18,
     18,  34,  17, 208,  12,   6, 240,  67,  34,  18,  18,  18,
     21,  18,  84, 208,  11,   6, 131,  34,  53,  34,  66,  66,
     66,  66, 240,  16,   6, 240,  68,  18,  18,  18,  18,  18,
     18,  18,  18,  36,  66,  20,  32,  16,   6,  98,  66,  66,
     17,  37,  18,  18,  18,  18,  18,  18,  18,  18, 208,  10,
      6, 130, 132,  66,  66,  66,  66,  66, 224,  12,   6, 130,
    132,  66,  66,  66,  66,  66,  66,  35,  48,  15,   6,  98,
     66,  66,  33,  18,  17,  35,  52,  34,  18,  18,  33, 208,
     11,   6, 100,  66,  66,  66,  66,  66,  66,  66, 224,  20,
      6, 240,  52,  33,  17,  17,  17,  17,  17,  17,  17,  17,
     17,  17,  17,  17,  17,  17, 208,  16,   6, 240,  49,  18,
     34,  18,  18,  18,  18,  18,  18,  18,  18,  18, 208,  14,
      6, 240,  67,  34,  18,  18,  18,  18,  18,  18,  18,  35,
    224,  17,   6, 240,  49,  18,  34,  18,  18,  18,  18,  18,
     18,  18,  20,  34,  66,  64,  15,   6, 240,  68,  18,  18,
     18,  18,  18,  18,  18,  18,  36,  66,  66,  12,   6, 240,
     50,  18,  21,  18,  66,  66,  66, 240,  16,  10,   6, 240,
     68,  18,  68,  52,  66,  20, 224,  10,   6, 210,  53,  34,
     66,  66,  66,  83, 208,  16,   6, 240,  50,  18,  18,  18,
     18,  18,  18,  18,  18,  18,  34,  17, 208,  12,   6, 240,
     50,  36,  34,  18,  17,  36,  50,  66, 224,  16,   6, 240,
     50,  51,  17,  19,  17,  19,  17,  17,  18,  17,  34,  17,
    208,  14,   6, 240,  51,  18,  18,  17,  50,  66,  49,  18,
     18,  19, 192,  16,   6, 240,  50,  33,  18,  33,  18,  18,
     33,  17,  51,  66,  65,  66,  48,  10,   6, 240,  53,  51,
     35,  35,  50,  69, 208,  12,   6, 131,  34,  66,  81,  50,
     97,  66,  66,  83, 112,  12,   6,  98,  66,  66,  66,  66,
     66,  66,  66,  66, 160,  12,   6,  99,  82,  66,  65,  98,
     49,  82,  66,  35, 144,   9,   6, 240, 163,  18,  19, 240,
    240,  16,
};

const tFont g_sFontlucidatypewriter6x11b =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    6,

    //
    // The height of the font.
    //
    11,

    //
    // The baseline of the font.
    //
    9,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   15,   26,   43,   57,   73,   88,
          96,  108,  120,  130,  140,  149,  156,  164,
         176,  191,  201,  212,  224,  236,  247,  260,
         270,  284,  297,  307,  318,  328,  335,  345,
         354,  369,  381,  395,  406,  421,  431,  442,
         455,  471,  481,  493,  509,  519,  530,  546,
         561,  574,  590,  605,  615,  625,  641,  653,
         668,  682,  694,  704,  716,  728,  740,  753,
         759,  766,  779,  794,  804,  820,  832,  843,
         859,  875,  885,  897,  912,  923,  943,  959,
         973,  990, 1005, 1017, 1027, 1037, 1053, 1065,
        1081, 1095, 1111, 1121, 1133, 1145, 1157,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidatypewriter6x11bData
};
