//*****************************************************************************
//
// Copyright (c) 2014 Dimitar Toshkov Zhekov,
// with Reserved Font Name "Terminus Font".
// 
// This Font Software is licensed under the SIL Open Font License, Version 1.1.
// This license is copied below, and is also available with a FAQ at:
// http://scripts.sil.org/OFL
// 
// 
// -----------------------------------------------------------
// SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007
// -----------------------------------------------------------
// 
// PREAMBLE
// The goals of the Open Font License (OFL) are to stimulate worldwide
// development of collaborative font projects, to support the font creation
// efforts of academic and linguistic communities, and to provide a free and
// open framework in which fonts may be shared and improved in partnership
// with others.
// 
// The OFL allows the licensed fonts to be used, studied, modified and
// redistributed freely as long as they are not sold by themselves. The
// fonts, including any derivative works, can be bundled, embedded, 
// redistributed and/or sold with any software provided that any reserved
// names are not used by derivative works. The fonts and derivatives,
// however, cannot be released under any other type of license. The
// requirement for fonts to remain under this license does not apply
// to any document created using the fonts or their derivatives.
// 
// DEFINITIONS
// "Font Software" refers to the set of files released by the Copyright
// Holder(s) under this license and clearly marked as such. This may
// include source files, build scripts and documentation.
// 
// "Reserved Font Name" refers to any names specified as such after the
// copyright statement(s).
// 
// "Original Version" refers to the collection of Font Software components as
// distributed by the Copyright Holder(s).
// 
// "Modified Version" refers to any derivative made by adding to, deleting,
// or substituting -- in part or in whole -- any of the components of the
// Original Version, by changing formats or by porting the Font Software to a
// new environment.
// 
// "Author" refers to any designer, engineer, programmer, technical
// writer or other person who contributed to the Font Software.
// 
// PERMISSION & CONDITIONS
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of the Font Software, to use, study, copy, merge, embed, modify,
// redistribute, and sell modified and unmodified copies of the Font
// Software, subject to the following conditions:
// 
// 1) Neither the Font Software nor any of its individual components,
// in Original or Modified Versions, may be sold by itself.
// 
// 2) Original or Modified Versions of the Font Software may be bundled,
// redistributed and/or sold with any software, provided that each copy
// contains the above copyright notice and this license. These can be
// included either as stand-alone text files, human-readable headers or
// in the appropriate machine-readable metadata fields within text or
// binary files as long as those fields can be easily viewed by the user.
// 
// 3) No Modified Version of the Font Software may use the Reserved Font
// Name(s) unless explicit written permission is granted by the corresponding
// Copyright Holder. This restriction only applies to the primary font name as
// presented to the users.
// 
// 4) The name(s) of the Copyright Holder(s) or the Author(s) of the Font
// Software shall not be used to promote, endorse or advertise any
// Modified Version, except to acknowledge the contribution(s) of the
// Copyright Holder(s) and the Author(s) or with their explicit written
// permission.
// 
// 5) The Font Software, modified or unmodified, in part or in whole,
// must be distributed entirely under this license, and must not be
// distributed under any other license. The requirement for fonts to
// remain under this license does not apply to any document created
// using the Font Software.
// 
// TERMINATION
// This license becomes null and void if any of the above conditions are
// not met.
// 
// DISCLAIMER
// THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
// OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL THE
// COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL
// DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM
// OTHER DEALINGS IN THE FONT SOFTWARE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Terminus
//     Size: 11x22
//     Bold: no
//     Italic: no
//     Memory usage: 2500 bytes
//
//*****************************************************************************

static const uint8_t g_pui8terminus11x22Data[2297] =
{
      5,  11,   0,  30,  32,  19,   6, 240,  49,  81,  81,  81,
     81,  81,  81,  81,  81, 240,  33,  81,  81, 240, 240,  80,
     15,   8, 129,  49,  49,  49,  49,  49,  49,  49,  49,  49,
      0,  16,  48,  33,  10, 240, 240,  33,  49,  81,  49,  81,
     49,  81,  49,  57,  49,  49,  81,  49,  81,  49,  81,  49,
     57,  49,  49,  81,  49,  81,  49,  81,  49,   0,   6,  80,
     37,  10, 240, 145, 145, 117,  65,  33,  33,  33,  49,  49,
     17,  49,  81,  49,  97,  33, 117, 113,  33,  97,  49,  81,
     49,  17,  49,  49,  33,  33,  33,  69, 113, 145, 240, 240,
     80,  33,  10, 240, 240,  18,  65,  33,  33,  49,  33,  33,
     33,  66,  49, 129, 145, 129, 145, 129, 145, 129,  50,  65,
     33,  33,  33,  49,  33,  33,  66,   0,   6,  64,  36,  10,
    240, 240,  36,  81,  65,  65,  65,  65,  65,  81,  33, 114,
    113,  17,  97,  49,  33,  17,  81,  17,  17,  97,  33,  97,
     33,  97,  49,  65,  17,  52,  33,   0,   6,  48,  10,   6,
     97,  81,  81,  81,  81,   0,  12,  80,  20,   8, 240, 193,
     97,  97, 113,  97, 113, 113, 113, 113, 113, 129, 113, 129,
    129, 240, 240, 224,  20,   8, 240, 145, 129, 129, 113, 129,
    113, 113, 113, 113, 113,  97, 113,  97,  97,   0,   5, 112,
     21,  10,   0,   7,  81,  81,  65,  49,  97,  17, 129,  89,
     81, 129,  17,  97,  49,  65,  81,   0,   9,  16,  10,   0,
      8,   1, 145, 145, 145,  89,  81, 145, 145, 145,   0,   9,
     48,  12,   7,   0,  11,  65,  97,  97,  97,  81, 240, 240,
     64,   7,  10,   0,  12,  72,   0,  14,  10,   6,   0,  10,
     65,  81,  81, 240, 240,  80,  21,   9, 240, 240,  49, 129,
    113, 129, 113, 129, 113, 129, 113, 129, 113, 129, 113, 129,
      0,   6,  80,  37,  10, 240, 240,  36,  81,  65,  49,  97,
     33,  97,  33,  82,  33,  65,  17,  33,  49,  33,  33,  33,
     49,  33,  17,  65,  34,  81,  33,  97,  33,  97,  49,  65,
     84,   0,   6,  96,  22,   9, 240, 241, 114,  97,  17,  81,
     33, 129, 129, 129, 129, 129, 129, 129, 129, 129,  87,   0,
      5, 112,  25,  10, 240, 240,  36,  81,  65,  49,  97,  33,
     97,  33,  97, 145, 129, 129, 129, 129, 129, 129, 129, 152,
      0,   6,  64,  25,  10, 240, 240,  36,  81,  65,  49,  97,
    145, 145, 129,  84, 161, 161, 145, 145,  33,  97,  49,  65,
     84,   0,   6,  96,  29,  10, 240, 240, 113, 130, 113,  17,
     97,  33,  81,  49,  65,  65,  49,  81,  33,  97,  33,  97,
     33,  97,  40, 145, 145, 145,   0,   6,  64,  23,  10, 240,
    248,  33, 145, 145, 145, 150, 161, 161, 145, 145,  33,  97,
     33,  97,  49,  65,  84,   0,   6,  96,  28,  10, 240, 240,
     37,  65, 129, 145, 145, 150,  65,  81,  49,  97,  33,  97,
     33,  97,  33,  97,  33,  97,  49,  65,  84,   0,   6,  96,
     21,  10, 240, 248,  33,  97,  33,  97, 145, 129, 145, 129,
    145, 129, 145, 129, 145, 145, 145,   0,   7,  32,  10, 240,
    240,  36,  81,  65,  49,  97,  33,  97,  33,  97,  49,  65,
     84,  81,  65,  49,  97,  33,  97,  33,  97,  33,  97,  49,
     65,  84,   0,   6,  96,  28,  10, 240, 240,  36,  81,  65,
     49,  97,  33,  97,  33,  97,  33,  97,  33,  97,  49,  81,
     70, 145, 145, 145, 129,  69,   0,   6,  96,  14,   6, 240,
    240,  97,  81,  81, 240, 225,  81,  81, 240, 240, 176,  17,
      7, 240, 240, 209,  97,  97, 240, 240,  65,  97,  97,  97,
     81, 240, 240,  64,  21,   9, 240, 240,  49, 113, 113, 113,
    113, 113, 113, 129, 145, 145, 145, 145, 145, 145,   0,   5,
    112,  11,  10,   0,   8, 104, 240, 240, 200,   0,  11,  64,
     20,   9, 240, 193, 145, 145, 145, 145, 145, 145, 129, 113,
    113, 113, 113, 113, 113,   0,   6,  80,  23,  10, 240, 240,
     36,  81,  65,  49,  97,  33,  97, 145, 129, 129, 129, 145,
    240, 225, 145, 145,   0,   6, 112,  37,  10, 240, 240,  37,
     65,  81,  33, 113,  17,  68,  17,  49,  49,  17,  33,  65,
     17,  33,  65,  17,  33,  65,  17,  33,  65,  17,  49,  49,
     17,  68,  17, 161, 167,   0,   6,  48,  33,  10, 240, 240,
     36,  81,  65,  49,  97,  33,  97,  33,  97,  33,  97,  33,
     97,  40,  33,  97,  33,  97,  33,  97,  33,  97,  33,  97,
     33,  97,   0,   6,  64,  31,  10, 240, 246,  65,  81,  49,
     97,  33,  97,  33,  97,  33,  81,  54,  65,  81,  49,  97,
     33,  97,  33,  97,  33,  97,  33,  81,  54,   0,   6,  96,
     27,  10, 240, 240,  36,  81,  65,  49,  97,  33,  97,  33,
    145, 145, 145, 145, 145, 145,  97,  33,  97,  49,  65,  84,
      0,   6,  96,  32,  10, 240, 246,  65,  81,  49,  97,  33,
     97,  33,  97,  33,  97,  33,  97,  33,  97,  33,  97,  33,
     97,  33,  97,  33,  97,  33,  81,  54,   0,   6,  96,  20,
     10, 240, 248,  33, 145, 145, 145, 145, 150,  65, 145, 145,
    145, 145, 145, 152,   0,   6,  64,  20,  10, 240, 248,  33,
    145, 145, 145, 145, 150,  65, 145, 145, 145, 145, 145, 145,
      0,   7,  48,  30,  10, 240, 240,  36,  81,  65,  49,  97,
     33,  97,  33, 145, 145, 145,  52,  33,  97,  33,  97,  33,
     97,  33,  97,  49,  65,  84,   0,   6,  96,  33,  10, 240,
    241,  97,  33,  97,  33,  97,  33,  97,  33,  97,  33,  97,
     40,  33,  97,  33,  97,  33,  97,  33,  97,  33,  97,  33,
     97,  33,  97,   0,   6,  64,  20,   8, 240, 149,  81, 113,
    113, 113, 113, 113, 113, 113, 113, 113, 113, 113,  85, 240,
    240, 208,  25,  10, 240, 240,  69, 113, 145, 145, 145, 145,
    145, 145, 145,  49,  81,  49,  81,  49,  81,  65,  49,  99,
      0,   6, 112,  32,  10, 240, 241,  97,  33,  81,  49,  65,
     65,  49,  81,  33,  97,  17, 114, 130, 129,  17, 113,  33,
     97,  49,  81,  65,  65,  81,  49,  97,   0,   6,  64,  20,
     10, 240, 241, 145, 145, 145, 145, 145, 145, 145, 145, 145,
    145, 145, 145, 152,   0,   6,  64,  42,  10, 240, 241, 113,
     18,  82,  17,  17,  49,  17,  17,  17,  49,  17,  17,  33,
     17,  33,  17,  49,  49,  17,  49,  49,  17, 113,  17, 113,
     17, 113,  17, 113,  17, 113,  17, 113,  17, 113,   0,   6,
     48,  38,  10, 240, 241,  97,  33,  97,  33,  97,  33,  97,
     34,  81,  33,  17,  65,  33,  33,  49,  33,  49,  33,  33,
     65,  17,  33,  82,  33,  97,  33,  97,  33,  97,  33,  97,
      0,   6,  64,  33,  10, 240, 240,  36,  81,  65,  49,  97,
     33,  97,  33,  97,  33,  97,  33,  97,  33,  97,  33,  97,
     33,  97,  33,  97,  33,  97,  49,  65,  84,   0,   6,  96,
     26,  10, 240, 246,  65,  81,  49,  97,  33,  97,  33,  97,
     33,  97,  33,  81,  54,  65, 145, 145, 145, 145, 145,   0,
      7,  48,  37,  10, 240, 240,  36,  81,  65,  49,  97,  33,
     97,  33,  97,  33,  97,  33,  97,  33,  97,  33,  97,  33,
     97,  33,  97,  33,  33,  49,  49,  33,  17,  84, 161, 161,
    240, 240,  32,  32,  10, 240, 246,  65,  81,  49,  97,  33,
     97,  33,  97,  33,  97,  33,  81,  54,  65,  17, 113,  33,
     97,  49,  81,  65,  65,  81,  49,  97,   0,   6,  64,  25,
     10, 240, 240,  36,  81,  65,  49,  97,  33, 145, 161, 164,
    161, 161, 145, 145,  33,  97,  49,  65,  84,   0,   6,  96,
     20,  10, 240, 249,  81, 145, 145, 145, 145, 145, 145, 145,
    145, 145, 145, 145, 145,   0,   6, 112,  33,  10, 240, 241,
     97,  33,  97,  33,  97,  33,  97,  33,  97,  33,  97,  33,
     97,  33,  97,  33,  97,  33,  97,  33,  97,  33,  97,  49,
     65,  84,   0,   6,  96,  32,  10, 240, 241,  97,  33,  97,
     33,  97,  33,  97,  33,  97,  49,  65,  65,  65,  65,  65,
     65,  65,  81,  33,  97,  33,  97,  33, 114, 130,   0,   6,
    112,  42,  10, 240, 241, 113,  17, 113,  17, 113,  17, 113,
     17, 113,  17, 113,  17, 113,  17,  49,  49,  17,  49,  49,
     17,  33,  17,  33,  17,  17,  49,  17,  17,  17,  49,  17,
     18,  82,  17, 113,   0,   6,  48,  32,  10, 240, 241,  97,
     33,  97,  49,  65,  65,  65,  81,  33,  97,  33, 114, 130,
    113,  33,  97,  33,  81,  65,  65,  65,  49,  97,  33,  97,
      0,   6,  64,  28,  10, 240, 241, 113,  17, 113,  33,  81,
     49,  81,  65,  49,  81,  49,  97,  17, 113,  17, 129, 145,
    145, 145, 145, 145,   0,   6, 112,  20,  10, 240, 248, 145,
    145, 145, 129, 129, 129, 129, 129, 129, 129, 145, 145, 152,
      0,   6,  64,  20,   8, 240, 148,  65, 113, 113, 113, 113,
    113, 113, 113, 113, 113, 113, 113, 116, 240, 240, 224,  20,
      9, 240, 193, 129, 145, 129, 145, 129, 145, 129, 145, 129,
    145, 129, 145, 129,   0,   5, 112,  20,   8, 240, 148, 113,
    113, 113, 113, 113, 113, 113, 113, 113, 113, 113, 113,  68,
    240, 240, 224,  14,  10, 225, 129,  17,  97,  49,  65,  81,
     33, 113,   0,  20,  16,   8,  10,   0,  22,  72, 240, 240,
     32,   8,   8,   1, 129, 129,   0,  19,  80,  21,  10,   0,
      8, 117, 161, 161, 145,  55,  33,  97,  33,  97,  33,  97,
     33,  97,  55,   0,   6,  64,  28,  10, 240, 241, 145, 145,
    145, 150,  65,  81,  49,  97,  33,  97,  33,  97,  33,  97,
     33,  97,  33,  97,  33,  81,  54,   0,   6,  96,  21,  10,
      0,   9,   4,  81,  65,  49,  97,  33, 145, 145, 145, 145,
     97,  49,  65,  84,   0,   6,  96,  29,  10, 240, 240, 113,
    145, 145, 145,  70,  49,  81,  33,  97,  33,  97,  33,  97,
     33,  97,  33,  97,  33,  97,  49,  81,  70,   0,   6,  64,
     21,  10,   0,   9,   4,  81,  65,  49,  97,  33,  97,  40,
     33, 145, 145, 161,  81,  69,   0,   6,  80,  20,  10, 240,
    240,  68,  81, 145, 145, 103,  97, 145, 145, 145, 145, 145,
    145, 145, 145,   0,   7,  27,  10,   0,   9,   6,  49,  81,
     33,  97,  33,  97,  33,  97,  33,  97,  33,  97,  33,  97,
     49,  81,  70, 145, 145, 129,  69, 224,  29,  10, 240, 241,
    145, 145, 145, 150,  65,  81,  49,  97,  33,  97,  33,  97,
     33,  97,  33,  97,  33,  97,  33,  97,  33,  97,   0,   6,
     64,  19,   8, 240, 177, 113, 113, 211, 113, 113, 113, 113,
    113, 113, 113, 113,  85, 240, 240, 208,  25,   9, 240, 240,
     33, 129, 129, 243, 129, 129, 129, 129, 129, 129, 129, 129,
    129,  49,  65,  49,  65,  49,  65,  68, 208,  28,   9, 240,
    193, 129, 129, 129, 129,  81,  33,  65,  49,  49,  65,  33,
     83,  99,  97,  33,  81,  49,  65,  65,  49,  81,   0,   5,
    112,  20,   8, 240, 147, 113, 113, 113, 113, 113, 113, 113,
    113, 113, 113, 113, 113,  85, 240, 240, 208,  35,  10,   0,
      8, 103,  49,  49,  33,  33,  49,  49,  17,  49,  49,  17,
     49,  49,  17,  49,  49,  17,  49,  49,  17,  49,  49,  17,
     49,  49,  17,  49,  49,   0,   6,  48,  26,  10,   0,   8,
    102,  65,  81,  49,  97,  33,  97,  33,  97,  33,  97,  33,
     97,  33,  97,  33,  97,  33,  97,   0,   6,  64,  25,  10,
      0,   9,   4,  81,  65,  49,  97,  33,  97,  33,  97,  33,
     97,  33,  97,  33,  97,  49,  65,  84,   0,   6,  96,  28,
     10,   0,   8, 102,  65,  81,  49,  97,  33,  97,  33,  97,
     33,  97,  33,  97,  33,  97,  33,  81,  54,  65, 145, 145,
    145, 240,  64,  27,  10,   0,   9,   6,  49,  81,  33,  97,
     33,  97,  33,  97,  33,  97,  33,  97,  33,  97,  49,  81,
     70, 145, 145, 145, 145, 192,  19,  10,   0,   8,  97,  37,
     33,  17, 114, 129, 145, 145, 145, 145, 145, 145,   0,   7,
     48,  19,  10,   0,   8, 118,  49,  97,  33, 145, 166, 161,
    145, 145,  33,  97,  54,   0,   6,  80,  21,  10, 240, 240,
     49, 145, 145, 145, 103,  97, 145, 145, 145, 145, 145, 145,
    145, 164,   0,   6,  64,  26,  10,   0,   8,  97,  97,  33,
     97,  33,  97,  33,  97,  33,  97,  33,  97,  33,  97,  33,
     97,  49,  81,  70,   0,   6,  64,  25,  10,   0,   8,  97,
     97,  33,  97,  33,  97,  49,  65,  65,  65,  65,  65,  81,
     33,  97,  33, 114, 130,   0,   6, 112,  32,  10,   0,   8,
     97, 113,  17, 113,  17, 113,  17,  49,  49,  17,  49,  49,
     17,  49,  49,  17,  49,  49,  17,  49,  49,  17,  49,  49,
     39,   0,   6,  64,  25,  10,   0,   8,  97,  97,  33,  97,
     49,  65,  81,  33, 114, 130, 113,  33,  81,  65,  49,  97,
     33,  97,   0,   6,  64,  28,  10,   0,   8,  97,  97,  33,
     97,  33,  97,  33,  97,  33,  97,  33,  97,  33,  97,  33,
     97,  49,  81,  70, 145, 145, 129,  69, 224,  17,  10,   0,
      8, 104, 145, 129, 129, 129, 129, 129, 129, 129, 152,   0,
      6,  64,  20,   9, 240, 240,  18,  97, 113, 129, 129, 129,
     98, 145, 129, 129, 129, 129, 145, 146,   0,   6,  20,   6,
    240,  49,  81,  81,  81,  81,  81,  81,  81,  81,  81,  81,
     81,  81,  81, 240, 240,  80,  20,   9, 240, 194, 145, 145,
    129, 129, 129, 146,  97, 129, 129, 129, 129, 113,  98,   0,
      6,  64,  15,  10, 178,  65,  33,  33,  49,  33,  49,  33,
     33,  66,   0,  21,  80,
};

const tFont g_sFontterminus11x22 =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    11,

    //
    // The height of the font.
    //
    22,

    //
    // The baseline of the font.
    //
    17,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   24,   39,   72,  109,  142,  178,
         188,  208,  228,  249,  265,  277,  284,  294,
         315,  352,  374,  399,  424,  453,  476,  504,
         525,  557,  585,  599,  616,  637,  648,  668,
         691,  728,  761,  792,  819,  851,  871,  891,
         921,  954,  974,  999, 1031, 1051, 1093, 1131,
        1164, 1190, 1227, 1259, 1284, 1304, 1337, 1369,
        1411, 1443, 1471, 1491, 1511, 1531, 1551, 1565,
        1573, 1581, 1602, 1630, 1651, 1680, 1701, 1721,
        1748, 1777, 1796, 1821, 1849, 1869, 1904, 1930,
        1955, 1983, 2010, 2029, 2048, 2069, 2095, 2120,
        2152, 2177, 2205, 2222, 2242, 2262, 2282,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8terminus11x22Data
};
