//*****************************************************************************
//
// Copyright 1988 Bitstream, Inc., Cambridge, Massachusetts, USA
// Bitstream and Charter are registered trademarks of Bitstream, Inc.
// 
// The names "Bitstream" and "Charter" are registered trademarks of
// Bitstream, Inc.  Permission to use these trademarks is hereby
// granted only in association with the images described in this file.
// 
// Permission to use, copy, modify, and distribute this software and
// its documentation for any purpose and without fee is hereby
// granted, provided that the above copyright notice appear in all
// copies and that both that copyright notice and this permission
// notice appear in supporting documentation, and that the name of
// Bitstream not be used in advertising or publicity pertaining to
// distribution of the software without specific, written prior
// permission.  Bitstream makes no representations about the
// suitability of this software for any purpose.  It is provided "as
// is" without express or implied warranty.
// 
// BITSTREAM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN
// NO EVENT SHALL BITSTREAM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
// OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
// NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
// CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
// 
// Copyright (c) 1987, 1994 Digital Equipment Corporation
// 
// The X Consortium, and any party obtaining a copy of these files from
// the X Consortium, directly or indirectly, is granted, free of charge, a
// full and unrestricted irrevocable, world-wide, paid up, royalty-free,
// nonexclusive right and license to deal in this software and
// documentation files (the "Software"), including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons who receive
// copies from any such party to do so.  This license includes without
// limitation a license to do the foregoing actions under any patents of
// the party supplying this software to the X Consortium.
// 
// Digital Equipment Corporation make no representations about the
// suitability of this software for any purpose.  It is provided "as
// is" without express or implied warranty.
// 
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Charter
//     Size: 5x10
//     Bold: no
//     Italic: no
//     Memory usage: 1244 bytes
//
//*****************************************************************************

static const uint8_t g_pui8charter5x10Data[1043] =
{
      4,   7,   0,   7,   9,   7,   1,  97,  97,  97, 209, 240,
     80,   9,   7,   1,  17,  65,  17,   0,   5,  96,  13,   7,
     33,  17,  66,  53,  49,  17,  53,  50,  65,  17, 176,  12,
      7,  19,  50,  17,  50,  99,  50,  17,  51,  81, 192,  19,
      7,  17,  49,  17,  17,  17,  33,  18,  17,  33,  18,  17,
     33,  17,  17,  17,  49, 240,  14,   7,  18,  65,  33,  67,
     66,  17,  33,  34,  50,  17, 240,  16,   6,   7,   1,  97,
      0,   6,  10,   7,  17,  81,  97,  97,  97,  97, 113, 192,
     10,   7,   1, 113,  97,  97,  97,  97,  81, 208,  10,   7,
     17,  81,  17,  65,  17, 240, 240, 144,   9,   7, 145,  97,
     69,  65,  97, 240,  48,   7,   7, 240, 240,  81,  97, 208,
      6,   7, 240, 210, 240, 176,   7,   7, 240, 240,  81, 240,
     80,  10,   7,  49,  97,  81,  97,  81,  97,  81, 208,  14,
      7,  18,  65,  33,  49,  33,  49,  33,  49,  33,  66, 240,
     48,  10,   7,   1,  97,  97,  97,  97,  97, 240,  80,  12,
      7,  18,  65,  33,  97,  81,  81,  17,  52, 240,  32,  11,
      7,  18,  65,  33,  82,  66, 113,  51, 240,  48,  12,   7,
     34,  65,  17,  49,  33,  53,  81,  97, 240,  32,  11,   7,
     20,  49,  99, 113,  34,  33,  51, 240,  32,  12,   7,  33,
     81,  83,  65,  33,  49,  33,  66, 240,  48,  11,   7,   4,
     49,  33,  81,  97,  81,  82, 240,  64,  13,   7,  18,  65,
     33,  66,  65,  18,  49,  33,  66, 240,  48,  12,   7,  18,
     65,  33,  49,  33,  67,  81,  81, 240,  64,   7,   7, 225,
    240,  81, 240,  80,   7,   7, 225, 240,  81,  97, 208,   9,
      7, 240,  34,  50,  67, 114, 240,  16,   6,   7, 229, 149,
    240, 128,   8,   7, 226, 114,  83,  34, 240,  64,  10,   7,
     17,  81,  17,  97,  81, 209, 240,  64,  16,   7,  50,  50,
     33,  33,  18,  18,  17,  17,  18,  20,  33,  49,  51, 144,
     14,   7,  33,  81,  17,  65,  17,  67,  49,  49,  33,  34,
    240,  16,  13,   7,   3,  65,  18,  51,  65,  33,  49,  33,
     51, 240,  48,  12,   7,  34,  65,  17,  49,  97, 113,  17,
     82, 240,  32,  14,   7,   3,  65,  33,  49,  49,  33,  49,
     33,  33,  51, 240,  48,  11,   7,   4,  49, 100,  49,  33,
     49, 100, 240,  32,  11,   7,   4,  49,  99,  65,  17,  65,
     97, 240,  80,  13,   7,  35,  49,  33,  33,  97,  34,  34,
     33,  67, 240,  16,  15,   7,   1,  49,  33,  49,  37,  33,
     49,  33,  49,  33,  49, 240,  16,  10,   7,   1,  97,  97,
     97,  97,  97, 240,  80,  11,   7,  34,  97,  97,  97,  49,
     33,  51, 240,  48,  14,   7,   1,  18,  49,  17,  66,  82,
     81,  17,  65,  33, 240,  32,  11,   7,   1,  97,  97,  97,
     97,  17,  67, 240,  48,  17,   7,   2,  49,  18,  34,  18,
     34,  17,  18,  17,  17,  18,  17,  19,  18, 240,  18,   7,
      1,  34,  34,  33,  33,  17,  17,  33,  17,  17,  33,  34,
     34,  33, 240,  16,  14,   7,  33,  81,  17,  49,  49,  33,
     49,  49,  17,  81, 240,  48,  12,   7,   3,  65,  33,  49,
     33,  51,  65,  97, 240,  80,  14,   7,  33,  81,  17,  49,
     49,  33,  49,  49,  17,  81,  99, 144,  14,   7,   2,  81,
     17,  65,  17,  66,  81,  17,  65,  33, 240,  32,  12,   7,
     19,  49,  33,  50, 114,  49,  33,  51, 240,  48,  12,   7,
      5,  33,  17,  17,  65,  97,  97,  83, 240,  32,  15,   7,
      1,  49,  33,  49,  33,  49,  33,  49,  33,  49,  51, 240,
     32,  14,   7,   2,  33,  33,  49,  49,  17,  65,  17,  82,
     81, 240,  48,  18,   7,   2,  33,  17,  17,  33,  49,  18,
     17,  17,  18,  17,  34,  18,  33,  33, 240,  14,   7,   2,
     18,  49,  17,  81,  97,  81,  17,  50,  18, 240,  16,  13,
      7,   2,  18,  49,  33,  49,  17,  81,  97,  83, 240,  32,
     12,   7,   4,  49,  33,  81,  81,  81,  33,  52, 240,  32,
     10,   7,   2,  81,  97,  97,  97,  97,  98, 192,  10,   7,
      1, 113,  97, 113,  97, 113,  97, 160,  10,   7,   2,  97,
     97,  97,  97,  97,  82, 192,   8,   7,  19,  49,  49, 240,
    240, 224,   6,   7,   0,   6,  20,  48,   6,   7,   1,  97,
      0,   6,   9,   7, 241,  98,  65,  17,  82, 240,  48,  12,
      7,   1,  97,  99,  65,  33,  49,  33,  51, 240,  48,   9,
      7, 241,  81,  17,  65, 114, 240,  48,  12,   7,  34,  97,
     67,  49,  33,  49,  33,  67, 240,  32,   8,   7, 241,  83,
     65, 114, 240,  48,  10,   7,  17,  81,  98,  81,  97,  97,
    240,  80,  10,   7, 241,  81,  17,  81,  97,  83,  81,  80,
     13,   7,   1,  97,  99,  65,  33,  49,  33,  49,  18, 240,
     32,   9,   7,   1, 209,  97,  97,  97, 240,  80,  10,   7,
     33, 209,  97,  97,  97,  97,  66,  80,  12,   7,   1,  97,
     97,  17,  66,  82,  81,  17, 240,  48,  10,   7,   1,  97,
     97,  97,  97,  97, 240,  80,  14,   7, 229,  33,  17,  17,
     33,  17,  17,  33,  17,  17, 240,  16,  11,   7, 228,  49,
     33,  49,  33,  49,  18, 240,  32,  10,   7, 241,  81,  17,
     65,  17,  81, 240,  64,  11,   7, 227,  65,  33,  49,  33,
     51,  65,  98,  80,  11,   7, 243,  49,  33,  49,  33,  67,
     97,  82,  48,   8,   7, 226,  81,  97,  97, 240,  80,   8,
      7, 241,  81,  98,  81, 240,  80,   9,   7, 113,  98,  81,
     97,  98, 240,  64,  11,   7, 225,  18,  49,  33,  49,  33,
     67, 240,  32,  10,   7, 225,  18,  49,  33,  66,  81, 240,
     64,  14,   7, 225,  33,  17,  17,  18,  17,  35,  17,  33,
     33, 240,  16,   8,   7, 228,  66,  82,  68, 240,  32,  11,
      7, 226,  17,  65,  17,  66,  81,  97,  81,  96,   9,   7,
    227,  81,  81,  17,  67, 240,  48,  10,   7,  33,  81,  97,
     81, 113,  97, 113, 176,  11,   7,   1,  97,  97,  97,  97,
     97,  97,  97,  96,  10,   7,   1, 113,  97, 113,  81,  97,
     81, 208,   9,   7, 130,  33,  17,  34, 240, 240, 112,
};

const tFont g_sFontcharter5x10 =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    7,

    //
    // The height of the font.
    //
    8,

    //
    // The baseline of the font.
    //
    6,

    //
    // The offset to each character in the font.
    //
    {
           0,    4,   13,   22,   35,   47,   66,   80,
          86,   96,  106,  116,  125,  132,  138,  145,
         155,  169,  179,  191,  202,  214,  225,  237,
         248,  261,  273,  280,  287,  296,  302,  310,
         320,  336,  350,  363,  375,  389,  400,  411,
         424,  439,  449,  460,  474,  485,  502,  520,
         534,  546,  560,  574,  586,  598,  613,  627,
         645,  659,  672,  684,  694,  704,  714,  722,
         728,  734,  743,  755,  764,  776,  784,  794,
         804,  817,  826,  836,  848,  858,  872,  883,
         893,  904,  915,  923,  931,  940,  951,  961,
         975,  983,  994, 1003, 1013, 1024, 1034,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8charter5x10Data
};
