//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidasans
//     Size: 5x9
//     Bold: yes
//     Italic: no
//     Memory usage: 1184 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidasans5x9bData[981] =
{
      5,   6,   0,   6,  96,   9,   6,  97,  81,  81,  81, 177,
    240,  32,   9,   6,  98,  17,  33,  33, 240, 240, 128,  10,
      6, 131,  50,  37,  33,  17,  37,  19, 240,  13,   6,  33,
     68,  19,  66,  83,  49,  17,  20,  65,  81,  48,  14,   6,
    113,  50,  17,  17,  17,  19,  35,  65,  18,  17,  34, 192,
     12,   6, 116,  33,  33,  35,  18,  18,  18,  34,  37, 192,
      8,   6,  98,  66,  65, 240, 240,  80,  11,   6, 113,  81,
     65,  81,  81,  81,  97,  81,  64,  11,   6,  97,  81,  97,
     81,  81,  81,  65,  81,  80,   8,   6,  99,  49,  17, 240,
    240, 144,   8,   6, 225,  81,  53,  49,  81, 240,   8,   6,
    240, 240,  98,  81,  65,  80,   6,   6, 240, 146, 240, 208,
      7,   6, 240, 240,  98, 240,  16,  11,   6, 161,  65,  81,
     65,  81,  65,  81,  65,  80,  13,   6, 115,  33,  49,  17,
     49,  17,  49,  17,  49,  35, 224,  10,   6,  98,  81,  81,
     81,  81,  81, 240,  16,   9,   6,  99,  97,  81,  65,  50,
     68, 224,   9,   6,  99,  97,  50,  97,  81,  35, 240,  10,
      6, 130,  51,  34,  17,  37,  65,  81, 224,   9,   6, 100,
     33,  83,  97,  81,  35, 240,  11,   6, 116,  17,  84,  33,
     49,  17,  49,  35, 224,  10,   6, 100,  66,  65,  65,  81,
     66, 240,  16,  12,   6, 115,  33,  49,  35,  33,  34,  17,
     49,  35, 224,  11,   6, 115,  33,  49,  17,  49,  36,  81,
     20, 224,   8,   6, 240,  49, 240,  33, 240,  32,   9,   6,
    240,  49, 240,  33,  81,  81,  80,   9,   6, 240,  17,  50,
     34,  98,  97, 208,   7,   6, 240,  53, 117, 240,  64,   9,
      6, 193,  98,  98,  34,  49, 240,  32,   9,   6, 100,  81,
     81,  50, 161, 240,  16,  13,   6, 132,  17,  35,  34,  17,
     18,  33,  17,  18,  19, 224,  12,   6, 130,  66,  49,  18,
     36,  18,  33,  17,  50, 192,  12,   6, 100,  33,  33,  35,
     49,  18,  33,  33,  36, 224,   9,   6, 116,  18,  65,  81,
     82,  84, 208,   9,   6, 101,  17,  51,  66,  66,  70, 208,
      9,   6, 100,  33,  83,  49,  81,  84, 224,  10,   6,  99,
     49,  81,  83,  49,  81, 240,  32,  11,   6, 116,  18,  65,
     81,  49,  18,  33,  36, 208,  14,   6,  97,  49,  17,  49,
     21,  17,  49,  17,  49,  17,  49, 208,  10,   6,  97,  81,
     81,  81,  81,  81, 240,  32,  11,   6, 129,  81,  81,  81,
     81,  81,  81,  51,  48,  14,   6,  97,  34,  17,  17,  50,
     65,  17,  49,  17,  49,  34, 208,   9,   6,  97,  81,  81,
     81,  81,  84, 224,  13,   6,  98,  36,  37,  19,  18,  18,
     18,  18,  33,  17, 192,  17,   6,  97,  49,  18,  33,  17,
     17,  17,  17,  17,  17,  17,  34,  17,  49, 208,  10,   6,
    116,  18,  35,  66,  67,  34,  20, 208,  12,   6, 100,  33,
     33,  33,  33,  35,  49,  81, 240,  32,  11,   6, 116,  18,
     35,  66,  67,  34,  20,  82,  81,  13,   6, 100,  33,  33,
     33,  33,  35,  49,  17,  49,  34, 208,   9,   6, 115,  34,
     66,  98,  81,  35, 240,   9,   6, 101,  49,  81,  81,  81,
     81, 240,  14,   6,  97,  49,  17,  49,  17,  49,  17,  49,
     17,  49,  35, 224,  13,   6,  98,  49,  17,  33,  33,  33,
     49,  17,  50,  66, 224,  15,   6,  97,  33,  49,  17,  49,
     19,  18,  18,  18,  18,  18,  18, 192,  13,   6,  98,  18,
     33,  17,  65,  66,  65,  17,  33,  34, 208,  11,   6,  98,
     33,  33,  17,  66,  65,  81,  81, 240,   9,   6, 100,  66,
     65,  65,  66,  68, 224,  11,   6,  98,  65,  81,  81,  81,
     81,  81,  82,  64,  10,   6,  97,  97,  81,  97,  81,  97,
     81,  97,  11,   6,  98,  81,  81,  81,  81,  81,  81,  66,
     64,  12,   6, 129,  81,  65,  17,  49,  17,  33,  49, 240,
     64,   6,   6,   0,   6,   4,  32,   6,   6,  98,   0,   5,
     96,   8,   6, 240,  52,  81,  36,  36, 224,  11,   6,  97,
     81,  84,  33,  49,  17,  49,  20, 224,   8,   6, 240,  66,
     49,  81,  98, 240,  11,   6, 161,  81,  36,  17,  49,  17,
     49,  36, 208,   8,   6, 240,  67,  36,  34,  83, 224,  10,
      6, 114,  65,  67,  65,  81,  81, 240,  16,  12,   6, 240,
     68,  17,  49,  17,  49,  36,  66,  20,  32,  12,   6,  97,
     81,  84,  33,  33,  33,  33,  33,  33, 224,   9,   6,  97,
    177,  81,  81,  81, 240,  32,  10,   6, 113, 177,  81,  81,
     81,  81,  66,  64,  11,   6,  97,  81,  81,  18,  35,  51,
     49,  18, 224,  10,   6,  97,  81,  81,  81,  81,  81, 240,
     32,  10,   6, 240,  55,  33,  33,  33,  33,  33, 224,  11,
      6, 240,  52,  33,  33,  33,  33,  33,  33, 224,  10,   6,
    240,  67,  33,  49,  17,  49,  35, 224,  12,   6, 240,  52,
     33,  49,  17,  49,  20,  33,  81,  80,  11,   6, 240,  68,
     17,  49,  17,  49,  36,  81,  81,   9,   6, 240,  51,  49,
     81,  81, 240,  32,   8,   6, 240,  52,  34,  98,  36, 224,
     10,   6,  97,  81,  82,  65,  81,  82, 240,  16,  11,   6,
    240,  49,  33,  33,  33,  33,  33,  36, 224,  11,   6, 240,
     50,  33,  33,  17,  49,  17,  66, 224,  12,   6, 240,  49,
     34,  33,  19,  18,  18,  18,  18, 192,  10,   6, 240,  50,
     17,  50,  66,  49,  18, 224,  13,   6, 240,  50,  33,  33,
     17,  49,  17,  65,  81,  65,  64,   8,   6, 240,  52,  65,
     65,  68, 224,  11,   6, 113,  81,  81,  81,  66,  81,  81,
     81,  64,  11,   6,  97,  81,  81,  81,  81,  81,  81,  81,
     80,  11,   6,  97,  81,  81,  81,  82,  65,  81,  81,  80,
      9,   6, 240, 147,  17,  17,  19, 240,  64,
};

const tFont g_sFontlucidasans5x9b =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    6,

    //
    // The height of the font.
    //
    9,

    //
    // The baseline of the font.
    //
    7,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   14,   23,   33,   46,   60,   72,
          80,   91,  102,  110,  118,  126,  132,  139,
         150,  163,  173,  182,  191,  201,  210,  221,
         231,  243,  254,  262,  271,  280,  287,  296,
         305,  318,  330,  342,  351,  360,  369,  379,
         390,  404,  414,  425,  439,  448,  461,  478,
         488,  500,  511,  524,  533,  542,  556,  569,
         584,  597,  608,  617,  628,  638,  649,  661,
         667,  673,  681,  692,  700,  711,  719,  729,
         741,  753,  762,  772,  783,  793,  803,  814,
         824,  836,  847,  856,  864,  874,  885,  896,
         908,  918,  931,  939,  950,  961,  972,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidasans5x9bData
};
