//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidatypewriter
//     Size: 5x10
//     Bold: no
//     Italic: no
//     Memory usage: 1140 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidatypewriter5x10Data[939] =
{
      5,   5, 240, 240, 240,   8,   5,  81,  65,  65,  65, 145,
    224,   9,   5,  81,  17,  33,  17, 240, 240,  32,  12,   5,
     97,  17,  20,  34,  36,  17,  17,  33,  17, 192,  10,   5,
     83,  34,  50,  66,  50,  35,  49, 128,  11,   5,  82,  17,
     19,  35,  51,  35,  17,  18, 176,  12,   5,  98,  50,  50,
     33,  18,  17,  18,  34,  81,  96,   7,   5,  81,  65, 240,
    240,  64,  11,   5,  98,  49,  49,  65,  65,  65,  81,  81,
     32,  11,   5,  81,  81,  81,  65,  65,  65,  49,  49,  64,
      7,   5,  97,  52,  20, 240, 176,   8,   5, 240,  33,  37,
     33,  65, 192,   7,   5, 240, 241,  65,  65,  64,   6,   5,
    240,  84, 240,  96,   5,   5, 240, 241, 224,  11,   5, 129,
     50,  49,  65,  49,  65,  50,  49,  64,  13,   5,  98,  33,
     33,  17,  33,  17,  33,  17,  33,  34, 192,   9,   5,  83,
     65,  65,  65,  65,  37, 160,   9,   5,  83,  65,  65,  49,
     49,  67, 192,   9,   5,  83,  65,  34,  81,  65,  34, 208,
     10,   5, 113,  50,  50,  33,  17,  36,  49, 192,   9,   5,
     83,  33,  66,  81,  65,  34, 208,  11,   5,  99,  17,  67,
     33,  33,  17,  33,  34, 192,   9,   5,  83,  65,  49,  65,
     49,  65, 224,  11,   5,  99,  17,  33,  34,  36,  17,  33,
     34, 192,  11,   5,  98,  33,  33,  17,  33,  35,  65,  19,
    192,   5,   5, 241, 225, 224,   7,   5, 241, 225,  65,  65,
     64,   8,   5, 240,  34,  19,  35,  66, 176,   7,   5, 240,
     84,  20, 240,  16,   7,   5, 242,  67,  35,  18, 208,   9,
      5,  84,  17,  33,  50,  33, 145, 208,   9,   5,  98,  35,
     35,  35,  35,  49, 208,  11,   5, 113,  51,  33,  17,  35,
     17,  50,  49, 160,  12,   5,  84,  17,  33,  19,  33,  33,
     17,  33,  20, 176,   9,   5,  99,  18,  49,  65,  66,  67,
    176,  13,   5,  83,  33,  33,  17,  33,  17,  33,  17,  33,
     19, 192,   9,   5,  84,  17,  67,  33,  65,  68, 176,   9,
      5,  84,  17,  65,  68,  17,  65, 224,  11,   5,  99,  18,
     49,  65,  33,  18,  17,  35, 176,  14,   5,  81,  33,  17,
     33,  20,  17,  33,  17,  33,  17,  33, 176,   9,   5,  83,
     49,  65,  65,  65,  51, 192,   9,   5,  83,  65,  65,  65,
     65,  35, 192,  13,   5,  81,  18,  17,  17,  34,  50,  49,
     17,  33,  33, 176,   9,   5,  81,  65,  65,  65,  65,  68,
    176,  10,   5,  81,  33,  20,  20,  20,  20,  20, 176,  15,
      5,  81,  33,  18,  17,  18,  17,  17,  18,  17,  18,  17,
     33, 176,  13,   5,  98,  33,  33,  17,  33,  17,  33,  17,
     33,  34, 192,  11,   5,  84,  17,  33,  17,  33,  19,  33,
     65, 224,  14,   5,  98,  33,  33,  17,  33,  17,  33,  17,
     33,  35,  49,  81,  13,   5,  83,  33,  17,  33,  17,  34,
     49,  17,  33,  33, 176,   9,   5,  83,  33,  66,  82,  65,
     19, 192,   9,   5,  85,  33,  65,  65,  65,  65, 192,  14,
      5,  81,  33,  17,  33,  17,  33,  17,  33,  17,  33,  20,
    176,  13,   5,  81,  50,  49,  17,  17,  33,  17,  33,  17,
     49, 192,  15,   5,  81,  17,  18,  17,  18,  17,  18,  17,
     20,  17,  17,  17, 176,  13,   5,  82,  33,  17,  17,  49,
     66,  33,  17,  17,  49, 160,  12,   5,  81,  49,  17,  17,
     33,  17,  49,  65,  65, 192,   9,   5,  84,  50,  49,  49,
     50,  52, 176,  11,   5,  83,  33,  65,  65,  65,  65,  65,
     67,  32,  10,   5,  81,  66,  65,  65,  81,  65,  66,  65,
     11,   5,  83,  65,  65,  65,  65,  65,  65,  35,  32,  12,
      5,  33,  65,  50,  50,  33,  33,  17,  33, 240,  16,   6,
      5, 240, 240,  85,  80,   6,   5,  82, 240, 240, 128,   9,
      5, 243,  35,  33,  17,  34,  17, 176,  11,   5,  81,  65,
     67,  33,  33,  17,  33,  19, 192,   8,   5, 240,  19,  17,
     65,  83, 176,  11,   5, 129,  65,  35,  17,  33,  17,  33,
     20, 176,   8,   5, 240,  19,  20,  17,  83, 176,   9,   5,
     99,  33,  52,  33,  65,  65, 208,  11,   5, 240,  19,  17,
     33,  17,  33,  20,  65,  20,  12,   5,  81,  65,  67,  33,
     17,  33,  17,  33,  17, 192,   8,   5, 113, 115,  65,  65,
     65, 192,  10,   5, 113, 115,  65,  65,  65,  65,  35,  32,
     11,   5,  81,  65,  65,  18,  19,  35,  33,  18, 176,   9,
      5,  83,  65,  65,  65,  65,  65, 192,  10,   5, 246,  17,
     18,  17,  18,  17,  17, 160,  10,   5, 243,  33,  17,  33,
     17,  33,  17, 192,  10,   5, 240,  18,  33,  33,  17,  33,
     34, 192,  11,   5, 243,  33,  33,  17,  33,  19,  33,  65,
     64,  11,   5, 240,  19,  17,  33,  17,  33,  20,  65,  65,
      8,   5, 243,  33,  17,  33,  65, 224,   7,   5, 243,  34,
     81,  35, 192,   9,   5,  97,  65,  52,  33,  65,  67, 176,
     10,   5, 241,  17,  33,  17,  33,  17,  35, 192,   9,   5,
    241,  33,  17,  33,  34,  50, 192,  12,   5, 241,  17,  18,
     17,  17,  17,  18,  17,  17, 176,   9,   5, 241,  18,  34,
     50,  33,  33, 176,  10,   5, 241,  33,  20,  34,  50,  49,
     50,  48,   7,   5, 244,  49,  49,  52, 176,  11,   5,  98,
     49,  65,  65,  50,  65,  65,  66,  32,  11,   5,  81,  65,
     65,  65,  65,  65,  65,  65,  64,  11,   5,  82,  65,  65,
     65,  66,  49,  65,  50,  48,   9,   5, 240,  82,  17,  17,
     18, 240,  16,
};

const tFont g_sFontlucidatypewriter5x10 =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    5,

    //
    // The height of the font.
    //
    9,

    //
    // The baseline of the font.
    //
    7,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   13,   22,   34,   44,   55,   67,
          74,   85,   96,  103,  111,  118,  124,  129,
         140,  153,  162,  171,  180,  190,  199,  210,
         219,  230,  241,  246,  253,  261,  268,  275,
         284,  293,  304,  316,  325,  338,  347,  356,
         367,  381,  390,  399,  412,  421,  431,  446,
         459,  470,  484,  497,  506,  515,  529,  542,
         557,  570,  582,  591,  602,  612,  623,  635,
         641,  647,  656,  667,  675,  686,  694,  703,
         714,  726,  734,  744,  755,  764,  774,  784,
         794,  805,  816,  824,  831,  840,  850,  859,
         871,  880,  890,  897,  908,  919,  930,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidatypewriter5x10Data
};
