//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidasans
//     Size: 6x11
//     Bold: no
//     Italic: no
//     Memory usage: 1372 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidasans6x11Data[1172] =
{
      5,   6,   0,   8,  32,  10,   6, 193,  81,  81,  81, 177,
     81, 240,  32,  11,   6,  97,  17,  49,  17,  49,  17, 240,
    240, 240,  17,   6, 209,  17,  49,  17,  34,  18,  33,  17,
     34,  18,  33,  17,  49,  17, 224,  16,   6, 129,  68,  17,
     17,  49,  17,  67,  65,  17,  49,  17,  20,  65, 144,  15,
      6, 209,  65,  17,  33,  17,  33,  65,  65,  33,  17,  33,
     97, 192,  14,   6, 210,  49,  33,  50,  66,  34,  33,  18,
     34,  34,  33, 192,   8,   6,  97,  81,  81,   0,   5, 112,
     12,   6, 113,  81,  65,  81,  81,  81,  81,  97,  81, 160,
     12,   6,  97,  81,  97,  81,  81,  81,  81,  65,  81, 176,
     10,   6, 193,  17,  65,  65,  17, 240, 240, 144,  10,   6,
    240,  81,  81,  53,  49,  81, 240,  96,   9,   6, 240, 240,
    209,  81,  81,  65,  80,   7,   6, 240, 242, 240, 240,  64,
      8,   6, 240, 240, 193,  81, 240,  32,  12,   6, 161,  81,
     65,  81,  65,  65,  81,  65,  81, 176,  15,   6, 210,  49,
     33,  33,  33,  33,  33,  33,  33,  33,  33,  50, 240,  10,
      6, 225,  51,  81,  81,  81,  81,  81, 240,  10,   6, 195,
     97,  81,  65,  65,  65,  84, 224,  10,   6, 195,  97,  81,
     50,  97,  81,  35, 240,  12,   6, 241,  66,  49,  17,  33,
     33,  37,  65,  81, 224,  10,   6, 196,  33,  81,  83,  97,
     81,  35, 240,  12,   6, 211,  33,  81,  83,  49,  33,  33,
     33,  50, 240,  11,   6, 196,  81,  65,  81,  65,  81,  81,
    240,  16,  14,   6, 210,  49,  33,  33,  33,  50,  49,  33,
     33,  33,  50, 240,  12,   6, 210,  49,  33,  33,  33,  51,
     81,  81,  35, 240,  10,   6, 240,  49,  81, 240,  33,  81,
    240,  32,  11,   6, 240,  65,  81, 240,  33,  81,  81,  65,
     80,  10,   6, 240,  98,  34,  49,  98,  98, 240,  64,   7,
      6, 240, 149, 117, 240, 160,  10,   6, 240,  50,  98,  97,
     50,  34, 240, 112,  10,   6, 195,  97,  81,  50, 161,  81,
    240,  16,  12,   6, 227,  33,  50,  36,  17,  34,  35,  17,
    100, 192,  14,   6, 225,  81,  65,  17,  49,  17,  37,  17,
     49,  17,  49, 208,  14,   6, 195,  49,  33,  33,  33,  35,
     49,  33,  33,  33,  35, 240,  10,   6, 227,  33,  65,  81,
     81,  97,  99, 208,  12,   6, 196,  33,  49,  17,  66,  66,
     66,  49,  20, 224,  10,   6, 196,  33,  81,  83,  49,  81,
     84, 224,  11,   6, 196,  33,  81,  83,  49,  81,  81, 240,
     32,  12,   6, 227,  33,  65,  81,  81,  49,  33,  33,  51,
    208,  16,   6, 193,  49,  17,  49,  17,  49,  21,  17,  49,
     17,  49,  17,  49, 208,  11,   6, 193,  81,  81,  81,  81,
     81,  81, 240,  32,  12,   6, 225,  81,  81,  81,  81,  81,
     81,  81,  50,  64,  16,   6, 193,  49,  17,  33,  33,  17,
     50,  65,  17,  49,  33,  33,  49, 208,  10,   6, 193,  81,
     81,  81,  81,  81,  84, 224,  16,   6, 194,  51,  50,  17,
     17,  17,  19,  17,  33,  33,  33,  33, 240,  32,  14,   6,
    193,  67,  50,  17,  34,  33,  18,  33,  18,  51,  65, 192,
     13,   6, 226,  49,  33,  17,  66,  66,  65,  17,  33,  50,
    224,  13,   6, 195,  49,  33,  33,  33,  35,  49,  81,  81,
    240,  32,  14,   6, 226,  49,  33,  17,  66,  66,  65,  17,
     33,  50,  97,  97,  15,   6, 195,  49,  33,  33,  33,  35,
     49,  17,  49,  33,  33,  49, 208,  10,   6, 211,  33,  81,
     98,  97,  81,  35, 240,  10,   6, 197,  49,  81,  81,  81,
     81,  81, 240,  16,   6, 193,  49,  17,  49,  17,  49,  17,
     49,  17,  49,  17,  49,  35, 224,  15,   6, 193,  49,  17,
     49,  17,  49,  33,  17,  49,  17,  65,  81, 240,  17,   6,
    193,  81,  33,  33,  33,  33,  17,  17,  33,  49,  17,  49,
     17,  49, 192,  16,   6, 193,  49,  17,  49,  33,  17,  65,
     65,  17,  33,  49,  17,  49, 208,  13,   6, 193,  49,  17,
     49,  33,  17,  65,  81,  81,  81, 240,  10,   6, 196,  81,
     65,  66,  65,  65,  84, 224,  12,   6,  98,  65,  81,  81,
     81,  81,  81,  81,  82, 160,  12,   6,  97,  81,  97,  81,
     97,  97,  81,  97,  81, 112,  12,   6,  98,  81,  81,  81,
     81,  81,  81,  81,  66, 160,  14,   6, 225,  81,  65,  17,
     49,  17,  33,  49,  17,  49, 240,  64,   6,   6,   0,   6,
    101, 112,   7,   6,   1,  97,   0,   7,  32,  13,   6, 240,
     66,  97,  51,  33,  33,  33,  33,  50,  17, 208,  16,   6,
     97,  81,  81,  17,  50,  17,  33,  33,  33,  33,  33,  33,
     35, 240,  10,   6, 240,  67,  33,  81,  81,  81,  99, 224,
     16,   6, 145,  81,  51,  33,  33,  33,  33,  33,  33,  33,
     18,  49,  17, 224,  11,   6, 240,  66,  49,  33,  36,  33,
     81,  99, 224,  12,   6, 130,  49,  68,  49,  81,  81,  81,
     81, 240,  16,  17,   6, 240,  67,  33,  33,  33,  33,  33,
     33,  33,  18,  49,  17,  81,  50,  48,  17,   6,  97,  81,
     81,  17,  50,  17,  33,  33,  33,  33,  33,  33,  33,  33,
    224,  11,   6,  97, 177,  81,  81,  81,  81,  81, 240,  32,
     12,   6, 113, 177,  81,  81,  81,  81,  81,  81,  65,  80,
     16,   6,  97,  81,  81,  33,  33,  17,  50,  65,  17,  49,
     33,  33,  49, 208,  12,   6,  97,  81,  81,  81,  81,  81,
     81,  81, 240,  32,  16,   6, 240,  49,  17,  35,  18,  17,
     33,  33,  33,  33,  33,  33,  33, 224,  16,   6, 240,  49,
     17,  50,  17,  33,  33,  33,  33,  33,  33,  33,  33, 224,
     14,   6, 240,  66,  49,  33,  33,  33,  33,  33,  33,  33,
     50, 240,  17,   6, 240,  49,  17,  50,  17,  33,  33,  33,
     33,  33,  33,  35,  49,  81,  80,  17,   6, 240,  67,  33,
     33,  33,  33,  33,  33,  33,  18,  49,  17,  81,  81,  32,
     12,   6, 240,  49,  17,  51,  49,  81,  81,  81, 240,  32,
     11,   6, 240,  66,  49,  82,  82,  81,  50, 240,  16,  10,
      6, 209,  68,  49,  81,  81,  81,  98, 224,  16,   6, 240,
     49,  33,  33,  33,  33,  33,  33,  33,  33,  18,  49,  17,
    224,  14,   6, 240,  49,  33,  33,  33,  33,  33,  33,  33,
     50,  66, 240,  16,   6, 240,  49,  81,  33,  33,  33,  33,
     17,  17,  33,  49,  17,  49, 192,  14,   6, 240,  49,  33,
     33,  33,  50,  66,  49,  33,  33,  33, 224,  16,   6, 240,
     49,  33,  33,  33,  33,  33,  33,  33,  50,  66,  65,  66,
     64,  10,   6, 240,  52,  81,  65,  65,  65,  84, 224,  12,
      6, 129,  65,  81,  81,  65,  97,  81,  81,  97, 144,  12,
      6,  97,  81,  81,  81,  81,  81,  81,  81,  81, 176,  12,
      6,  97,  97,  81,  81,  97,  65,  81,  81,  65, 176,   9,
      6, 240, 162,  34,  34, 240, 240,  16,
};

const tFont g_sFontlucidasans6x11 =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    6,

    //
    // The height of the font.
    //
    11,

    //
    // The baseline of the font.
    //
    9,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   15,   26,   43,   59,   74,   88,
          96,  108,  120,  130,  140,  149,  156,  164,
         176,  191,  201,  211,  221,  233,  243,  255,
         266,  280,  292,  302,  313,  323,  330,  340,
         350,  362,  376,  390,  400,  412,  422,  433,
         445,  461,  472,  484,  500,  510,  526,  540,
         553,  566,  580,  595,  605,  615,  631,  646,
         663,  679,  692,  702,  714,  726,  738,  752,
         758,  765,  778,  794,  804,  820,  831,  843,
         860,  877,  888,  900,  916,  928,  944,  960,
         974,  991, 1008, 1020, 1031, 1041, 1057, 1071,
        1087, 1101, 1117, 1127, 1139, 1151, 1163,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidasans6x11Data
};
