//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidatypewriter
//     Size: 6x11
//     Bold: no
//     Italic: no
//     Memory usage: 1396 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidatypewriter6x11Data[1196] =
{
      5,   6,   0,   8,  32,  10,   6, 193,  81,  81,  81, 177,
     81, 240,  32,  11,   6,  97,  17,  49,  17,  49,  17, 240,
    240, 240,  17,   6, 209,  17,  49,  17,  34,  18,  33,  17,
     34,  18,  33,  17,  49,  17, 224,  16,   6, 129,  68,  17,
     17,  49,  17,  67,  65,  17,  49,  17,  20,  65, 144,  16,
      6, 209,  50,  17,  17,  33,  17,  81,  65,  17,  33,  17,
     18,  49, 208,  15,   6, 210,  49,  33,  50,  66,  17,  17,
     33,  33,  33,  50,  17, 208,   8,   6,  97,  81,  81,   0,
      5, 112,  12,   6, 129,  65,  65,  81,  81,  81,  81,  97,
     97, 144,  12,   6,  97,  97,  97,  81,  81,  81,  81,  65,
     65, 176,  10,   6, 193,  17,  65,  65,  17, 240, 240, 144,
     10,   6, 240,  81,  81,  53,  49,  81, 240,  96,   9,   6,
    240, 240, 209,  81,  81,  65,  80,   7,   6, 240, 245, 240,
    240,  16,   8,   6, 240, 240, 193,  81, 240,  32,  12,   6,
    161,  81,  65,  81,  65,  65,  81,  65,  81, 176,  15,   6,
    211,  33,  49,  17,  49,  17,  49,  17,  49,  17,  49,  35,
    224,  11,   6, 225,  66,  49,  17,  81,  81,  81,  81, 240,
     11,   6, 211,  33,  49,  81,  50,  49,  65,  85, 208,  12,
      6, 211,  33,  49,  81,  50,  97,  17,  49,  35, 224,  13,
      6, 226,  49,  17,  49,  17,  33,  33,  37,  65,  81, 224,
     11,   6, 197,  17,  81,  84,  97,  17,  49,  35, 224,  13,
      6, 211,  33,  49,  17,  84,  33,  49,  17,  49,  35, 224,
     11,   6, 197,  81,  65,  65,  81,  65,  81, 240,  16,  14,
      6, 211,  33,  49,  17,  49,  35,  33,  49,  17,  49,  35,
    224,  13,   6, 211,  33,  49,  17,  49,  36,  81,  17,  49,
     35, 224,  10,   6, 240,  49,  81, 240,  33,  81, 240,  32,
     11,   6, 240,  65,  81, 240,  33,  81,  81,  65,  80,  10,
      6, 240,  81,  65,  65,  97,  97, 240,  96,   7,   6, 240,
    149, 117, 240, 160,  10,   6, 240,  49,  97,  97,  65,  65,
    240, 128,  10,   6, 211,  33,  49,  81,  50, 161,  81, 240,
     14,   6, 211,  33,  49,  17,  19,  17,  17,  17,  17,  21,
    100, 208,  14,   6, 210,  66,  49,  33,  33,  33,  36,  33,
     33,  33,  33, 224,  14,   6, 195,  49,  33,  33,  33,  35,
     49,  33,  33,  33,  35, 240,  11,   6, 227,  33,  33,  17,
     81,  81,  97,  99, 208,  15,   6, 195,  49,  33,  33,  49,
     17,  49,  17,  49,  17,  33,  35, 240,  10,   6, 196,  33,
     81,  83,  49,  81,  84, 224,  11,   6, 196,  33,  81,  83,
     49,  81,  81, 240,  32,  13,   6, 227,  33,  33,  17,  81,
     81,  49,  33,  33,  51, 208,  16,   6, 193,  33,  33,  33,
     33,  33,  36,  33,  33,  33,  33,  33,  33, 224,  10,   6,
    195,  65,  81,  81,  81,  81,  67, 240,  12,   6, 227,  65,
     81,  81,  81,  81,  81,  81,  35,  48,  16,   6, 193,  49,
     17,  33,  33,  17,  50,  65,  17,  49,  33,  33,  49, 208,
     10,   6, 193,  81,  81,  81,  81,  81,  84, 224,  19,   6,
    193,  49,  18,  18,  18,  18,  17,  17,  17,  17,  17,  17,
     17,  49,  17,  49, 208,  17,   6, 193,  33,  34,  17,  34,
     17,  33,  18,  33,  18,  33,  33,  33,  33, 224,  13,   6,
    226,  49,  33,  17,  66,  66,  65,  17,  33,  50, 224,  13,
      6, 195,  49,  33,  33,  33,  35,  49,  81,  81, 240,  32,
     14,   6, 226,  49,  33,  17,  66,  66,  65,  17,  33,  50,
     82,  82,  15,   6, 195,  49,  33,  33,  33,  35,  49,  17,
     49,  33,  33,  33, 224,  10,   6, 211,  33,  81,  98,  97,
     81,  35, 240,  10,   6, 197,  49,  81,  81,  81,  81,  81,
    240,  16,   6, 193,  33,  33,  33,  33,  33,  33,  33,  33,
     33,  33,  33,  50, 240,  14,   6, 193,  33,  33,  33,  33,
     33,  33,  33,  50,  66,  66, 240,  19,   6, 193,  49,  17,
     17,  17,  17,  17,  17,  17,  17,  17,  21,  33,  17,  49,
     17, 224,  14,   6, 193,  33,  33,  33,  50,  66,  66,  49,
     33,  33,  33, 224,  13,   6, 193,  49,  17,  49,  33,  17,
     65,  81,  81,  81, 240,  10,   6, 196,  81,  65,  66,  65,
     65,  84, 224,  12,   6,  99,  49,  81,  81,  81,  81,  81,
     81,  83, 144,  12,   6,  97,  81,  97,  81,  97,  97,  81,
     97,  81, 112,  12,   6,  99,  81,  81,  81,  81,  81,  81,
     81,  51, 144,  14,   6, 225,  81,  65,  17,  49,  17,  33,
     49,  17,  49, 240,  64,   6,   6,   0,   6, 102,  96,   7,
      6,   1,  97,   0,   7,  32,  13,   6, 240,  66,  97,  51,
     33,  33,  33,  18,  49,  17, 224,  16,   6,  97,  81,  81,
     17,  50,  17,  33,  33,  33,  33,  33,  33,  35, 240,  10,
      6, 240,  67,  33,  81,  81,  81,  99, 224,  16,   6, 145,
     81,  51,  33,  33,  33,  33,  33,  33,  33,  18,  49,  17,
    224,  11,   6, 240,  66,  49,  33,  36,  33,  81,  99, 224,
     12,   6, 131,  33,  68,  49,  81,  81,  81,  81, 240,  16,
     17,   6, 240,  67,  33,  33,  33,  33,  33,  33,  33,  18,
     49,  17,  81,  35,  48,  17,   6,  97,  81,  81,  17,  50,
     17,  33,  33,  33,  33,  33,  33,  33,  33, 224,  10,   6,
    129, 147,  81,  81,  81,  81,  81, 240,  12,   6, 145, 147,
     81,  81,  81,  81,  81,  81,  35,  48,  16,   6,  97,  81,
     81,  33,  33,  17,  50,  65,  17,  49,  33,  33,  49, 208,
     11,   6,  99,  81,  81,  81,  81,  81,  81,  81, 240,  21,
      6, 240,  50,  17,  33,  17,  17,  17,  17,  17,  17,  17,
     17,  17,  17,  17,  17,  17,  17, 208,  16,   6, 240,  49,
     17,  50,  17,  33,  33,  33,  33,  33,  33,  33,  33, 224,
     14,   6, 240,  66,  49,  33,  33,  33,  33,  33,  33,  33,
     50, 240,  17,   6, 240,  49,  17,  50,  17,  33,  33,  33,
     33,  33,  33,  35,  49,  81,  80,  17,   6, 240,  67,  33,
     33,  33,  33,  33,  33,  33,  18,  49,  17,  81,  81,  32,
     13,   6, 240,  49,  18,  34,  17,  33,  81,  81,  81, 240,
     32,  10,   6, 240,  67,  33,  82,  98,  81,  35, 240,  10,
      6, 209,  68,  49,  81,  81,  81,  98, 224,  16,   6, 240,
     49,  33,  33,  33,  33,  33,  33,  33,  33,  18,  49,  17,
    224,  14,   6, 240,  49,  33,  33,  33,  33,  33,  33,  33,
     50,  66, 240,  17,   6, 240,  49,  49,  17,  17,  17,  17,
     17,  17,  21,  33,  17,  49,  17, 224,  14,   6, 240,  49,
     49,  33,  17,  65,  81,  65,  17,  33,  49, 208,  15,   6,
    240,  49,  33,  33,  33,  33,  33,  50,  66,  65,  65,  81,
     80,  10,   6, 240,  52,  81,  65,  65,  65,  84, 224,  12,
      6, 146,  49,  81,  81,  50,  97,  81,  81,  98, 112,  12,
      6,  97,  81,  81,  81,  81,  81,  81,  81,  81, 176,  12,
      6,  98,  97,  81,  81,  98,  49,  81,  81,  50, 160,   9,
      6, 240, 162,  34,  34, 240, 240,  16,
};

const tFont g_sFontlucidatypewriter6x11 =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    6,

    //
    // The height of the font.
    //
    11,

    //
    // The baseline of the font.
    //
    9,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   15,   26,   43,   59,   75,   90,
          98,  110,  122,  132,  142,  151,  158,  166,
         178,  193,  204,  215,  227,  240,  251,  264,
         275,  289,  302,  312,  323,  333,  340,  350,
         360,  374,  388,  402,  413,  428,  438,  449,
         462,  478,  488,  500,  516,  526,  545,  562,
         575,  588,  602,  617,  627,  637,  653,  667,
         686,  700,  713,  723,  735,  747,  759,  773,
         779,  786,  799,  815,  825,  841,  852,  864,
         881,  898,  908,  920,  936,  947,  968,  984,
         998, 1015, 1032, 1045, 1055, 1065, 1081, 1095,
        1112, 1126, 1141, 1151, 1163, 1175, 1187,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidatypewriter6x11Data
};
