//*****************************************************************************
//
// Copyright 1988 Bitstream, Inc., Cambridge, Massachusetts, USA
// Bitstream and Charter are registered trademarks of Bitstream, Inc.
// 
// The names "Bitstream" and "Charter" are registered trademarks of
// Bitstream, Inc.  Permission to use these trademarks is hereby
// granted only in association with the images described in this file.
// 
// Permission to use, copy, modify, and distribute this software and
// its documentation for any purpose and without fee is hereby
// granted, provided that the above copyright notice appear in all
// copies and that both that copyright notice and this permission
// notice appear in supporting documentation, and that the name of
// Bitstream not be used in advertising or publicity pertaining to
// distribution of the software without specific, written prior
// permission.  Bitstream makes no representations about the
// suitability of this software for any purpose.  It is provided "as
// is" without express or implied warranty.
// 
// BITSTREAM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN
// NO EVENT SHALL BITSTREAM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
// OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
// NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
// CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
// 
// Copyright (c) 1987, 1994 Digital Equipment Corporation
// 
// The X Consortium, and any party obtaining a copy of these files from
// the X Consortium, directly or indirectly, is granted, free of charge, a
// full and unrestricted irrevocable, world-wide, paid up, royalty-free,
// nonexclusive right and license to deal in this software and
// documentation files (the "Software"), including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons who receive
// copies from any such party to do so.  This license includes without
// limitation a license to do the foregoing actions under any patents of
// the party supplying this software to the X Consortium.
// 
// Digital Equipment Corporation make no representations about the
// suitability of this software for any purpose.  It is provided "as
// is" without express or implied warranty.
// 
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Charter
//     Size: 6x13
//     Bold: no
//     Italic: yes
//     Memory usage: 1460 bytes
//
//*****************************************************************************

static const uint8_t g_pui8charter6x13iData[1259] =
{
      4,   8,   0,  10,  10,   8, 161,  98,  97, 113, 113, 226,
    240, 112,  11,   8,   1,  17,  81,  17,  81,  17,   0,   7,
     80,  16,   8, 177,  17,  81,  17,  54,  49,  17,  55,  33,
     17,  81,  17, 240,  80,  15,   8,  49,  99,  65,  18,  66,
    114,  97,  17,  49,  18,  82,  97, 224,  26,   8,  33,  65,
     17,  17,  33,  17,  33,  17,  33,  17,  17,  18,  18,  17,
     17,  65,  17,  65,  33,  17,  17,  65, 240,  32,  18,   8,
    162,  81,  33,  65,  17,  82,  33,  33,  33,  17,  33,  34,
     66,  33, 240,  48,   8,   8,   1, 113, 113,   0,   7, 112,
     12,   8,  34,  81, 113, 113,  97, 113, 113, 113, 129, 224,
     12,   8,  33, 129, 113, 113, 113, 113,  97, 113,  82, 224,
     11,   8,  33,  81,  18,  82,  81,  17,   0,   6,  80,  11,
      8, 177, 113, 113,  71,  65, 113, 113, 240,  80,   7,   8,
      0,   7,  17,  98, 224,   8,   8, 240, 240, 162, 240, 240,
    128,   7,   8,   0,   7,   1, 240, 128,  11,   8, 225,  97,
     97,  97, 113,  97,  97,  97, 240,  16,   8, 162,  81,  33,
     49,  49,  49,  49,  49,  49,  49,  33,  82, 240,  96,  11,
      8, 161,  98, 113, 113,  97, 113,  99, 240,  96,  13,   8,
    162,  81,  33, 113,  97,  97,  97,  33,  52, 240,  80,  13,
      8, 163,  65,  49,  98,  66, 130,  33,  49,  67, 240,  80,
     13,   8, 193,  98,  81,  17,  65,  33,  54,  81, 113, 240,
     80,  12,   8, 164,  49, 115, 129, 113,  49,  33,  67, 240,
     96,  16,   8,  50,  81,  97,  97,  18,  66,  33,  49,  49,
     49,  33,  82, 240,  96,  12,   8, 149,  49,  49,  97,  97,
     97, 113,  82, 240, 112,  15,   8, 162,  81,  33,  65,  33,
     67,  65,  49,  49,  33,  82, 240,  96,  14,   8, 162,  81,
     33,  49,  49,  49,  34,  67,  98,  66, 240, 112,   8,   8,
    240, 161, 240, 241, 240, 128,   8,   8, 240, 162, 240, 241,
     98, 224,  10,   8, 240,  82,  51,  65, 131, 130, 240, 176,
      8,   8, 240, 150, 166, 240, 240,  64,  10,   8, 240,  18,
    131, 129,  67,  50, 240, 240,  11,   8, 146,  81,  33, 113,
     82,  97, 225, 240, 128,  22,   8,  52,  34,  65,  17,  35,
     17,  33,  17,  33,  17,  33,  33,  17,  33,  18,  36,  33,
     66,  36, 160,  16,   8, 193,  97,  17,  81,  17,  65,  33,
     68,  49,  49,  34,  50, 240,  32,  15,   8, 148,  81,  33,
     65,  18,  52,  65,  49,  49,  33,  52, 240,  80,  13,   8,
    179,  50,  33,  33, 113, 113, 129,  33,  82, 240,  80,  16,
      8, 148,  81,  33,  65,  49,  33,  65,  33,  49,  49,  34,
     36, 240,  80,  15,   8, 149,  65,  33,  65,  17,  68,  65,
     33,  65,  49,  37, 240,  64,  14,   8, 149,  65,  33,  65,
     17,  68,  65,  33,  65,  99, 240,  96,  15,   8, 180,  34,
     49,  17, 113,  51,  17,  65,  49,  49,  67, 240,  64,  17,
      8, 147,  19,  33,  49,  49,  49,  38,  33,  49,  49,  49,
     35,  19, 240,  32,  11,   8, 147,  97, 113, 113,  97, 113,
     99, 240,  96,  12,   8, 178,  97, 113, 113, 113,  65,  17,
     82, 240, 112,  16,   8, 147,  18,  49,  33,  67,  67,  81,
     17,  81,  33,  50,  34, 240,  48,  12,   8, 147,  97, 113,
     97, 113, 113,  33,  53, 240,  64,  24,   8, 146,  65,  33,
     50,  17,  17,  34,  17,  17,  17,  17,  17,  18,  33,  17,
     18,  17,  18,  17,  34, 240,  16,  21,   8, 146,  50,  34,
     33,  33,  17,  33,  33,  18,  17,  33,  33,  17,  33,  34,
     34,  49, 240,  48,  16,   8, 178,  66,  33,  34,  65,  17,
     81,  17,  81,  33,  34,  66, 240,  80,  14,   8, 148,  81,
     33,  65,  33,  49,  33,  67,  81,  98, 240, 112,  16,   8,
    178,  66,  33,  34,  65,  17,  81,  17,  81,  33,  49,  67,
    115, 144,  16,   8, 148,  81,  33,  65,  18,  51,  81,  33,
     65,  33,  51,  34, 240,  32,  13,   8, 164,  49,  49,  49,
    130, 129,  49,  49,  67, 240,  80,  13,   8, 134,  33,  17,
     33,  65, 113, 113, 113,  98, 240,  96,  17,   8, 130,  34,
     49,  33,  65,  33,  49,  49,  49,  49,  49,  33,  82, 240,
     96,  17,   8, 130,  50,  33,  49,  49,  49,  49,  33,  65,
     17,  81,  17,  97, 240,  96,  22,   8, 130,  33,  33,  17,
     33,  33,  17,  18,  33,  17,  18,  17,  34,  34,  34,  33,
     49,  49, 240,  48,  16,   8, 147,  18,  49,  33,  82,  97,
     97,  17,  65,  33,  50,  34, 240,  48,  14,   8, 131,  19,
     33,  49,  49,  33,  82,  97, 113,  99, 240,  80,  13,   8,
    149,  49,  33,  97, 113,  97,  97,  33,  53, 240,  64,  11,
      8, 162,  81, 113, 113, 113,  97, 113, 114, 224,  11,   8,
    129, 129, 113, 129, 113, 129, 113, 129, 176,  11,   8, 162,
    113, 113,  97, 113, 113, 113,  82, 224,  10,   8,  34,  81,
     33,  49,  65,   0,   7,  32,   6,   8,   0,   9,   5,  48,
      8,   8,  17,  97, 114,   0,   7,  96,  13,   8, 240, 179,
     65,  33,  49,  49,  49,  33,  84, 240,  64,  15,   8,   2,
    113, 113, 115,  81,  33,  49,  49,  49,  33,  82, 240,  96,
     12,   8, 240, 178,  81,  17,  65, 113,  33,  82, 240,  96,
     16,   8,  65, 113, 113,  83,  65,  33,  49,  49,  49,  33,
     82,  17, 240,  64,  11,   8, 240, 177,  99,  66,  97,  33,
     82, 240,  96,  14,   8,  66,  81,  17,  81,  99,  97,  97,
    113, 113, 113,  82,  96,  15,   8, 240, 178,  17,  49,  33,
     82,  97,  82,  18,  49,  49,  67,  64,  17,   8,  18, 113,
     97, 113,  18,  66,  17,  65,  33,  65,  17,  65,  50, 240,
     48,  11,   8,  17, 240, 114,  97, 113, 113, 114, 240, 112,
     12,   8,  49, 240, 114, 113,  97, 113, 113, 113,  82,  96,
     15,   8,  18,  97, 113, 113,  33,  67,  82,  81,  33,  65,
     34, 240,  64,  12,   8,   2, 113, 113, 113,  97, 113, 113,
    114, 240, 112,  19,   8, 240, 148,  18,  33,  18,  17,  17,
     33,  33,  17,  33,  33,  17,  33,  34, 240,  16,  15,   8,
    240, 146,  18,  66,  17,  65,  33,  49,  33,  65,  35, 240,
     48,  13,   8, 240, 177,  97,  17,  65,  33,  65,  17,  97,
    240, 112,  14,   8, 240, 165,  65,  33,  49,  49,  49,  33,
     67,  81,  99,  80,  14,   8, 240, 179,  65,  33,  49,  49,
     49,  33,  83, 113,  99,  48,  11,   8, 240, 148,  81,  17,
     81,  97, 113, 240, 128,  11,   8, 240, 178,  81, 129,  81,
     33,  82, 240,  96,  11,   8, 240,  33,  99,  81, 113, 113,
    114, 240, 112,  14,   8, 240, 146,  33,  65,  33,  49,  33,
     65,  33,  69, 240,  64,  14,   8, 240, 146,  33,  65,  33,
     65,  17,  81,  17,  82, 240,  96,  17,   8, 240, 146,  17,
     33,  33,  17,  33,  35,  33,  34,  18,  49,  33, 240,  64,
     13,   8, 240, 162,  18,  66,  98,  81,  17,  66,  18, 240,
     64,  14,   8, 240, 162,  33,  65,  17,  81,  17,  82,  98,
     97,  82,  96,  12,   8, 240, 164,  65,  17,  97,  97,  18,
     52, 240,  80,  11,   8, 177,  97, 113,  82, 129, 113, 113,
    129, 192,  13,   8,   1, 113, 113, 113, 113, 113, 113, 113,
    113, 113, 112,  11,   8, 129, 129, 113, 130,  81, 113, 113,
     97, 240,   9,   8, 146,  33,  33,  34,   0,   7,  48,
};

const tFont g_sFontcharter6x13i =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    8,

    //
    // The height of the font.
    //
    10,

    //
    // The baseline of the font.
    //
    8,

    //
    // The offset to each character in the font.
    //
    {
           0,    4,   14,   25,   41,   56,   82,  100,
         108,  120,  132,  143,  154,  161,  169,  176,
         187,  203,  214,  227,  240,  253,  265,  281,
         293,  308,  322,  330,  338,  348,  356,  366,
         377,  399,  415,  430,  443,  459,  474,  488,
         503,  520,  531,  543,  559,  571,  595,  616,
         632,  646,  662,  678,  691,  704,  721,  738,
         760,  776,  790,  803,  814,  825,  836,  846,
         852,  860,  873,  888,  900,  916,  927,  941,
         956,  973,  984,  996, 1011, 1023, 1042, 1057,
        1070, 1084, 1098, 1109, 1120, 1131, 1145, 1159,
        1176, 1189, 1203, 1215, 1226, 1239, 1250,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8charter6x13iData
};
