//*****************************************************************************
//
// Copyright 1988 Bitstream, Inc., Cambridge, Massachusetts, USA
// Bitstream and Charter are registered trademarks of Bitstream, Inc.
// 
// The names "Bitstream" and "Charter" are registered trademarks of
// Bitstream, Inc.  Permission to use these trademarks is hereby
// granted only in association with the images described in this file.
// 
// Permission to use, copy, modify, and distribute this software and
// its documentation for any purpose and without fee is hereby
// granted, provided that the above copyright notice appear in all
// copies and that both that copyright notice and this permission
// notice appear in supporting documentation, and that the name of
// Bitstream not be used in advertising or publicity pertaining to
// distribution of the software without specific, written prior
// permission.  Bitstream makes no representations about the
// suitability of this software for any purpose.  It is provided "as
// is" without express or implied warranty.
// 
// BITSTREAM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN
// NO EVENT SHALL BITSTREAM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
// OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
// NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
// CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
// 
// Copyright (c) 1987, 1994 Digital Equipment Corporation
// 
// The X Consortium, and any party obtaining a copy of these files from
// the X Consortium, directly or indirectly, is granted, free of charge, a
// full and unrestricted irrevocable, world-wide, paid up, royalty-free,
// nonexclusive right and license to deal in this software and
// documentation files (the "Software"), including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons who receive
// copies from any such party to do so.  This license includes without
// limitation a license to do the foregoing actions under any patents of
// the party supplying this software to the X Consortium.
// 
// Digital Equipment Corporation make no representations about the
// suitability of this software for any purpose.  It is provided "as
// is" without express or implied warranty.
// 
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Charter
//     Size: 4x10
//     Bold: no
//     Italic: yes
//     Memory usage: 1252 bytes
//
//*****************************************************************************

static const uint8_t g_pui8charter4x10iData[1049] =
{
      4,   7,   0,   7,   9,   7,  17,  97,  97,  81, 209, 240,
     80,   9,   7,   1,  17,  65,  17,   0,   5,  96,  13,   7,
     33,  17,  66,  53,  49,  17,  53,  50,  65,  17, 176,  11,
      7,  34,  67,  66,  98,  50,  17,  66,  81, 192,  19,   7,
     17,  49,  17,  17,  17,  33,  18,  17,  33,  18,  17,  33,
     17,  17,  17,  49, 240,  15,   7,  34,  65,  17,  65,  17,
     66,  17,  33,  33,  66,  17, 240,  16,   6,   7,   1,  97,
      0,   6,  10,   7,  33,  81,  97,  81,  97,  97, 113, 192,
     10,   7,  17, 113,  97,  97,  97,  81,  81, 208,   9,   7,
     17,  81,  17,  66, 240, 240, 160,   9,   7, 145,  97,  69,
     65,  97, 240,  48,   7,   7, 240, 240,  81,  97, 208,   6,
      7, 240, 210, 240, 176,   7,   7, 240, 240,  81, 240,  80,
     10,   7,  65,  81,  97,  81,  81,  97,  81, 208,  14,   7,
     34,  65,  33,  33,  49,  33,  49,  33,  33,  66, 240,  48,
     10,   7,  17,  82,  97,  97,  97,  82, 240,  64,  12,   7,
     34,  65,  33,  97,  66,  65,  33,  36, 240,  32,  11,   7,
     34,  65,  33,  82,  66, 113,  36, 240,  32,  11,   7,  49,
     82,  65,  17,  53,  81,  81, 240,  48,  11,   7,  20,  49,
     98, 113,  49,  18,  50, 240,  64,  12,   7,  34,  65,  83,
     65,  33,  49,  33,  66, 240,  48,  11,   7,  20,  49,  33,
     81,  81,  81,  82, 240,  64,  13,   7,  34,  65,  33,  51,
     50,  18,  33,  33,  66, 240,  48,  12,   7,  18,  65,  33,
     49,  33,  66,  97,  66, 240,  64,   7,   7, 241, 240,  65,
    240,  80,   7,   7, 242, 240,  65,  82, 192,   9,   7, 240,
     34,  50,  67, 114, 240,  16,   6,   7, 229, 149, 240, 128,
      8,   7, 226, 114,  83,  34, 240,  64,  10,   7,  18,  65,
     33,  82,  65, 193, 240,  80,  16,   7,  50,  50,  33,  33,
     18,  18,  17,  17,  18,  20,  33,  49,  51, 144,  12,   7,
     50,  82,  65,  17,  52,  49,  33,  34,  34, 240,  13,   7,
     19,  65,  18,  51,  65,  33,  49,  18,  35, 240,  48,  12,
      7,  35,  49,  33,  33,  97,  97,  33,  67, 240,  32,  14,
      7,  19,  81,  18,  33,  49,  33,  49,  33,  18,  35, 240,
     48,  12,   7,  20,  49,  99,  65,  17,  65,  33,  36, 240,
     32,  11,   7,  20,  49,  99,  65,  17,  65,  82, 240,  64,
     13,   7,  51,  34,  33,  17,  97,  50,  17,  49,  51, 240,
     32,  15,   7,  18,  18,  33,  33,  52,  49,  33,  49,  33,
     34,  18, 240,  16,  10,   7,  18,  81,  97,  97,  97,  82,
    240,  64,  11,   7,  34,  97,  81,  97,  65,  17,  66, 240,
     64,  15,   7,  18,  18,  33,  33,  49,  17,  67,  65,  17,
     50,  33, 240,  16,  11,   7,  18,  81,  97,  97,  97,  17,
     52, 240,  32,  16,   7,  17,  50,  18,  33,  34,  18,  34,
     18,  17,  18,  17,  19,  18, 240,  16,   7,  17,  34,  34,
     33,  34,  17,  49,  18,  33,  34,  34,  33, 240,  16,  14,
      7,  35,  49,  49,  17,  65,  17,  65,  17,  49,  51, 240,
     32,  12,   7,  19,  65,  33,  49,  18,  50,  81,  82, 240,
     64,  14,   7,  35,  49,  49,  17,  65,  17,  65,  18,  33,
     66,  99, 128,  14,   7,  19,  65,  33,  49,  18,  50,  81,
     17,  50,  33, 240,  16,  12,   7,  34,  65,  17,  66, 113,
     49,  33,  66, 240,  48,  12,   7,   5,  33,  17,  17,  65,
     81,  97,  98, 240,  48,  15,   7,   2,  18,  49,  33,  33,
     33,  49,  33,  49,  33,  66, 240,  48,  13,   7,   2,  18,
     33,  49,  49,  17,  66,  82,  81, 240,  64,  18,   7,   2,
     33,  18,  34,  17,  17,  18,  17,  18,  18,  34,  18,  33,
     33, 240,  16,  14,   7,  18,  18,  49,  17,  66,  82,  65,
     17,  50,  18, 240,  16,  12,   7,   2,  18,  49,  17,  66,
     81,  97,  98, 240,  48,  12,   7,  20,  49,  17,  81,  97,
     81,  17,  52, 240,  32,  10,   7,  34,  65,  97,  97,  81,
     97,  98, 192,  10,   7,   1, 113,  97, 113,  97, 113,  97,
    160,  10,   7,  18,  97,  97,  97,  81,  97,  82, 192,   8,
      7,  19,  49,  49, 240, 240, 224,   6,   7,   0,   6,  20,
     48,   6,   7,   1,  97,   0,   6,  12,   7, 240,  18,  65,
     17,  49,  17,  81,  17, 240,  32,  12,   7,   2,  97,  98,
     66,  17,  49,  18,  65, 240,  64,   9,   7, 242,  65,  97,
     17,  81, 240,  64,  13,   7,  49,  97,  82,  65,  17,  49,
     17,  81,  17, 240,  32,   9,   7, 240,  17,  83,  50,  99,
    240,  32,  11,   7,  50,  65,  98,  81,  97,  97,  81,  82,
     80,  13,   7, 240,  17,  17,  49,  17,  81,  68,  49,  33,
     66,  64,  13,   7,  17,  97,  99,  65,  17,  49,  33,  49,
     34, 240,  16,   9,   7,   1, 209,  97,  97,  97, 240,  80,
     10,   7,  33, 194,  97,  97,  81,  97,  81,  96,  13,   7,
     17,  97,  97,  17,  66,  65,  17,  65,  33, 240,  32,  10,
      7,   1,  97,  97,  97,  97,  97, 240,  80,  13,   7, 230,
     18,  17,  17,  17,  33,  17,  17,  17,  34, 224,  11,   7,
    228,  65,  17,  49,  33,  49,  34, 240,  16,  10,   7, 242,
     65,  33,  49,  33,  66, 240,  48,  11,   7, 244,  65,  17,
     49,  18,  50,  81,  82,  80,  12,   7, 240,  18,  50,  17,
     49,  18,  66,  97,  98,  48,   9,   7, 225,  17,  66,  81,
     97, 240,  80,   8,   7, 242,  81, 113,  66, 240,  64,   9,
      7, 129,  83,  65,  97,  98, 240,  64,  12,   7, 225,  33,
     49,  33,  49,  17,  66,  17, 240,  32,  10,   7, 225,  33,
     65,  17,  66,  81, 240,  64,  13,   7, 225,  33,  17,  33,
     17,  17,  36,  49,  17, 240,  32,  10,   7, 241,  17,  66,
     82,  65,  18, 240,  32,  10,   7, 241,  33,  66,  82,  81,
     97,  66,  80,  10,   7, 243,  49,  17,  81,  17,  51, 240,
     48,  10,   7,  33,  81,  97,  81, 113,  97, 113, 176,  11,
      7,   1,  97,  97,  97,  97,  97,  97,  97,  96,  10,   7,
      1, 113,  97, 113,  81,  97,  81, 208,   9,   7, 130,  33,
     17,  34, 240, 240, 112,
};

const tFont g_sFontcharter4x10i =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    7,

    //
    // The height of the font.
    //
    8,

    //
    // The baseline of the font.
    //
    6,

    //
    // The offset to each character in the font.
    //
    {
           0,    4,   13,   22,   35,   46,   65,   80,
          86,   96,  106,  115,  124,  131,  137,  144,
         154,  168,  178,  190,  201,  212,  223,  235,
         246,  259,  271,  278,  285,  294,  300,  308,
         318,  334,  346,  359,  371,  385,  397,  408,
         421,  436,  446,  457,  472,  483,  499,  515,
         529,  541,  555,  569,  581,  593,  608,  621,
         639,  653,  665,  677,  687,  697,  707,  715,
         721,  727,  739,  751,  760,  773,  782,  793,
         806,  819,  828,  838,  851,  861,  874,  885,
         895,  906,  918,  927,  935,  944,  956,  966,
         979,  989,  999, 1009, 1019, 1030, 1040,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8charter4x10iData
};
