//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidasans
//     Size: 5x9
//     Bold: yes
//     Italic: yes
//     Memory usage: 1188 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidasans5x9biData[987] =
{
      5,   6,   0,   6,  96,   9,   6, 114,  66,  65,  81, 162,
    240,  16,   9,   6,  97,  33,  33,  33, 240, 240, 128,  11,
      6, 131,  49,  17,  21,  33,  17,  37,  19, 240,  12,   6,
     49,  67,  34,  66,  82,  66,  36,  49,  81,  64,  13,   6,
    113,  50,  17,  17,  17,  18,  35,  65,  50,  50, 192,  12,
      6, 131,  49,  17,  35,  18,  33,  18,  34,  36, 208,   8,
      6,  98,  65,  81, 240, 240,  80,  11,   6, 129,  65,  66,
     65,  81,  81,  81,  81,  80,  11,   6, 113,  97,  81,  81,
     66,  65,  81,  65,  80,   9,   6, 113,  65,  17,  51, 240,
    240,  48,   9,   6, 241,  81,  37,  33,  81, 240,  16,   8,
      6, 240, 240,  98,  81,  65,  80,   6,   6, 240, 146, 240,
    208,   7,   6, 240, 240,  98, 240,  16,  11,   6, 177,  65,
     65,  81,  65,  81,  65,  65,  80,  13,   6, 115,  49,  17,
     33,  33,  33,  33,  33,  18,  50, 240,  10,   6,  99,  66,
     65,  81,  66,  66, 240,  16,   9,   6, 116,  81,  66,  49,
     65,  68, 224,   9,   6, 116,  81,  35,  81,  82,  20, 224,
     10,   6, 146,  51,  33,  17,  37,  65,  66, 224,   9,   6,
    116,  33,  82,  97,  81,  35, 240,  11,   6, 131,  33,  68,
     33,  49,  17,  33,  51, 224,  10,   6, 101,  65,  65,  66,
     65,  65, 240,  32,  12,   6, 131,  33,  33,  35,  34,  18,
     17,  49,  20, 224,  11,   6, 115,  49,  33,  17,  49,  36,
     65,  35, 240,   8,   6, 240,  50, 240,  18, 240,  16,   8,
      6, 240,  66, 242,  81,  66,  64,   9,   6, 240,  17,  50,
     34,  82,  97, 224,   7,   6, 240,  53, 117, 240,  64,   9,
      6, 225,  83,  97,  20,  17, 240,  32,   9,   6, 100,  81,
     65,  50, 162, 240,  16,  11,   6, 131,  18,  33,  21,  17,
     19,  21,  35, 224,  12,   6, 146,  49,  17,  49,  17,  52,
     17,  35,  50, 192,  12,   6, 116,  33,  33,  35,  34,  17,
     34,  33,  20, 224,   9,   6, 132,  17,  65,  81,  82,  84,
    208,  11,   6, 117,  18,  33,  17,  51,  51,  33,  20, 224,
      9,   6, 116,  33,  83,  34,  66,  68, 224,  10,   6, 116,
     33,  81,  68,  34,  66, 240,  16,  11,   6, 132,  17,  65,
     81,  49,  17,  34,  36, 208,  13,   6, 114,  18,  17,  34,
     23,  33,  18,  33,  18,  18, 208,  10,   6, 114,  66,  65,
     81,  66,  66, 240,  16,  11,   6, 146,  66,  66,  65,  66,
     66,  66,  35,  48,  13,   6, 113,  18,  33,  17,  50,  51,
     50,  17,  33,  34, 208,   9,   6, 113,  81,  81,  66,  66,
     68, 224,  14,   6, 114,  33,  18,  33,  18,  22,  18,  18,
     18,  17,  33, 192,  14,   6, 113,  49,  18,  33,  18,  20,
     18,  17,  34,  17,  49, 208,  13,   6, 131,  33,  33,  17,
     49,  17,  49,  17,  34,  35, 224,  12,   6, 116,  33,  33,
     33,  33,  20,  34,  66, 240,  16,  14,   6, 131,  33,  33,
     17,  49,  17,  49,  17,  34,  35,  82,  82,  13,   6, 116,
     33,  33,  33,  17,  35,  50,  17,  33,  33, 224,   9,   6,
    131,  33,  82,  97,  82,  20, 224,   9,   6, 102,  34,  65,
     81,  66,  66, 240,  13,   6, 113,  34,  17,  36,  33,  17,
     49,  17,  34,  35, 224,  12,   6,  98,  51,  33,  18,  18,
     33,  17,  50,  66, 240,  15,   6,  97,  33,  18,  18,  18,
     33,  18,  34,  18,  17,  33,  33, 224,  14,   6, 114,  18,
     33,  17,  50,  66,  49,  17,  49,  18,  17, 176,  12,   6,
     97,  34,  33,  17,  50,  66,  65,  81, 240,  16,   9,   6,
    117,  65,  65,  65,  65,  69, 208,  11,   6, 130,  50,  66,
     65,  81,  81,  66,  67,  48,  11,   6,  97,  81,  97,  81,
     81,  81,  97,  81,  48,  11,   6, 115,  66,  65,  81,  81,
     66,  66,  50,  64,  10,   6, 226,  66,  49,  17,  34,  33,
    240,  64,   6,   6,   0,   6,   4,  32,   6,   6,  98,   0,
      5,  96,  11,   6, 240,  68,  18,  18,  17,  18,  34,  17,
    224,  10,   6, 114,  66,  68,  19,  17,  21,  20, 224,   8,
      6, 240,  67,  33,  81,  83, 240,  11,   6, 146,  66,  36,
     18,  17,  33,  18,  36, 224,   9,   6, 240,  67,  35,  50,
     17,  36, 224,  11,   6, 131,  34,  52,  50,  65,  81,  66,
     66,  64,  13,   6, 240,  83,  33,  18,  17,  33,  36,  33,
     33,  35,  48,  12,   6, 114,  66,  65,  18,  36,  18,  17,
     34,  17, 224,   9,   6, 114, 162,  65,  66,  66, 240,  16,
     10,   6, 146, 161,  81,  81,  66,  65,  51,  48,  12,   6,
    114,  65,  81,  33,  18,  17,  36,  34,  17, 224,  10,   6,
    114,  66,  65,  81,  66,  66, 240,  16,  11,   6, 240,  67,
     17,  20,  18,  20,  18,  17, 192,  11,   6, 240,  65,  18,
     36,  18,  17,  34,  17, 224,  10,   6, 240,  67,  33,  33,
     33,  33,  35, 240,  12,   6, 240,  68,  34,  17,  33,  18,
     20,  34,  66,  64,  13,   6, 240,  68,  18,  18,  17,  19,
     18,  17,  81,  66,  32,   9,   6, 240,  67,  34,  66,  65,
    240,  32,   8,   6, 240,  67,  49,  98,  35, 240,   9,   6,
    113,  81,  67,  50,  65,  83, 240,  11,   6, 240,  65,  18,
     33,  18,  20,  34,  17, 224,  10,   6, 240,  50,  18,  18,
     17,  50,  66, 240,  12,   6, 240,  49,  19,  17,  17,  19,
     17,  20,  33, 208,   8,   6, 240,  68,  50,  51,  36, 224,
     13,   6, 240,  65,  49,  18,  17,  34,  17,  35,  65,  50,
     64,   8,   6, 240,  68,  65,  49,  69, 208,  11,   6, 114,
     65,  81,  66,  66,  66,  66,  66,  64,  11,   6, 113,  81,
     65,  81,  81,  81,  81,  81,  80,  11,   6, 114,  66,  66,
     66,  66,  65,  81,  66,  64,   9,   6, 240, 147,  17,  17,
     19, 240,  64,
};

const tFont g_sFontlucidasans5x9bi =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    6,

    //
    // The height of the font.
    //
    9,

    //
    // The baseline of the font.
    //
    7,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   14,   23,   34,   46,   59,   71,
          79,   90,  101,  110,  119,  127,  133,  140,
         151,  164,  174,  183,  192,  202,  211,  222,
         232,  244,  255,  263,  271,  280,  287,  296,
         305,  316,  328,  340,  349,  360,  369,  379,
         390,  403,  413,  424,  437,  446,  460,  474,
         487,  499,  513,  526,  535,  544,  557,  569,
         584,  598,  610,  619,  630,  641,  652,  662,
         668,  674,  685,  695,  703,  714,  723,  734,
         747,  759,  768,  778,  790,  800,  811,  822,
         832,  844,  857,  866,  874,  883,  894,  904,
         916,  924,  937,  945,  956,  967,  978,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidasans5x9biData
};
