//*****************************************************************************
//
// Copyright (c) 2014 Dimitar Toshkov Zhekov,
// with Reserved Font Name "Terminus Font".
// 
// This Font Software is licensed under the SIL Open Font License, Version 1.1.
// This license is copied below, and is also available with a FAQ at:
// http://scripts.sil.org/OFL
// 
// 
// -----------------------------------------------------------
// SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007
// -----------------------------------------------------------
// 
// PREAMBLE
// The goals of the Open Font License (OFL) are to stimulate worldwide
// development of collaborative font projects, to support the font creation
// efforts of academic and linguistic communities, and to provide a free and
// open framework in which fonts may be shared and improved in partnership
// with others.
// 
// The OFL allows the licensed fonts to be used, studied, modified and
// redistributed freely as long as they are not sold by themselves. The
// fonts, including any derivative works, can be bundled, embedded, 
// redistributed and/or sold with any software provided that any reserved
// names are not used by derivative works. The fonts and derivatives,
// however, cannot be released under any other type of license. The
// requirement for fonts to remain under this license does not apply
// to any document created using the fonts or their derivatives.
// 
// DEFINITIONS
// "Font Software" refers to the set of files released by the Copyright
// Holder(s) under this license and clearly marked as such. This may
// include source files, build scripts and documentation.
// 
// "Reserved Font Name" refers to any names specified as such after the
// copyright statement(s).
// 
// "Original Version" refers to the collection of Font Software components as
// distributed by the Copyright Holder(s).
// 
// "Modified Version" refers to any derivative made by adding to, deleting,
// or substituting -- in part or in whole -- any of the components of the
// Original Version, by changing formats or by porting the Font Software to a
// new environment.
// 
// "Author" refers to any designer, engineer, programmer, technical
// writer or other person who contributed to the Font Software.
// 
// PERMISSION & CONDITIONS
// Permission is hereby granted, free of charge, to any person obtaining
// a copy of the Font Software, to use, study, copy, merge, embed, modify,
// redistribute, and sell modified and unmodified copies of the Font
// Software, subject to the following conditions:
// 
// 1) Neither the Font Software nor any of its individual components,
// in Original or Modified Versions, may be sold by itself.
// 
// 2) Original or Modified Versions of the Font Software may be bundled,
// redistributed and/or sold with any software, provided that each copy
// contains the above copyright notice and this license. These can be
// included either as stand-alone text files, human-readable headers or
// in the appropriate machine-readable metadata fields within text or
// binary files as long as those fields can be easily viewed by the user.
// 
// 3) No Modified Version of the Font Software may use the Reserved Font
// Name(s) unless explicit written permission is granted by the corresponding
// Copyright Holder. This restriction only applies to the primary font name as
// presented to the users.
// 
// 4) The name(s) of the Copyright Holder(s) or the Author(s) of the Font
// Software shall not be used to promote, endorse or advertise any
// Modified Version, except to acknowledge the contribution(s) of the
// Copyright Holder(s) and the Author(s) or with their explicit written
// permission.
// 
// 5) The Font Software, modified or unmodified, in part or in whole,
// must be distributed entirely under this license, and must not be
// distributed under any other license. The requirement for fonts to
// remain under this license does not apply to any document created
// using the Font Software.
// 
// TERMINATION
// This license becomes null and void if any of the above conditions are
// not met.
// 
// DISCLAIMER
// THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT
// OF COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL THE
// COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
// INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL
// DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM
// OTHER DEALINGS IN THE FONT SOFTWARE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Terminus
//     Size: 6x12
//     Bold: no
//     Italic: no
//     Memory usage: 1460 bytes
//
//*****************************************************************************

static const uint8_t g_pui8terminus6x12Data[1260] =
{
      4,   6,   0,   9,  10,   4, 129,  49,  49,  49,  49, 113,
     49, 176,  11,   5,  81,  17,  33,  17,  33,  17, 240, 240,
    192,  17,   6, 209,  17,  49,  17,  37,  33,  17,  49,  17,
     37,  33,  17,  49,  17, 224,  18,   6, 225,  67,  33,  17,
     17,  17,  17,  67,  65,  17,  17,  17,  17,  35,  65, 144,
     19,   6, 209,  33,  17,  17,  17,  33,  17,  81,  65,  81,
     17,  33,  17,  17,  17,  33, 208,  17,   6, 225,  65,  17,
     49,  17,  65,  66,  17,  17,  33,  33,  33,  50,  17, 208,
      8,   4,  65,  49,  49, 240, 240,  80,  11,   5, 193,  49,
     49,  65,  65,  65,  81,  81, 192,  11,   5, 161,  81,  81,
     65,  65,  65,  49,  49, 224,  12,   6, 240, 161,  17,  65,
     53,  49,  65,  17, 240,  80,  10,   6, 240, 177,  81,  53,
     49,  81, 240,  96,   8,   5, 240, 240, 177,  65,  49, 144,
      8,   6, 240, 240, 101, 240, 240,  16,   7,   4, 240, 240,
     33,  49, 176,  11,   5, 209,  65,  49,  65,  49,  65,  49,
     65, 224,  18,   6, 211,  33,  49,  17,  34,  17,  17,  17,
     18,  33,  17,  49,  17,  49,  35, 224,  11,   5, 177,  50,
     65,  65,  65,  65,  65,  51, 192,  13,   6, 211,  33,  49,
     17,  49,  65,  65,  65,  65,  85, 208,  13,   6, 211,  33,
     49,  81,  50,  97,  81,  17,  49,  35, 224,  15,   6, 240,
     17,  66,  49,  17,  33,  33,  17,  49,  21,  81,  81, 208,
     12,   6, 197,  17,  81,  84,  97,  81,  17,  49,  35, 224,
     14,   6, 211,  33,  81,  84,  33,  49,  17,  49,  17,  49,
     35, 224,  11,   6, 197,  81,  81,  65,  81,  65,  81,  81,
    240,  16,   6, 211,  33,  49,  17,  49,  35,  33,  49,  17,
     49,  17,  49,  35, 224,  14,   6, 211,  33,  49,  17,  49,
     17,  49,  36,  81,  81,  35, 224,   8,   4, 240,  17,  49,
    177,  49, 176,   9,   5, 240,  97,  65, 225,  65,  49, 144,
     11,   5, 240,  49,  49,  49,  49,  81,  81,  81, 176,   7,
      6, 240, 149, 213, 240, 160,  10,   5, 241,  81,  81,  81,
     49,  49,  49, 224,  12,   6, 211,  33,  49,  17,  49,  65,
     65, 177,  81, 240,  18,   6, 211,  33,  49,  17,  34,  17,
     17,  17,  17,  17,  17,  17,  34,  17, 100, 208,  17,   6,
    211,  33,  49,  17,  49,  17,  49,  21,  17,  49,  17,  49,
     17,  49, 208,  16,   6, 196,  33,  49,  17,  49,  20,  33,
     49,  17,  49,  17,  49,  20, 224,  13,   6, 211,  33,  49,
     17,  81,  81,  81,  81,  49,  35, 224,  17,   6, 195,  49,
     33,  33,  49,  17,  49,  17,  49,  17,  49,  17,  33,  35,
    240,  11,   6, 197,  17,  81,  84,  33,  81,  81,  85, 208,
     12,   6, 197,  17,  81,  84,  33,  81,  81,  81, 240,  32,
     15,   6, 211,  33,  49,  17,  81,  81,  19,  17,  49,  17,
     49,  35, 224,  18,   6, 193,  49,  17,  49,  17,  49,  21,
     17,  49,  17,  49,  17,  49,  17,  49, 208,  11,   5, 163,
     49,  65,  65,  65,  65,  65,  51, 192,  13,   6, 227,  65,
     81,  81,  81,  33,  33,  33,  33,  50, 240,  17,   6, 193,
     49,  17,  33,  33,  17,  50,  66,  65,  17,  49,  33,  33,
     49, 208,  11,   6, 193,  81,  81,  81,  81,  81,  81,  85,
    208,  21,   6, 193,  49,  18,  18,  17,  17,  17,  17,  17,
     17,  17,  49,  17,  49,  17,  49,  17,  49, 208,  20,   6,
    193,  49,  17,  49,  18,  33,  17,  17,  17,  17,  34,  17,
     49,  17,  49,  17,  49, 208,  17,   6, 211,  33,  49,  17,
     49,  17,  49,  17,  49,  17,  49,  17,  49,  35, 224,  15,
      6, 196,  33,  49,  17,  49,  17,  49,  20,  33,  81,  81,
    240,  32,  19,   6, 211,  33,  49,  17,  49,  17,  49,  17,
     49,  17,  49,  17,  17,  17,  35,  97, 112,  17,   6, 196,
     33,  49,  17,  49,  17,  49,  20,  33,  17,  49,  33,  33,
     49, 208,  13,   6, 211,  33,  49,  17,  99,  97,  81,  17,
     49,  35, 224,  11,   6, 197,  49,  81,  81,  81,  81,  81,
     81, 240,  18,   6, 193,  49,  17,  49,  17,  49,  17,  49,
     17,  49,  17,  49,  17,  49,  35, 224,  17,   6, 193,  49,
     17,  49,  17,  49,  33,  17,  49,  17,  49,  17,  65,  81,
    240,  21,   6, 193,  49,  17,  49,  17,  49,  17,  49,  17,
     17,  17,  17,  17,  17,  18,  18,  17,  49, 208,  17,   6,
    193,  49,  17,  49,  33,  17,  65,  81,  65,  17,  33,  49,
     17,  49, 208,  15,   6, 193,  49,  17,  49,  33,  17,  49,
     17,  65,  81,  81,  81, 240,  11,   6, 197,  81,  65,  65,
     65,  65,  81,  85, 208,  11,   5, 163,  33,  65,  65,  65,
     65,  65,  67, 192,  11,   5, 161,  65,  81,  65,  81,  65,
     81,  65, 176,  11,   5, 163,  65,  65,  65,  65,  65,  65,
     35, 192,  10,   6, 129,  65,  17,  33,  49,   0,   6,  16,
      6,   6,   0,   7,  69, 112,   7,   5,   1,  81,   0,   6,
     80,  12,   6, 240, 163,  97,  36,  17,  49,  17,  49,  36,
    208,  15,   6, 193,  81,  84,  33,  49,  17,  49,  17,  49,
     17,  49,  20, 224,  12,   6, 240, 163,  33,  49,  17,  81,
     81,  49,  35, 224,  16,   6, 240,  17,  81,  36,  17,  49,
     17,  49,  17,  49,  17,  49,  36, 208,  12,   6, 240, 163,
     33,  49,  21,  17,  81,  49,  35, 224,  11,   5, 194,  33,
     51,  49,  65,  65,  65,  65, 208,  16,   6, 240, 164,  17,
     49,  17,  49,  17,  49,  17,  49,  36,  81,  35,  32,  16,
      6, 193,  81,  84,  33,  49,  17,  49,  17,  49,  17,  49,
     17,  49, 208,  11,   5,  97,  65, 130,  65,  65,  65,  65,
     51, 192,  14,   5, 129,  65, 130,  65,  65,  65,  65,  65,
     17,  33,  34,  32,  15,   5, 161,  65,  65,  33,  17,  17,
     34,  50,  49,  17,  33,  33, 176,  11,   5, 162,  65,  65,
     65,  65,  65,  65,  51, 192,  20,   6, 240, 148,  33,  17,
     17,  17,  17,  17,  17,  17,  17,  17,  17,  17,  17,  17,
     17, 208,  15,   6, 240, 148,  33,  49,  17,  49,  17,  49,
     17,  49,  17,  49, 208,  14,   6, 240, 163,  33,  49,  17,
     49,  17,  49,  17,  49,  35, 224,  16,   6, 240, 148,  33,
     49,  17,  49,  17,  49,  17,  49,  20,  33,  81,  80,  15,
      6, 240, 164,  17,  49,  17,  49,  17,  49,  17,  49,  36,
     81,  81,  12,   6, 240, 145,  19,  18,  65,  81,  81,  81,
    240,  32,  10,   6, 240, 164,  17,  99,  97,  81,  20, 224,
     11,   5, 177,  65,  51,  49,  65,  65,  65,  82, 176,  15,
      6, 240, 145,  49,  17,  49,  17,  49,  17,  49,  17,  49,
     36, 208,  14,   6, 240, 145,  49,  17,  49,  33,  17,  49,
     17,  65,  81, 240,  18,   6, 240, 145,  49,  17,  49,  17,
     17,  17,  17,  17,  17,  17,  17,  17,  35, 224,  14,   6,
    240, 145,  49,  33,  17,  65,  81,  65,  17,  33,  49, 208,
     17,   6, 240, 145,  49,  17,  49,  17,  49,  17,  49,  17,
     49,  36,  81,  35,  32,  10,   6, 240, 149,  65,  65,  65,
     65,  85, 208,  11,   5, 194,  33,  65,  49,  81,  65,  65,
     82, 176,  11,   4, 129,  49,  49,  49,  49,  49,  49,  49,
    176,  11,   5, 162,  81,  65,  81,  49,  65,  65,  34, 208,
     12,   6, 113,  33,  17,  17,  17,  17,  33,   0,   6,  32,};

const tFont g_sFontterminus6x12 =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    6,

    //
    // The height of the font.
    //
    12,

    //
    // The baseline of the font.
    //
    10,

    //
    // The offset to each character in the font.
    //
    {
           0,    4,   14,   25,   42,   60,   79,   96,
         104,  115,  126,  138,  148,  156,  164,  171,
         182,  200,  211,  224,  237,  252,  264,  278,
         289,  305,  319,  327,  336,  347,  354,  364,
         376,  394,  411,  427,  440,  457,  468,  480,
         495,  513,  524,  537,  554,  565,  586,  606,
         623,  638,  657,  674,  687,  698,  716,  733,
         754,  771,  786,  797,  808,  819,  830,  840,
         846,  853,  865,  880,  892,  908,  920,  931,
         947,  963,  974,  988, 1003, 1014, 1034, 1049,
        1063, 1079, 1094, 1106, 1116, 1127, 1142, 1156,
        1174, 1188, 1205, 1215, 1226, 1237, 1248,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8terminus6x12Data
};
