//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidabright
//     Size: 5x9
//     Bold: no
//     Italic: no
//     Memory usage: 1192 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidabright5x9Data[991] =
{
      5,   6,   0,   6,  96,   9,   6,  97,  81,  81,  81, 177,
    240,  32,   7,   6,  98,  66, 240, 240, 160,  10,   6, 131,
     21,  33,  17,  37,  34,  51, 240,  10,   6, 114,  51,  50,
     82,  51,  50,  81, 160,  11,   6,  98,  17,  35,  51,  67,
     51,  33,  18, 224,  11,   6, 114,  66,  66,  50,  18,  17,
     18,  52, 208,   7,   6,  97,  81, 240, 240, 176,  11,   6,
    113,  65,  81,  81,  81,  81,  81,  97,  64,  11,   6,  97,
     97,  81,  81,  81,  81,  81,  65,  80,   8,   6,  98,  82,
     50,  97, 240, 192,   8,   6, 225,  81,  53,  49,  81, 240,
      8,   6, 240, 240,  97,  81,  81,  80,   6,   6, 240, 146,
    240, 208,   7,   6, 240, 240,  97, 240,  32,  11,   6, 145,
     81,  65,  81,  65,  81,  65,  81,  80,  13,   6, 114,  49,
     33,  33,  33,  33,  33,  33,  33,  50, 240,   9,   6,  98,
     81,  81,  81,  81,  67, 240,  10,   6,  99,  49,  17,  81,
     65,  65,  83, 240,  12,   6,  99,  49,  17,  65,  82,  49,
     17,  50, 240,  16,  10,   6, 130,  51,  34,  17,  37,  65,
     67, 208,  11,   6,  99,  49,  82,  97,  49,  17,  50, 240,
     16,  12,   6, 115,  33,  33,  35,  49,  33,  33,  33,  50,
    240,  10,   6, 100,  81,  65,  65,  66,  65, 240,  32,  13,
      6, 100,  33,  33,  49,  17,  33,  18,  33,  33,  35, 240,
     12,   6, 114,  49,  33,  33,  33,  51,  33,  33,  35, 240,
      8,   6, 240,  49, 240,  33, 240,  32,   9,   6, 240,  49,
    240,  33,  81,  81,  80,   9,   6, 240,  18,  35,  19,  83,
     82, 192,   7,   6, 240, 149,  21, 240,  64,   9,   6, 194,
     83,  83,  19,  34, 240,  16,  11,   6,  99,  49,  17,  65,
     81,  81,  81, 240,  16,  13,   6, 132,  17,  17,  18,  19,
     17,  17,  22,  17,  20, 208,  12,   6, 129,  82,  49,  17,
     52,  17,  49,  18,  34, 192,  12,   6, 101,  33,  33,  35,
     49,  33,  33,  33,  21, 208,  10,   6, 116,  18,  33,  17,
     81,  82,  84, 208,  12,   6, 101,  33,  49,  17,  49,  17,
     49,  17,  54, 208,  11,   6, 100,  49,  17,  50,  65,  81,
     17,  36, 224,  11,   6, 100,  49,  17,  50,  65,  81,  65,
    240,  32,  11,   6, 116,  18,  33,  17,  81,  37,  33,  36,
    208,  12,   6, 102,  17,  33,  36,  33,  33,  33,  33,  22,
    192,   9,   6,  99,  65,  81,  81,  81,  67, 240,  11,   6,
    114,  65,  81,  81,  81,  81,  66,  66,  64,  12,   6,  99,
     17,  33,  17,  50,  66,  65,  17,  37, 208,  10,   6,  99,
     65,  81,  81,  81,  17,  36, 224,  15,   6,  98,  49,  18,
     18,  18,  18,  17,  19,  17,  17,  20,  18, 192,  15,   6,
     98,  19,  18,  17,  34,  17,  33,  18,  33,  18,  19,  17,
    208,  13,   6, 115,  34,  18,  17,  49,  17,  49,  18,  18,
     35, 224,  11,   6, 100,  49,  33,  33,  33,  35,  49,  67,
    240,  14,   6, 115,  34,  18,  17,  49,  17,  49,  18,  18,
     35,  82,  82,  12,   6, 100,  49,  17,  49,  17,  50,  65,
     17,  37, 208,  11,   6,  99,  49,  17,  50,  82,  49,  17,
     51, 240,   9,   6, 101,  49,  81,  81,  81,  67, 224,  13,
      6, 102,  17,  33,  33,  33,  33,  33,  33,  33,  36, 208,
     13,   6,  98,  34,  17,  49,  17,  33,  49,  17,  50,  81,
    224,  15,   6,  98,  17,  19,  17,  49,  19,  18,  18,  18,
     18,  33,  17, 208,  13,   6,  98,  33,  33,  18,  50,  51,
     34,  17,  34,  18, 208,  11,   6,  98,  33,  33,  18,  35,
     65,  81,  67, 224,  11,   6, 100,  33,  17,  81,  65,  81,
     17,  36, 224,  11,   6,  98,  65,  81,  81,  81,  81,  81,
     82,  64,  11,   6,  97,  81,  97,  81,  97,  81,  97,  81,
     32,  11,   6,  98,  81,  81,  81,  81,  81,  81,  66,  64,
     13,   6,  33,  81,  67,  49,  17,  34,  18,  17,  49, 240,
     64,   6,   6, 240, 240, 195, 144,   6,   6,  98,   0,   5,
     96,  10,   6, 240,  51,  66,  49,  17,  50,  17, 224,  11,
      6,  98,  81,  84,  33,  33,  33,  33,  35, 224,   9,   6,
    240,  66,  49,  17,  49,  98, 240,  11,   6, 130,  81,  51,
     33,  33,  33,  33,  37, 208,   8,   6, 240,  66,  51,  49,
     98, 240,  10,   6, 114,  66,  50,  81,  81,  66, 240,  16,
     12,   6, 240,  52,  33,  17,  51,  52,  33,  33,  35,  48,
     11,   6,  98,  81,  83,  49,  17,  49,  17,  37, 208,   8,
      6, 113, 162,  81,  81,  67, 240,  10,   6, 113, 177,  81,
     81,  81,  66,  66,  64,  11,   6,  98,  81,  81,  18,  35,
     49,  17,  37, 208,   9,   6,  98,  81,  81,  81,  81,  67,
    240,  11,   6, 240,  54,  17,  17,  17,  17,  17,  23, 192,
     10,   6, 240,  52,  49,  17,  49,  17,  37, 208,  10,   6,
    240,  66,  49,  33,  33,  33,  50, 240,  12,   6, 240,  53,
     33,  33,  33,  33,  35,  49,  67,  48,  11,   6, 240,  67,
     33,  33,  33,  33,  36,  81,  67,   9,   6, 240,  52,  49,
     17,  49,  67, 240,   8,   6, 240,  51,  51,  51,  51, 240,
      9,   6, 113,  81,  67,  65,  81,  82, 240,  10,   6, 240,
     52,  49,  17,  49,  17,  52, 208,  10,   6, 240,  50,  17,
     33,  33,  50,  66, 240,  12,   6, 240,  50,  17,  18,  18,
     17,  20,  33,  33, 208,  10,   6, 240,  50,  17,  51,  35,
     49,  18, 224,  12,   6, 240,  50,  17,  33,  33,  51,  50,
     81,  65,  64,  10,   6, 240,  52,  33,  17,  65,  17,  36,
    224,  11,   6, 114,  65,  81,  81,  66,  81,  81,  82,  48,
     11,   6,  97,  81,  81,  81,  81,  81,  81,  81,  80,  11,
      6,  98,  81,  81,  81,  82,  65,  81,  66,  64,   9,   6,
    240, 147,  17,  17,  19, 240,  64,
};

const tFont g_sFontlucidabright5x9 =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    6,

    //
    // The height of the font.
    //
    9,

    //
    // The baseline of the font.
    //
    7,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   14,   21,   31,   41,   52,   63,
          70,   81,   92,  100,  108,  116,  122,  129,
         140,  153,  162,  172,  184,  194,  205,  217,
         227,  240,  252,  260,  269,  278,  285,  294,
         305,  318,  330,  342,  352,  364,  375,  386,
         397,  409,  418,  429,  441,  451,  466,  481,
         494,  505,  519,  531,  542,  551,  564,  577,
         592,  605,  616,  627,  638,  649,  660,  673,
         679,  685,  695,  706,  715,  726,  734,  744,
         756,  767,  775,  785,  796,  805,  816,  826,
         836,  848,  859,  868,  876,  885,  895,  905,
         917,  927,  939,  949,  960,  971,  982,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidabright5x9Data
};
