//*****************************************************************************
//
// This is the LEGAL NOTICE pertaining to the Lucida fonts from Bigelow & Holmes:
// 
// 	NOTICE TO USER: The source code, including the glyphs or icons 
// 	forming a par of the OPEN LOOK TM Graphic User Interface, on this 
// 	tape and in these files is copyrighted under U.S. and international
// 	laws. Sun Microsystems, Inc. of Mountain View, California owns
// 	the copyright and has design patents pending on many of the icons. 
// 	AT&T is the owner of the OPEN LOOK trademark associated with the
// 	materials on this tape. Users and possessors of this source code 
// 	are hereby granted a nonexclusive, royalty-free copyright and 
// 	design patent license to use this code in individual and 
// 	commercial software. A royalty-free, nonexclusive trademark
// 	license to refer to the code and output as "OPEN LOOK" compatible 
// 	is available from AT&T if, and only if, the appearance of the 
// 	icons or glyphs is not changed in any manner except as absolutely
// 	necessary to accommodate the standard resolution of the screen or
// 	other output device, the code and output is not changed except as 
// 	authorized herein, and the code and output is validated by AT&T. 
// 	Bigelow & Holmes is the owner of the Lucida (R) trademark for the
// 	fonts and bit-mapped images associated with the materials on this 
// 	tape. Users are granted a royalty-free, nonexclusive license to use
// 	the trademark only to identify the fonts and bit-mapped images if, 
// 	and only if, the fonts and bit-mapped images are not modified in any
// 	way by the user. 
// 
// 
// 	Any use of this source code must include, in the user documentation 
// 	and internal comments to the code, notices to the end user as  
// 	follows:
// 
// 
// 	(c) Copyright 1989 Sun Microsystems, Inc. Sun design patents
// 	pending in the U.S. and foreign countries. OPEN LOOK is a 
// 	trademark of AT&T. Used by written permission of the owners.
// 
// 
//  	(c) Copyright Bigelow & Holmes 1986, 1985. Lucida is a registered 
// 	trademark of Bigelow & Holmes. Permission to use the Lucida 
// 	trademark is hereby granted only in association with the images 
// 	and fonts described in this file.
// 
// 
// 
// 	SUN MICROSYSTEMS, INC., AT&T, AND BIGELOW & HOLMES 
// 	MAKE NO REPRESENTATIONS ABOUT THE SUITABILITY OF
//  	THIS SOURCE CODE FOR ANY PURPOSE. IT IS PROVIDED "AS IS" 
// 	WITHOUT EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
// 	SUN  MICROSYSTEMS, INC., AT&T AND BIGELOW  & HOLMES, 
// 	SEVERALLY AND INDIVIDUALLY, DISCLAIM ALL WARRANTIES 
// 	WITH REGARD TO THIS SOURCE CODE, INCLUDING ALL IMPLIED
// 	WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
// 	PARTICULAR PURPOSE. IN NO EVENT SHALL SUN MICROSYSTEMS,
// 	INC., AT&T OR BIGELOW & HOLMES BE LIABLE FOR ANY
// 	SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
// 	OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA 	
// 	OR PROFITS, WHETHER IN AN ACTION OF  CONTRACT, NEGLIGENCE
// 	OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION
// 	WITH THE USE OR PERFORMANCE OF THIS SOURCE CODE.
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Lucidabright
//     Size: 6x12
//     Bold: yes
//     Italic: no
//     Memory usage: 1532 bytes
//
//*****************************************************************************

static const uint8_t g_pui8lucidabright6x12bData[1331] =
{
      5,   9,   0,  11,  32,  12,   9,   1, 129, 129, 129, 129,
    129, 240,  33, 240, 176,  13,   9,   1,  17,  97,  17,  97,
     17,  97,  17,   0,   7,  64,  18,   9,  33,  17,  97,  17,
     70,  81,  17,  81,  17,  86,  65,  17,  97,  17, 240, 128,
     15,   9,  19,  81,  18,  81,  17, 114, 130, 114,  81,  18,
     84, 113, 240,  22,   9,  17,  49,  49,  17,  17,  65,  19,
     81,  17, 113,  17,  83,  17,  65,  17,  17,  49,  49, 240,
    112,  20,   9,  34,  97,  33,  84,  65,  18,  18,  33,  33,
     17,  49,  35,  50,  34,  67,  18, 240,  80,   9,   9,   3,
     99, 113, 129,   0,   7,  80,  13,   9,  17, 113, 129, 129,
    129, 129, 129, 129, 129, 145, 112,  13,   9,   1, 145, 129,
    129, 129, 129, 129, 129, 129, 113, 128,   8,   9,  18, 100,
     84,   0,   8,  64,  11,   9, 193, 129, 129,  87,  81, 129,
    129, 240, 128,   9,   9,   0,   6,  98, 114, 129, 114, 112,
      8,   9, 240, 240, 242, 240, 240, 208,   7,   9,   0,   7,
    114, 240, 160,  13,   9,  65, 114, 113, 129, 113, 129, 113,
    129, 114, 113, 128,  18,   9,  20,  81,  33,  65,  65,  49,
     65,  49,  65,  49,  65,  65,  33,  84, 240, 112,  12,   9,
      2, 129, 129, 129, 129, 129, 129, 115, 240, 144,  13,   9,
      3,  97,  33, 129, 129, 113, 113, 113, 132, 240, 128,  14,
      9,   3,  97,  33, 129,  98, 145, 129,  81,  33,  83, 240,
    144,  14,   9,  34, 114,  97,  17,  81,  33,  85, 113, 129,
    115, 240, 112,  13,   9,   4,  81, 129, 131, 130, 129,  81,
     33,  83, 240, 144,  16,   9,  35,  81,  33,  65, 132,  81,
     49,  65,  49,  65,  49,  83, 240, 128,  12,   9,   5, 129,
    113, 113, 114, 113, 114, 113, 240, 176,  17,   9,  19,  81,
     49,  65,  49,  83,  81,  34,  65,  49,  65,  49,  83, 240,
    128,  16,   9,  19,  81,  34,  65,  49,  65,  49,  84, 129,
     65,  33,  83, 240, 144,   9,   9, 240, 193, 240, 240,  81,
    240, 176,  10,   9, 240, 193, 240, 240,  81, 129, 129, 128,
     11,   9, 225,  98,  98,  82, 146, 130, 145, 240,  96,   8,
      9, 240, 240, 102, 198, 240, 240,  11,   9, 145, 146, 130,
    146,  82,  98,  97, 240, 176,  13,   9,   3,  97,  33, 129,
    114,  97, 129, 240,  33, 240, 160,  23,   9,  52,  50,  50,
     33,  18,  33,  17,  17,  18,  17,  17,  17,  18,  17,  17,
     18,  18,  34, 132, 240, 112,  16,   9,  49, 130,  99,  97,
     33,  69,  65,  50,  34,  65,  34,  51, 240,  64,  17,   9,
      5,  81,  49,  65,  49,  68,  81,  33,  81,  49,  65,  49,
     53, 240, 112,  14,   9,  36,  65,  49,  49, 129, 129, 129,
    145,  49,  84, 240,  96,  18,   9,   6,  65,  65,  49,  81,
     33,  81,  33,  81,  33,  81,  33,  65,  38, 240,  96,  16,
      9,   6,  65,  49,  65,  33,  84,  81,  33,  81, 129,  49,
     54, 240,  96,  15,   9,   6,  65,  49,  65,  33,  84,  81,
     33,  81, 129, 115, 240, 144,  16,   9,  36,  65,  49,  49,
    129, 129,  51,  33,  65,  65,  49,  84, 240,  96,  19,   9,
      3,  35,  33,  65,  49,  65,  54,  49,  65,  49,  65,  49,
     65,  35,  35, 240,  64,  12,   9,   3, 113, 129, 129, 129,
    129, 129, 115, 240, 144,  14,   9,  19, 113, 129, 129, 129,
    129, 129, 129,  97,  17,  99,  96,  19,   9,   3,  18,  65,
     34,  65,  18,  82, 113,  17,  97,  18,  81,  34,  51,  19,
    240,  80,  13,   9,   3, 113, 129, 129, 129, 129, 129,  33,
     69, 240, 112,  26,   9,   3,  51,  18,  50,  35,  34,  33,
     17,  17,  17,  33,  17,  17,  17,  33,  33,  33,  33,  33,
     33,  19,  51, 240,  48,  22,   9,   2,  51,  34,  49,  50,
     49,  49,  17,  33,  49,  33,  17,  49,  35,  49,  50,  35,
     49, 240,  80,  18,   9,  35,  81,  49,  49,  81,  33,  81,
     33,  81,  33,  81,  49,  49,  83, 240, 112,  15,   9,   5,
     81,  49,  65,  49,  65,  49,  68,  81, 129, 115, 240, 144,
     18,   9,  35,  81,  49,  49,  81,  33,  81,  33,  81,  33,
     81,  49,  50,  68, 130, 130,  18,   9,   5,  81,  49,  65,
     49,  65,  33,  84,  81,  33,  81,  34,  51,  34, 240,  80,
     14,   9,  19,  81,  33,  81, 145, 146, 129,  81,  33,  83,
    240, 144,  12,   9,   7,  81, 129, 129, 129, 129, 129, 115,
    240, 112,  19,   9,   3,  35,  33,  65,  49,  65,  49,  65,
     49,  65,  49,  65,  49,  65,  68, 240,  96,  18,   9,   3,
     50,  34,  49,  65,  49,  65,  34,  81,  17,  97,  17,  98,
    129, 240, 112,  24,   9,   3,  33,  33,  17,  34,  33,  17,
     34,  33,  33,  18,  33,  35,  18,  50,  34,  50,  34,  65,
     33, 240,  80,  18,   9,   3,  34,  50,  33,  81,  18,  98,
     99,  82,  17,  81,  49,  50,  35, 240,  80,  15,   9,   3,
     34,  50,  34,  65,  33,  98, 113, 129, 129, 115, 240, 112,
     14,   9,   5,  65,  33, 129, 113, 129, 113, 129,  33,  69,
    240, 112,  13,   9,   2, 113, 129, 129, 129, 129, 129, 129,
    129, 130, 112,  13,   9,   1, 130, 129, 129, 145, 129, 145,
    129, 130, 129,  64,  13,   9,   2, 129, 129, 129, 129, 129,
    129, 129, 129, 114, 112,  15,   9,  49, 114, 114,  97,  33,
     81,  33,  81,  33,  65,  65, 240, 240,   6,   9,   0,   9,
      4, 224,   5,   9,   2,   0,  11,  11,   9, 240, 196, 129,
     84,  81,  33,  85, 240, 112,  15,   9,   2, 129, 129, 132,
     81,  49,  65,  49,  65,  49,  68, 240, 112,  11,   9, 240,
    212,  65,  49,  65, 130, 132, 240, 112,  15,   9,  50, 129,
    129,  84,  65,  49,  65,  49,  65,  49,  85, 240,  96,  11,
      9, 240, 211,  81,  49,  69,  65, 148, 240, 112,  13,   9,
     19,  97,  17,  97, 115, 113, 129, 129, 115, 240, 144,  14,
      9, 240, 212,  65,  33,  81,  33,  98, 101,  65,  49,  68,
     80,  16,   9,   2, 129, 129, 133,  65,  49,  65,  49,  65,
     49,  51,  19, 240,  80,  11,   9,  17, 240, 162, 129, 129,
    129, 115, 240, 144,  13,   9,  33, 240, 162, 129, 129, 129,
    129,  97,  17,  99,  96,  16,   9,   2, 129, 129, 129,  19,
     65,  18,  82, 113,  17,  83,  18, 240,  96,  12,   9,   2,
    129, 129, 129, 129, 129, 129, 115, 240, 144,  16,   9, 240,
    200,  33,  33,  33,  33,  33,  33,  33,  33,  33,  25, 240,
     48,  14,   9, 240, 198,  65,  49,  65,  49,  65,  49,  51,
     19, 240,  80,  13,   9, 240, 212,  66,  34,  49,  65,  50,
     34,  68, 240, 112,  14,   9, 240, 197,  81,  49,  65,  49,
     65,  49,  68,  81, 115,  96,  14,   9, 240, 212,  65,  49,
     65,  49,  65,  49,  84, 129, 115,  48,  11,   9, 240, 196,
     97,  17,  97, 129, 115, 240, 144,  12,   9, 240, 196,  81,
     33,  98,  97,  33,  84, 240, 128,  12,   9,  17, 129, 129,
    115, 113, 129, 129, 130, 240, 144,  14,   9, 240, 194,  34,
     65,  49,  65,  49,  65,  49,  70, 240,  80,  13,   9, 240,
    195,  34,  50,  33,  81,  18,  98, 113, 240, 128,  18,   9,
    240, 195,  17,  34,  17,  34,  17,  35,  17,  17,  50,  18,
     65,  49, 240,  80,  14,   9, 240, 195,  18,  66,  17,  98,
     97,  18,  66,  19, 240,  96,  15,   9, 240, 195,  34,  50,
     33,  81,  18,  81,  17, 113, 129,  98,  96,  12,   9, 240,
    197,  65,  33, 113, 113,  33,  69, 240, 112,  13,   9,  18,
    113, 129, 129, 114, 129, 129, 129, 129, 130,  96,  13,   9,
      1, 129, 129, 129, 129, 129, 129, 129, 129, 129, 128,  13,
      9,   2, 129, 129, 129, 130, 113, 129, 129, 129, 114, 112,
     11,   9, 240, 240,  99,  33,  49,  35, 240, 240, 144,
};

const tFont g_sFontlucidabright6x12b =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    9,

    //
    // The height of the font.
    //
    10,

    //
    // The baseline of the font.
    //
    8,

    //
    // The offset to each character in the font.
    //
    {
           0,    5,   17,   30,   48,   63,   85,  105,
         114,  127,  140,  148,  159,  168,  176,  183,
         196,  214,  226,  239,  253,  267,  280,  296,
         308,  325,  341,  350,  360,  371,  379,  390,
         403,  426,  442,  459,  473,  491,  507,  522,
         538,  557,  569,  583,  602,  615,  641,  663,
         681,  696,  714,  732,  746,  758,  777,  795,
         819,  837,  852,  866,  879,  892,  905,  920,
         926,  931,  942,  957,  968,  983,  994, 1007,
        1021, 1037, 1048, 1061, 1077, 1089, 1105, 1119,
        1132, 1146, 1160, 1171, 1183, 1195, 1209, 1222,
        1240, 1254, 1269, 1281, 1294, 1307, 1320,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8lucidabright6x12bData
};
