//*****************************************************************************
//
// Copyright 1988 Bitstream, Inc., Cambridge, Massachusetts, USA
// Bitstream and Charter are registered trademarks of Bitstream, Inc.
// 
// The names "Bitstream" and "Charter" are registered trademarks of
// Bitstream, Inc.  Permission to use these trademarks is hereby
// granted only in association with the images described in this file.
// 
// Permission to use, copy, modify, and distribute this software and
// its documentation for any purpose and without fee is hereby
// granted, provided that the above copyright notice appear in all
// copies and that both that copyright notice and this permission
// notice appear in supporting documentation, and that the name of
// Bitstream not be used in advertising or publicity pertaining to
// distribution of the software without specific, written prior
// permission.  Bitstream makes no representations about the
// suitability of this software for any purpose.  It is provided "as
// is" without express or implied warranty.
// 
// BITSTREAM DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN
// NO EVENT SHALL BITSTREAM BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS
// OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
// NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
// CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
// 
// Copyright (c) 1987, 1994 Digital Equipment Corporation
// 
// The X Consortium, and any party obtaining a copy of these files from
// the X Consortium, directly or indirectly, is granted, free of charge, a
// full and unrestricted irrevocable, world-wide, paid up, royalty-free,
// nonexclusive right and license to deal in this software and
// documentation files (the "Software"), including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons who receive
// copies from any such party to do so.  This license includes without
// limitation a license to do the foregoing actions under any patents of
// the party supplying this software to the X Consortium.
// 
// Digital Equipment Corporation make no representations about the
// suitability of this software for any purpose.  It is provided "as
// is" without express or implied warranty.
// 
//*****************************************************************************

//*****************************************************************************
//
// This file is generated by ftrasterize; DO NOT EDIT BY HAND!
//
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include "grlib/grlib.h"

//*****************************************************************************
//
// Details of this font:
//     Characters: 32 to 126 inclusive
//     Style: Charter
//     Size: 5x11
//     Bold: yes
//     Italic: no
//     Memory usage: 1248 bytes
//
//*****************************************************************************

static const uint8_t g_pui8charter5x11bData[1046] =
{
      4,   7,   0,   7,   9,   7,   2,  82,  97, 194,  82, 240,
     64,   9,   7,   1,  17,  65,  17,   0,   5,  96,  13,   7,
     33,  17,  66,  53,  49,  17,  53,  50,  65,  17, 176,  12,
      7,  19,  50,  17,  51,  83,  50,  17,  51,  81, 192,  19,
      7,  17,  33,  33,  17,  17,  33,  18,  17,  33,  18,  17,
     33,  17,  17,  33,  33, 240,  13,   7,  18,  65,  33,  66,
     18,  21,  33,  34,  35,  18, 240,   8,   7, 114,  82,  82,
    240, 240,  48,  10,   7,  18,  65,  97,  97,  97,  97, 114,
    176,  10,   7,   2, 113,  97,  97,  97,  97,  66, 192,  10,
      7,  17,  81,  17,  65,  17, 240, 240, 144,   9,   7, 145,
     97,  69,  65,  97, 240,  48,   7,   7, 240, 240,  81,  97,
    208,   6,   7, 240, 211, 240, 160,   7,   7, 240, 210,  82,
    240,  64,  10,   7,  49,  81,  97,  97,  81,  97,  81, 208,
     14,   7,  18,  65,  33,  49,  33,  49,  33,  49,  33,  66,
    240,  48,  10,   7,  17,  82,  97,  97,  97,  82, 240,  64,
     12,   7,  18,  65,  33,  97,  81,  81,  17,  52, 240,  32,
     11,   7,  18,  65,  33,  82,  66, 113,  51, 240,  48,  12,
      7,  49,  82,  65,  17,  49,  33,  53,  81, 240,  32,  11,
      7,   4,  49, 100,  97,  49,  33,  51, 240,  48,  12,   7,
     33,  66,  84,  49,  33,  49,  33,  66, 240,  48,  11,   7,
      4,  49,  33,  81,  97,  81,  82, 240,  64,  14,   7,  18,
     65,  33,  50,  17,  49,  18,  49,  33,  66, 240,  48,  12,
      7,  18,  65,  33,  49,  33,  52,  81,  66, 240,  64,   8,
      7, 226,  82,  82,  82, 240,  64,   8,   7, 226,  82, 194,
     97,  81,  96,   9,   7, 240,  34,  35,  82, 114, 240,  16,
      6,   7, 229, 149, 240, 128,   8,   7, 226, 115,  66,  50,
    240,  64,  10,   7,  18,  66,  17,  82, 178,  82, 240,  48,
     16,   7,  50,  50,  33,  33,  18,  18,  17,  17,  18,  20,
     33,  49,  51, 144,  12,   7,  49,  82,  81,  17,  52,  49,
     33,  34,  34, 240,  13,   7,   4,  49,  34,  36,  49,  49,
     33,  49,  36, 240,  32,  12,   7,  20,  34,  33,  33,  97,
     98,  33,  52, 240,  16,  14,   7,   4,  49,  34,  33,  49,
     33,  49,  33,  34,  36, 240,  32,  12,   7,   4,  49,  99,
     65,  17,  65,  33,  52, 240,  32,  12,   7,   5,  33,  49,
     33,  33,  52,  49,  98, 240,  64,  13,   7,  20,  34,  33,
     33,  97,  34,  33,  49,  52, 240,  16,  14,   7,   2,  34,
     17,  65,  22,  17,  65,  17,  65,  18,  34, 240,  10,   7,
      1,  97,  97,  97,  97,  97, 240,  80,  11,   7,  34,  97,
     97,  97,  49,  33,  51, 240,  48,  15,   7,   2,  18,  33,
     33,  49,  17,  67,  65,  18,  50,  18, 240,  16,  11,   7,
      2,  81,  97,  97,  97,  33,  52, 240,  32,  15,   7,   3,
     37,  35,  17,  17,  18,  19,  18,  19,  19,  17,  18, 224,
     16,   7,   2,  18,  34,  33,  35,  17,  33,  19,  33,  34,
     34,  18, 240,  16,  14,   7,  20,  34,  34,  17,  65,  17,
     65,  18,  34,  36, 240,  16,  12,   7,   3,  65,  33,  49,
     33,  51,  65,  98, 240,  64,  14,   7,  20,  34,  34,  17,
     65,  17,  65,  18,  34,  36,  66,  99,  14,   7,   4,  49,
     33,  49,  33,  51,  65,  33,  50,  18, 240,  16,  12,   7,
     19,  49,  33,  51,  83,  49,  33,  51, 240,  48,  12,   7,
      5,  33,  17,  17,  65,  97,  97,  83, 240,  32,  15,   7,
      2,  18,  33,  49,  33,  49,  33,  49,  33,  49,  51, 240,
     32,  14,   7,   3,  18,  34,  33,  34,  17,  65,  17,  67,
     81, 240,  32,  17,   7,   3,  17,  17,  17,  18,  17,  17,
     18,  17,  22,  33,  33,  49,  33, 240,  13,   7,   3,  18,
     34,  17,  66,  82,  65,  18,  34,  19, 240,  12,   7,   3,
     19,  18,  33,  51,  81,  97,  83, 240,  16,  12,   7,   4,
     49,  18,  81,  81,  82,  17,  52, 240,  32,  10,   7,   2,
     81,  97,  97,  97,  97,  98, 192,  10,   7,   1, 113,  97,
     97, 113,  97, 113, 160,  10,   7,   2,  97,  97,  97,  97,
     97,  82, 192,   8,   7,  19,  49,  49, 240, 240, 224,   6,
      7,   0,   6,  20,  48,   8,   7, 114,  82,  82, 240, 240,
     48,   9,   7, 228,  67,  49,  33,  52, 240,  32,  12,   7,
      1,  97, 101,  33,  49,  33,  49,  36, 240,  32,   9,   7,
    242,  65,  17,  65, 114, 240,  48,  13,   7,  50,  97,  52,
     33,  49,  33,  34,  50,  17, 240,  16,   8,   7, 242,  68,
     49, 115, 240,  32,  11,   7,  18,  65,  17,  66,  81,  97,
     98, 240,  64,  11,   7, 243,  49,  17,  81,  83,  65,  17,
     66,  80,  13,   7,   1,  97, 101,  33,  49,  33,  49,  34,
     18, 240,  16,  10,   7,   1,  97,  97,  97,  97,  97, 240,
     80,  11,   7,  33,  97,  97,  97,  97,  97,  67,  81,  80,
     13,   7,   1,  97,  97,  33,  51,  65,  18,  50,  17, 240,
     32,  10,   7,   1,  97,  97,  97,  97,  97, 240,  80,  10,
      7, 232,  33,  34,  33,  35,  18,  17, 224,  11,   7, 229,
     33,  49,  33,  49,  34,  18, 240,  16,  10,   7, 242,  65,
     33,  49,  33,  66, 240,  48,  11,   7, 229,  33,  49,  33,
     49,  36,  49,  98,  80,  11,   7, 244,  33,  49,  33,  49,
     37,  97,  82,  32,   9,   7, 227,  65,  17,  65,  98, 240,
     64,   9,   7, 227,  67,  65,  17,  66, 240,  64,   9,   7,
    113,  98,  81,  97,  98, 240,  64,  11,   7, 225,  34,  33,
     49,  33,  49,  37, 240,  16,   9,   7, 229,  49,  17,  67,
     81, 240,  48,  12,   7, 228,  18,  17,  17,  17,  37,  49,
     17, 240,  16,  10,   7, 226,  18,  51,  67,  50,  18, 240,
     16,  11,   7, 229,  49,  17,  67,  81,  65,  17,  66,  80,
     10,   7, 228,  49,  17,  81,  17,  52, 240,  32,  10,   7,
     18,  81,  97,  81, 113,  97,  98, 176,  11,   7,   1,  97,
     97,  97,  97,  97,  97,  97,  96,  10,   7,   2,  97,  97,
    113,  81,  97,  82, 192,   9,   7, 130,  33,  17,  34, 240,
    240, 112,
};

const tFont g_sFontcharter5x11b =
{
    //
    // The format of the font.
    //
    FONT_FMT_PIXEL_RLE,

    //
    // The maximum width of the font.
    //
    7,

    //
    // The height of the font.
    //
    8,

    //
    // The baseline of the font.
    //
    6,

    //
    // The offset to each character in the font.
    //
    {
           0,    4,   13,   22,   35,   47,   66,   79,
          87,   97,  107,  117,  126,  133,  139,  146,
         156,  170,  180,  192,  203,  215,  226,  238,
         249,  263,  275,  283,  291,  300,  306,  314,
         324,  340,  352,  365,  377,  391,  403,  415,
         428,  442,  452,  463,  478,  489,  504,  520,
         534,  546,  560,  574,  586,  598,  613,  627,
         644,  657,  669,  681,  691,  701,  711,  719,
         725,  733,  742,  754,  763,  776,  784,  795,
         806,  819,  829,  840,  853,  863,  873,  884,
         894,  905,  916,  925,  934,  943,  954,  963,
         975,  985,  996, 1006, 1016, 1027, 1037,
    },

    //
    // A pointer to the actual font data
    //
    g_pui8charter5x11bData
};
