"""Protocol constants mirrored from the firmware headers. DO NOT EDIT BY HAND.

Generated by scripts/generate_protocol.py from:
  - ccs_workspace/badge.lgbt/badge_drivers/ir.h
  - ccs_workspace/badge.lgbt/badge_drivers/led.h
  - ccs_workspace/badge.lgbt/badge_drivers/storage.h
  - ccs_workspace/badge.lgbt/badge_drivers/tlc6983.h

To regenerate after a firmware header change:

    uv run generate-protocol

To check this file is still in sync with the headers (no changes written):

    uv run generate-protocol --check
"""


# ---- ir.h: serial link-layer protocol -------------------------------------
CRC_SEED = 0x8FB6
SERIAL_PROTO_VERSION = 0x0001

# Opcodes (SERIAL_OPCODE_* in ir.h).
SERIAL_OPCODE_HELO = 0x01
SERIAL_OPCODE_ACK = 0x02
SERIAL_OPCODE_NACK = 0x03
SERIAL_OPCODE_VERSION = 0x04
SERIAL_OPCODE_PUTFILE = 0x09
SERIAL_OPCODE_APPFILE = 0x0A
SERIAL_OPCODE_DELFILE = 0x0B
SERIAL_OPCODE_SETNAME = 0x0D
SERIAL_OPCODE_GETFILE = 0x13

SERIAL_CAP_DELETE = 0x0001

# from_id of the USB controller; see SERIAL_CONTROLLER_ID in ir.h.
SERIAL_CONTROLLER_ID = 0x1234000000000000

# Floor on an animation's frame delay, in ms; see MIN_FRAME_DELAY_MS in ir.h.
MIN_FRAME_DELAY_MS = 20

# ir_header_t, packed little-endian: struct.pack/unpack format and field
# names, in declaration order.
HEADER_FMT = '<HHHQHH'
HEADER_FIELDS = ('version_header', 'payload_len', 'opcode', 'from_id', 'crc16_payload', 'crc16_header')

# ir_version_t, packed little-endian: the SERIAL_OPCODE_VERSION payload.
VERSION_FMT = '<HBBH'
VERSION_FIELDS = ('proto_version', 'fw_year', 'fw_rev', 'capabilities')

# ---- led.h / storage.h: animation storage ----------------------------------
# ANIM_NAME_MAX_LEN in led.h: the firmware's name buffer, including the null
# terminator.
ANIM_NAME_MAX_LEN = 16

# STORAGE_MAX_ANIM_FRAMES in storage.h: ceiling on frames per stored animation.
STORAGE_MAX_ANIM_FRAMES = 200

# ---- led.h / tlc6983.h: screen geometry ------------------------------------
# screen_frame_t.pixels[SCREEN_HEIGHT][SCREEN_WIDTH] in led.h.
SCREEN_HEIGHT = 7
SCREEN_WIDTH = 15
# sizeof(rgbcolor_t) in tlc6983.h.
RGBCOLOR_BYTES = 3
# One frame on the wire: SCREEN_HEIGHT * SCREEN_WIDTH * RGBCOLOR_BYTES.
FRAME_BYTES = 315
